### ISSUE TITLE
The bucket slot doesn't work

### ISSUE THREAD

**Issue by Zilgyd** [Tiviacz1337/Travelers-Backpack#1001]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Server Forge 1.21-51.0.33

1. Describe the bug 

Icon bucket doesn't work, if I put a water bucket doesn't fill the tank and it happens with bucket milk and potions.

2. Write steps to reproduce the bug

Simply get into bagpack inventory and trying to put a bucket with water or milk, or a potion

3. What is expected behaviour 

I expect that the tank be filled

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Forge issue, wait for updates for Forge
