### ISSUE TITLE
Tough as Nails incompatibility

### ISSUE THREAD

**Issue by DionKill** [Tiviacz1337/Travelers-Backpack#1004]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
- NeoForge 47.1.106 for 1.20.1
- Traveler's Backpack 9.1.15
- Tough as Nails 9.0.0.96

1. Describe the bug 
Not sure if it's a bug or not, but there is no way to add the bottle of purified water to the tanks, and drinking normal water does not refill the thirst bar in 1.20.1.

2. Write steps to reproduce the bug
Fill the tanks with water, then use the hose in drink mode to drink the water and nothing happens.

3. What is expected behaviour 
- Adding purified water bottles into the tanks should work
- Drinking water and/or purified water should fill the thirst bar

**Comment by Tiviacz1337** [comment]
NeoForge is supported only since 1.20.4+

**Comment by Tiviacz1337** [comment]
I think I can add ability to refill thirst by drinking normal water from tanks. Purified water is not possible because TaN do not register it as fluid and it cant be put in tanks. (I wont register/create fluid for them)

**Comment by DionKill** [comment]
Yes that would be nice. For NeoForge, apparently it supports Forge mods up to 1.20.1, that's why the mod loads.

**Comment by Tiviacz1337** [comment]
Sorry, I'm implementing it right now for 1.21 for Neo, Water will be drinkable if you put water potion bottle in tanks, not normal water since nomal water can't be drink in TaN

**Comment by Tiviacz1337** [comment]
Okay I see in fact you can drink water, but from canteen so, I'll add it for water too

**Comment by Tiviacz1337** [comment]
Okay so current settings: 
Potion in tank: 3 drinks, 40% hydration, 25% poison chance (Just like potion drunk from hand)
Water bucket in tank: 3 * 5 drinks, 40% hydration, 25% poison chance
Water bucket in tank (if ther's less than 1 bucket of water): consumes 200mb and restores: 3 drinks, 40% hydration, 25% poison chance

**Comment by Tiviacz1337** [comment]
Added compatibily for NeoForge and Fabric 1.21.1. Download available on curseforge and modrinth
Update for older versions is coming soon

**Comment by DionKill** [comment]
Thank you so much for adding this!

**Comment by Tiviacz1337** [comment]
added for forge 1.20.1 too
