### ISSUE TITLE
The backpack disappears and I can't open it

### ISSUE THREAD

**Issue by Kussyara** [Tiviacz1337/Travelers-Backpack#1005]
Forge 1.20.1-9.1.15 (Server: Mohist 1.20.1)

1. Describe the bug 

After each re-entry into the server, the backpack disappears and it is impossible to enter it

2. Write steps to reproduce the bug

Rejoin to the server

3. What is expected behaviour 

It only helps if you enter the portal to hell. Or if you die

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Check if you use skin restorer plugin, mohist might be slightly broken with traveler's backpack
