### ISSUE TITLE
Unable to pull output of crafting

### ISSUE THREAD

**Issue by spacespacexx** [Tiviacz1337/Travelers-Backpack#1006]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 1.16.0
Minecraft 1.20.1

How do I extract the output of the crafting grid automatically? In the wiki it says "Inserting and extracting items from crafting grid - input is on the rear side, output is on the front side of the backpack." I can insert items into the crafting grid with a hopper but I am not able to get the output with a hopper.

**Comment by Tiviacz1337** [comment]
to output from crafting you'll need something that can pull from the side, like pipes. I think vanilla hoppers do not have such blocks to pull from sides
