### ISSUE TITLE
Backpacks wont show up

### ISSUE THREAD

**Issue by Rilyhx** [Tiviacz1337/Travelers-Backpack#1008]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 1.21.1-52.0.9

1. Describe the bug 
The upgrades, hoses and sleeping bags will show up but the backpacks themselves are just blank tiles

2. Write steps to reproduce the bug

3. What is expected behavior 

I've used this mod for ages and this has never happened.

4. Screenshots (If applicable)
![Screenshot (1)](https://github.com/user-attachments/assets/3ddfc246-c820-43f6-8cb2-879c4ccc5a85)

**Comment by Tiviacz1337** [comment]
any chance you use other mods? like mods that improve game performance?
