### ISSUE TITLE
When I disconnect from the server my backpack becomes invisible and I can't interact with it unless I die (possible fix).

### ISSUE THREAD

**Issue by VerussKolts** [Tiviacz1337/Travelers-Backpack#1010]
0.I use a server launched from Arclight (version: arclight-forge-1.20.1-1.0.0) to be able to use both FORGE plugins and mods (I'm using forge version 47.1.1)

 
1.When I log out of the server and log back in my backpack becomes invisible to me and I can't interact with the backpack in any way. After a lot of fiddling around, I found a possible solution that worked for me, I deleted the latest version of the skins restorer (version: 
SkinsRestorer 15.4.2) plugin and the backpack mod worked perfectly.

I've made this post to give a possible solution, I hope it helps I've been trying to figure out the solution for a day now

**Comment by Tiviacz1337** [comment]
Skin Restorer issue
