### ISSUE TITLE
Broken Backpack

### ISSUE THREAD

**Issue by quack4** [Tiviacz1337/Travelers-Backpack#1013]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 1.21

1. Describe the bug 

Backpack displayed on back, but when I press "B" it doesnt open. it also isnt displayed at all in my inventory. 

2. Write steps to reproduce the bug

No clue how it happened

3. What is expected behaviour 

For the backpack to open when I press B

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Maybe check your controls if it's not conflicting?

**Comment by EtiTheSpirit** [comment]
I can reproduce this on Forge 1.20.1, mod version 9.1.15.

I have rebound the control to something that is not conflicting, and the button does nothing for me either, regardless of where the backpack is in my inventory.
