### ISSUE TITLE
Backpack overlay should respect F1 and hide the tanks/tools

### ISSUE THREAD

**Issue by Aesthir** [Tiviacz1337/Travelers-Backpack#1014]
**Is your feature request related to a problem? Please describe.**
When I want to take a screenshot, I usually press F1 to remove all HUDs. Every other mod respects F1 except the traveler's backpack tanks & tools overlay. I'd like screenshots to not display my pack tanks and I'd also like to not have to go into settings to turn off the overlay manually for screenshots.

**Describe the solution you'd like**
I'd like F1 to be respected.

**Describe alternatives you've considered**
1. Turning the overlay off manually before every screenshot, then turning it back on afterwards is tedious.
2. Cropping the screenshots afterwards.
3. Disabling the overlay entirely.

**Additional context**
![2024-09-09_03 43 57](https://github.com/user-attachments/assets/17b96144-84f2-4811-a732-f35c0949ad74)

After pressing F1, the overlay stays in the bottom right corner:
![2024-09-09_03 43 59](https://github.com/user-attachments/assets/b4a46d4f-d26c-4279-aa7a-ef663fa46b5a)

**Comment by Tiviacz1337** [comment]
Mod version, game version, mod loader?

**Comment by Tiviacz1337** [comment]
fixed for fabric in mod version 9.1.17

**Comment by Aesthir** [comment]
Thanks! Works great!
