### ISSUE TITLE
The backpack's crafting grid can be inputted without being upgraded, but it cannot be outputted.

### ISSUE THREAD

**Issue by Htao-uu** [Tiviacz1337/Travelers-Backpack#1015]
Fabric 1.20.1-9.1.16

Describe the bug :
When the backpack in this mod is full, and you scroll the mouse wheel on an item in the player's inventory, the item will disappear.
Upon verification, it was found that items were placed into the crafting grid and the backpack did not have the crafting upgrade installed.

Write steps to reproduce the bug
When the backpack in this mod is full, and you scroll the mouse wheel on an item in the player's inventory

What is expected behaviour 
Without the crafting table upgrade, items should not be placed into the crafting grid

**Comment by Tiviacz1337** [comment]
How can I get this functioon of scrolling the mouse wheel on an item? Is this a seperate mod or it's vanilla thing? I can't seem to scroll items to backpack

**Comment by Htao-uu** [comment]
> How can I get this functioon of scrolling the mouse wheel on an item? Is this a seperate mod or it's vanilla thing? I can't seem to scroll items to backpack

Maybe is the function of Mouse tweeker

**Comment by Tiviacz1337** [comment]
This is fixed in 9.1.17
