### ISSUE TITLE
JEI "Move Items" button does not show up with backpack Crafting Upgrade

### ISSUE THREAD

**Issue by StAlexandre** [Tiviacz1337/Travelers-Backpack#1016]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

FML 47.3.7
Minecraft 1.20.1
Traveler's Backpack 9.1.15
JEI 15.14.0.64

1. Describe the bug 

When trying to quick craft in the Traveler's Backpack from JEI, the expected "Move Items" button is no longer present (compared to 9.1.14)

2. Write steps to reproduce the bug

a. Obtain any Traveler's Backpack.
b. Upgrade it with the Crafting Upgrade.
c. Attempt to use JEI to move items into the crafting grid.

3. What is expected behaviour 

When JEI opens, "Move Items" button is present and items can be quickly moved into the crafting grid.

4. Screenshots (If applicable)

https://github.com/user-attachments/assets/93bb1744-039c-43b6-bcbc-b52ea22e26fb

**Comment by Tiviacz1337** [comment]
Thank you for report, I will check that

**Comment by Tiviacz1337** [comment]
Fixed https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5764972
