### ISSUE TITLE
Backpack Stopped equipping

### ISSUE THREAD

**Issue by Terallis** [Tiviacz1337/Travelers-Backpack#1017]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 47.3.7 for Minecraft 1.20.1. Traveller's Backpack version: 1.20.1-9.1.15

1. Describe the bug 
So, I've been playing a modded server for some time with no issue. However, suddenly the backpack seemed to just stop equipping entirely. Everything else works like when using it from the quickbar. But now, when clicking the button to equip it on the character, nothing happens. I likewise tried putting it on the ground and equipping it through that, but that was even worse as the backpack just... disappeared. It acted as though it was trying to be equipped and just disappeared entirely.

This all happened, seemingly randomly, as I unequipped a Squid Backpack to equip a Magma Cream Backpack for venturing in the Nether. Something I have done many times before already. But this time, the Squid Backpack did unequip, but then I was just entirely unable to equip any other backpacks. I have tried /kill with keepInventory both on and off, I've tried restarting my game, restarting the server, and even trying entirely fresh backpacks.

The strangest part of it all is that I'm the only one it seems to be happening to, as friends of mine that play on the server are still able to equip and unequip their backpacks just fine. Weirder still, when all this happened, my heavily enchanted pickaxe seemed to disappear alone with it all. This is through using Inventorio with the auto-use tools in the side. But again, it's all worked just fine until now.

(EDIT: After checking the .dat file of my character, it seems like... SOMEHOW my diamond pickaxe that disappeared found its way... into the slot reserved for equipping the Traveller's Backpacks? I removed the entry and it works again, but I feel that's a bug in itself and have no idea how it happened.)

2. Write steps to reproduce the bug
Given how randomly it occurred, I have no idea how to reproduce this.

3. What is expected behaviour 
Expected behaviour is that the backpack equips and unequips normally, through the intended button.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Seems like it's random compatibility bug, I'm not sure how to approach it since I need steps to reproduce the issue. You've said you play modded server and maybe some mod caused this weird behaviour.
