### ISSUE TITLE
Backpack inventory and tier reset after updating to 1.21

### ISSUE THREAD

**Issue by juxstified** [Tiviacz1337/Travelers-Backpack#1018]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric Loader 0.16.3
Mod Version Updated to 10.0.6 from 9.1.16
Game Version Updated to 1.21 from 1.20.1

1. Describe the bug 

All of my backpack inventory is wiped after updating and the tier is always reset to leather as well.

2. Write steps to reproduce the bug

To isolate the bug I created a new instance of Minecraft in Fabric with only this mod and its dependencies enabled and my inventory disappeared when I upgraded.

3. What is expected behaviour 

I would assume that my inventory would remain intact or there would be a way to restore it from a backup.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
The 1.21 version use completely different code to save backpack items than 1.20.1, sorry for your loss. Backpack itself only creates backup if player dies with backpack on the back. I do not support migration between versions, you have to empty your backpack before updating the game
