### ISSUE TITLE
Duplication glitch with trinkets, accessories and compat layer.

### ISSUE THREAD

**Issue by AsgerJon** [Tiviacz1337/Travelers-Backpack#1019]
**Background**
Minecraft 1.21
Fabric Loader 0.16.3
Fabric API 0.102.0+1.21
Accessories 1.0.0-beta.34+1.21
Trinkets 3.10.0
Accessories Trinkets Compact Layer 3.10.0+beta.11
Cloth Config v15 15.0.130
Traveler's Backpack fabric-1.21-10.0.7
Cardinal Components API 6.1.1

**Description**
Items in backpacks and upgrades duplicates

**Steps to Reproduce**
Create a new world with command permissions. Use commands to give yourself two standard backpacks, leather and iron upgrade. Upgrade one backpack to iron-tier. Equip this backpack and place any items in it. Then, open your inventory and go to the 'Accessories' screen. Drag and drop the other backpack onto the back slot and close the GUI. The items from the first backpack have now been duplicated in both backpacks. Further,  the second backpack is now also iron-tier.

**Comment by Tiviacz1337** [comment]
update will be available tomorrow

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5735575
Fixed
