### ISSUE TITLE
Backpack not rendered and refuses to don/doff. 10.1.1

### ISSUE THREAD

**Issue by ArcanisOfAeons** [Tiviacz1337/Travelers-Backpack#1020]
Minecraft 1.21.1
NeoForge 21.1.35
Travelers Backpack 10.1.1

Updating to 10.1.1 from 10.0.5. Backpack is not rendered on back and there's no backpack slot in UI opposite the armor (I haven't changed my configs and it still says TRUE for that) and according to level.dat I am still wearing my backpack but I am not able to either doff it or don another (hence why I checked level.dat). I can access the pack and move inventories but the doff button says "Integration enabled - take backpack from back slot" and does nothing. Went back to 10.0.5 and everything works. Took off pack in 10.0.5, loaded in 10.1.1 and now the don button says "Integration enabled - put backpack in back slot" but again refuses to do so.

My guess is something to do with Curios as I have that mod for Charm of Undying and the Curios API integrations came back in 10.1.0 for NeoForge.

**Comment by Tiviacz1337** [comment]
Okay, you probably have backpack equipped in UI since 10.1.1 introduces curios integration on by default. 
Do the following: Edit the config and change curiosIntegration to false - you'll be able to access backpack normally. Then you can go to game and equip it normally with button again.
