### ISSUE TITLE
[Fabric 1.21 - 10.0.7] disableBackpackRender does not function with Trinkets integration enabled

### ISSUE THREAD

**Issue by harpuppy** [Tiviacz1337/Travelers-Backpack#1021]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric Loader 0.16.3, including mods:
> Cardinal Components 6.1.1
> Cloth Config 15.0.130
> Fabric API 0.102.0
> ModMenu 11.0.1
> TravelersBackpack Fabric 1.21-10.0.7
> Trinkets 3.10.0

The backpack is always rendered when equipped to a back slot with Trinkets integration enabled, even when disableBackpackRender is set to true.

Initially thought it could be a compat issue as I play with a lot of mods, but in a new instance with only the dependencies installed the problem was the same.

**Comment by Tiviacz1337** [comment]
I thought Trinkets had a way to hide certain trinkets frorm rendering because I use theirs rendering registry for backpack now, but I've mistaken it with curios I guess. I'll make the config option hide the backpack in the next update

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5735575
Added backpack visibility toggle button

**Comment by lennysme** [comment]
How do I toggle the visibility? I cannot locate the button anywhere. Many thanks!

**Comment by Tiviacz1337** [comment]
> How do I toggle the visibility? I cannot locate the button anywhere. Many thanks!

Open backpack when equipped -> open backpack settings tab -> button appears in right bottom corner of backpack inventory

**Comment by lennysme** [comment]
Hi, thank you for your speedy reply, I appreciate it. We are playing on the Prominence II pack and it just updated to v3.0.5h. I cannot see what you are referring to, unfortunately. There have been some other borks in the backpack UI that I assume are more related to the pack itself:

Open backpack inventory default screen (dragon backpack--prior to update, mine had the crafting menu in the bottom right, and I cannot combine it with the new crafting upgrade in a smithing table with leather to add it back, alas...)
![image](https://github.com/user-attachments/assets/21ba2910-b73f-4ef2-9bee-963b407d072c)

Clicking the side menu gear for settings...
![image](https://github.com/user-attachments/assets/0165566f-8519-498a-af69-007c29a06945)

How the tool slots look if I add some tools. No idea what the lock icons are for.
![image](https://github.com/user-attachments/assets/15dabc3a-b297-4682-821e-92ce616cc817)

The hose also seems not to be working, but that is separate from the UI issues, so I will open a new ticket later for that.

Many thanks!

**Comment by Tiviacz1337** [comment]
Seems like the pack uses outdated resourcepack, the best way would be disabling this texture pack, but I'll show you on the screenshot where button is. In fact you cant see it, but you can click it anyway
![image](https://github.com/user-attachments/assets/39a38579-9e9f-4eea-830f-c92235b3cdb2)

**Comment by Tiviacz1337** [comment]
Regarding the hose, you can join my discord sever, it'll be easier to handle it

**Comment by lennysme** [comment]
Thank you so much for the resource pack tip; I have turned it off, as well as the many GUI "upgrade" ones in the pack. It looks like this now, but no button, weirdly:

![image](https://github.com/user-attachments/assets/2278aa28-7abc-4f6a-95dd-5288e4b9ca94)

(my tools look normal again! thank you!)
![image](https://github.com/user-attachments/assets/f028e6e7-3f96-4fe0-b6ad-94742f1be71c)

**Comment by Tiviacz1337** [comment]
Hmm, are you sure you use the version I've linekd above? Also if you play on server, did you update mod on server too? 
The visibility button is available since 1.21.1-10.1.2

**Comment by lennysme** [comment]
Right you are; I checked the pack and it is way back in 1.20.1, haha. Thank you for all your help.

**Comment by Tiviacz1337** [comment]
> Right you are; I checked the pack and it is way back in 1.20.1, haha. Thank you for all your help.

Oh that's not a problem, you can always update to 1.20.1-9.1.17 for Fabric. Latest update for 1.20.1 that also adds visibility button. I thought you were playing on 1.21 ;) 
[Link to download](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5758816)
Also this update might also resolve your problems with hose
