### ISSUE TITLE
Server Crashes and Entity Tracking Issues

### ISSUE THREAD

**Issue by r4vencherry** [Tiviacz1337/Travelers-Backpack#1022]
**Fabric 1.21** - `fabric-loader-0.16.0-1.21`

**1. Describe the bug** 
The bug involves server crashes and entity management issues tied to the Traveler's Backpack mod. These crashes occurred frequently, and were mostly isolated to the End dimension and certain chunks. Whenever I reached a chunk area, the server crashed.

**2. Write steps to reproduce the bug**

- Install the Traveler's Backpack mod on a Minecraft Java server (version 1.21).
- Create and interact with backpacks.
- After a few hours, upon entering certain chunks in the End, the server crashed. This was tested several times and confirmed the crash occurred in the End, especially when entering the chunk (1, 3, 0) and nearby chunks.
- Note: After removing all in-game items and the mod from the server, the crashes stop.

**3. What is expected behaviour** 
- Players should be able to enter and interact around all chunks in the End without any issues?

---

Here's a zip with all 31 crash reports: 
[crash-reports.zip](https://github.com/user-attachments/files/17007437/crash-reports.zip)

---

### Summary of error messages and warnings:

- `ConcurrentModificationException` Errors: Frequent ConcurrentModificationException errors were encountered in server logs. These often occurred just before the crash. Example:

```js
[Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1628) ~[?:?]
	...
```

- Warnings and errors regarding duplicate entity UUIDs were logged a few times in the server console. Example:

```js 
UUID of added entity already exists: class_1542['Pig Traveler's Backpack'/111667, l='ServerLevel[world]', x=238.50, y=-48.36, z=3.50]`

---

[Server thread/WARN]: Duplicate entity UUID 2c6becef-bf8d-4ccd-a22c-430c02bea33f: class_1542['Pig Traveler's Backpack'/111667, l='ServerLevel[world]', x=238.50, y=-48.36, z=3.50]
[Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.class_3898.method_18701(class_3898.java:1106) ~[server-intermediary.jar:?]
	...
```
I don't know if it helps but I did not craft or had a Pig Traveler's Backpack (crafted or dropped from loot).

- `IllegalStateException` - Entity Already Tracked: The server encountered IllegalStateException errors stating "Entity is already tracked!"—this error directly followed the duplicate UUID warnings.

- Warnings about trying to load invalid items: 

```js
[Server thread/ERROR]: Tried to load invalid item: 'No component with type: 'travelersbackpack:sleeping_bag_color'; No component with type: 'travelersbackpack:sleeping_bag_color' missed input: {"travelersbackpack:sleeping_bag_color":6}; Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: travelersbackpack:pig'

[Server thread/ERROR]: Tried to load invalid item: 'No component with type: 'travelersbackpack:sleeping_bag_color'; No component with type: 'travelersbackpack:sleeping_bag_color' missed input: {"travelersbackpack:sleeping_bag_color":15}; Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: travelersbackpack:standard'
```

**Warnings Post-Mod Removal:**
I deleted all in game items related to the mod prior removing the mod from the server, however, I'm still seeing sporadic warnings about missing components: 

```js
No component with type: 'travelersbackpack:sleeping_bag_color'; Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: travelersbackpack:pig
```

After performing a server stop-backup-restart sequence, the following warnings appeared:

```js
[Server thread/WARN]: Failed to deserialize component: unregistered key travelersbackpack:travelersbackpack_entity
[Server thread/WARN]: Failed to deserialize component: unregistered key travelersbackpack:travelersbackpack_entity
```

---

**Note to the team:** 

Thank you to the team for creating and sharing this amazing mod. In the short time I used it, I really enjoyed it and found it incredibly useful. Unfortunately, I won't be able to continue using it for now due to the issues I've encountered. I understand that there are numerous factors that could be contributing to these problems, and they might not all be related to the mod itself—there are server settings and other existing mods to consider as well. However, I thought it would be helpful to share these reports, error messages, and warnings in case they assist in improving the mod or provide useful information for your team. I hope this is helpful, and feel free to reach out if you have any questions. Thanks again!

**Comment by Tiviacz1337** [comment]
I've changed the code that handles void protection of backpack. Hope it helps with the issue since I've seen specific line in 1st crash log you've sent and it was related with void protection.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5735575
This update should resolve the problem
