### ISSUE TITLE
Every mob has a backpack

### ISSUE THREAD

**Issue by MartynHollandNL** [Tiviacz1337/Travelers-Backpack#1024]
_0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)_

Fabric 0.16.3, MC 1.21 Java
travelersbackpack-fabric-1.21.1-10.1.1

_1. Describe the bug_ 

Every mob spawns with a backpack

_2. Write steps to reproduce the bug_

a mob spawns, has a backpack

_3. What is expected behaviour_ 

a mob spawns, a chance it has a backpack

_4. Screenshots (If applicable)_

https://i.imgur.com/SBCLCdF.png
https://i.imgur.com/dv7gyxA.png

please help i am drowning in backpacks

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5738221
Hotfix released, sorry for this bug
I've hidden the previous version, enjoy
