### ISSUE TITLE
how do i place the backpack

### ISSUE THREAD

**Issue by bro11790** [Tiviacz1337/Travelers-Backpack#1025]
0. Fabric 1.20.1

1. Describe the bug 
theres no help on how to place the backpack. i equiped it via i think ctrl and now have no clue how to place it again since theres no button showing in inventory and no slot for it.

2. Write steps to reproduce the bug

3. What is expected behaviour 

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Open inventory by clicking B button (check in controls if it doesnt work maybe its conflicting). Then click the button in left corner of gui to unequip backpack
