### ISSUE TITLE
Backpack renders despite client setting.

### ISSUE THREAD

**Issue by catreplicators** [Tiviacz1337/Travelers-Backpack#1026]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.20.1, mod version 9.1.16

1. Describe the bug 
Despite client setting "Disable backpack render" being true, the backpack still renders on the player if Trinkets integration is enabled.

2. Write steps to reproduce the bug
a. Enable trinkets integration
b. Equip backpack
c. Go into third person view

3. What is expected behaviour 
The expected result is that the backpack is invisible when this setting is enabled.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Theres going to be an update for Fabric tomorrow that will introduce show/hide button for backpack. At the moment disable backpack render config option do not work correctly with trinkets enabled.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5758816

Added show/hide backpack button
