### ISSUE TITLE
Backpack Contents Replacing When Shift right clicked to put on

### ISSUE THREAD

**Issue by SoonerJD** [Tiviacz1337/Travelers-Backpack#1027]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
fabric 0.16.2-1.21

1. Describe the bug 
When Shift Right click is pressed to switch backpacks from hotbar with accessories and trinkets compat layer, it replaces the contents and changes the tier of the one getting put on your back with the one getting taken off.

2. Write steps to reproduce the bug
When Shift Right click is pressed to switch backpacks from hotbar with accessories and trinkets compat layer, it replaces the contents of the one getting put on your back with the one getting taken off.

3. What is expected behaviour 
To not replace the contents of the backpack

4. Screenshots (If applicable)

**Comment by randymac** [comment]
I have experienced this issue when simply right clicking on a backpack that is active in my hotbar while the cursor is pointing at something out of range.
fabric .16.5
minecraft 1.21

**Comment by Tiviacz1337** [comment]
> I have experienced this issue when simply right clicking on a backpack that is active in my hotbar while the cursor is pointing at something out of range.
> 
> fabric .16.5
> 
> minecraft 1.21
> 
> 
> 
> 

Im not sure what do you mean. When you right click on the backpack with right click it opens its inventory.

**Comment by Tiviacz1337** [comment]
I didnt know shift + right click accessory swap was possible. Ill check that

**Comment by randymac** [comment]
Sorry for clogging up this thread, I just tried and cannot reproduce without shift.  Probably I hit shift and didnt realize it.  I can reproduce with shift right click.

**Comment by Tiviacz1337** [comment]
Quick equipping with Shift + right click is going to be disabled

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5812788
Fixed
