### ISSUE TITLE
backpack options for placing on death with accessories integration (gravestones mod doesnt pick up acessories)

### ISSUE THREAD

**Issue by randymac** [Tiviacz1337/Travelers-Backpack#1028]
**Is your feature request related to a problem? Please describe.**

Just want to start with thank you for all the work on this great mod!

We recently switched from trinkets to accessories integration because of issues we were having ( possibly trinkets incompatible with other mods). since the change, backpack is not placed in the world and backup is not made on death.  I understand this is may be intentional, or it may be related to our Gravestones mod. 

The Gravestones mod does not support Accessories (or trinkets, but he says that is coming) and all accessories equiped are not included in gravestone and drop in the world. This has led to several of us losing our backpacks , not sure if we just couldnt find it or what, with no way to restore.

**Describe the solution you'd like**
Is there any way we could force the backpack to be placed in the world again, make the backup be generated, or even generate backup manually?

**Describe alternatives you've considered**
I see you made some trinkets upgrades, we may switch back if it stops crashing and backpacks are placed and backed up again.

**Additional context**
Fabric mod loader .16.5
minecraft 1.21
Accessories Fabric 1.0.0 Beta 35 for 1.21](https://modrinth.com/mod/accessories/version/nDjQ9Zvd)
[Gravestones](https://modrinth.com/mod/Heh3BbSv) by Pneumono_ 1.0.9

**Comment by Tiviacz1337** [comment]
At the moment, if integration is enabled (so backpack is placeable is trinkets/accessories slot) it will drop only from trinkets/accessories inventory. Ive disabled the ability to place backpack on the ground because there was too much mess and bugs with this solution. 
Althrough enabling backpack backup is possible, I will probably do that in the next update.
You might consider using universal graves for fabric, im pretty sure its fully compatible with accessories (but its better to check anyways)

**Comment by randymac** [comment]
Thanks for the response and suggestion.  I tried out Universal Graves and it seems to work very well with Accessories, putting everything back where it was from grave. I will see about getting our server switched to this. 


Would love if you could enable the backups again, possibly periodically or on demand  as options instead of just on death.

 Thanks again!

**Comment by Tiviacz1337** [comment]
Backpack backups will be made everytime player dies with backpack equipped, regardless of whether Trinkets/Accessories is enabled or not. Coming in the next update

**Comment by Ryuushen** [comment]
Hello, don't mean to hijack the post but Unequip Backpack using right click to the ground also doesn't work with Accessories

**Comment by Tiviacz1337** [comment]
> Hello, don't mean to hijack the post but Unequip Backpack using right click to the ground also doesn't work with Accessories 

I know, it wont work. Ive disabled it on purpose. All Accessories/Curios/Trinkets items are supposed to be equipped and unequipped from the gui. Equipping from the ground and unequipping were causing only duplication issues because those mods do not support such mechanics.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5812788
Backpack backup enabled even if trinkets/accessories integration enabled
