### ISSUE TITLE
travelersbackpack not compatible with Loader's extended semantic version format

### ISSUE THREAD

**Issue by LeGuerrierGorillo** [Tiviacz1337/Travelers-Backpack#1029]
I'm on a aternos server on 1.20.1 and the modloader is version 0.16.5. Ah top of the log there is a warn: 
[ForkJoinPool-1-worker-1/WARN]: Mod travelersbackpack uses the version fabric-1.20.1-9.1.16 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version.
I put the last version of the mod for 1.20.1 on the server and I don't know how to fix this. The backpack works good but I just have this warn.
![image](https://github.com/user-attachments/assets/472472a3-400a-4db1-8b4e-980870fc488a)
A screenshot of the warn

**Comment by Tiviacz1337** [comment]
This is internal warning, I have to edit the versioning format. The update is going to be released tomorrow

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5758816

Fixed
