### ISSUE TITLE
"Failed to deserialize component" warn in Aternos server

### ISSUE THREAD

**Issue by LeGuerrierGorillo** [Tiviacz1337/Travelers-Backpack#1030]
Minecraft1.20.1 modloader 0.1635 in the last version of the mod.
I install the last version of the mod and I get multiple warns in my console who said: [Server thread/WARN]: Failed to deserialize component: unregistered key travelersbackpack:travelersbackpack_entity
It's a new feature who do this or it's a bug to fix?
![image](https://github.com/user-attachments/assets/b2f88a8c-5617-453a-8f25-c852ba465e62)

**Comment by Tiviacz1337** [comment]
This is warning, you use travelersbackpack on the save that previously used older version. travelersbackpack:travelersbackpack_entity component has been deleted in latest release and backpacks that spawn on entities are handled differently. It's just a warning, nothing to worry about. It won't happen in newly created worlds
