### ISSUE TITLE
The modes for the hose dont exist so i cant use my hose, and I cant put fluid in my backpack with buckets

### ISSUE THREAD

**Issue by BOB-FROM-SB** [Tiviacz1337/Travelers-Backpack#1032]
0. Forge 52.0.16 Minecraft version is 1.21.1

1. Describe the bug
when i scroll with my hose nothing happens, and the slots to put water into my backpack dont let me put buckets into it so i cant put fluid into my backpack at all.

2. Write steps to reproduce the bug
try to scroll with hose and try to put water into backpack with a bucket.

3. What is expected behaviour 
being able to switch modes with hose, and being able to put water, lava ect into your backpack with a bucket.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Forge 1.21.1 does not have fluid handlers implemented yet. You have to wait until forge release an update, eventually you can switch to neoforge - it all works

**Comment by BOB-FROM-SB** [comment]
im using different mods that require forge tho
