### ISSUE TITLE
Disconnection and problem on the server

### ISSUE THREAD

**Issue by Oliwier2001** [Tiviacz1337/Travelers-Backpack#1033]
0. Forge 1.21.1-10.0.1

1. Describe the bug:
After equipping/putting on the backpack, it kicks you out of the server and you can't get back in. It appears with this

2. Write steps to reproduce the bug

3. What is expected behaviour: Feedback

[disconnect-2024-09-28_01.57.42-client.txt](https://github.com/user-attachments/files/17171926/disconnect-2024-09-28_01.57.42-client.txt)

[disconnect-2024-09-27_20.08.03-client.txt](https://github.com/user-attachments/files/17171931/disconnect-2024-09-27_20.08.03-client.txt)

[disconnect-2024-09-27_19.59.46-client.txt](https://github.com/user-attachments/files/17171934/disconnect-2024-09-27_19.59.46-client.txt)

**Comment by Tiviacz1337** [comment]
Do you have the mod installed on server?

**Comment by Oliwier2001** [comment]
Yes

**Comment by Tiviacz1337** [comment]
is the backpack empty? or it has something inside?

**Comment by Oliwier2001** [comment]
it originally had/had the items but due to a problem we uninstalled it. Then we tried to fix it and it was empty, and that's how the problem occurred

**Comment by Tiviacz1337** [comment]
I can't reproduce the issue. I used the exact same forge version like you. I think the issue might be connected with contents of backpack or some kind of mod incompatibility.

**Comment by Oliwier2001** [comment]
ok, I'll try to know the mod. maybe I'll write what happens next later
