### ISSUE TITLE
Hoses do not work correctly (90% of the time)

### ISSUE THREAD

**Issue by shrad1994** [Tiviacz1337/Travelers-Backpack#1039]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
0.16.5 FABRIC

1. Describe the bug 
Majority of the time the hose does not function. My keybind is "Z" I hold Z and scroll but the hose simply stutters but does not change into "Hose suck mode" etc, simply stays as "Hose". After dropping it, picking it up, taking backpack off and putting backpack back on, I can SOMETIMES get the hose to then function normally for a very short window.

Tools function correctly with the keybind, removing tools does not fix the hose issue.

2. Write steps to reproduce the bug
Equip backpack
Check to make sure you have no conflicting keybinds
Hold hose in hand with no offhand
Hold keybind for "Swap Tool/Change Hose Mode"
Scroll mousewheel
Hose simply stutters as if something is changing but hose remains as "Hose"

3. What is expected behaviour 
Hose will change from "Hose" into "Hose suck mode" "Hose drink mode" "Hose spill mode" etc while holding keybind and scrolling.

4. Screenshots (If applicable)
https://youtu.be/hPRlxsnTq_w

**Comment by Tiviacz1337** [comment]
Do you play on modpack from curseforge/modrinth so I can download it and make tests?

**Comment by shrad1994** [comment]
Here's a duplicate profile from curseforge https://drive.google.com/file/d/1X1xoQt88KTs_MB3csH8XyBiaDZGW70Gp/view?usp=drive_link

**Comment by shrad1994** [comment]
MC 1.21 fabric 0.16.5

**Comment by Tiviacz1337** [comment]
is it your own modpack or some modpack i can download?

**Comment by shrad1994** [comment]
my own modpack, only a few actual mods, majority are client side things like map, gfx, etc

**Comment by Tiviacz1337** [comment]
I will check it

**Comment by Tiviacz1337** [comment]
It works for me correctly on your modpack. The problem is keybinding. You use many other mods that assign same keybind like Traveler's Backpack to hose (Z) and it does not work when it conflicts, you can either change the keybinding for Traveler's Backpack or for other mods. I changed Swap Tool/Change hose mode keybinding to not conflicting key and it works correctly

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5812788
I've changed slightly how keybind is recognized, but still it's better to check keybinds
