### ISSUE TITLE
[Bug] Accessories & Trinkets Compat Layer - Equipping makes backpack disappear from inventory

### ISSUE THREAD

**Issue by xXNickznXx** [Tiviacz1337/Travelers-Backpack#1040]
### 0. Information

- Fabric 1.21
- Traveler's Backpack 10.1.2
- Accessories Fabric 1.0.0 Beta 35
- Trinkets Compat 3.10.0 Layer Beta.11

### 1. Describe the bug 

Right-clicking the backpack in the hotbar equips it, its even accessible with pressing 'B', but it disappears from the inventory and its also not in the accessories slot.

### 2. Write steps to reproduce the bug

1. Set the setting `allowOnlyEquippedBackpack` to `true`
2. Right-click a backpack in the hotbar
3. Watch the backpack disappear from the inventory

### 3. What is expected behaviour 

The backpack should be put in the accessories slot.

**Comment by Tiviacz1337** [comment]
Fixed, backpack won't be equipped when right clicked, you have to manully put it in back slot

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5812788
Fixed
