### ISSUE TITLE
Pls Help how to unhide the backpack icon?

### ISSUE THREAD

**Issue by Pratyush283p** [Tiviacz1337/Travelers-Backpack#1042]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Forge latest for 1.21 for 52.0.33

1. Describe the bug 
how to unhide he backpack icon in inventory

2. Write steps to reproduce the bug

right click+shift on the backpack icon in inventory

3. What is expected behaviour 

the icon disappears never to be seen again

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Find **config** folder in your minecraft installation folder ->  find travelersbackpack-client.toml and open it with notepad -> change showBackpackIconInInventory to true

**Comment by Pratyush283p** [comment]
Where to find it in a aternos server cause I hid the backpack there and I am the creator ( a server with frnds)

**Comment by Tiviacz1337** [comment]
You have to edit config in minecraft folder on your computer, because it's client config (so user decides about it) your friends will have icon visible if they didnt hide it

**Comment by Pratyush283p** [comment]
Nvm found it but u should make it a key bind too cause this process is to much complicated for those who don't know abt these especially the ones who play in servers like me

**Comment by Tiviacz1337** [comment]
I thought that adding a note that shift + right click hides the icon should do the trick if someone doesn't want to hide it. But yeah probably keybind would be useful too

**Comment by Pratyush283p** [comment]
A keybind will be too difficult in the current system, u can make a command something like /tb show or smth like /tb restore(although it already exists)
