### ISSUE TITLE
[1.21.1 Fabric] Game crashing when placing backpack in Back slot (Accessories with Trinket compat)

### ISSUE THREAD

**Issue by Nephillia** [Tiviacz1337/Travelers-Backpack#1043]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.21.1
Accessories 1.1.0-beta4
Trinkets Compat Layer 3.10.0-beta 14
Traveler's Backpack 10.1.2

1. Describe the bug 

Game crashes when equipping backpack in Back slot. Cannot rejoin server without reset. I posted this in the Git for Accessories too because tbh I can't figure out which mod is doing the crashing primarily as other features of both work fine.
Client Log:
https://mclo.gs/zY6o49z

Server Log:
https://mclo.gs/7BgHOj4

2. Write steps to reproduce the bug
Obtain backpack
Attempt to put backpack into Back slot (Trinket/Accessories menu of inventory)
Game freezes and crashes/kicked by server for Ticking Exception

3. What is expected behaviour 
Put Backpack in Back slot and no issue.

Apologies in advance if this is not the proper avenue for posting this bug!

**Comment by Dragon-Seeker** [comment]
Hey @Tiviacz1337 why are you checking for an accessory menu class instance by chance? The Latest screen rewrite refactors such but you can use [`AccessoriesMenuBase`](https://github.com/wisp-forest/accessories/blob/1.21.x-ScreenExperiments/common/src/main/java/io/wispforest/accessories/menu/variants/AccessoriesMenuBase.java) as the instance check.

**Comment by Tiviacz1337** [comment]
> Hey @Tiviacz1337 why are you checking for an accessory menu class instance by chance? The Latest screen rewrite refactors such but you can use [`AccessoriesMenuBase`](https://github.com/wisp-forest/accessories/blob/1.21.x-ScreenExperiments/common/src/main/java/io/wispforest/accessories/menu/variants/AccessoriesMenuBase.java) as the instance check.

Hello, I check it because it was causing duplication issues when tick method was running during player accessory swap in the gui and that was the only solution Ive came up with

**Comment by danmvision** [comment]
Hi,
Just wondering if this issue will be fixed?
The backpack does wok in previous versions of accessories but not in the latest version which added some good features.

**Comment by Tiviacz1337** [comment]
> Hi,
> 
> Just wondering if this issue will be fixed?
> 
> The backpack does wok in previous versions of accessories but not in the latest version which added some good features.

Yes it will be fixed very soon

**Comment by danmvision** [comment]
Perfect !! Thanks

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5812788
Fixed
