### ISSUE TITLE
console warning since last update:

### ISSUE THREAD

**Issue by Amberslice** [Tiviacz1337/Travelers-Backpack#1044]
Fabric 0.16.5 1.20.1
Modpack https://modrinth.com/modpack/sillysquirrels

console warnings:
Server thread/WARN Failed to deserialize component: unregistered key travelersbackpack:travelersbackpack_entity

Unsure, just appeared since we updated travellers backpack to: 1.20.1 9.1.17

**Comment by Tiviacz1337** [comment]
You can keep playing, I've removed the component since it was no longer used. It's just a warning nothing to worry about, it will show because you play on save that used previous version of TB.
