### ISSUE TITLE
Backpack Vanish W/O Recovery

### ISSUE THREAD

**Issue by Arcul** [Tiviacz1337/Travelers-Backpack#1046]
Forge v1.21

When dying from falling half-way on a scaffold tower, the backpack is not placed at chat-displayed or log-displayed coordinates. As such backpack is lost and contents lost

Make tall scaffold tower, fall halfway and re-land on the scaffold and die to fall damage.

N/A

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5812838
Fixed
