### ISSUE TITLE
Backpack disappeared after death

### ISSUE THREAD

**Issue by littlewing1977** [Tiviacz1337/Travelers-Backpack#1047]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
I'm running Minecraft 1.21 with Fabric.
I'm also running Trinkets 3.10.0

1. Describe the bug 
Backpack disappears after death

2. Write steps to reproduce the bug
Today, I updated the mod to 10.1.2.  I was killed by a Guardian while wearing my backpack.  The backpack disappeared.  I restored it from a backup, but I noticed that the backpack is not displayed in the backpack slot.  I can press B to open the backpack though.  I also cannot take the backpack off.  The other player on my server said that his backpack is also not showing up in the backpack slot, but he can open it with B.
Also, no spare backpacks disappeared when I died; only the one that was on my back.

3. What is expected behaviour 
My backpack should not disappear and it should show in my backpack slot.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Did it happen after updating from older version of travelers backpack maybe?

**Comment by Tiviacz1337** [comment]
What version of Traveler's Backpack were you using before updating?

**Comment by littlewing1977** [comment]
Yes.  I downgraded and restored my playerdata file and it was working again, but still missing from the trinket slot.  So I figured it had to do with the upgrading.  I did some manual tinkering and got the backpack back.  Then I pulled it out of the trinket slot and placed it in my inventory.  Then I upgraded to the new version again and put it back in my trinket slot.  That process worked without issue.  So I figured I will remove if from the slot each time there is an update.
________________________________

**Comment by Tiviacz1337** [comment]
At some point I've added automatic trinket integration to 1.21 and if you updated from older version it probably caused some issues.
