### ISSUE TITLE
Basic Backpack

### ISSUE THREAD

**Issue by P4YN-Ki** [Tiviacz1337/Travelers-Backpack#1048]
**Is your feature request related to a problem? Please describe.**
This is not a problem, but a feature request.

**Describe the solution you'd like**
A basic backpack added to the mod, which I can then add tanks to either side or both at the same time. So it feels like there is a little more progression, especially for the early game. This won't fix everyones tastes, but it would be nice to have on more technical playthroughs where getting glass or iron is really difficult in the early game (TerraFirmaCraft/Greg). Doesn't have to be a full sized backpack and it could be disbaled in configs for people who don't want to use it or skipped entirely.

**Describe alternatives you've considered**
Installing other mods to handle the basic backpack, but ultimately I think it's best handled by the same mod rather then multiple mods. It means being balanced and updated, so it'll be a feature that sticks for future generations of Minecraft.

**Additional context**
This is purely a whim that I genuinely think would be a nice addition. In my play through Traveler's Backpacks are a end of early game item, maybe even mid-stage item depending on the difficulty of my modpack.

**Comment by Tiviacz1337** [comment]
The update with this feature is in progress, basically tanks will be optional and few QOL backpack upgrades are going to be added, like auto pickup, feeding upgrade or void upgrade. But still, it's rather bigger change and it will take me some time to finish. I try to dedicate as much time I can, but I still have to balance work/school/modding. 
But yes requested feature is being worked on :)

**Comment by P4YN-Ki** [comment]
Well damn, thanks for taking the time to respond so quickly! This is awesome news, I thank you for taking the time to read and respond, as well as for your continued efforts on the minecraft modding front. You are greatly appreciated and I look forward to all future updates.

**Comment by Tiviacz1337** [comment]
Little update on this issue, I've been working on the update since my last message and I can say the update is mostly done and release is coming soon :)  (I have to add few more upgrades, but I have the base code so it shouldn't take me long) 

![image](https://github.com/user-attachments/assets/ec6a228f-b453-4bdf-9b06-cf92e3e24593)

Edit: initial release will be available for 1.21+ NeoForge.  Upgrades update probably won't be backported to older versions though but I'm not 100% sure yet.

**Comment by P4YN-Ki** [comment]
Well that is cool indeed, my current playing version is 1.20.1, but that is of no consequence after all it's just a matter of time before most of the mods are updated to that point. Thanks for posting back with updated information, it's looking pretty cool. Awesome stuff!

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all?page=1&pageSize=20
Released upgrades update for Forge & Neo 1.21

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
And fabric

Sadly, the update is probably not going to be backported to 1.20.1, so I'm closing this issue

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/6049502
Turned out I've backported it to forge 1.20.1 anyways
