### ISSUE TITLE
Backpacks and items disappeared from game

### ISSUE THREAD

**Issue by ERROR5169** [Tiviacz1337/Travelers-Backpack#1049]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Using Forge, 1.21.1 and the mod version, 1.21.1-10.1.0

1. Describe the bug 

I had to sort my mods folder and took the files out and then put them back in. All of the backpacks I've crafted and items in them have disappeared from the game. Obviously if this isn't something fixable that's okay, I will humbly accept. <3

2. Write steps to reproduce the bug

Took mod file out of mod folder, put it back in again.

3. What is expected behaviour 

I don't understand this question, sorry. :c

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
It seems like you loaded the game without traveler's backpack, thats why the items were removed because they were not present in the game. sadly there's nothing you can do to get backpacks back when they got removed if you didnt have mod installed.
