### ISSUE TITLE
Mod does not work as intended or expected.

### ISSUE THREAD

**Issue by AleksandarFFXI** [Tiviacz1337/Travelers-Backpack#1050]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 0.16.7

1. Describe the bug 
Backpacks will not equip at all with just the Mod and the required dependencies or with Create Mods

2. Write steps to reproduce the bug

Just play the game (1.21.1 Minecraft + Fabric 0.16.7 + CurseForge)

3. What is expected behavior 
Equip the Backpack

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
How do you equip backpack?

**Comment by AleksandarFFXI** [comment]
On Body (Tried other slots as well) with or without Trinkets Mod. By moving the Backpack Item from inventory to the Armor slot. No keyboard shortcuts being used. This is with out without other mods. Only the Travelers Backpack and required dependencies.

**Comment by Tiviacz1337** [comment]
> On Body (Tried other slots as well) with or without Trinkets Mod. By moving the Backpack Item from inventory to the Armor slot. No keyboard shortcuts being used. This is with out without other mods. Only the Travelers Backpack and required dependencies.

When trinkets is installed (1.21.1 has automatic integration, other versions you have to enable it in config) you have to put backpack in trinkets back slot. 

Without trinkets or with trinkets integration off you have to open backpack - hold backpack in hand and right click and then click equip button in left bottom corner
of inventory gui

**Comment by AleksandarFFXI** [comment]
Did, Never worked.

**Comment by Tiviacz1337** [comment]
Im not sure what do you mean that never worked. Could you join my discord so we will resolve this issue? 
What version of travelers backpack do you use?
