### ISSUE TITLE
Sleeping bag spawn persist bug

### ISSUE THREAD

**Issue by Cynori** [Tiviacz1337/Travelers-Backpack#1051]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
using forge 1.20.1-9.1.16

1. Describe the bug 
i set config to have sleeping bags set spawn when used but the spawn point remains when the sleeping bag is picked back up

2. Write steps to reproduce the bug
set config setting to true, 
sleep in sleeping bag,
pick it up, 
die
you will respawn where the sleeping bag was

3. What is expected behaviour 
expected setting the config option to true to make sleeping bags act like default minecraft beds. maybe add a third option to the config to make it act like a bed

**Comment by Tiviacz1337** [comment]
If config option is enabled, it sets spawn point to the sleeping bag position even if sleeping bag is removed and that's not going to be changed. Disable this option to not set spawn point

**Comment by Cynori** [comment]
ty
