### ISSUE TITLE
[BUG] craftingtweaks and Travelers-Backpack cause game crash

### ISSUE THREAD

**Issue by SanQianQVQ** [Tiviacz1337/Travelers-Backpack#1052]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.20.1 9.1.16  Travelers-Backpack
craftingtweaks-fabric-1.20.1-18.2.5
Log: https://mclo.gs/C7h4hUD

1. Describe the bug 
press tab, then game crash

2. Write steps to reproduce the bug
press tab

3. What is expected behaviour 
compat

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5812761
Fixed here

**Comment by SanQianQVQ** [comment]
> https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5812761 Fixed here

It turned out that on CurseForge, the mod I downloaded on Modrinth
