### ISSUE TITLE
Render setting not working

### ISSUE THREAD

**Issue by Catvr1x** [Tiviacz1337/Travelers-Backpack#1054]
0. Version:
fabric-1.21.1 traveler's backpack v10.1.3

1. Bug description:
When I change render backpack settings, nothing happens

2. Steps to reproduce the bug:
Menu -> Mods -> Traveler's Backpack -> Client -> Change these: Disable Backpack Render / Render Backpack With Elytra
and nothing happens

3. Expected behaviour:
Packpack should become invisible

4. Screenshots:
![image](https://github.com/user-attachments/assets/2722b4d7-b304-48a8-a32f-91856910bb00)
![image](https://github.com/user-attachments/assets/eddc1297-0fde-4dc8-8159-44ebf9ddd846)

**Comment by Tiviacz1337** [comment]
This config option has been disabled, you can disable backpack rendering from backpack gui in-game
Open backpak inventory -> Click Backpack settings tab -> click eye button under right tank

**Comment by Tiviacz1337** [comment]
![image](https://github.com/user-attachments/assets/7897303e-2ee3-4c33-abaa-71b6f8e0d103)

**Comment by Catvr1x** [comment]
Damn, I'm dumb. Thanks!
