### ISSUE TITLE
Please add an in game option to hide the backpacks

### ISSUE THREAD

**Issue by acriibunii** [Tiviacz1337/Travelers-Backpack#1055]
Please add an in game option to hide the render of a backpack, I know you can turn off rendering in the config client side, but when on a server with other people I don't want others seeing it either when it clashes with my skin/armor. even if it isn't a setting, make it an upgrade we can craft that will turn the backpack invisible, something like smithing a backpack with a pot of invis will make it invisible until you drop the item in water.

**Comment by Tiviacz1337** [comment]
You can hide backpack in game, what version do you use? 
You can open backpack -> open backpack settings -> and click visibility button under right tank
