### ISSUE TITLE
Not showing on Trinkets slot

### ISSUE THREAD

**Issue by Peperehobbits01** [Tiviacz1337/Travelers-Backpack#1056]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 0.15.11 Minecraft 1.20.1

1. Describe the bug 

When you try to put a backpack in the trinkets slot or when you equip it whit the ui element in the backpack ui, it dosen't show in the bakcpack trinkets slot.

2. Write steps to reproduce the bug

1. Run the game on version mentionned above.
2. Use Traveler's backpack 9.1.15
3. When on the world, equip a backpack.
4. You will see it dosent work whit trinkets slot.

3. What is expected behaviour 

Backpack shows in trinkets slot when equiped

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
1.20.1 didnt have trinkets integration enabled by default. You can enable it in config by changing trinketsIntegration option to true in Backpack Settings tab. 

You can equip your backpack by opening backpack from the hand and clicking button in left bottom corner of inventory. Then you can access your backpack with B key (if it doesnt open inventory, check your controls if you do not have any key conflicts)
![image](https://github.com/user-attachments/assets/7bd5e592-f8d0-4bd4-bb40-44ac5aeb3c33)
