### ISSUE TITLE
Tanks being an upgrade/optional

### ISSUE THREAD

**Issue by Hyperbuss** [Tiviacz1337/Travelers-Backpack#1058]
I've always found it kinda strange that the tanks are part of the base backpack while similarly powerful stuff like crafting is an upgrade. I would also appreciate it aesthetically, having a way to have a tankless backpack. my friends and I don't use this function often and they just kinda look silly in a rustic context.

**Comment by Tiviacz1337** [comment]
This feature is in progress. Along with tanks as an upgrade, few more functional upgrades are in works like autopickup, feeding, jukebox upgrade and few more QOL upgrades to backpack.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all?page=1&pageSize=20
Released upgrades update for Forge & Neo 1.21
