### ISSUE TITLE
The backpack interface is bugged

### ISSUE THREAD

**Issue by Zettahel** [Tiviacz1337/Travelers-Backpack#1059]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Forge 1.20.1-9.1.16

1. Describe the bug 

When you open the backpack, none of the interface is visible. It is still there and usable, but it is invisible. The organization buttons are scattered and conflict with the item interface.

2. Write steps to reproduce the bug

I don't know if there were steps, from the first moment I packed the backpack it looked like this

3. What is expected behaviour 

that the interface is visible and that the buttons do not overlap

4. Screenshots (If applicable)
![Captura de pantalla 2024-10-31 231208](https://github.com/user-attachments/assets/69884307-a2c3-433a-9595-931964bef88a)

**Comment by Tiviacz1337** [comment]
This is issue with outdated resourcepack. Disable Mandala modded resourcepack
