### ISSUE TITLE
Backpack Overwrite with Curios Integration

### ISSUE THREAD

**Issue by Licoricethecat** [Tiviacz1337/Travelers-Backpack#1061]
0. NeoForge 21.1.73 // travelers backpack 10.1.3 // curios 9.0.14

1. Whenever curios inventory is opened and hotkeys are used to swap backpacks between the back slot and hotbar, backpack in hotbar overwrites all items and tier level in backpack in back slot

2. Write steps to reproduce the bug (see above)

3. Both inventories and tiers stay the same as before and no stuff is lost

**Comment by Tiviacz1337** [comment]
Fixed in latest release for neoforge
