### ISSUE TITLE
The latest mod version 1.16.5, when used on a server, still requires entering the Nether or dying once before it can be used normally

### ISSUE THREAD

**Issue by Free-WanJY** [Tiviacz1337/Travelers-Backpack#1065]
The latest mod version 1.16.5, when used on a server, still requires entering the Nether or dying once before it can be used normally.
The core of my server is CatServer-1.16.5-build79.
Loaded plugins have:
{
SimpleTpa
AuthMe
ChainMining
Residence
MInimotd
SkinsRestorer
LuckPerms
WorldGuard
WordEdit
CMILib
ProtocolLib
}
MOD:
{
TravelersBackpack-1.16.5-5.4.51
Jade-1.16.4-2.8.3
……
}

**Comment by Tiviacz1337** [comment]
Remove skin restorer plugin
