### ISSUE TITLE
Equipping backpack from hotbar on curio slot 

### ISSUE THREAD

**Issue by LucasI27** [Tiviacz1337/Travelers-Backpack#1066]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Forge 1.20.1-9.1.16

1. Describe the bug 

When using curious integration and/or accessories compat, the "quick equip" with SHIFT+RMB or just RMB (this is editable in Accessories config) doesn't work as expected

2. Write steps to reproduce the bug

With curious integration config enabled, trying to equip the backpack from the hotbar doesn't do anything, curiously trying to reproduce this with the integration disabled equips the backpack correctly in the curious back slot, even tho it isn't accessible (enabling the config to make the backpack only accessible when equipped doesn't seem to change the outcome)

3. What is expected behaviour 

Trying to equip the backpack from the hotbar right-clicking (like armors) should equip it in the back curious slot

5. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Backpack can be opened from hand, that's why quick equipping is disabled
