### ISSUE TITLE
icon to insert backpack disappeared

### ISSUE THREAD

**Issue by giulisisi** [Tiviacz1337/Travelers-Backpack#1067]
forge version 1.21.1

I clicked the backpack icon and it disappeared. The backpack remains on my back and I have no way to remove it without dying.

![minecraft aiuto ](https://github.com/user-attachments/assets/0266be8d-dcd2-4ee9-bce0-1e1f4a59019e)

**Comment by Tiviacz1337** [comment]
You have to click B (default keybind to access it)
