### ISSUE TITLE
Can't remove liquid from backpack tanks. 

### ISSUE THREAD

**Issue by MrZurgation** [Tiviacz1337/Travelers-Backpack#1069]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
I'm using the curseforge launcher version 1.265.0.21056. HardRock TerraFirmaCraft version 1.5.4.

1. Describe the bug 
I'm unable to fill a bucket from my tanks. Specifically, I can't even place a bucket in the slot for them to be filled, almost like the GUI's treating it like an invalid item type. 

2. Write steps to reproduce the bug
I filled both the tanks with water using a wooden bucket (the one made with lumber), and then tried to remove the water using the same buckets. It won't let me even place them in the slot that I used to fill the tanks.

3. What is expected behavior 
I expect to be able to place the buckets in the same slots I used to fill them and have the tanks empty the appropriate amount of liquid into the buckets, much the same way the tanks filled with the appropriate amount of liquid in the reverse process. 

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Does it work for normal vanilla buckets?
