### ISSUE TITLE
Update Please!!!

### ISSUE THREAD

**Issue by MiNDy2001** [Tiviacz1337/Travelers-Backpack#107]
Hello, I'm Mindy, and I've wanted to use your mod for Minecraft 1.15.2. The only issue is, the mod is only available for earlier game versions. If you could take some of your time to update the mod, it'd be extremely appreciated! Thank you!

**Comment by Tiviacz1337** [comment]
I'll update the mod sometime in the future

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/2982997
