### ISSUE TITLE
{Feature Request} Current changes of Forge's port to Fabric

### ISSUE THREAD

**Issue by NattoRiisa** [Tiviacz1337/Travelers-Backpack#1070]
**Is your feature request related to a problem? Please describe.**
Somewhat behind in content such as the backpack changes and whatnot.

**Describe the solution you'd like**
as the title suggests,,, updating what was on forge's port to fabric

**Describe alternatives you've considered**
n/a 

**Additional context**
I can wait as long as possible, just thought I'd put this issue as a reminder,,, feel free to close if it's unnecessary !

**Comment by Tiviacz1337** [comment]
If you mean the upgrades update, of course all changes will be ported to Fabric. I work on the port and it should be available in about 2 weeks, because of Fabric and Forge code differences

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5995861

Upgrades update available for Fabric
