### ISSUE TITLE
Disable Scroll Wheel Unable to work

### ISSUE THREAD

**Issue by Chikaze** [Tiviacz1337/Travelers-Backpack#1071]
minecraft 1.21.1
NeoForge 21.1.79
Traveler's Backpack 10.1.5

Disable Scroll Wheel  = true
Scroll Wheel still appears and cannot switch tools

**Comment by Tiviacz1337** [comment]
Confirmed, will be fixed in the next update

**Comment by Chikaze** [comment]
Thank you

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5946823 Fixed
