### ISSUE TITLE
Cloth-Config2

### ISSUE THREAD

**Issue by zwiniecki13** [Tiviacz1337/Travelers-Backpack#1072]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

fabric, and travelersbackpack version 1.21.1-10.1.3 and ive tried just about every version of cloth config i can, still no dice :/

1. Describe the bug 

When I try to boot the game, it says error unless i remove the cloth config mod i have, then it says i need cloth-config2 any version, im so confused and ive been working on this for about an hour now and have no idea what im doing wrong, maybe im overlooking something simple? please help!!

and yes i can get you a recent log if needed :)

**Comment by zwiniecki13** [comment]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install cloth-config2, any version.
More details:
	 - Mod 'Traveler's Backpack' (travelersbackpack) 10.1.3 requires any version of cloth-config2, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Tiviacz1337** [comment]
Could you show me the project which you download cloth config from?

**Comment by zwiniecki13** [comment]
yeah! ive tried this link: https://modrinth.com/mod/cloth-config/versions?l=fabric
and this one: https://www.curseforge.com/minecraft/mc-mods/cloth-config
tons of versions, no dice on any :/

**Comment by Tiviacz1337** [comment]
Make sure you are downloading cloth config for **Fabric**
It seems like Your game is not seeing cloth config and you say tou installed it. It means youve probably downloaded version for wrong modloader

**Comment by zwiniecki13** [comment]
i double triple checked, i have all fabric versions

**Comment by Tiviacz1337** [comment]
Could you give me the whole list of your mods? Also could you share latest.log?
