### ISSUE TITLE
Recipe Bug

### ISSUE THREAD

**Issue by Akhyaaar** [Tiviacz1337/Travelers-Backpack#1075]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
**Mod loader Forge 52.0.16 with OptiFine HD U J1 on minecraft 1.21.1**

1. Describe the bug 
The bug prevents me from crafting certain upgrades (?) for the backpack because there’s a barrier present. Even when I try to input the recipe manually (without using the JEI mod), it still doesn’t work.

2. Write steps to reproduce the bug
When I installed this mod and placed it in the mods & resource pack section, I encountered an issue where, upon opening JEI (Just Enough Items) to view the recipe for this backpack mod, a barrier appeared below/next to it. At first, I thought, "Did I forget to enable the resource pack?" and it turned out that I had indeed forgotten. However, even after enabling it, the issue persisted. I have already reinstalled and even moved the behavior & resource files to the datapack folder, but the problem still remains.

3. What is expected behaviour 
If there were no bug, the recipe would appear normally like other items that can be crafted through crafting. For example, the backpack, tank, and hose can be crafted.

4. Screenshots (If applicable)
![Screenshot 2024-11-26 174544](https://github.com/user-attachments/assets/d003e240-4447-486f-b7f9-ae83c01341e4)

**Comment by Tiviacz1337** [comment]
Try installing latest forge release for 1.21.1: 1.21.1 - 52.0.28

**Comment by Akhyaaar** [comment]
> Try installing latest forge release for 1.21.1: 1.21.1 - 52.0.28
okay, it work. thank you

**Comment by Tiviacz1337** [comment]
Keeping the issue open for other people until I release fix for Traveler's Backpack to require at least Forge 52.0.21 for 1.21.1

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5946825 Fixed
