### ISSUE TITLE
Can't Equip Backpack..sorta

### ISSUE THREAD

**Issue by SpicyDandelion** [Tiviacz1337/Travelers-Backpack#1077]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

**Fabric 1.20.1 - 0.16.9**

1. Describe the bug 

**Can't equip the backpack. I use both Accessories and Trinkets as that's how I get this mod to work in my 1.21.1 playthrough. However, I can't equip it whatsoever. Not using just the mod alone, with trinkets, or with accessories. I saw in earlier bug reports to open the backpack on the hotbar and click the button inside the backpack to equip it....which technically worked. However I can't open it with "B" even though nothing else is bound to that keybind. When it equipped, it doesn't show up anywhere in my character inventory/accessories/trinket screens (pics included).**

2. Write steps to reproduce the bug

**I'm not really sure how to accurately reproduce this, as I have like....100+ mods. Theoretically all you need is this mod, accessories, and trinkets. 

-Go into creative to spawn one in for testing. 
-Shift right click backpack to equip, nothing happens. 
-Try to manually equip by dragging into chestpiece slot>Backpack slot>Nothing happens. 
-Try equipping into the accessories screen backpack slot, nothing happens. 
-Try opening the backpack on hotbar and equipping it using the equip button. See that it DOES equip, but cannot see where in characters inventory. 
-Try pressing "B" and see that it does not open. Look at keybinds and make sure nothing is set to "B" other than travelers backpack. Xaero's Map was! So I changed it to something else. Make sure nothing else is again, nothing is. 
-Try pressing "B" to open inventory...Nothing happens.
-Since you can't open backpack with "B" you can't take it off either, as you can't see it anywhere else in the character screen **

3. What is expected behaviour 

Can equip with Shift+Right Click, With Accessories Mod, or Trinkets mod. Can equip using the mods feature to open the backpack on the hotbar within the backpacks inventory. 

4. Screenshots (If applicable)

The first three are my screenshots for THIS specific issue, with the mods turned on. The other two are my 1.21.1 game where I can equip them (Using accessories) <3 This is the result of equipping the backpack within the backpack (LOL) Now it's stuck on meee. 

![2024-12-04_16 10 08](https://github.com/user-attachments/assets/526d56fd-e4c4-4858-8c9f-42be53f68515)
![2024-12-04_16 10 27](https://github.com/user-attachments/assets/448c133c-cece-40c0-a078-c67b152b94f5)
![2024-12-04_16 10 40](https://github.com/user-attachments/assets/ba0bfc86-3fc3-4149-a58d-90a4c9496467)

![2024-12-04_16 27 39](https://github.com/user-attachments/assets/4e988a09-2cd5-4885-a60d-433df3956967)
![2024-12-04_16 27 31](https://github.com/user-attachments/assets/1a13c0af-5240-4c01-a0a8-629333e6f701)

**Comment by Tiviacz1337** [comment]
I'm not quite sure if using both accessories and trinkets is right - both mods adds the same functionality and accessories supports trinkets compat layer. It seems like you see overlay in right bottom corner - it means your backpack is equipped and you should be able to open it with B key. If you can't maybe check the controls if there are any conflicts. If its still not working I'd suggest to take backpack off, go to config and check what is the state of trinketsIntegration config option, if it's True backpack will work only equipped in Trinkets/Accessories back slot, if its false - backpack will only work if equipped with button from backpack inventory (opened from the hand)

1.21.1 has trinketsIntegration enabled by default
1.20.1 has trinketsIntegration disabled by default, so you might want to change that

**Comment by SpicyDandelion** [comment]
Where can I find the trinketsintegration? I don't see a config file with that in it >~<

**Comment by SpicyDandelion** [comment]
Ah! I was thinking it would be in the trinkets config, which doesn't exist lmao. I also looked in the accessories config. For some reason it didn't occur to me to check the backpack config. This fixed it!!! <3 much love and appreciation
