### ISSUE TITLE
equipped backpack disappears after mod update

### ISSUE THREAD

**Issue by tenshiiclone** [Tiviacz1337/Travelers-Backpack#1078]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
neofforge 21.1.83
mode version 10.1.6

1. Describe the bug 
equipped backpack disappears after mod update

2. Write steps to reproduce the bug
update travelers backpack
equipped backpack is gone

3. What is expected behaviour 
equipped backpack stays

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
disable backSlotIntegration in Traveler's Backpack Config, backpack will appear on your back

**Comment by tenshiiclone** [comment]
thank you i was very worried
