### ISSUE TITLE
Issue with buckets in forge modloader 52.0.29

### ISSUE THREAD

**Issue by lucasmdias** [Tiviacz1337/Travelers-Backpack#1080]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Forge - 52.0.29
Minecraft - 1.21.1
MOD Version - 1.21.1-10.1.2

1. Describe the bug 

When trying to put liquids in the backpack, the bucket slot does not accept either full or empty buckets, whether with water or lava. From what I was able to test, this is only happening with the Forge version.

No Resourcepack other than the default

2. Write steps to reproduce the bug

I was only able to test with empty backpacks, as it is my first time using the mod. To reproduce the bug, just grab any backpack, whether it is in your hand, equipped, or on the ground with the tank addon, and try to put any bucket inside it.

3. What is expected behaviour 

the bucket should be placed in the slot and emptied, with its contents filling the backpack's tank

4. Screenshots (If applicable)

![image](https://github.com/user-attachments/assets/3ad0435a-6775-472f-b1f2-f162854e447c)

**Comment by Tiviacz1337** [comment]
Unfortunately this is Forge issue not Traveler's Backpack. As soon as Forge implements handling fluids in buckets, tanks will work correctly. It's already implemented on NeoForge and everything is working correctly, so there's nothing we can do than wait for Forge updates :(
