### ISSUE TITLE
Backpack not interactable or replaceable

### ISSUE THREAD

**Issue by Rijan2** [Tiviacz1337/Travelers-Backpack#1082]
Fabric 1.21.1 - 0.16.9
travellers backpack v10.1.3

i left the game , came back after 20 mins the backpack cant be accessed or replaced

leave game , come back , there is a bug

the backpack icon in inventory is gone , i cant see it on my back,  i can see my tools i put inside , the backpack can also not be replaced with another backpack

tools displayed bottom right:
![image](https://github.com/user-attachments/assets/7a377f1e-64b8-48b3-b045-345814cc8cf7)

Backpack not there , not interactable or usable either
![image](https://github.com/user-attachments/assets/4f4be99b-b3b6-40dc-8c10-a14de2da2ae4)

cant equip another backpack as well
![image](https://github.com/user-attachments/assets/4e7dac7a-4337-4b56-82f7-60af3cc19d6c)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5995861

Upgrades update for fabric containing a lot of bug fixes, make backpack backups or empty them before updating - items should transfer but make backup just in case something went wrong
