### ISSUE TITLE
After the character died, the backpack became broken

### ISSUE THREAD

**Issue by Koxae** [Tiviacz1337/Travelers-Backpack#1083]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Minecraft 1.21.1, Fabric 0.16.7, Mod 1.10.1.3

1. Describe the bug 

After the character died, the backpack became broken. It stopped opening with a hot key, some items from it disappeared. Then I cleared the backpack and removed it from the character, but when I opened the backpack from the hotbar, some items were there again, they were duplicated. I deleted all backpacks for the character and deleted the mod. But reinstalling the mod returns broken backpacks that cannot be opened with a hot key. The previous version of the mod generally crashes the game.

I forgot to add that at the time of the character's death there was an item with a curse of vanishing in the backpack.

2. Write steps to reproduce the bug

The character with the backpack on must die.

3. What is expected behaviour 

Backpack won't open with hot key

**Comment by Tiviacz1337** [comment]
The update for Fabric is in works and it will be fixed with new release

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5995861

Released upgrades update containing lots of bug fixes, make sure to backup or empty backpacks before updating - items should transfer but make backup just in case something went wrong
