### ISSUE TITLE
Pickup and Void Upgrades have opposite effects

### ISSUE THREAD

**Issue by berberborscing** [Tiviacz1337/Travelers-Backpack#1084]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
NeoForge (1.21.1-10.1.6)

1. Describe the bug 
The Pickup and Void backpack upgrades have the opposite effects as intended.

2. Write steps to reproduce the bug
Configure the Pickup and Void upgrades to pickup and delete certain items, and notice that the Pickup upgrade makes items vanish while the Void upgrade works as the Pickup upgrade should.

3. What is expected behaviour 
Pickup should suck specified items into backpack, while Void should delete specified items on pickup

**Comment by Tiviacz1337** [comment]
I can't reproduce this issue, maybe you've set wrong filter options? For me void & pickup combo works completely fine

**Comment by Tiviacz1337** [comment]
![image](https://github.com/user-attachments/assets/fca6699a-0d60-4d45-9bf2-c9719807d9c5)

Pickup picks up all items, void removes only rotten flesh and torches
