### ISSUE TITLE
Dragon Backpack doesn't regenerate health

### ISSUE THREAD

**Issue by berberborscing** [Tiviacz1337/Travelers-Backpack#1086]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
NeoForge 1.21.1-10.1.6

1. Describe the bug 
When the Dragon Backpack is worn, the regen buff is constantly reapplied, causing no actual health regeneration to take place

2. Write steps to reproduce the bug
Equip the Dragon backpack and enable the ability with less than your max HP and insufficient hunger to regenerate naturally

3. What is expected behaviour 
Health should be regenerated.

**Comment by Tiviacz1337** [comment]
Fixed
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all?page=1&pageSize=20
