### ISSUE TITLE
Backpack can't be opened after game restart on a server (posting again because I made a few mistakes)

### ISSUE THREAD

**Issue by Caywo** [Tiviacz1337/Travelers-Backpack#1087]
1. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 1.20.1. Mod: 1.20.1-9.1.16

2. Describe the bug
Other players can see the backpack equipped but I cannot access it with the corresponding hotkey, nor does the tank icon display. The only solution is to die and loot the backpack

3. Write steps to reproduce the bug
Join the server, equip backpack with the button thats in the backpack's inventory, leave server, close game and rejoin.

4. What is expected behaviour
Backpack dissapears and can't be accessed

**Comment by Tiviacz1337** [comment]
Do you use skin changer on your server?

**Comment by Caywo** [comment]
Yes, I use Skin Restorer

**Comment by Tiviacz1337** [comment]
Try removing it and check if issue occurs

**Comment by Caywo** [comment]
Yeah it worked. Thank you very much
