### ISSUE TITLE
The backpacks will be shown twice in the EMI

### ISSUE THREAD

**Issue by Boshigiri** [Tiviacz1337/Travelers-Backpack#1088]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
travelersbackpack-neoforge-1.21.1-10.1.6

1. Describe the bug 
The backpacks will be shown twice in the EMI, and backpack icons are all with tank
Versions below travelersbackpack-neoforge-1.21.1-10.1.3 do not have this issue

2. Write steps to reproduce the bug
pass

3. What is expected behaviour 
pass

4. Screenshots (If applicable)
![QQ截图20241214214213](https://github.com/user-attachments/assets/a4ffcb25-515f-465a-9dc2-b8e2cf680e9c)

**Comment by Tiviacz1337** [comment]
Backpacks will always display with tanks in creative menu, that's how backpacks always looked so I wanted to keep it. Backpack being shown twice is in fact a bug and I will check that

**Comment by Tiviacz1337** [comment]
Basically, the duplicated backpacks are backpacks with different component data. I use special method to add backpacks to creative tab with additional data, but emi shows both - registered items and items from creative tab. That's why its "duplicated". Unfortunately no way to fix it.

**Comment by Boshigiri** [comment]
So it maybe a EMI issue?
I will seek help from emi

**Comment by Tiviacz1337** [comment]
That's the explanation I've read on same issue but reported to emi dev. But sure you can ask if there's any solution now.
