### ISSUE TITLE
[Crash] Opening backpack on wall or in inventory crashes game

### ISSUE THREAD

**Issue by Aesthir** [Tiviacz1337/Travelers-Backpack#1089]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 0.16.9
Minecraft 1.21.1
TB 10.1.3

1. Describe the bug 
Old backpacks placed on wall way back. I can no longer open them without game crashing. I tried pulling one from the wall into inventory and opened it with a right click... crashed the game anyway.

Here's a crash report: https://mclo.gs/hHs86HR
and another: https://mclo.gs/QSUYD0W

**Comment by Tiviacz1337** [comment]
Try resetting backpack to default -> place backpack in world and shift right click with blank upgrade. It will restore default settings and shatter items around your backpack

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5995861

Upgrades update for Fabric, issue should be resolved, items should transfer but make backup of your backpacks before updating in case something went wrong
