### ISSUE TITLE
cant craft sleeping bag v1.0.24.24

### ISSUE THREAD

**Issue by gabgab2001** [Tiviacz1337/Travelers-Backpack#109]
I'm playing on a mac with forge 1.12.2 and I installed the latest version of travelers backpack (1.0.24.24) into a mod pack and I started to craft some backpack items. I was able to create the backpack tanks no problem but I was not able to craft the sleeping bag. I tested the mod by itself in a new world and the glitch still is there. I downloaded the previous version of the mod (1.0.23.23) and everything works so far. Thanks!

**Comment by Tiviacz1337** [comment]
2 red wool + 1 white wool

**Comment by gabgab2001** [comment]
Thanks! I used the recipe as advertised on curse forge of two red carpets and one white wool block, so you may want to announce the recipe has changed. Thanks again.
