### ISSUE TITLE
Compatibility issues with Aether mod and Trinkets

### ISSUE THREAD

**Issue by aidan-walden** [Tiviacz1337/Travelers-Backpack#1090]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Modloader: Fabric
Minecraft version: 1.21.1
Mod version: 1.21.1-10.1.3
Aether version: 1.5.1-beta5
Trinkets version: 3.10.0

1. Describe the bug 

I'm not sure if this is an issue with Aether or with this mod.

When the aforementioned mods are installed together, there is some undefined behavior that can be observed, particularly with the crafting grid. 
Some things I've observed:
- Hotkey sometimes doesn't work at all
- Sometimes the hotkey works, but the crafting grid is unavailable even if the backpack has been upgraded (I have only been able to observe this one on a dedicated server)

Using the Aether backpack slot, or right clicking the backpack in your hand, resolves all of these issues

2. Write steps to reproduce the bug

Install the following mods:
- The Aether
- Trinkets
- Travelers Backpack

Put a backpack in the Trinkets slot
Press B to open the backpack
Observe that nothing happens
Place the backpack in the Aether backpack slot and press B
Observe the intended behaviour

3. What is expected behaviour 
The backpack keybind (and all other features) should work regardless of the slot used, with the Aether mod present

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
The big update is coming for fabric, it should be fixed

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5995861

Latest update, issues with trinkets should be resolved, althrough make backups of your backpacks (or empty them, before updating)

**Comment by Tiviacz1337** [comment]
If issue still occurs - make new issue on github
