### ISSUE TITLE
Can't add templates or leather to Smithing Table

### ISSUE THREAD

**Issue by mandychuu** [Tiviacz1337/Travelers-Backpack#1093]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
I'm using Forge 52.0.29 via the Curseforge launcher.

1. Describe the bug 
I'm trying to apply a crafting table upgrade to the Standard backpack, but I can't add neither smithing templates nor leather to the Smithing Table.

2. Write steps to reproduce the bug
The Standard backpack slots in correctly to the Smithing Table, but the template and leather will not slot.

3. What is expected behaviour 
If working, it should produce the Standard backpack with a crafting table.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Could you provide screenshot?

**Comment by Tiviacz1337** [comment]
it should be leather + backpack + upgrade

**Comment by hoanovicz** [comment]
I have the same problem. it's not possible to put leather into the smithing table as a template. neither is it possible to put the (crafting) upgrade into it. I just stays in your hand if you click. Worked with the tier upgrades though (where no template was necessary)
Forge 1.21.1-52.0.28

**Comment by Tiviacz1337** [comment]
What version of mod do you use

**Comment by hoanovicz** [comment]
1.21.1-10.1.2

**Comment by Tiviacz1337** [comment]
Its already upgrades update, you no longer add upgrades in smithing table, just open your backpack and put upgrade in any empty upgrade slot on your right

**Comment by hoanovicz** [comment]
ahh alright I didn't know. that works. thank you!
