### ISSUE TITLE
Can't put milk in tanks

### ISSUE THREAD

**Issue by dylanparry** [Tiviacz1337/Travelers-Backpack#1098]
Mod version 1.21.1-10.1.5 on Fabric.

I can't seem to put milk into the tanks either from a bucket or by using the hose on a cow. This worked on the old version before the rewrite. It works fine for water and lava.

**Comment by Tiviacz1337** [comment]
Milk has been removed from the mod, if you know any mod that adds milk as fluid I can make them compatible and create effect for it

**Comment by juxstified** [comment]
> Milk has been removed from the mod, if you know any mod that adds milk as fluid I can make them compatible and create effect for it

Does this mean we will have to use a different mod in addition to this one to be able to have milk in our tanks again?

**Comment by Tiviacz1337** [comment]
Yes, but I have to add compat first. Milk is still present on forge & neoforge because those loaders add milk as fluid internally. On Fabric I have to create milk fluid from scratch and I do not want to do that.
