### ISSUE TITLE
Backpack gui button not equipping / unequipping properly

### ISSUE THREAD

**Issue by ZeClass** [Tiviacz1337/Travelers-Backpack#1099]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Minecraft 1.12.1 Fabric 0.16.9
Travelers Backpack - 10.1.3
Accessories 1.1.0 beta.18
Accessories Trinkets Compatibility Layer 3.10.0 beta.18

1. Describe the bug 
When I open the backpack inventory (keybind or right clicking), the button in the bottom left to equip / unequip to back slot does not work.
I can still manually equip / unequip via opening the accessories gui in my inventory, only the button doesn't work.
When hovering over the button, it says "Integration enabled - take backpack from back slot" or "Integration enabled - put backpack in back slot"

2. Write steps to reproduce the bug
Get backpack, open backpack, attempt to use the button to equip / unequip backpack.

3. What is expected behaviour 
For the button to equip/unequip the backpack like normal.

**Comment by Tiviacz1337** [comment]
That's not a bug, if trinkets/accessories integration is enabled the only way to use backpack is to put it in their 'back' slot. If Integration is disabled then equip button can be used. Tooltip on button is just a hint to put in back slot
