### ISSUE TITLE
Blaze Backpack's ability causes crash

### ISSUE THREAD

**Issue by MerMelone** [Tiviacz1337/Travelers-Backpack#1101]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 1.21.1-10.1.2

1. Describe the bug 
When the Blaze Backpack is worn and the player is shot by a Blaze's fireball, the game crashes.

2. Write steps to reproduce the bug
Equip the Blaze backpack and enable the ability, approach a blaze in survival mode and let it hit you.

3. What is expected behaviour 
The game shouldn't crash and the backpack's ability should protect the player.

[crash-2024-12-20_16.52.42-server.txt](https://github.com/user-attachments/files/18212680/crash-2024-12-20_16.52.42-server.txt)

**Comment by Tiviacz1337** [comment]
Fixed
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all?page=1&pageSize=20
