### ISSUE TITLE
Issue Updating from 1.20.1 to 1.21.1 version

### ISSUE THREAD

**Issue by vogelb** [Tiviacz1337/Travelers-Backpack#1103]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
 
Before Update: Java 17, MC 1.20.1, Forge 47.2.0, Backpack 1.20.1-9.1.12
After Update: Java 21, MC 1.21.1, Forge 52.0.37, Backpack 1.21.1-10.1.2

2. Describe the bug 
Before the Update, I had an almost fully packed, fully updated backpack with full tanks 
After the update, the backpack was reset to the initial tier, without tanks and empty 

4. Write steps to reproduce the bug
Update from MC 1.20.1 to 1.21.1, versions as above

5. What is expected behaviour 
The backpack has the same tier and contents as before the update

6. Screenshots (If applicable)
![before](https://github.com/user-attachments/assets/6999c263-f039-456c-93ab-5fbbbb1651c8)
![after](https://github.com/user-attachments/assets/1c02cf83-3b11-40e0-94e2-99fed4529290)

[server.log](https://github.com/user-attachments/files/18247326/server.log)

**Comment by Tiviacz1337** [comment]
Mc 1.21.1 uses completely different system for saving data for items. I do not support migration, you have to empty your backpack before moving to the next version (which was rewrite of the mod though)

**Comment by vogelb** [comment]
Ok, totally acceptable.
Thanks for your effort to support the new MC version!
