### ISSUE TITLE
compatability w/ Tough as Nails

### ISSUE THREAD

**Issue by ShugarCubez** [Tiviacz1337/Travelers-Backpack#111]
I'm not sure if this has already been requested, but I use a mod on a currently private mod pack. (Tough As Nails) that uses Thirst and Temperature modules to enhance the game play. Is it possible to have bottles retrieve the "Purified Water Bucket" water ? I can seem to put the water in, but I can't take it out with normal Minecraft bottles and only buckets. I can't seem to put the "purified water bottle" in the tank to fill it as well.

![test](https://user-images.githubusercontent.com/66182890/83684814-aab6ed00-a5b5-11ea-8a0b-2a9b74402689.png)
![test2](https://user-images.githubusercontent.com/66182890/83684817-ab4f8380-a5b5-11ea-85af-c379e8074071.png)

**Comment by Tiviacz1337** [comment]
What about hose? Can you drink purified water with hose?

**Comment by ShugarCubez** [comment]
How would I drink from the hose if its only has mode "suck"

**Comment by Tiviacz1337** [comment]
Shift + scroll changes hose mode

**Comment by ShugarCubez** [comment]
Are we still trying to figure this out ?

**Comment by ShugarCubez** [comment]
@Tiviacz1337 Let me know when you're available :)

**Comment by Tiviacz1337** [comment]
I'll fix it asap

**Comment by Tiviacz1337** [comment]
I think I'll have to create addon to make it compatibile

**Comment by ShugarCubez** [comment]
Oh wow that sounds great, but .. uh does that mean you are going to create
one in the near future? And would it work on 1.12.2 ?

**Comment by Tiviacz1337** [comment]
Addon almost ready need to polish few things. Should be available in next week

**Comment by ShugarCubez** [comment]
Oooh thank you so much

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-integrations
