### ISSUE TITLE
the backpack disappears in explosions

### ISSUE THREAD

**Issue by alesslimbert** [Tiviacz1337/Travelers-Backpack#112]
I use a tomb mod to avoid losing inventory and when I die the backpack usually stays next to the grave but only in explosions does it disappear if you could make it part of the inventory in some way or if it did not disappear when an explosion happened I would appreciate it very much.

**Comment by Tiviacz1337** [comment]
Is it happening only with tomb mod installed?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/2984416
