### ISSUE TITLE
Unable to put potions in tank

### ISSUE THREAD

**Issue by D-Bigboy-302** [Tiviacz1337/Travelers-Backpack#114]
Mod Version: 1.15.2-4.0.1
Forge Version: 31.2.20

Not sure if its a bug or I'm just missing/doing something wrong, but I can't seem to put any potions in the backpack tanks.

**Comment by Tiviacz1337** [comment]
This feature is not implemented yet

**Comment by Flexico** [comment]
Awwwww maaaaaaann!
