### ISSUE TITLE
Crash while Shift-right clicking bag in block form. 1.15.2

### ISSUE THREAD

**Issue by ArMoReDfUrY** [Tiviacz1337/Travelers-Backpack#115]
as in title. bag was deployed as a block in the world then shift right clicked, this was with an empty hand.

here's the reports pastebin: 
https://pastebin.com/7fEG1jKV

**Comment by Tiviacz1337** [comment]
Steps to reproduce?

**Comment by ArMoReDfUrY** [comment]
place bag on ground as a block. shift right click it.

the error looks like it's trying to get block facing after the bag has been picked up, then it crashes when there is just minecraft:air

**Comment by Tiviacz1337** [comment]
well I try to do the exact same thing and nothing happens. Do you play on server?

**Comment by ArMoReDfUrY** [comment]
single player at the moment. mod list is in the crashlog. 
yeh there is probably a conflict somewhere.
might have been a 1 time thing though i'll do some testing with it later tonight.

**Comment by chris5022** [comment]
i have this same problem i am playing multiplayer in a lan connection
[crash-2020-06-21_16.25.14-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/4810291/crash-2020-06-21_16.25.14-client.txt)

**Comment by Tiviacz1337** [comment]
Can you record a video of it?

**Comment by chris5022** [comment]
ok i have run some tests i see the problem. with a shader on it crashes. not sure what the conflict between them is but that is what happens. the rest of the mod works fine as far as i have seen. still have not used the hose but past that its fine

**Comment by ArMoReDfUrY** [comment]
i am using optifine but shaders are off
been busy still gotta run the tests, should have them soon.

**Comment by twoworlds** [comment]
Same problem here:
https://pastebin.com/TMTjHRwm
I am playing on a private server. I have optifine installed but no shaders active.

**Comment by unclelag** [comment]
Does this look similar @Tiviacz1337 ?
https://forums.minecraftforge.net/topic/72966-1143-solved-minecraft-crashes-when-adding-custom-blockstate-properties-to-block/

**Comment by ArMoReDfUrY** [comment]
ran a bunch of tests on the bag. still getting a crash on shift-right clicking the bag in its block form.

sleeping bag opens and closes fine.

hose works fine apart from an occasional duping of lava source blocks when placing. (i even have the hose setup as a water source for the survive mod. works great.)

tool slots work fine

rendering fine on the player, tanks too.

this seems to be the only bug iv'e found so far, not including potions in tanks as you said it's unimplemented.

**Comment by Tiviacz1337** [comment]
I think I've found the issue. Update should be available today

**Comment by ArMoReDfUrY** [comment]
Thanks for the fix, i'll close this after i test the release :)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/2985879

**Comment by unclelag** [comment]
Tested it just now. It definitely works for me now.
Thanks a bunch and keep up the good work!

**Comment by ArMoReDfUrY** [comment]
Working great. thanks for the fix. this is now closed
