### ISSUE TITLE
When using the sleeping bag from the backpack, the game crashes [1.15.2]

### ISSUE THREAD

**Issue by krzysztof23** [Tiviacz1337/Travelers-Backpack#116]
When using the sleeping bag from the backpack, the game crashes [1.15.2]
I am using the latest version of the modification available TravelersBackpack-1.15.2-4.0.2.jar

The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Xaero's World Map has crashed! Please contact the author at planetminecraft.com/member/xaero96 or minecraftforum.net/members/xaero96

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/2985049
