### ISSUE TITLE
(Suggestion) Unnerfed Tools Column

### ISSUE THREAD

**Issue by Sweek9** [Tiviacz1337/Travelers-Backpack#119]
The green column looks like it was designed with space for a full 6 spots but 4 are removed nerfing its use. 2 slots is not enough. I want to be able to cycle through pickaxe, axe, shovel, shears, machete, hose, empty bucket, silk touch tools, torches, et cetera.

**Comment by ArMoReDfUrY** [comment]
too op. tools is enough. 
hose won't work as it uses the same shift-scroll function to change modes.
no torches as it only works with un-stackable items and its not necessary. 

you should add this mod on top. they work well together and it will hold the hose and any non stackables e.g. buckets
[Tool Belt](https://www.curseforge.com/minecraft/mc-mods/tool-belt)
