### ISSUE TITLE
Can't pick up or quick stack currently held item when accessing backpack.

### ISSUE THREAD

**Issue by AlphaBraveHeart** [Tiviacz1337/Travelers-Backpack#121]
Forge: 14.23.5.2854
Version: 1.12.2

When accessing my equipped backpack using the assigned key, I am no longer able to pick up, stack into, or quick-stack the item that I am holding. Not sure if there is a way to fix this though.

**Comment by Tiviacz1337** [comment]
I'm pretty sure it has been fixed in 1.0.27
