### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by agentwolf88** [Tiviacz1337/Travelers-Backpack#122]
MC 1.12.2
Forge 14.23.5.2854
TBP TravelersBackpack-1.12.2-1.0.28.jar

https://pastebin.com/YibmS5QZ

**Comment by Tiviacz1337** [comment]
Patch will be available today

**Comment by agentwolf88** [comment]
Good job! Thank you!

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/2987730
My bad I haven't checked that before
