### ISSUE TITLE
Creash with the mod

### ISSUE THREAD

**Issue by juanvrt58** [Tiviacz1337/Travelers-Backpack#123]
When i destroy the backpack the game crash me. I play in a modded server with only one person, and he´s have the same problem! Help!

**Comment by Tiviacz1337** [comment]
Could you provide log, mod version and mc version..?

**Comment by juanvrt58** [comment]
Mod: TravelersBackpack-1.15.2-4.0.0.jar
Mc version 1.15.2
log:
The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.util.Direction, values=[north, south, west, east]} as it does not exist in Block{minecraft:air}

**Comment by Tiviacz1337** [comment]
Please use latest version before reporting issues. https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/2985879
