### ISSUE TITLE
lots of stuff screwed because of the latest update

### ISSUE THREAD

**Issue by TheMightyMcGrew** [Tiviacz1337/Travelers-Backpack#126]
This mod is screwing with a lot of keybinds. Especially its own. B no longer works when there is no other keybind to B, it simply will not accept B. Also completely removing your previous versions really screws servers who werent experiencing the crashes that caused you guys to update. If you could re-post the previous version we'd love to have that one back, because without it being available on curse twitch wont accept the modpacks we issue with those older versions. Also elytra mods are now keybind bugged as well

**Comment by Tiviacz1337** [comment]
I've made version 1.0.27 available on the page, but be aware this version of mod is no longer supported.
