### ISSUE TITLE
Add all custom backpacks

### ISSUE THREAD

**Issue by Tiviacz1337** [Tiviacz1337/Travelers-Backpack#127]
List of textures to be remade: (Like a lot) 

- [x] Cow
- [x] Bat
- [x] Blaze
- [ ] Carrot
- [x] Coal
- [x] Netherite (New)
- [x] Diamond
- [x] Emerald
- [x] Gold
- [x] Iron
- [x] Iron Golem
- [x] Lapis
- [x] Redstone
- [x] Bookshelf
- [x] Cactus
- [x] Cake
- [x] ~~Chest~~
- [ ] Cookie
- [x] Dragon
- [x] ~~Egg~~
- [ ] Electric
- [ ] Deluxe
- [x] Enderman
- [x] End
- [x] Chicken
- [x] Ocelot
- [x] Ghast
- [x] Hay
- [x] Horse
- [x] ~~Leather~~
- [x] ~~Glowstone~~
- [x] Magma Cube
- [x] Melon
- [ ] Brown Mushroom
- [ ] Red Mushroom
- [x] ~~Mooshroom~~
- [x] Nether
- [x] Wither
- [x] ~~Crying Obsidian (New)~~
- [x] ~~Obsidian~~
- [x] ~~Overworld~~
- [ ] Pigman
- [x] Pig
- [x] Pumpkin
- [x] Quartz
- [ ] Rainbow
- [x] Sandstone
- [x] Sheep
- [ ] Silverfish
- [x] Squid
- [x] ~~Sunflower~~
- [x] Creeper
- [x] Skeleton
- [ ] Wither Skeleton
- [ ] Slime
- [x] Snow
- [x] Spider
- [x] Sponge
- [x] Villager
- [x] Fox (New)
- [x] Wolf
- [ ] Zombie
- [x] ~~Modded Network~~ 
- [x] Dyeable Backpack

**Comment by MrCheschire** [comment]
What Prompted the dropping of the overworld backpack?

**Comment by Darkona** [comment]
Just spitballing here, but why do the textures need to be remade Tiviacz? Need any help?

**Comment by Tiviacz1337** [comment]
Minecraft had textures update in 1.14. I've remade them to use latest textures for blocks/mobs and such to fit them in to latest versions.
