### ISSUE TITLE
I lose my backpack with my things when I die 1.15.2

### ISSUE THREAD

**Issue by Damii16** [Tiviacz1337/Travelers-Backpack#128]
Does the backpack disappear when you die? my backpack disappeared with all my things inside after they killed me.
Will it be a problem or is the mod already?
I am playing in Minecraft version 1.15.2
the most recent version of your mod

**Comment by Tiviacz1337** [comment]
How did you die?

**Comment by Damii16** [comment]
I died from the dynamite explosion of a creature from a mod that I installed.

**Comment by Damii16** [comment]
I have just tried in a separate world the same sequence in which I died and the backpack if it appears to me, I don't know what happened then.
It must be my bad luck that I bugged in my survival and lost the most important thing :(
