### ISSUE TITLE
[Bug] [v4.0.5] Backpack can dissapear on death if backpackDeathPlace is set to true.

### ISSUE THREAD

**Issue by Edulml** [Tiviacz1337/Travelers-Backpack#130]
It happened when I died and there was not a single solid block to place the backpack on top of.

**Comment by Tiviacz1337** [comment]
Did you die from explosion?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3002962
