### ISSUE TITLE
[Feature request] Instead of shift+scroll to swap the tools in the backpack I think it should be keybind + scroll.

### ISSUE THREAD

**Issue by Edulml** [Tiviacz1337/Travelers-Backpack#131]
Often when I'm on a ledge I like to swap to whatever tool or block I want to use while moving around, but if I hit a tool I must stop moving, let go of shift, move the selector beyond the tool, and then hold back shift and move again. While trying to do that quickly I have often fallen down.

Even if I'm not on a ledge, it completely breaks the flow of whatever I was doing when I have to sneak and lose all of my speed.

**Comment by Tiviacz1337** [comment]
Won't be easy to add, but I'll definitely consider this

**Comment by Tiviacz1337** [comment]
Finally! https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3040845
