### ISSUE TITLE
Server owner functionality lacking

### ISSUE THREAD

**Issue by TheMightyMcGrew** [Tiviacz1337/Travelers-Backpack#132]
There are so many instances where backpacks just poof when players died. And I go gamemode 3 searchign for where these backpacks mightve decided to lay themselves down at, and at times i just cant find them. Some commands or something would be nice to have to find local backpacks that are placed, maybe even some kind of log system server side to see if it got destroyed, placed, etc. Was even contemplating the possibility of giving the players something to find their backpacks, much like corails Key ssystem would highlight the gravestone once the players were withing range of their graves. Maybe an item they spawn with to highlight the backpack once their within range of where they died and the backpack placed

**Comment by Tiviacz1337** [comment]
I found the issue that backpack many times just dissapear if creeper kills player by explosion. Already fixed on 1.12.2 new update should be available today I think. I'll also add chat message for player which died with backpack with coords

**Comment by TheMightyMcGrew** [comment]
yes I use this on my 1.12.2 modded server. Not sure if its a huge ordeal but iceandfire dragons also wreck these things, I personally dont have a problem with that becauses players should know the dangers of going up against a dragon with their valuable backpacks. A chat issuance for players backpack coords sounds perfect man thanks so much! Also apologies for one of my previous reports, i think i was a bit salty after the mess i had to clean up when we updated, i hadnt realized you changed the item ID's and had to rewrite all of reskillable for the new ID's. Which btw is that going to be an issue everytime now? Because I need plenty of heads up for players if backpacks will keep dissappearing after every update

**Comment by Tiviacz1337** [comment]
That was my fault too, because I haven't warned people at all before this, only in changelog. That was 1 time change and will not happen anymore. If you updated your version to 1.0.27+ then you're good.

**Comment by TheMightyMcGrew** [comment]
man thats super awesome, thanks so much. And big thanks for bringing such an awesome mod forward for people to use. Its devs like you that inspire me to learn to code this stuff myself. Keep doin what your doin and ill do my best to bring you any ideas or bugs i come across

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3002958
