### ISSUE TITLE
update the hose so it can fill drums or containers with the hose in hand.

### ISSUE THREAD

**Issue by chyper111** [Tiviacz1337/Travelers-Backpack#133]
It would be great if this mods hose could fill a drum or container. Oils is such a pain to collect without buildcraft or a machine mod and the hose dose almost exactly what i want but it wont add into a drum or tank. Please add this feature for 1.12

**Comment by Tiviacz1337** [comment]
Did you try taking oil to water bucket then insert to the tank?

**Comment by Tiviacz1337** [comment]
Well actually you can insert oil to the tanks. Just change hose mode to spill and rightclick on any tank

**Comment by chyper111** [comment]
it didnt work
