### ISSUE TITLE
The hose didn't work on and extra utilities drum.

### ISSUE THREAD

**Issue by chyper111** [Tiviacz1337/Travelers-Backpack#134]
I cant fill drums with oil from galacticarft. Its also doesnt pick up tar from metallurgy. it would be great if it could fill these with the fill option i tried but it didnt work

**Comment by Tiviacz1337** [comment]
I've just checked everything and it is working fine. Make sure your backpack tank is empty then change hose mode to _suck mode_ right-click on oil. Then change to _spill mode_ and shift + right-click on drum, works perfectly. Also picking tar is not an issue tooan

**Comment by chyper111** [comment]
thanks i guess i didnt understand the spill option
