### ISSUE TITLE
[1.12.2] Some Tools Blocked from Tool Slots

### ISSUE THREAD

**Issue by Flexico** [Tiviacz1337/Travelers-Backpack#135]
Specifically, the Thermal Expansion and IC2 wrenches, and Mekanism's Atomic Disassembler. The wrenches are the main tools I used those slots for!

**Comment by Tiviacz1337** [comment]
Did it work before? I'll tweak it in next release

**Comment by Flexico** [comment]
It worked in the old version for 1.7.10! I only just found out it got ported.

**Comment by Tiviacz1337** [comment]
Could you give me something like list of tools, which would you like to put in tool slot? So I could test if it works with those tools before updating mod on site.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3040845
