### ISSUE TITLE
Backpack/ armour issue:

### ISSUE THREAD

**Issue by FusionGenesis** [Tiviacz1337/Travelers-Backpack#136]
When I put the backpack on, it shrinks my armour so it looks like there is a mini man inside of your player, and there is also a thing in which when you hold an item while wearing the backpack it shrinks the item. It doesn't effect gameplay, but is annoying because it just doesn't look good. If it DOESN'T glitch out the armour while wearing the backpack, in which it won't for the next 2 days once you keep on downloading a NEW version, it still effects swimming, as the armour does not follow the player's movement, as the armour will keep on doing a WALKING animation, but the actual player is doing a swimming one.
I don't know if it is a mod incompatibility or something, but if it is, then pls tell us. And if not pls fix the armour bug. I also can't use the different types of backpacks, and can only use the default one. And I can't put potions in the tanks. pls fix these. I can't send screens here so I can't show you unless you tell me to send a screen somewhere else. 
It's a great mod, however. But the thing is just the visual armour glitch.

**Comment by Tiviacz1337** [comment]
It must be compat issue, also you can't put potions because it's niy same as custom backpacks

**Comment by FusionGenesis** [comment]
[image: Screen Shot 2020-07-15 at 15.39.54.png]
[image: Screen Shot 2020-07-15 at 15.41.28.png]
[image: Screen Shot 2020-07-15 at 15.41.10.png]

**Comment by FusionGenesis** [comment]
"Btw my friend has the same glitch but he really likes it."
---------- Forwarded message ---------
From: GalaxisEliminator X <galaxiseliminatorx@gmail.com>
Date: Fri, Jul 17, 2020 at 8:29 AM
Subject: Re: [Tiviacz1337/Travelers-Backpack] Backpack/ armour issue: (#136)
To: Tiviacz1337/Travelers-Backpack <
reply@reply.github.com>


[image: Screen Shot 2020-07-15 at 15.39.54.png]
[image: Screen Shot 2020-07-15 at 15.41.28.png]
[image: Screen Shot 2020-07-15 at 15.41.10.png]

**Comment by Tiviacz1337** [comment]
I can not see images
