### ISSUE TITLE
[Bug] Sleeping bags are pushable by pistons, allowing to dupe them.

### ISSUE THREAD

**Issue by Lgmrszd** [Tiviacz1337/Travelers-Backpack#137]
Each half of a sleeping bag can be pushed by piston. If it is pushed entirely, it remains functional and stays after removing backpack, allowing players to create free unlimited non-resetting spawn point beds.
[Screenshots](https://imgur.com/a/JfIEROM)

This bug persists if only Traveler's Backpack installed.
MC Version: 1.12.2
Forge version: 14.23.5.2854

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3040845
