### ISSUE TITLE
[Suggestion] Keep backpack upon death option

### ISSUE THREAD

**Issue by Vulant** [Tiviacz1337/Travelers-Backpack#138]
Allow a setting in the config to allow backpacks to stay in a player's inventory upon death, or if the backpack is worn, to be compatible with a gravestone mod (or tombstone).

Possible issue?: With CoFH Core's Soulbound enchant, the backpack does not stay in the player's inventory if it is worn, but does work if it is just in the player's inventory like any other item.

**Comment by Tiviacz1337** [comment]
Only option to keep backpack in inventory is to enable keepInventory gamerule
