### ISSUE TITLE
adventure backpack suddenly inaccessible

### ISSUE THREAD

**Issue by astralamari** [Tiviacz1337/Travelers-Backpack#141]
Hello! i was using my adventure backpack while it was on my back and i inserted some very important items... lo and behold for whatever reason i cant open it again. i can open other backpacks ive spawned in but the one on my back i cant get to! any help?

**Comment by Tiviacz1337** [comment]
version?

**Comment by astralamari** [comment]
most recent! but i figured out the problem: there was too much data stored in a bag of yurting (a bag which holds structures) and the bag couldnt open
