### ISSUE TITLE
Can't See Backpack

### ISSUE THREAD

**Issue by Matemarthur** [Tiviacz1337/Travelers-Backpack#142]
Recently I installed Emoticons Mod and its dependency McLib. 
Today I just downloaded TB mod and works fine except for the part where the backpack must be visible on the back of Steve, thing that is not happening.  

I tried adjusting the mod in the mod options but found nothing useful. 

Please help and thank you. The mod is wonderful

**Comment by topkapi17** [comment]
The same happens to me. You can't see the backpack on Steve's back. Could you please tell me how to make it look?

**Comment by Matemarthur** [comment]
I just found a solution, lol. The problem was the Emoticons Mod

Go to Emoticons mod settings (CTRL+0) and check the box "Disable non-emoticon animation". That will cause walking/swimming/flying animations disappear and backpacks, elytras and any other stuff like zombie Heads or weird helmets will be visible again. 

But remember, this only works in the mod config of Emoticons Mod (and his dependency, ie, "McLib")

**Comment by Tiviacz1337** [comment]
There's nothing I can do about it, tweak config
