### ISSUE TITLE
Keybindings do not work after update to newer version [1.12.2]

### ISSUE THREAD

**Issue by Lolbyte64** [Tiviacz1337/Travelers-Backpack#144]
I updated the mod (1.12.2 version) and now I can't access my backpack while it's on my back

**Comment by Tiviacz1337** [comment]
You can try resetting the keybindings

**Comment by Lolbyte64** [comment]
Thanks, I'll try it out

**Comment by Tiviacz1337** [comment]
Did it fix the issue?

**Comment by Lolbyte64** [comment]
Yes, yes it did, thank you
