### ISSUE TITLE
Please bro could you put the mod but for 1.14.4.

### ISSUE THREAD

**Issue by frankzproxd** [Tiviacz1337/Travelers-Backpack#145]
Bro could you do it for version 1.14.4 I would really thank you very much thank you very much I hope you see it is one of the best mods I have seen.

**Comment by Tiviacz1337** [comment]
Why not move to 1.15.2 already, it's latest supported version of Minecraft for mods

**Comment by frankzproxd** [comment]
Is that there are mods that are only for 1.14.4 and I would like to know if you can do them bro):

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3042329

**Comment by frankzproxd** [comment]
Thanks bro y soy peruano :v
