### ISSUE TITLE
[1.15.2 - Forge 31.2.36] Armor is not rendered correctly

### ISSUE THREAD

**Issue by Jergeric** [Tiviacz1337/Travelers-Backpack#146]
Aloha, we have the problem that the armor is not rendered correctly as soon as the backpack is on.

If I can help with anything, just let me know^^

In the attachment you will find our system details, mod list and a screenshot of the problem.

![2020-08-16_08 25 43](https://user-images.githubusercontent.com/33686596/90328578-aa67a480-df9d-11ea-91aa-19a4717a55b2.png)

[System Details.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/5080132/System.Details.txt)

**Comment by Tiviacz1337** [comment]
Could you send me the modpack?

**Comment by Jergeric** [comment]
https://www.curseforge.com/minecraft/modpacks/magrathea-the-rise

**Comment by Tiviacz1337** [comment]
I've checked all mods from latest update and none of them cause the issue, could you check rest of them? I don't use twitch launcher

**Comment by Tiviacz1337** [comment]
#136

**Comment by Lumpya** [comment]
I have the same issue too, i started uninstalling mods one by one, and as i just uninstalled the Obfuscate Lib, the render error is gone. It may have some render conflicts with the mod?
