### ISSUE TITLE
no puedo abrir la mochila.

### ISSUE THREAD

**Issue by XI65IX** [Tiviacz1337/Travelers-Backpack#147]
no puedo abrir la mochila de calamar, para abrir la mochila le asigne la tecla K.
me paso después de ir al aether, mod de aether haven, no se si al meter algo de ese lugar se buggeo pero en el aether podía abrirla.
ayuda!

**Comment by Tiviacz1337** [comment]
Version of mod?

**Comment by XI65IX** [comment]
last one
