### ISSUE TITLE
Conflict with Invtweaks [1.16.2]

### ISSUE THREAD

**Issue by Mikeliro** [Tiviacz1337/Travelers-Backpack#149]
Minecraft: 1.16.2
Forge: 33.0.21
Mod: 5.1.0
 Invtweaks: 1.0.0

When I click to organize my backpack inventory in the Invtweaks mod. The item in the bucket slot is multiplied.

Video with the bug.
https://www.youtube.com/watch?v=GV2kKJvqqMw&feature=youtu.be

**Comment by Mikeliro** [comment]
The bug persists in version 5.1.1 of the mod, but only with buckets.

**Comment by Tiviacz1337** [comment]
Fixed in dev on 1.16.4

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3152521
