### ISSUE TITLE
1.16.1 - Backpack lose all the inv after player died

### ISSUE THREAD

**Issue by SlamVzla** [Tiviacz1337/Travelers-Backpack#153]
Hi.

After i die in the game, i found the backpack place it in the floor but it was complete empty

**Comment by Tiviacz1337** [comment]
I can't reproduce this issue

**Comment by Tiviacz1337** [comment]
Probably fixed

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3050208
