### ISSUE TITLE
Backpack not useable 16.2

### ISSUE THREAD

**Issue by Schoolisoutfan** [Tiviacz1337/Travelers-Backpack#156]
I'm using TravelersBackpack-1.16.2-5.1.1.jar with  forge-1.16.2-33.0.22 but I couldn't wear the bagpack. The only slot which works is the hand. But the 3 symbols from your modpage doesn't appear.

**Comment by Tiviacz1337** [comment]
Try using /kill then equip the backpack since 1.16.2-5.1.0 version was a bit bugged, so that may be the issue.
