### ISSUE TITLE
Hose Bug [1.16.2]

### ISSUE THREAD

**Issue by Mikeliro** [Tiviacz1337/Travelers-Backpack#157]
Minecraft: 1.16.2
Forge: 33.0.21 - 33.0.37
Mod: 5.1.0 - 5.1.1

If you use the item "Hose" in the left hand, it disappears.
If you have an item in your right hand it multiplies that item when it disappears. Note: Only visually.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3150799
