### ISSUE TITLE
[1.16.2] Items Deleted when Inserted into a Backpack

### ISSUE THREAD

**Issue by Flexico** [Tiviacz1337/Travelers-Backpack#159]
MC: 1.16.2
Forge: 33.0.32
TB: 5.1.1

When another block tries to insert something into the backpack (I tested it with Hoppers, Droppers, and Computercraft Turtles) the item(s) simply vanish!

**Comment by Tiviacz1337** [comment]
https://github.com/Tiviacz1337/Travelers-Backpack/issues/198
