### ISSUE TITLE
[1.15.2] Placing a Forbidden Arcanus Edelwood Bucket into the bucket slot produces an iron bucket

### ISSUE THREAD

**Issue by IceDragon200** [Tiviacz1337/Travelers-Backpack#160]
An accident happened, I had an edelwood bucket with water, placing it into the tank slot produced an iron bucket instead of a empty edelwood bucket.

I'm not sure if it's an issue with FA or here, but I'm reporting it as found.

__Versions__

* Travelers Backpack 1.15.2-4.0.6
* Forbidden Arcanus 1.15.2-1.5

**Comment by Tiviacz1337** [comment]
Sorry but there's nothing I can do about it. It means that container bucket for Edelwood water is simply iron bucket instead of proper one
