### ISSUE TITLE
[Feature request] Easier sleeping bag

### ISSUE THREAD

**Issue by Yupoman** [Tiviacz1337/Travelers-Backpack#162]
It would be great if the sleeping bag could be used quickly (with a key or something). I know that as it is it is more realistic, but having to open the inventory, disassemble the backpack, place it on the floor, open the inventory again, unfold the bag, lie down, break the backpack and then equip it again, is extremely tedious.

**Comment by Tiviacz1337** [comment]
I want to keep it like it is. I don't think it's a big deal it takes 5 seconds to do.. Also you can just shift+right click to instantly equip your backpack from the ground
