### ISSUE TITLE
[1.12.2] Hud icons don't update when cycling through tools in the green slots. When you open the backpack after cycling through tools... it updates correctly.

### ISSUE THREAD

**Issue by Z-Tunic** [Tiviacz1337/Travelers-Backpack#163]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 2
jei_1.12.2-4.15.0.291
TravelersBackpack-1.12.2-1.0.34

-----

Store an Axe, Shovel in the green slots within any back[ack, then have a Pickaxe in your main-hand. Now... cycle through the tools and you will notice that the icons don't change despite the tool changing in your main-hand. When you open the backpack... it'll update the tool icons. This bug didn't occur in previous versions.

**Comment by Advewave** [comment]
same happens with me

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3150850
