### ISSUE TITLE
【BUG 1.15.2】墓碑mod并未收录此背包，因此，死亡的时候，身上的物品会留在墓碑mod，而背包则掉落

### ISSUE THREAD

**Issue by love309099225** [Tiviacz1337/Travelers-Backpack#164]
【BUG 1.15.2】墓碑mod并未收录此背包，因此，死亡的时候，身上的物品会留在墓碑mod，而背包则掉落
[BUG 1.15.2] This backpack is not included in the Tombstone mod. Therefore, when you die, your items will stay in the Tombstone mod and the backpack will drop.

**Comment by Tiviacz1337** [comment]
Nothing I can do about it
