### ISSUE TITLE
[1.12.2] Game freezes when placing fluids from hose into cauldron

### ISSUE THREAD

**Issue by lgnmcrules** [Tiviacz1337/Travelers-Backpack#165]
The game freezes when trying to put modded liquids that can normally go into a cauldron into a cauldron via the spill mode on the hose.  

For example, the golden apple juice from Tough as Nails can normally be placed into a cauldron but freezes when attempted via the hose and the liquid in the backpack.  (Also you can't drink it, but that's not the issue but more of a suggestion)

**Comment by Tiviacz1337** [comment]
Do you have any logs?
