### ISSUE TITLE
My backpack transforms from iron golem to normal

### ISSUE THREAD

**Issue by WoxemYT** [Tiviacz1337/Travelers-Backpack#166]
A creeper kill me, then when I go to my backpack It wasnt in the floor like always, but when I look at my inventory now I have normal backpack, and all the things I put inside the golem backpack disapered. 
What happened?

**Comment by Tiviacz1337** [comment]
do you have any logs when this happened?

**Comment by WoxemYT** [comment]
Sorry I have not any logs of the incident
