### ISSUE TITLE
[1.16.2] Missing Texture and backpacks

### ISSUE THREAD

**Issue by Spews** [Tiviacz1337/Travelers-Backpack#168]
Forge: 33.0.61
Mod: 1.16.2-5.1.1

When in hand or in the world doesn't have texure but it's show when is on the back

![2020-09-23_12 30 01](https://user-images.githubusercontent.com/33796179/94048345-fece2300-fd98-11ea-8290-076875f19f2a.png)

And when i use JEI to see items from the mod I can only see the Standard and some stuff

![2020-09-23_12 30 16](https://user-images.githubusercontent.com/33796179/94048533-45238200-fd99-11ea-81e3-fcf7e292cf28.png)

also couldn't fin the cofig file in any folder

**Comment by Tiviacz1337** [comment]
any logs?

**Comment by Spews** [comment]
Any log but I just realized that you get the bug if you start from Twitch I make a modpack on the normal laucher and it run okay.

**Comment by Rmdhn1** [comment]
i tried starting on a normal launcher and still got the issue

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3150799
