### ISSUE TITLE
Missing Backpack Textures

### ISSUE THREAD

**Issue by Jacob94DX** [Tiviacz1337/Travelers-Backpack#170]
Every time I enter a world the backpack's textures disappear but only the block model and the item model. The backpack has it's textures when it's on the back. 
![2020-09-29_17 53 59](https://user-images.githubusercontent.com/72108739/94625368-3ac42500-027e-11eb-912c-c203cfaa9844.png)
![2020-09-29_17 54 59](https://user-images.githubusercontent.com/72108739/94625373-3dbf1580-027e-11eb-945f-d48121190337.png)
And here's the log:
[latest.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/5302414/latest.log)

The Backpack's textures reappear when I reload the textures, but doing that takes a minute or so and I have to do this every time I enter a world so the textures reappear.

**Comment by Tiviacz1337** [comment]
Send me your modpack, I cant reproduce this issue, please if you can send whole modpack not only mods via discord dm

**Comment by Jacob94DX** [comment]
I don't have the mod in a modpack but here's a zip containing most of the mods I have
[mods.zip](https://github.com/Tiviacz1337/Travelers-Backpack/files/5379175/mods.zip)

**Comment by idkwhatislife** [comment]
> Send me your modpack, I cant reproduce this issue, please if you can send whole modpack not only mods via discord dm

so im using curios to use a toolbelt mod, and that causes the backpack to lose its texture just like Jacob, but still functions the same

**Comment by Rmdhn1** [comment]
i have a feeling its the Curse app, i don't know since i also have the same problem but the only mods i have that Jacob also has is Sound Filter and JEI, Disabled them still didn't work

**Comment by Rmdhn1** [comment]
Nope, tried just using forge from the normal launcher, didn't work

**Comment by Rmdhn1** [comment]
BRUH THERE'S NO TEXTURES FOR IT WHEN I OPEN THE JAR FILE LMFAOOOOO

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3150799
