### ISSUE TITLE
Unable to open backpack

### ISSUE THREAD

**Issue by DemonFromHeaven** [Tiviacz1337/Travelers-Backpack#173]
During gameplay, my backpack suddenly stopped opening. Unsure of what caused it, here is the error log (pastebin) from the server console every time I try opening it.

https://pastebin.com/Mdsr58AZ

**Comment by Tiviacz1337** [comment]
Game version?

**Comment by DemonFromHeaven** [comment]
> Game version? any mods?

Game version 1.16.1, I realized this might be an issue in compression. My best guess would be:

I have the Apotheosis mod which lets me mine spawners using silk touch. I had around 10 or so spawners inside my backpack and spawners contain a lot of information (Type of mob, min/max spawn rate, player distance, max entities, spawn range, etc). It might be _too much_ information to be compressed in the GUI and hence the size might have increased the cap.

I don't believe any other mod has anything to do with it since I only had some vanilla objects and apotheosis spawners in the backpack, so I will not bother listing all of them here. Thank you for the reply!

**Comment by Flexico** [comment]
I have the same problem in 1.16.3, and I also have Apotheosis! And some testing tells me that yes, the problem seems to be caused by too much information saved in the backpack.

**Comment by Tiviacz1337** [comment]
Probably the compound on the stack is too small to contain all this data about spawners. I can't do much about this though.
