### ISSUE TITLE
Cannot use the hose (1.12.2)

### ISSUE THREAD

**Issue by EvyonHD** [Tiviacz1337/Travelers-Backpack#176]
Whenever I try to change the hose mode, it just switches to the other Hotbar slot and not the new hose form. When I press N, it just changes the tank.

**Comment by ColaLiao** [comment]
change hose mode you need hold hose, and press shift button, than rolling your middle button of mouse.

**Comment by DGSitze** [comment]
I am having the same problem. doing the correct input Shift+mouse wheel while holding hose but it doesnt change mode, it just moves to the next hotbar slot.
and as said a while ago a hose in your offhand /shield hand will delete the hose....

**Comment by ColaLiao** [comment]
OK, i know what happen now,
because the mod change the swap button, so now you need press "Z" +mouse wheel.

**Comment by Goodman420** [comment]
Still dont works to me.

**Comment by Tiviacz1337** [comment]
First you have to attach hose to backpack (By clicking Right-click) then click "Z" (Default) + Mouse wheel
