### ISSUE TITLE
1.15.2 Inventory sorting buttons from Quark are weird with backpack UI

### ISSUE THREAD

**Issue by Hiranus** [Tiviacz1337/Travelers-Backpack#179]
Forge: 31.2.46

This is only mod that makes Quark's sorting buttons go weird. Is it possible that this mod doesn't report its inventory size properly somewhere?

![image](https://user-images.githubusercontent.com/6943031/99247258-ffb68a80-2806-11eb-80c0-ce5d7b59af1d.png)

**Comment by Tiviacz1337** [comment]
This version should make button disappear, but who knows https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3150799
