### ISSUE TITLE
Cannot equip backpack or access inventory with hotkeys

### ISSUE THREAD

**Issue by Fenius** [Tiviacz1337/Travelers-Backpack#181]
This started after I bound Blood orb from Blood Magic mod (BloodMagic-1.16.3-3.0.1-6). Only thing I can narrow it down to. Hot keys no longer work when trying to access backpack inventory or equip it. Changing to new hot keys does not work either. I can access inventory when placed on the ground. I can use the sleeping bag when placed on the ground. Icon to equip when on the ground is not in bag inventory screen. Using Forge 1.16.4-35.1.0.  Also, before this I was unable to swap weapons regardless of which hot key was bound. This was ongoing before the orb was bound. No errors logs no crash. Mod appears to load fine on server and client. Appears to maybe a Keypair generating error, not sure, not a programming expert, in latest log file.

[latest.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/5589895/latest.log)

[debug.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/5589891/debug.log)

**Comment by CharleeToombs** [comment]
I can't equip it and i just made the backpack on my new server... but I can place it to open it/use the sleeping bag... I don't have the other mod the op indicated though?.. it doesn't have an icon for equipping it? I'm on 1.16.4, and using version 5.3.1 :D

**Comment by Tiviacz1337** [comment]
Well, probably data that is stored in backpack's stack is exceeded, therefore you can't open backpack, while it reads from stack's nbt. There was an issue like this. Sadly, I can't do much about this.

**Comment by CharleeToombs** [comment]
I noticed I was able to view the content only when I right clicked the backpack on my hotbar when nothing was nearby.. so try that? Also the tool swap works if you press shift+[letter designation]
