### ISSUE TITLE
Yoooo.... so why do you have the curseforge page lieing...

### ISSUE THREAD

**Issue by RonGoryMore** [Tiviacz1337/Travelers-Backpack#182]
First off, absolutely amazing mod, never play without anymore, the craft on the go aspect is great.    but....
Definitely full of bs... you didnt incorporate any of the special backpacks, and there is no way to cycle hose modes... the whole "hold shift and scroll while holding the hose" just scrolls items. as well as holding the tank button, just cycles them real fast. 
super bummed about both of these. real pain in the ass having to use buckets all the time. could you at least incorpate a command to change it or something if not a more practical fix like making the mechanic work properly. or even more simple, if you place the hose in the bucket slot, automatically switches to blow mode while equipped that way, also why is there not a slot on the backpack for the hose.. 
and the customizable aspect of the extra backpacks... really sad thats not a thing. it would negate me using several other mods for similar effects... please fix or fill me in on this. im down to help if thats part of the issue, hands down one of my favorite mods. gobber 2 being a close tie

**Comment by RonGoryMore** [comment]
oh.. ok... i see you've updated the page.. still super lame man.. not planning on it or just haven't had the time? how about the hose mode issue, not planning on fixin that either?

**Comment by Tiviacz1337** [comment]
1. Custom backpack will eventually be available, but not now since textures changed. I'm not going to use old-textured backpacks in latest versions.
2. I can't reproduce the hose issue on my own. Maybe it's mod compatibility issue

**Comment by RonGoryMore** [comment]
Weird. Thanks for the response. I really dont know why it wouldn't work...
I'll try running it with just that on one day and see if that helps. Any
other suggestions maybe? I remapped keys but even when I default them it
still doesn't let me scroll through modes... I know your probably like
"fuck you dude" but simple fix maybe set so that attack is spray and right
click is suck... as opposed to being able to "punch" things with it or have
to switch modes at all... just a thought.. take it easy,
thanks for the explanation..

**Comment by RonGoryMore** [comment]
Oh, also I think it had said something about there being a "hose mode"
control option.. I only have backpack inventory, swap tool, and toggle hose
tank. There is no option for hose mode,

**Comment by Tiviacz1337** [comment]
IT should work with swap tool keybind + scroll up & down

**Comment by RonGoryMore** [comment]
Haha, yeah I figured it out like 20 minutes after I emailed you back
ironically. That was like the one thing I hadn't tried.. think I might be
burnt. Thanks dude, appreciate it.
