### ISSUE TITLE
Shift-middle scroll scrolls the toolbar and does not change the mode of the hose 1.12

### ISSUE THREAD

**Issue by DangerouslyFunny** [Tiviacz1337/Travelers-Backpack#184]
Shift-middle mouse scroll scrolls the toolbar and does not change the mode of the hose 1.12

**Comment by Tiviacz1337** [comment]
The keybind changed [default Z] check your controls

**Comment by Tiviacz1337** [comment]
@DangerouslyFunny did you check it?

**Comment by Coraline77447** [comment]
I was in the same situation as DangerouslyFunny but in 1.16.4 until I read your reply to DangerouslyFunny and it is Z to change the mode of the hose, so it's working as intended.
