### ISSUE TITLE
1.12.2 problems

### ISSUE THREAD

**Issue by RedWolfGaming** [Tiviacz1337/Travelers-Backpack#185]
1. When I fill the backpack even once, it makes it show that it's full and acts like it (until placed down) giving infinite water and lava just for 1 bucket of it

2. with the lava in it, the backpack doesn't even glow

3. backpacks (like the ender dragon) don't give buffs for some reason

4. can't remember other bugs...

**Comment by Tiviacz1337** [comment]
well, I can only refer to 2. I could change this, but it'd look stranger than it looks now so. Other are not reproducible by me
