### ISSUE TITLE
Backpack dissapearded in void.

### ISSUE THREAD

**Issue by Rayo183** [Tiviacz1337/Travelers-Backpack#186]
I accidentally got into spectator mode and fell into the void. (And died) But my backpack appeared into the void. And now I can't get it. (It is a problem because it was filled with all my things from survival). Please tell me if you know how to get my backpack back. :(

**Comment by Tiviacz1337** [comment]
I don't think there's any chance to get it back tbh, you fell into the void so you'd lose it anyway
