### ISSUE TITLE
[1.12.2] Dupe Bug

### ISSUE THREAD

**Issue by Focamacho** [Tiviacz1337/Travelers-Backpack#187]
Forge Version: 1.12.2-14.23.5.2854
Traveler's Backpack Version: 1.12.2-1.0.34
Video: https://youtu.be/ukXeU6BkPjI

Explanation: You can dupe items using backpacks from this mod.
Steps:
1. Get two backpacks and put them in your hotbar.
2. Open a backpack and put some items inside.
3. Hover the second backpack with your mouse and press the number to change slots with the other backpack.
4. Drop the backpack you are hovering.
5. Take the items from the backpack that is open.
6. Take the other backpack from the ground and take the same items from it.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3150850
