### ISSUE TITLE
water and lava ui is out of place and duplicated

### ISSUE THREAD

**Issue by Xcc14** [Tiviacz1337/Travelers-Backpack#189]
in the travelers backpack it shows the water and lava levels out of the slots
![Badlion Client Screenshot 2020 12 09 - 13 03 14 23](https://user-images.githubusercontent.com/75735576/101633378-0c518b80-3a1f-11eb-903a-4c6f3bbdaaae.png)

**Comment by jeffreyrey108** [comment]
I have the same problem
my forge version is :35.1.13
Please help me

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3150799
