### ISSUE TITLE
liquids duplicate visualy

### ISSUE THREAD

**Issue by acqbmn** [Tiviacz1337/Travelers-Backpack#191]
![image](https://user-images.githubusercontent.com/75390627/102020628-1514cb00-3d59-11eb-9d09-4008c6f8dc11.png)
it doesn´t matter the liquid

**Comment by Tiviacz1337** [comment]
Version of the game?

**Comment by acqbmn** [comment]
1.16.4

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3150799
