### ISSUE TITLE
Backpack & contents disappearing when broken

### ISSUE THREAD

**Issue by DropkickPadawan** [Tiviacz1337/Travelers-Backpack#194]
I'm playing with a few mods, one of them being Dungeoncrawl version 2.2.2, and while running through a dungeon I placed the backpack down in order to place some of my loot inside, and when I broke it to pick it back up, the item appeared, then phased into the wall and disappeared.

**Comment by Tiviacz1337** [comment]
That's more like unlucky, it's definitely not a bug. If you can reproduce this issue, write steps here.
