### ISSUE TITLE
1.12.2 NPE

### ISSUE THREAD

**Issue by kreezxil** [Tiviacz1337/Travelers-Backpack#196]
CLIENT CRASH REPORT: https://gist.github.com/kreezxil/a9eaaed1235d129e57dc1195240eb933
Forge 1.12.2-14.23.5.2854

I don't know what my player was doing to be exact. When they do, I'll make sure to get more information.

**Comment by bjonkk** [comment]
I was opening some backpacks that were left on the floor

**Comment by Tiviacz1337** [comment]
Any steps how to reproduce?
