### ISSUE TITLE
[1.16.4] Items deleted when inserted into placed backpack

### ISSUE THREAD

**Issue by Flexico** [Tiviacz1337/Travelers-Backpack#198]
Whether it's a hopper, dropper, pipe or mining turtle, any items automatically inserted into a placed backpack get deleted. Items can be pulled out, but not inserted.

MC 1.16.4
Forge 35.1.13
TB 5.3.1

**Comment by Tiviacz1337** [comment]
I'll have to fully re-write backpack inventory, then It'll be possible

**Comment by Tiviacz1337** [comment]
In the incoming update (5.3.3). Up and down sides of the backpack will be responsible for normal inventory (without tool or bucket slots) Front and rear sides for crafting inventory. Also side where is each fluid tank, is responsible for this tank

**Comment by Flexico** [comment]
Oh, most excellent! =D Did you really re-write the backpack inventory in just 2 days?

**Comment by Tiviacz1337** [comment]
Yes, I thought it would be more difficult. But it turned out it's pretty easy :D

**Comment by Flexico** [comment]
Well awesome! ^_^

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3152521
