### ISSUE TITLE
1.16.4 texture failure and liquids are visually duplicated 

### ISSUE THREAD

**Issue by templar742** [Tiviacz1337/Travelers-Backpack#199]
I tried it and it works, but the backpack has no textures and the visualization of the liquids is doubled

![2020-12-23_22 26 04](https://user-images.githubusercontent.com/76543692/103056280-e4137200-4572-11eb-922d-b59dda3d2ac0.png)

**Comment by Tiviacz1337** [comment]
Do you play single or multiplayer?

**Comment by Raktul842** [comment]
Hi, i play single and have the same bug 
I am plaining to use it in multiplayer too

**Comment by TRBZN61** [comment]
i have that same issue in Version 1.16.3, too.
what means "Fiexed in dev"?
I need it for 1.16.3 pls

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3150799
