### ISSUE TITLE
1.16.4 Emptying Tank Crash

### ISSUE THREAD

**Issue by XxPowerEyexX** [Tiviacz1337/Travelers-Backpack#200]
I am having a strange issue. i have 4 buckets of water in my backpack tank and im using the hose to quickly fill a trench and everythig is fine until i use all 4 buckets. 

MC Version: 1.16.4
Forge Version: 35.1.10
Traverlers Backpack Version: 5.3.1
Crash Log Txt Dump: [https://pastebin.com/VvrXGtfe](url)

**Comment by Tiviacz1337** [comment]
Please provide new link to crashlog, this does not work

**Comment by Tiviacz1337** [comment]
When does it happen?

**Comment by XxPowerEyexX** [comment]
i just updated to the latest version available on Curse Forge and it seems to be fixed. Im unsure if it was something i was doing wrong or something coded wrongly but its all good now.
