### ISSUE TITLE
Feature/Bug: Tooltip integration in backpack

### ISSUE THREAD

**Issue by narroc** [Tiviacz1337/Travelers-Backpack#202]
When the backpack UI is open, items in the backpack or main inventory do not have any tooltips. Can these be enabled? Should they already exist and are just broken?

**Comment by Tiviacz1337** [comment]
I realized it yesterday :P

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3150799
