### ISSUE TITLE
[1.16.4] Cannot display hover information when in backpack gui

### ISSUE THREAD

**Issue by ScottCTD** [Tiviacz1337/Travelers-Backpack#203]
![image](https://user-images.githubusercontent.com/35100768/103206633-3cfa5600-4937-11eb-977b-f0a3bedc7586.png)
As the image above says: My mouse is hovering on the backpack item, but its information does not appear.

My forge version is 35.1.15
Mod Version is 1.16.4-5.3.1

I tested it with only your mod and forge.
![image](https://user-images.githubusercontent.com/35100768/103206718-7763f300-4937-11eb-80cf-66b3cbb74e1f.png)

Thanks for making this mod! Hope you could fix it, although it is not a major issue.

**Comment by Tiviacz1337** [comment]
Use 5.3.2
