### ISSUE TITLE
wont work on server (still)

### ISSUE THREAD

**Issue by LithTheKitten** [Tiviacz1337/Travelers-Backpack#205]
even with the updated version for 1.12.2, NONE of the backpacks will work. i cant place them, or equip them, this only happens on a server. is this intentional? or a bug, because it works perfectly fine on 1.16.4, yet that version only has 1 bag. 

1.12.2
backpack 1.0.35
forge 14.23.5.2855

**Comment by Tiviacz1337** [comment]
Could you record video of it or something?

**Comment by LithTheKitten** [comment]
> Could you record video of it or something?


![ezgif-6-f663db5d6ab2](https://user-images.githubusercontent.com/41239850/103237588-a5344200-490d-11eb-903c-b1ec2bab71ab.gif)

**Comment by LithTheKitten** [comment]
it wont let me send anything past 10MB so this is the best i can do

**Comment by LithTheKitten** [comment]
cant drop the bags with Q (drop item button), cant place, or equip, cant even toss the bags away, they just get deleted

**Comment by Tiviacz1337** [comment]
Are you sure you installed the mod on the server? O.o

**Comment by Tiviacz1337** [comment]
From this video, it seems that you installed the mod only on client.

**Comment by LithTheKitten** [comment]
its in the server's mod folder and client side mod folder
it works perfectly fine when its on a single player world but on the server it wont work

**Comment by Tiviacz1337** [comment]
![image](https://user-images.githubusercontent.com/34790800/103240353-683d6f00-4950-11eb-8e70-6b4afcfe1525.png)
We've just tested it on the server, everything works well. Please check your mods folder.
