### ISSUE TITLE
[1.16.4-5.3.3] Bag duplication

### ISSUE THREAD

**Issue by WindFox** [Tiviacz1337/Travelers-Backpack#206]
There is an issue where if you shift+R-Click a placed pack to pick it up, it gets equipped AND makes a copy of itself into the inventory.

The copy is a new bag with the same inventory, allowing for item duplication.

Tested with a minimal pack with this and JEI only.

Steps:
1. Create new world
2. Obtain a backpack
3. Shift-click bag onto the ground
4. Shift+r-click the back to pick it up.
5. Notice bag is equipped (by pushing hotkey) AND another bag is in the player inventory (or on the ground if not close enough)
6. ...profit! (Literally.)

**Comment by Tiviacz1337** [comment]
Does this happen every time? Are you spawn protection area on server?

**Comment by WindFox** [comment]
Every time.
Anywhere in the world. Any dimension. Survival and creative. (Granted you kinda expect it on creative when placing, but not picking up)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3155224
