### ISSUE TITLE
[1.16.4] Putting Immersive Engineering’s Treated Wood crates in the bag causes the bag to not be openable in any way!

### ISSUE THREAD

**Issue by TheUnforgotten22** [Tiviacz1337/Travelers-Backpack#208]
I lost all my shit everything.  I was moving bases and I put all my stuff in the crates because they are like wooden shulker boxes and I put all of them in the backpack and then when I got to my new base I can’t open the bag again... rip please fix this!

**Comment by Tiviacz1337** [comment]
It seems that packet is too big to be sent. You can type /kill and get items back by accessing backpack on the ground

**Comment by Tiviacz1337** [comment]
I've tested it by myself and figured out what was the problem

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3155224
