### ISSUE TITLE
Bucket slot bug - Travelers Backpack [5.3.4]

### ISSUE THREAD

**Issue by Mikeliro** [Tiviacz1337/Travelers-Backpack#211]
If you put a Bucket in the bucket slot and remove the backpack from the back, the buckets are duplicated.

**Comment by Mikeliro** [comment]
![image](https://user-images.githubusercontent.com/54607000/103448792-3fcdb180-4c7d-11eb-9933-87a22024c97a.png)
![image](https://user-images.githubusercontent.com/54607000/103448801-625fca80-4c7d-11eb-83aa-26a240cbf571.png)
![image](https://user-images.githubusercontent.com/54607000/103448810-7d323f00-4c7d-11eb-91c6-1a7d7a0dea7d.png)
![image](https://user-images.githubusercontent.com/54607000/103448818-9509c300-4c7d-11eb-923f-1fe6c5d7d9ff.png)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3165173
