### ISSUE TITLE
empty tank and empty jar

### ISSUE THREAD

**Issue by touhouzun** [Tiviacz1337/Travelers-Backpack#213]
forge: 14.23.5.2854
minecraft 1.12.2
mods used:
![捕获](https://user-images.githubusercontent.com/31458903/103470003-596b1800-4da7-11eb-88af-2db49a5a134c.PNG)
steps:
1. cooking for blockheads milk jar, traveler's backpack, hose (no liquid required)
2. place the empty jar, equip backpack, enable hose
3. hose in pouring mode (?) （外泄模式）
4. right-click while backpack's tank is empty
5. crash report:
[crash-2021-01-03_09.35.32-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/5761088/crash-2021-01-03_09.35.32-client.txt)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3165173

**Comment by touhouzun** [comment]
@Tiviacz1337 My dear, cooking for blockheads and traveller's backpack both have mc1.16.4 versions, but I didn't test with them at all ... Mine is mc1.12.2 _(:з)∠)_

**Comment by Tiviacz1337** [comment]
1.12.2 is no longer supported
