### ISSUE TITLE
Elytra incompatibility render option while using Curious Elytra Mod

### ISSUE THREAD

**Issue by GatoLeyo** [Tiviacz1337/Travelers-Backpack#214]
Turning off the render of the backpack while wearing elytra doesn't work if the elytra is on the back slot of the Curios API. Link to the API: https://www.curseforge.com/minecraft/mc-mods/curios

**Comment by Tiviacz1337** [comment]
With new version, travelers backpack will be compatibile with curios, therefore I won't make curios elytra disappear
