### ISSUE TITLE
[Feature ideas] Ability suggestion for remaining backpacks

### ISSUE THREAD

**Issue by Tenshi-Sora** [Tiviacz1337/Travelers-Backpack#215]
Hello community! I saw on curse forge that you were taking in suggestions for the backpacks that have yet to receive abilities and I thought of pitching in some ideas. I tried to keep it tied to the theme of each backpack and not be too powerful (side note, I don't know how to add the enhancement tag to make it easier for yall, sorry):

**Colored Backpacks**: Colored sleeping bags. Since these are just meant to be cosmetic/collectors how about making the sleeping bag color match the backpack? It still keeps the cosmetic/collectors idea while adding the different bed colors that Minecraft already has.

**Blaze**: Feather Falling. Since Pigman Backpack already provides fire resistance it was either shooting fire charges (op imo) or feather falling since they slowly fall.

**Carrot**: Attracts Pigs. Since pigs love carrots, how about they fallow the backpack when worn? Bonus if the range of detection for the pigs is increased but idk if that would be too powerful.

**Coal**: Auto-craft torches, auto-replace torches, or auto-place torches. This one I can see either way. Option 1, it auto crafts torches (may or may not need sticks). Option 2, as you use torches from your hotbar, it will re-fill it as long as there are torches in the backpack. Option 3, when you walk into low light level (aka monsters can spawn) it will auto place a torch on your foot. This would make it tied with Bat and Glowstone for most useful when mining regardless of which of the 3.

**Gold**: Can receive a "useless" enchantment. Since gold tools can spawn with enchantments, why not make it so the backpack can receive an enchantment too just for the enchantment effect. The enchantment itself can be a useless one like infinity which unless put on a bow is useless. Or make a new one called "SHINY!" which only the golden backpack can get.

**Iron**: +1/2 armor. It's more of a pet peeve of mine that iron armor has 7.5/10 armor. This would just make it a solid 8/10.

**Iron Golem**: Grows roses around itself. When placed, roses will grow around it since golems always give roses to villagers. The other thing I was thinking was strength boos when near a villager but I feel like that can be too powerful.

**Lapis**: Auto-collect and craft lapis into blocks. Lapis can be annoying sometimes when mining so this will just collect them and make them into blocks to save space. I personally wouldn't use it over the other ones but it was the only thing I could think of besides enchanting it like the gold backpack but I didn't want to be redundent.

**Cake**: Everything is a cake! Just like the memes, this backpack is not a backpack but rather a cake! You can't equip it though after taking the first bite.

**Chest**: Auto-dump when on a chest. Basically works like a hopper but only when on top of a chest and only to that chest.

**Cookie**: Cookie monster noises. If cookies are in the backpack, it will randomly consume one cookie and make the cookie monster eating noise.

**Egg**: Hatch chickens from eggs. If an egg is placed in the backpack, after some time it will hatch into a chicken. No more throwing eggs and hoping for a chicken, now you just wait for it to hatch (though it should take a few minutes like maybe 5 or 10 per chicken egg).

**Delux**: Power stealer. VERRY LOW spawn chance but you can put an empty backpack inside of it and it will steal its power at the expense of a slot (or a few. If more than one is used, it will gray out other slots or it will just disappear).

**Enderman**: Hydrophobia. Randomly teleports you when you are in the rain like an enderman. This is more of a troll backpack like the creeper. Either that or enderman aren't aggroed when you look at them.

**End**: Ender chest network. Connects to your ender chest network but because it has 12 more slots than an ender chest, it would either have 12 exclusive slots or these 12 are removed.

**Ghast**: No ghast agro. They are annoying, this will make them less anoying.

**Heybale**: Just like the carrot but for animals that follow wheat.

**Horse**: Can be equipped on a horse too. Horses have historically carried stuff so this makes scense.

**Leather**: Can be died like the wool variation for more cosmetic/collectors backpacks.

**Magma Cube**: Just like slimes but with the magma cube particles and sound.

**Brown/Red Mushroom**: When in dark places, it will spawn a mushroom of its color in an available slot. Can be placed to have the same effect but on the ground.

**Mooshroom**: Mushroom stew. Eats wheat and makes mushroom stew.

**Neather**: Auto-collects and destroys extra netherrack. You can manually place how many stacks of neatherrack you want to keep but anything passed 64 of how many stacks you start will auto destroy them. For the backpack to work, you need at least 1 stack in the backpack.

**Wither**: Withers enemies on damage taken. Applies the wither de-buff to anyone that hits you.

**Obsidian**: Auto-makes Obsidian. If your tank has both water and lava, it will combine them and make obsidian.

**Overworld**: Dirt to grass. Converts dirt into grass blocks when under sunlight. Grass growth time is the same as normal grass spread but it does it one at a time.

**Pumpkin**: Scares enderman. If you have this on and a pumpkin, enderman will tp away from you.

**Quartz**: See items. This backpack is translucent so how about allowing us to see what is inside like the crystal chest from the iron chest mod does.

**Sandstone**: Auto-collects sand and sandstone. Honestly, this one I have no idea, that is the best I could come up with.

**Sheep**: Shearable. Can be died (adding to the cosmetic/collectors) and can be sheared if placed. Will grow back after some time but must be on top of grass like a sheep.

**Silverfish**: Single silverfish. If you break a silverfish block, only that silverfish will be after you, all others will stay in their blocks.

**Wither Skeleton**: Withers enemies on damage done. Applies the wither de-buff to anyone that you hit.

**Snow**: Makes snowballs in rain or can't slip on ice. The other one I thought of was to make water into ice but that sounds broken.

**Spider**: Makes string or climb walls. I would say that climbing walls is op but it makes sense if it is the spider.

**Sponge**: Water absorption. Absorbs water source blocks around you and fills the tanks.

**Villager**: Makes random villager noises and iron golems give you flowers.

**Zombie**: Iron Golom Agro. Troll backpack that makes iron golems hostile towards you and makes villagers flee.

**Modded Network**: Works with pipes. This one feels too specific to not already have an efect but I saw nothing that states otherwise. This would function as a normal chest for network mods like simple storage and pipes that can connect to it.

That was my two cents. Some may be good and some may be bad but at least these will give some food for thought. If any of these listed already have an ability/are in progress, please let me know cuz I could not find anywhere that had the full list saying "this has this ability and this currently has no ability"

**Comment by Darkona** [comment]
In my old version, the horse backpack searched for horses you tamed and made them follow you like wolves. Useful because those bastards usually wander off and in a journey that's very uncomfortable. Probably I'll add it back myself as a PR.
