### ISSUE TITLE
problems with the hose mode

### ISSUE THREAD

**Issue by Conclavice** [Tiviacz1337/Travelers-Backpack#216]
so I've messed around with this and I can't seem to figure out how to fix it, I'm not able to change the hose mode. I've changed the key bind and all that stuff, also tried switching game mode and that didn't help. if there's a fix let me know, thanks!

**Comment by Tiviacz1337** [comment]
Click right click when backpack is on your back. Then Keybind + scroll to change mode or N default to change tank
