### ISSUE TITLE
[1.16.4]Display error?

### ISSUE THREAD

**Issue by EnterFor** [Tiviacz1337/Travelers-Backpack#217]
When I put my backpack on the ground, it shows like this
![image](https://user-images.githubusercontent.com/10114685/104029808-58305580-51c2-11eb-8814-fe7fa1c65669.png)
Version: 5.3.4
Forge：35.1.28

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3165173
