### ISSUE TITLE
My backpack has disappeared on death.

### ISSUE THREAD

**Issue by ItSammyboi** [Tiviacz1337/Travelers-Backpack#220]
(context) I had gotten into an unexpected fight with an ice dragon from the mod ice and fire so I died very terribly but anyway when I came back. my backpack was nowhere to be found. I found other comments at curse forge telling about this happening to them, although I haven't seen anything about it in the issues here.

**Comment by Tiviacz1337** [comment]
Where did you die? That's another issue that occured because dragon from ice and fire killed someone. Did backpack drop as item?  Maybe dragons can remove floating items from the world?

**Comment by Tiviacz1337** [comment]
In the update 5.3.6 which is not released yet, backpack will be immune to any damage source, therefore it won't be destroyed in lava, fire. That may fix this issue

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3165421
