### ISSUE TITLE
Traveler's backpack 

### ISSUE THREAD

**Issue by Tyler-Master** [Tiviacz1337/Travelers-Backpack#221]
In the newest version 5.3.5 for 1.16.4 the dupe bug is still around, dupped netherite ingot, gold blocks and more to confirm,
this was happening within the backpacks 3x3 crafting grid, the items disappear when you craft the item but come back when you reopen the backpack

**Comment by Tiviacz1337** [comment]
In which form did you use the backpack?

**Comment by Tyler-Master** [comment]
it was on my back using the hot key to open the inventory

**Comment by Tyler-Master** [comment]
https://user-images.githubusercontent.com/75922809/104218956-56e56f80-53f2-11eb-98a2-599754a91030.mov

**Comment by Tyler-Master** [comment]
https://youtu.be/U_zWga5QtSA heres a link to show it in action, sorry for the shaking.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3165421
