### ISSUE TITLE
[1.16.4] [Brass modpack] Crash when interacting with backpack placed on ground 

### ISSUE THREAD

**Issue by Janitor53** [Tiviacz1337/Travelers-Backpack#222]
Forge version: 35.1.36
Mod version: 5.3.6
Game crashed when I right click placed on ground backpack. Here is a crashlog: 
[crash-2021-01-12_11.02.03-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/5800648/crash-2021-01-12_11.02.03-client.txt)

**Comment by Tiviacz1337** [comment]
I can't reproduce it by myself Could you test the jar?

**Comment by Janitor53** [comment]
What jar?

**Comment by Tiviacz1337** [comment]
Join my discord and I'll send you new jar to test if crash still persists, as I said, I can't reproduce it by myself

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3166428
