### ISSUE TITLE
doesnt seem to go into any slots 

### ISSUE THREAD

**Issue by benbenlaw** [Tiviacz1337/Travelers-Backpack#223]
changed server config to allow curious support and backpack doesnt go into any slots
![image](https://user-images.githubusercontent.com/42780877/104304574-726c7b00-54c3-11eb-9fd3-3c1008fbf718.png)

**Comment by Tiviacz1337** [comment]
There should be "back" slot with backpack icon? Isn't there something like that?

**Comment by benbenlaw** [comment]
nope thats all that shows maybe it was changed to chest slot?

**Comment by Tiviacz1337** [comment]
I've already found the issue, it'll be fixed asap

**Comment by benbenlaw** [comment]
ahh nice one

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3166428
