### ISSUE TITLE
Can't load my old world

### ISSUE THREAD

**Issue by 47delasPECIIKOMODO** [Tiviacz1337/Travelers-Backpack#224]
I have a world and i need a backpack and your mod is really awsome, i downloaded your mod, the latest one, TravelersBackpack-1.16.4-5.3.6 i got the worning message from your mod with the warning, after that i tryed to load my world and i got this message screen "errors in currently selected datapacks prevented world from loading"
forge version 1.16.4-forge-35.1.36
[debug.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/5802703/debug.log)
[latest.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/5802706/latest.log)
![Poza dovada](https://user-images.githubusercontent.com/77338081/104327170-29341f80-54f3-11eb-8918-d58e720ecbf9.png)

**Comment by Tiviacz1337** [comment]
Did you set curiosIntegration to true?

**Comment by 47delasPECIIKOMODO** [comment]
no, i didn't modify any config files

**Comment by Tiviacz1337** [comment]
Hmm, log says nothing about my mod, maybe your world got corrupted _somehow_? I'm sorry but you'll have to restore world from backup
