### ISSUE TITLE
I cant open the back pack when its placed on the floor!

### ISSUE THREAD

**Issue by ImNotGamerX** [Tiviacz1337/Travelers-Backpack#227]
I cant open the back pack when its placed on the floor! So that means I cant use the sleeping bag!

**Comment by Tiviacz1337** [comment]
Thanks for this issue! I'm wondering what may be the problem without any logs...

**Comment by Katarnyah** [comment]
neither can I open the inventory nor use the sleeping bag when it's on the floor!
