### ISSUE TITLE
Backpack does not contain buttons in GUI

### ISSUE THREAD

**Issue by tavanuka** [Tiviacz1337/Travelers-Backpack#228]
The GUI has missing buttons for sleeping, unequip and equip buttons mentioned. Is this intentional or left out for now?

Bonus: hose mode does not change upon holding shift and scrolling. (is it meant to be in suck mode only?)
![image](https://user-images.githubusercontent.com/67005577/104450766-e3359500-55a0-11eb-8ebc-aa361d91ea69.png)

**Comment by Tiviacz1337** [comment]
If you enabled curios integration, you won't have buttons. Did you enable curios integration?

**Comment by tavanuka** [comment]
yes. I did. what about the sleeping bag button?

**Comment by Tiviacz1337** [comment]
Sleeping bag button is available only in placed backpack on the ground

**Comment by Tiviacz1337** [comment]
Also you can change hose with Z (Default, change in controls) + scroll (But first you have to assign hose to tank by right click, it resets everytime so make sure one of the tanks is highlighted
