### ISSUE TITLE
Item dissappearing from backpack

### ISSUE THREAD

**Issue by 1724229** [Tiviacz1337/Travelers-Backpack#230]
I've noticed items disappearing once in a while but I always thought it just misplaced them and moved on. But just now I noticed a whole backpack (useful backpack mod) which is always in there disappeared and an atomic disassembler (mekanism v10) so I can confirm that I wasn't misplacing things XD.

I'm playing on 1.16.4, and was crafting using JEI when the backpack got sorted like I clicked on the sort inventory button (inventory tweaks renewed) and stuff disappeared.

I'm not sure if this is something wrong with this mod or the other mods I'm using but since I noticed it while using the traveller's backpack I'm posting this here XD.

Other than that, awesome mod! Looking forward for the buffs to come to 1.16.4 if possible :3

**Comment by Tiviacz1337** [comment]
Version of the mod?

**Comment by 1724229** [comment]
1.16.4-5.3.4
Apparently someone else seems to have the same problem. I'm assuming the items in my backpack disappeared because the sorting function kinda works like a quick stacking.

**Comment by Tiviacz1337** [comment]
Can you use the latest version before submitting a report?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3171745

**Comment by 1724229** [comment]
Sorry didn't notice it was outdated. Thanks for the fix! I hope XD
