### ISSUE TITLE
Compatibility with Quark management features

### ISSUE THREAD

**Issue by WinZZer** [Tiviacz1337/Travelers-Backpack#231]
![1](https://user-images.githubusercontent.com/63591039/104745223-e4acbc00-575e-11eb-99bb-c92a2e87aeca.png)
As seen on screenshot, buttons from quark management located incorrectly and interfere with crafting in the backpack. Is it possible to fix this?

**Comment by Tiviacz1337** [comment]
It's not possible

**Comment by noobanidus** [comment]
While I realise this is a closed issue, [if you include some files from the Quark API, it should be possible to implement the interface "IQuarkButtonIgnored"](https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/api/IQuarkButtonIgnored.java) in the relevant GuiScreen that will allow you to have Quark not place any buttons at all. This would presumably prevent the issue the reporter is having with crafting interference. [This appears to be an example of someone including the api](https://github.com/svenhjol/CharmForge/blob/master/src/main/java/vazkii/quark/api/IQuarkButtonIgnored.java) although not specifically using this interface.

In previous versions I believe they had some API calls that allowed for more precise positioning of the buttons but that doesn't appear to be the case as of 1.16.4/1.16.5.
