### ISSUE TITLE
Unable to Open Backpack's Inventory

### ISSUE THREAD

**Issue by Coraline77447** [Tiviacz1337/Travelers-Backpack#232]
Hi, I can't open the Traveler's Backpack inventory with any keybindings assigned to it in the controls menu. Only way to get it off is by /kill @s if it's on the player since the only way to take it off normally is in the backpack's inventory which isn't possible to access at all by any means necessary...

P.s. Even if I reset the keybinding to its default then try to access its inventory nothing happens and that the default keybinding conflicts with another mod that I'm playing with uses the same keybinding...

**Comment by Tiviacz1337** [comment]
Which version are you using?

**Comment by Coraline77447** [comment]
I've just updated it to the latest and I'm gonna test it to see if any keybindings works but if not then ya know what to do, do ya?

**Comment by Coraline77447** [comment]
Just found this in my latest crash on start up during the mod loading process on 1.16.4 forge 35.1.37:

[18Jan2021 03:45:25.764] [Worker-Main7/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: Cannot register a capability implementation multiple times : com.tiviacz.travelersbackpack.capability.ITravelersBackpack

**Comment by Coraline77447** [comment]
I may have fixed what was causing the duplication errors which was that I had a resource pack that has mod support and was literally making duplicates of what's already being loaded during the mod loading processes...

**Comment by Coraline77447** [comment]
Ok, just switched the default keybind from B to L and it's working but for the last version for Traveler's Backpack that with any keybindings assigned to the inventory if the item in the mod doesn't work.

**Comment by Tiviacz1337** [comment]
So what's the problem now?

**Comment by Coraline77447** [comment]
Theres no problem now since the current version I'm using apparently fixed it (tested it in a test world to make sure that 5.3.8 has a working keybinding inventory which it does) which may still coexist within 5.3.7 before 5.3.8. What the issue was in 5.3.7 was that whichever keybindings I had assigned to the Backpack's inventory that I wasn't able to access it's inventory by any means necessary except for killing my character and setting it down on the ground only. I dont think that anyone else had the same problem as I had so apparently Traveler's Backpack 5.3.7 wasn't working for me at all for the inventory part. So I'm sorry for wasting your time on this useless report since the problem has been fixed by simply just updating the mod to a new version... You may close this report as you wish, ok?...
