### ISSUE TITLE
Disappearing items

### ISSUE THREAD

**Issue by yokashio** [Tiviacz1337/Travelers-Backpack#234]
Forge version 35,1,4
Backpack version 5.3.7

Had an issue where I would have an item already in the backpack, say 5 emeralds. I would place 10 more emeralds on top of those, equaling 15. I would close and re-open the backpack and the original value of 5 would be sitting there. 

I traded backpacks with a friend on our server, and he was able to replicate the problem using my backpack. I was also able to replicate the problem with his backpack. I don't know if its me who is tainting backpacks, or if it just suddenly happened to just me and him.

**Comment by Tiviacz1337** [comment]
Use 5.3.8
