### ISSUE TITLE
Inappropriate sorting with Inventory Tweaks Renewed

### ISSUE THREAD

**Issue by GreenBudgie** [Tiviacz1337/Travelers-Backpack#235]
When using sorting from Inventory Tweaks Renewed (www.curseforge.com/minecraft/mc-mods/inventory-tweaks-renewed) it places items in the backpack's crafting slots at first. I know that InvTweaks is in beta for 1.16.4 but I think that this bug is related to slot numeration inside of a backpack. As I can see, crafting slots are numbered 0-8 and InvTweaks treats them as the first slots in the inventory, placing items there at first.

To reproduce: install the last version of InvTweaks Renewed (invtweaks-1.16.4-1.0.1) and sort the backpack's inventory.

Expected behavior: items are placed at the top slots of backpack when sorting. 

Unsorted backpack:
![unsorted](https://user-images.githubusercontent.com/37713157/105490803-63a57580-5cc6-11eb-88c6-13e8cc5d3102.png)
Sorted backpack:
![sorted](https://user-images.githubusercontent.com/37713157/105490855-76b84580-5cc6-11eb-82ad-c0714dd3059b.png)

Mod version: TravelersBackpack-1.16.4-5.3.7

**Comment by Tiviacz1337** [comment]
The crafting grid should be unsortable btw. I'll not do anything with this atm, maybe new versions of IT R will add api or something that I'll allow me to configure sorting in container

**Comment by GreenBudgie** [comment]
This issue may be solved by inserting these lines into invtweaks-client.toml config file at [sorting] section

```
[[sorting.containerOverrides]]
    containerClass = "com.tiviacz.travelersbackpack.inventory.container.TravelersBackpackItemContainer"
    sortRange = "10-48"

[[sorting.containerOverrides]]
    containerClass = "com.tiviacz.travelersbackpack.inventory.container.TravelersBackpackTileContainer"
    sortRange = "10-48"
```
It prevents InvTweaks from sorting crafting and tool slots. I may suggest to add this configuration by default to InvTweaks creator.

**Comment by Tiviacz1337** [comment]
I didn't know about this. Indeed it's amazing
