### ISSUE TITLE
hose on water logged block

### ISSUE THREAD

**Issue by benbenlaw** [Tiviacz1337/Travelers-Backpack#239]
**Describe the bug**
using hose to fill tank with water from a waterlogged block

**To Reproduce**
slab slab into water
use hose to suck
crash

**Expected behavior**
water to go into tank with no crash
[crash-2021-01-28_14.24.39-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/5887972/crash-2021-01-28_14.24.39-client.txt)

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: [e.g. 1.16.4 - 5.3.7]

**Additional context**

**Comment by Vap0r1ze** [comment]
Had the same issue with a cobblestone slab
[crash-2021-03-02_09.03.38-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/6069148/crash-2021-03-02_09.03.38-client.txt)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3243518
