### ISSUE TITLE
interacting with tanks

### ISSUE THREAD

**Issue by benbenlaw** [Tiviacz1337/Travelers-Backpack#240]
**Describe the bug**
trying to take fluids from tabk causes crash
**To Reproduce**
try filling from tank from other mods

**Expected behavior**
be able to fill from tank

https://pastebin.com/tTgiT4cs

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: [e.g. 1.16.4 - 5.3.7]

**Additional context**

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3243518
