### ISSUE TITLE
placing liquid from tanks into the world

### ISSUE THREAD

**Issue by benbenlaw** [Tiviacz1337/Travelers-Backpack#241]
**Is your feature request related to a problem? Please describe.**
be cool if you could place the fluid from connected tanks into the world

**Describe the solution you'd like**
Liquid in tank able to be place in world from hose

**Describe alternatives you've considered**
none

**Additional context**

**Comment by Tiviacz1337** [comment]
It's already possible

**Comment by Tiviacz1337** [comment]
Of course for fluids that have valid block form

**Comment by benbenlaw** [comment]
how?
