### ISSUE TITLE
change mode button doesnt work

### ISSUE THREAD

**Issue by benbenlaw** [Tiviacz1337/Travelers-Backpack#242]
**Describe the bug**
change mode button doesnt work

**To Reproduce**
clicking changed mode hise button defualt z and it does nothing

**Expected behavior**
changes from suck mode

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: [e.g. 1.16.4 - 5.3.7]

**Additional context**

**Comment by Tiviacz1337** [comment]
I'm not even going to explain this, literally I've made new spoiler on site for anyone having problems with hose, just take a look at damn site
