### ISSUE TITLE
Tool scrolling with only two tools leaves an empty hand and stops scrolling

### ISSUE THREAD

**Issue by chaosblad3** [Tiviacz1337/Travelers-Backpack#243]
**Describe the bug**
Tool scrolling works perfectly if you have three tools, one in your hand and two in the designated slots in the backpack, but if you only have one tool in the backpack and the other slot empty then when you try to swap the tool you're currently holding it instead swaps it to an empty hand, putting your current tool in the empty slot in the backpack, and then because you are no longer holding a tool, the keybind+scroll no longer works meaning the only way to get either tool back out is to open the backpack and move it back to your hotbar manually.

**To Reproduce**
have one empty tool slot in the backpack and try to swap tools from one on your hotbar

**Expected behavior**
If you only have one tool in the backpack slots and you try to swap tools it should either 
A. skip the empty slot and just swap back and forth between the two tools
or 
B. cycle to an empty hand but have the keybind+scroll work while your hand is empty so you can pull out one of the stored tools from an empty hand.

**Required informations (please complete the following information):**
 - Mod version: 1.16.4 - 5.3.8

**Additional context**

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3243518
