### ISSUE TITLE
Losing Items in Backpack

### ISSUE THREAD

**Issue by MrTailson** [Tiviacz1337/Travelers-Backpack#245]
**Describe the bug**
There is a bug with the inventory. If you have an item in your backpack, and get more of that same item in your inventory and try to add it to the existing item in your backpack, the extra items you just added will disappear, leaving the backpack how it was before you added them. 
**To Reproduce**
1. Place any stackable item into the backpack's inventory.
2. Gather more of that same item into your own inventory or toolbelt.
3. Shift-click the items from your inventory or toolbelt into the existing item in the backpack.

**Expected behavior**

**Screenshots**

**Required information (please complete the following information):**
 - Mod version: 1.16.4 - 5.3.7.jar
 - Minecraft version: 1.16.5

**Additional context**

**Comment by Tiviacz1337** [comment]
Use 5.3.8 instead
