### ISSUE TITLE
Datapack problems

### ISSUE THREAD

**Issue by ILikeMinecraftMods** [Tiviacz1337/Travelers-Backpack#246]
I have included their great backpack mod in my worlds and wanted to use a data pack to change the recipe for the backpack (standart).
1. In my singleplayer-world, the recipe didn't work until I created it in a separate datapack for this recipe and didn't write it to all the others in one big datapack.
2. When I uploaded the datapack to my Forge server, the recipe did not work.

The tools I added to the tag **always** worked.

Have others had problems with it?
In my other datapacks with other mods had always worked perfectly!

**Comment by Tiviacz1337** [comment]
I don't know what may be the issue unfortunately, I do not work with datapacks.
