### ISSUE TITLE
Hose switching mode STILL DOES NOT WORK 

### ISSUE THREAD

**Issue by benbenbenlaw** [Tiviacz1337/Travelers-Backpack#247]
Tried 1.12.2-1.0.35 and 1.12.2-1.0.34 and both forge-1.12.2-14.23.5.2847 and forge-1.12.2-14.23.5.2838 and followed the spoiler's confusing "instructions." Re-configured keys, deleted the config - NOTHING works - the hose refuses to change from "suck" mode and will not suck up any water but from a source block - does not work with any tanks whatsoever. Very irritating.

**Comment by Tiviacz1337** [comment]
That must be some compat error, since I've been using hose on my own. I won't do anything with that, 1.12.2 is not supported.
