### ISSUE TITLE
Only basic backpack in 1.16.5

### ISSUE THREAD

**Issue by bauerwilhelm** [Tiviacz1337/Travelers-Backpack#249]
I'm not sure if I understand your description the right way (I'm German haha). I'm using 1.16.4-5.3.8 and just have that basic backpack (bp), even creative mode show only this one. 

Your "Add call custom bps" says there're 17 bps ported, Is this a bug? Every mod for 1.16.4 works perfectly fine in .16.5 yet...

Thanks for porting this awesome mod anyways, I use to play with it since 1.7.10!

**Comment by Tiviacz1337** [comment]
there's no custom backpacks yet, they are wip
