### ISSUE TITLE
Can't open backpack inventory when equipped

### ISSUE THREAD

**Issue by shell42dll** [Tiviacz1337/Travelers-Backpack#251]
**Describe the bug**
Cant open backpack interface when equiped
Can only switch Tools

**To Reproduce**
Have no idea, but this happen after i place Vanilla "Bee Nest" in backpack
_Update_ 
1.Equip Backpack
2.Place in 13 "Bee Nest" block

**Expected behavior**
Open backpack interface

**Screenshots**
Server error when i press keybind "backpack inventory" https://i.imgur.com/ECn6iGG.png

**Required informations (please complete the following information):**
 - Mod version: TravelersBackpack-1.15.2-4.0.8.jar

**Additional context**
Other 2 people on my server can use backpack as usual
Restarting game/server no result

**Comment by Tiviacz1337** [comment]
1.15.2 is not supported
