### ISSUE TITLE
Items get lost if you try to add some to an existing non complete stack in the backpack

### ISSUE THREAD

**Issue by MechanEs** [Tiviacz1337/Travelers-Backpack#253]
when there's a non complete stack of items in the backpack, and you try to add some item to it, after you close and reopen the 
backpack the stack will return to his original number of items.

1. open the backpack and put in it half a stack of something 
2. close, reopen and complete the stack moving items from the main inventory
3. close and reopen the backpack

after point 3, there will be half a stack and not a complete one (this bug works even if you don't complete the stack but you add something at point 2)

 - Mod version: [e.g. 1.16.4 - 5.3.7]

**Comment by Tiviacz1337** [comment]
5.3.8
