### ISSUE TITLE
cant open the inventory

### ISSUE THREAD

**Issue by zayoc** [Tiviacz1337/Travelers-Backpack#256]
**Describe the bug**
i add the mod the i craft the backpack and start to put my important stuff those were 3 backpacks of usefull backpacks, and 5 dragon horns with dragons, then i wanted to open the inventory to continue adding more stuff and it didnt open, i continue having the backpack in the back but it just doesnt works.

 - Mod version: TravelersBackpack-1.16.3-5.2.1.jar

**Comment by Tiviacz1337** [comment]
Update to latest version
