### ISSUE TITLE
Cant cicly through tolls. 

### ISSUE THREAD

**Issue by edgare13** [Tiviacz1337/Travelers-Backpack#257]
**Describe the bug**
When holding down Z cant scroll trhrough tools

**To Reproduce**
1. I click Z and scroll and nothing happens

**Expected behavior**

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: Latest for 1.12.2

It scrolls to the next item i checked options and still cant find where to map Z to doing tools as there are only 2 options for the mod which is open backpack and toggle hose tank. I made sure only this mod was using Z
Still not working

**Comment by Tiviacz1337** [comment]
1.12.2 is not supported, also check if Z is not used for any other mod in keybindings
