### ISSUE TITLE
Um, this isn't a bug but Traveller's has two "L"s.

### ISSUE THREAD

**Issue by blace2121** [Tiviacz1337/Travelers-Backpack#258]
Traveler's Backpack is spelled wrong and doesn't appear on curse if you spell it correctly.
**Describe the bug**

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: [e.g. 1.16.4 - 5.3.7]

**Additional context**

**Comment by Tiviacz1337** [comment]
I can't do anything about it, it's already changed but it's minor bug from curseforge site I think
