### ISSUE TITLE
Backpacks dont place and you cant wear them 1.16.5

### ISSUE THREAD

**Issue by ffsdfsdfsdfsd** [Tiviacz1337/Travelers-Backpack#259]
**Describe the bug**

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: [e.g. 1.16.4 - 5.3.7]

**Additional context**

**Comment by Tiviacz1337** [comment]
There's literally nothing that I can use to navigate the issue, if I couldn't place the backpack or wear it, I wouldn't release the version. Don't open issues like that
