### ISSUE TITLE
Can't Assign Hose In Creative Mode

### ISSUE THREAD

**Issue by Coraline77447** [Tiviacz1337/Travelers-Backpack#261]
Hi, when I'm in creative mode after right clicking the backpack to place it on the ground, then I try to assign the hose to either tank and nothing happens, I've tried to make a new hose, then a new backpack and even leaving the world/game and didn't fix it. I think I either found a new bug or I'd broke the mod even tho some of the other functions with Travelers Backpack can successfully be made like opening the backpack's inventory, tapping Z to put a tool into one if the yellowish greenish slots at the bottom left and probably can use its built in crafting table.
Before this happened I had water in the right tank and when I first tried to spill some of the water out of the right tank nothing happened and I think that if I were to have tried to do the same thing for the left tank that nothing would happen as well and now I cant even fill both tanks up cause I cant assign the hose to either tank after I right clicked the backpack onto the ground while in creative mode....

Traveler's Backpack 1.16.4 5.3.8
Forge 1.16.5 36.0.42

P.S. I know that I didn't properly made this as everyone else did with theirs but you should still be able to understand what I'm saying and what the problem is that I've encountered while playing with Traveler's Backpack.

**Comment by Tiviacz1337** [comment]
You can't assign hose to placed backpack, only while wearing
