### ISSUE TITLE
Crash when putting backpack on and cant log back in

### ISSUE THREAD

**Issue by PushedTree37974** [Tiviacz1337/Travelers-Backpack#264]
**Describe the bug**
So my friend and I are playing on Crackpack 3 (1.12.2) and they can't log into the server because her Wolf Backpack crashes her because she has it on her back

**To Reproduce**
1. Put on Wolf Backpack

**Required informations (please complete the following information):**
 - Mod Version: 1.0.22.22

**Additional context**
I looked in the server log and it said that the Wolf Backpack ability crashes then

**Comment by Tiviacz1337** [comment]
1.12.2 is not supported, also 1.0.22.22 is outdated version, consider updating
