### ISSUE TITLE
Items disappearing

### ISSUE THREAD

**Issue by 599XX-EVO** [Tiviacz1337/Travelers-Backpack#265]
**Describe the bug**
Some items are vanishing from the backpack, like, if I put 64 oak logs in the backpack, some of them will disappear and only leave a few ones there

**To Reproduce**
1. Put a stack of a certain block in the backpack (Ancient Debris and Oak Logs in my case)
2. Close the backpack and wait a few seconds
3. Re-open it

**Expected behavior**
There will be no stack, only a few ones of the same item

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: 1.16.4

**Additional context**
This happened with me twice, i've mined some ancient debris and put it into the backpack, when I re-opened it, there was only one ancient debris when it should have more.
Also with Oak Logs, I mined a stack of wood and put it into the backpack, re-opened it and there's only 3 oak logs, where did they go?

**Comment by Tiviacz1337** [comment]
use 5.3.8
