### ISSUE TITLE
Placing fluids into containers with nozzle crashes game

### ISSUE THREAD

**Issue by Csquaredaap** [Tiviacz1337/Travelers-Backpack#267]
So when i try and put fluids from the pack into mekanism or immersive engineering containers the entire game crashes!

**Comment by Csquaredaap** [comment]
And I also cannot figure out how to get a fluid out of the backpack using the cables as shown on the curseforge page

**Comment by Csquaredaap** [comment]
And i cant figure out how to extract the fluid from the backpack as shown on the curseforge page using the pipes

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3243518
