### ISSUE TITLE
Upgradeability

### ISSUE THREAD

**Issue by TitanGuard** [Tiviacz1337/Travelers-Backpack#268]
I suggest making them upgradeable to have more inventory space, possibly 2 new backpacks, 

[default] Traveler's backpack. 

Then a Nomad's backpack with an extra 18 slots of storage space with double the tank size along with a furnace addition. 

Then the Expeditionist's  backpack, it could have a full 36 slots of extra space, and 4 times more tank space over the Traveler's backpack. 

Recipes could take iron, gold, a chest, furnace, and the previous backpack for the Nomad's backpack, then diamonds, obsidian, glass, chests, and the previous backpack for the Expeditionist's backpack.

**Comment by Tiviacz1337** [comment]
Well, that's good idea for a new mod I could work on. Upgradeability kinda departs from original idea of powerful adventure backpack.

**Comment by TitanGuard** [comment]
> Well, that's good idea for a new mod I could work on. Upgradeability kinda departs from original idea of powerful adventure backpack.

i think that it would be amazing to have it as a new mod if you feel its not true to the original idea, i personally like working up to the powerful things and not getting it on the first go. I would love to see this fulfilled.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack
Backpack tiers added for forge fabric coming soon
