### ISSUE TITLE
[Suggestion] Config to customize the ammount of inventory slots and disable functions

### ISSUE THREAD

**Issue by arBorghi** [Tiviacz1337/Travelers-Backpack#269]
This idea came with the need of balancing my modpack and making all the items and mobs (like the horse) useful in some way.
Something like an ammount of slots multiple of 3 (because the crafting UI is 3x3), disabling the crafting table, tools inventory, etc.

**Comment by Tiviacz1337** [comment]
That's not possible for _this_ mod. Here's better issue: https://github.com/Tiviacz1337/Travelers-Backpack/issues/268
