### ISSUE TITLE
Curios Integration not working right

### ISSUE THREAD

**Issue by GhostGuy9** [Tiviacz1337/Travelers-Backpack#270]
So after enabling onto server, it wont let me access the backpack inventory and see tools/fluid.

**Comment by Tiviacz1337** [comment]
Did you take off your backpack before enabling integration?

**Comment by GhostGuy9** [comment]
Yes, I took off my backpack and then enabled it on the server. After starting the server back up I put it in my back slot, doesn’t appear on my back as well, and when I press the b key it doesn’t open the backpack inventory.

Daniel Webster

**Comment by TitanGuard** [comment]
> Yes, I took off my backpack and then enabled it on the server. After starting the server back up I put it in my back slot, doesn’t appear on my back as well, and when I press the b key it doesn’t open the backpack inventory.
> […](#)
> On Mar 21, 2021, 1:29 AM -0700, Tiviacz1337 ***@***.***>, wrote: Did you take off your backpack before enabling integration? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

you need to open the backpack then click the "Equip" button in the bottom left of the backpack GUI, that equips it without taking any slots up anywhere. i'm pretty sure curios is a bit broken or is used for other things than the Traveler's Backpack

**Comment by GhostGuy9** [comment]
But when I do that it doesn't equip. I have the curios integration on which disables the "Equip" option. The easiest solution is to disable the integration. I wanted to address this bug, if its a bug, and see if it can be fixed in some way.

**Comment by Tiviacz1337** [comment]
If you enable curios integration, You have to put backpack in back curios slot in order to work

**Comment by GhostGuy9** [comment]
I did put it in my back slot in Curios but when I do and press "B" is still does not open the backpack inventory.

**Comment by Tiviacz1337** [comment]
Try checking the keybindings

**Comment by Tiviacz1337** [comment]
Was keybinding an issue? Or it still does not work?

**Comment by GhostGuy9** [comment]
Still not working, I have had the key binds changed and it doesn't work.

**Comment by Tiviacz1337** [comment]
Then it's probably mod incompatibility, if you could find this, report to me. In my dev environment it's working fine

**Comment by GhostGuy9** [comment]
After updating the to the newest version, Curseforge did not tell me there was an update for the mod, and it works perfectly now.

**Comment by Tiviacz1337** [comment]
That's good

**Comment by aziles-guts** [comment]
This is currently an issue again in 9.1.15
