### ISSUE TITLE
Librarian Trades

### ISSUE THREAD

**Issue by ILikeMinecraftMods** [Tiviacz1337/Travelers-Backpack#273]
Can't Librarians sell nametags now?
That would be a significant change for the gaming experience!
Please remove this feature or add a specific chance for both.

**Comment by Tiviacz1337** [comment]
Wait, what?

**Comment by ILikeMinecraftMods** [comment]
???

**Comment by Tiviacz1337** [comment]
What's the issue

**Comment by ILikeMinecraftMods** [comment]
Librarians can no longer sell nametags,
but I would like to trade them.

**Comment by ExArch3r** [comment]
Since @ILikeMinecraftMods wasn't very clear about this issue, Librarians are selling backpacks in place of nametags now. I am encountering this as well.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3271219
