### ISSUE TITLE
Unable to Equip/Unequip

### ISSUE THREAD

**Issue by pjlasl** [Tiviacz1337/Travelers-Backpack#275]
**Describe the bug**
When I right-click on the backpack to add it to my back, I don't see the option to equip/unequip option in the GUI.
I had curios integration turned off.

**To Reproduce**
1. Hold backpack in hand
2. Right-click to show GUI
3. GUI does not have option to equip/unequip

**Expected behavior**
I expect to see the equip/unequip option when I right-click the backpack in hand.

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: 1.16.5 - 5.4.0]\
 - Forge 36.1
 - Minecraft 1.16.5

**Additional context**

**Comment by Tiviacz1337** [comment]
There's still a problem? I don't see anyone else reporting this issue

**Comment by pjlasl** [comment]
Yes it is still occuring. Here are a list of my mods:

Mods:
  [✔️] 1.16.5-additionalbars-2.0.2
  [✔️] abnormals_core-1.16.5-3.1.1
  [✔️] abnormals_delight-1.16.5-1.1.0
  [✔️] additionalbarsbop-2.0.2
  [✔️] AdvancedCompas-forge-1.16.5-1.0.0
  [✔️] alexsmobs-1.8.1
  [✔️] architectury-1.10.139-forge
  [✔️] Artifacts-1.16.5-2.8.3
  [✔️] astikorcarts-1.16.5-1.1.1
  [✔️] atmospheric-1.16.5-3.1.0
  [✔️] AttributeFix-1.16.5-10.1.2
  [✔️] autoplant-1.16.5-1.0.0
  [✔️] AutoRegLib-1.6-47
  [✔️] autumnity-1.16.5-2.1.0
  [✔️] bambooeverything-1.16.3-forge-1.0.0
  [✔️] Bayou-Blues-1.16.5-1.0.4
  [✔️] BedBenefits-1.16.5-5.0.3
  [✔️] berry_good-1.16.5-4.1.1
  [✔️] better_respawn-1.16.5-1.0.1
  [✔️] BetterAdvancements-1.16.5-0.1.0.105
  [✔️] Better-Badlands-1.16.5-2.0.3
  [✔️] BetterBurning-1.16.5-6.0.3
  [✔️] BetterCaves-Forge-1.16.4-1.1.1
  [✔️] betterendforge-1.16.4-1.5.1
  [✔️] BetterF3-1.1.2-forge-1.16.4
  [✔️] BetterMineshafts-Forge-1.16.4-2.0.3
  [✔️] BetterShieldsMC1.16.3-1.1.4
  [✔️] betterspawnercontrol_1.16.5-1.3
  [✔️] biomeinfo-1.16.4-v1.3
  [✔️] BiomesOPlenty-1.16.4-13.0.0.432-universal
  [✔️] blame-1.16.4-1.9.2
  [✔️] Bookshelf-1.16.5-10.0.7
  [✔️] Bountiful-1.16.4-3.3.1
  [✔️] caelus-forge-1.16.5-2.1.3.0
  [✔️] campfiretorches-1.16.3-1.0.3
  [✔️] campful-1.16.5-3.1.0
  [✔️] cartographer-0.0.2-1.16.5-36.0.52
  [✔️] charm-forge-1.16.5-2.3.2
  [✔️] chocolate-1.3.0-1.16.4
  [✔️] ChunkAnimator-1.16.5-1.2.3
  [✔️] citadel-1.6.2
  [✔️] cloth-config-4.11.18-forge
  [✔️] Clumps-6.0.0.17
  [✔️] CNB-1.16.3_5-1.2.11
  [✔️] collective-1.16.5-2.25
  [✔️] colytra-forge-1.16.4-5.1.0.0
  [✔️] comforts-forge-1.16.4-4.0.1.0
  [✔️] configured-0.3.0-1.16.3
  [✔️] corpse-1.16.5-1.0.2
  [✔️] create-mc1.16.5_v0.3.1a
  [✔️] cuneiform-1.16.3-1.2.3.1
  [✔️] curios-forge-1.16.5-4.0.5.0
  [✔️] deadlyendphantoms-1.16.4-3.0.0
  [✔️] Desolation 1.0.5b 1.16.5
  [✔️] despawningeggshatch_1.16.5-2.2
  [✔️] dismountentity_1.16.5-1.4
  [✔️] DungeonCrawl-1.16.3-2.2.4
  [✔️] dungeons_plus-1.16.4-1.1.3
  [✔️] DynamicSurroundings-1.16.4-4.0.4.1
  [✔️] EasyMagic-v1.0.2-1.16.5
  [✔️] endergetic-1.16.4-3.0.0
  [✔️] enhancedcelestials-1.0.2-1.16.4
  [✔️] Enhanced-Mushrooms-1.16.5-3.0.7
  [✔️] entityculling-1.2.1
  [✔️] environmental-1.16.5-1.0.0
  [✔️] extendedbonemeal_1.16.5-1.3
  [✔️] extraboats-1.16.5-2.1.0
  [✔️] extratrades-1.16.4-1.1
  [✔️] FallingTree-Forge-1.16.5-2.11.0
  [✔️] fancymenu_2.0.6_MC_1.16.2-1.16.5
  [✔️] FarmersDelight-1.16.3-0.3.2
  [✔️] farmersdelightintegration-1.16.5-1.0.3
  [✔️] farmersdelightintegrations-1.16.5-1.1
  [✔️] FastLeafDecay-v25
  [✔️] FpsReducer-mc1.16.4-1.18
  [✔️] geckolib-forge-1.16.5-3.0.19
  [✔️] goblintraders-1.3.1-1.16.3
  [✔️] guardvillagers-1.16.5.1.2.2
  [✔️] HerdMentality-1.16.5-6.0.2
  [✔️] hunterillager-1.16.4-1.2.2
  [✔️] illagers_plus-1.16.4v1.0
  [✔️] illagersweararmor-1.0.4
  [✔️] infernal-expansion-forge-1.3
  [✔️] InventoryHud_[1.16.2-1.16.5].forge-3.2.2
  [✔️] inventorytotem_1.16.5-1.3
  [✔️] Jade-1.16.4-2.6.1
  [✔️] jei-1.16.5-7.6.1.75
  [✔️] jeiintegration_1.16.5-7.0.1.15
  [✔️] Kiwi-1.16.5-3.4.2
  [✔️] konkrete_1.1.5_MC_1.16.2-1.16.5
  [✔️] kotlinforforge-1.11.0-obf
  [✔️] kubejs-1605.3.6-build.178-forge
  [✔️] LetSleepingDogsLie-1.16.3-1.1.1
  [✔️] LurkerMod(FORGE-1.16.4) - 1.0.8
  [✔️] masonry-1.16.3-0.3.6
  [✔️] mcw-bridges-1.0.5-mc1.16.5-4
  [✔️] mcw-doors-1.0.2-mc1.16.5
  [✔️] mcw-fences-1.0.0-mc1.16.5
  [✔️] mcw-furniture-2.0.1-mc1.16.5
  [✔️] mcw-roofs-2.0.1-mc1.16.5-4
  [✔️] mcw-trapdors-1.0.1-mc1.16.5
  [✔️] mcw-windows-1.0.3-mc1.16.5
  [✔️] MoreCraftingTables - 1.16.5
  [✔️] morezombievillagers_1.16.5-1.3
  [✔️] movingelevators-1.2.33-mc1.16.5
  [✔️] NetherPortalFix_1.16.3-7.2.1
  [✔️] netherportalspread_1.16.5-5.1
  [✔️] netherskeletons
  [✔️] oneplayersleeping-1.16.4-0.0.5
  [✔️] OuterEnd-0.2.8
  [✔️] outvoted-1.16.5-1.2.2
  [✔️] overloadedarmorbar-5.1.0
  [✔️] passiveshield_1.16.5-1.3
  [✔️] pathundergates-1.16.4-2.0.0-release
  [✔️] PickUpNotifier-v1.2-1.16.3
  [✔️] Pillagers-1.16.5-3.0.1
  [✔️] plaingrinder-1.16.5-1.0.0
  [✔️] polymorph-forge-1.16.5-0.24
  [✔️] pop-1.16.5-1.0.0
  [✔️] preview_OptiFine_1.16.5_HD_U_G8_pre11
  [✔️] QuarkOPlenty-1.16.5-1.2.1
  [✔️] Quark-r2.4-309
  [✔️] randompatches-2.4.4-forge
  [✔️] Regrowth-1.16.4-1.16.4-1.35.0.18
  [✔️] repurposed_structures-1.16.5-2.5.1
  [✔️] RevampedWolf-1.16.4-0.7.1
  [✔️] rhino-1.7.13-build.14
  [✔️] savageandravage-1.16.5-3.1.0
  [✔️] SaveMyStronghold-1.16.4-1.0
  [✔️] SereneSeasons-1.16.5-4.0.1.91-universal
  [✔️] smoothboot-forge-1.16.4-1.2.2
  [✔️] SpawnBalanceUtility-1.36.0.5
  [✔️] stoneholm-1.1
  [✔️] strayspawn_1.16.5-1.3
  [✔️] structure_gel-1.16.4-1.7.5
  [✔️] SubWild-1.16.5-1.2.0
  [✔️] supplementaries-1.16.5-0.11.0b
  [✔️] swingthroughgrass-1.16.4-1.5.3
  [✔️] TenshiLib-1.16.3-1.3.0
  [✔️] Tips-1.16.5-4.0.8
  [✔️] ToolBelt-1.16.5-1.16.0
  [✔️] totaldarkness-1.2-1.16.3
  [✔️] toughnessbar-6.1
  [✔️] TrashSlot_1.16.3-12.2.1
  [✔️] travelers_index-1.16.4-1.0.2
  [✔️] TravelersBackpack-1.16.5-5.4.0
  [✔️] u_team_core-1.16.5-3.2.0.194
  [✔️] upgrade_aquatic-1.16.5-3.1.0
  [✔️] Upgraded Netherite 1.16.4 - 1.8.1
  [✔️] upstream-1.0
  [✔️] Variant16x-1.16.5-v0.17.4.5_beta
  [✔️] Variant16x-BiomesOPlenty-1.16.5-v0.17.4.4_beta
  [✔️] villagernames_1.16.5-2.9
  [✔️] Waystones_1.16.5-7.4.0
  [✔️] WitherBones2.0.1-MC1.16.4
  [✔️] xlpackets-1.1
  [✔️] YungsApi-1.16.4-Forge-4

**Comment by Tiviacz1337** [comment]
Is there a way you could send me your modpack via Discord or something?

**Comment by Tiviacz1337** [comment]
Or did the issue resolve?

**Comment by pjlasl** [comment]
Sorry, I have been busy with RL. No, it is still happening. I'll try to see if there is a mod conflict...

**Comment by markygnlg** [comment]
I had the same problem when I had multiple bags - it turned out that I was wearing one already. I pressed 'b', then removed the equipped bag, then opened my 'main' bag in my hand, then equipped the bag I wanted.

I'm sure you checked this but, just in case,

**Comment by pjlasl** [comment]
I thought it was maybe because I had curios installed at first, but I disabled it and the option in the config...same thing.
I am going to give it another go, RL has gotten in the way of me looking into this further.

**Comment by Tiviacz1337** [comment]
If you wear backpack there should be tank icons in right bottom corner. Then use keybind to open backpack (Default B), mods may cause conflicts, so make sure you checked it's okay to use this keybind. Also if you already wear a backpack, equip/unequip button won't appear, unless it's worn backpack's gui. 
There might be bug too though, try /kill, maybe backpack is stuck somehow

**Comment by Tiviacz1337** [comment]
No more responds, closing

**Comment by Chessenok** [comment]
Also have this bug, on 1.20.1. I have button and all its ok, but my friend doesnt.
