### ISSUE TITLE
On backpacks and shulkers and balancing

### ISSUE THREAD

**Issue by nickylp8** [Tiviacz1337/Travelers-Backpack#276]
Hi! I hope you're doing great. So I've been looking for a good backpack mod for a server I'm making to play with a couple of friends and I really really liked this one in particular. However, there is a an adjustment that would (in my opinion) make this mod the perfect backpack mod.

So, as the mod works right now, you can place backpacks inside shulkers, but you can't place shulkers inside backpacks. While this fixes the issue of infinite inventory space, for my intents and purposes, I would like it way more if it was the other way around, as in, being able to place shulkers inside backpacks and not letting backpacks inside shulkers. Since I am aware that some people might prefer it to stay as it is, I feel like the best solution here would be to make it so via the config, one could choose if they want shulkers to be able to be placed inside backpacks or not, or the other way around. To explain what I mean a bit better, in the config there would be two options as follows:

Shulkers can be placed inside backpacks: true/false
Backpacks can be placed inside shulkers: true /false

I think this would allow people the most options and it would make it a lot easier to balance backpacks for everyone's intents and purposes. I have no idea how difficult it would be to make this happen, but if it is possible, it would make the mod better.

Also, maybe another solution could be to add a list inside of the config file where people can write the ID of the items they wish to prevent from being put into the backpacks, and another list of "containers" where the backpacks cannot be put into (for example suppose a person doesn't want to allow backpacks to be placed inside of chests). I feel like this solution could potentially be better as it may allow for compatibility with other mods such as iron chests, but it does sound a lot harder to pull off and it might be naïve of me to ask for this as I'm not sure if this would even work. 

Anyway that is my request, thanks for taking the time out of your day to read this and thank you for porting this mod, I really do appreciate it :)

**Comment by nickylp8** [comment]
Also, forgot to add this, but the version of the mod I'm using is for forge 1.12.2, so it would be nice if you do decide to add this feature, to put it in this version too. Thanks :)

**Comment by Tiviacz1337** [comment]
So, about backpacks inside shulkers, that seems kinda overcomplicated, but I'll probably add tag, where you can add any item you want via datapack, and they will not be allowed to be placed inside backpack.

**Comment by Tiviacz1337** [comment]
I've added blacklisted_items tag

**Comment by nickylp8** [comment]
Thank you so much! I'll try to update all the mods I'm using to 1.16.5, I think its worth it now that you added this feature

**Comment by Tiviacz1337** [comment]
It'll be available in the next update in a few days

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3271219
