### ISSUE TITLE
Librarians sell backpacks in place of nametags

### ISSUE THREAD

**Issue by ExArch3r** [Tiviacz1337/Travelers-Backpack#280]
**Describe the bug**
Master librarians normally sell nametags but instead only offer backpacks. 

**To Reproduce**
1. Level a librarian to master and try to trade with it, it will offer a backpack instead of a name tag

**Expected behavior**
They normally sell nametags instead of the backpack

**Screenshots**

**Required informations (please complete the following information):**
- Minecraft 1.6.5 and the latest version of the mod downloaded today

**Additional context**
Love the mod, this is the first bug I've encountered so far.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3271219
