### ISSUE TITLE
MISSING ITEMS

### ISSUE THREAD

**Issue by catgirl30** [Tiviacz1337/Travelers-Backpack#283]
**Describe the bug**
No drawers basicallly all the items are missing

**To Reproduce**
1. Download the  newset version and run it

**Expected behavior**
The mod working and the items schowing up

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: [e.g. 1.16.4 - 5.3.7]

**Additional context**

**Comment by Tiviacz1337** [comment]
Few of the custom backpacks are available from version 5.4.0
