### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by RedWolfGaming** [Tiviacz1337/Travelers-Backpack#284]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

1.12.2
I am sad when the backpacks are updated to 1.16 the 1.12.2 is abandoned (in terms of not that much uniqueness) along with some compatibility suggestion of some certain mods

backpacks
magnet backpack where the items on a certain range get collected
furnace backpack where you can smelt items
hopper backpack where there's one button that puts all items from your inventory (except Hotbar) in a top to bottom order and whatever is stackable goes with it to the backpack
pufferfish backpack where you can have water breathing underwater
spider backpack allows you to climb and hang on the ceiling 
bats backpack allows you to have feather falling
ocelot allows you to have night vision and scares away creepers
magma backpack or any lava based backpack gives fire resistance
brewer backpack turns water to random potions every 10 minutes worn (configurable)
shield styled backpack gives resistance
enderchest backpack allows a remote access to an ender chest

any features that are overpowered here can have existing backpacks crafted with expensive materials to give that feature (can't abandon 1.12.2 and it's possibilities)

Tough as nails compatibility where you can have the water tank fill up with purified water when under water or in rain (maybe a place to put the filter from tough as nails mod)

 so many possibilities of other mod compatability/ features to this backpack mod or more backpacks

**Comment by 1adam2010** [comment]
dont work crafting sleeping bag
