### ISSUE TITLE
Using JEI to add a backpack recipe to the backpacks crafting grid will trash either items or the 'standard' bag.

### ISSUE THREAD

**Issue by markygnlg** [Tiviacz1337/Travelers-Backpack#285]
**Describe the bug**
I use multiple colours of the **TravelersBackpack** [**T/B** - from here on] & change their colours (ie. 'v1.12 Abilities') to differentiate between them.
When I remembered that the **T/B** has a crafting grid I used it to change a standard **T/B** to a **T/B-redstone** - but because you can not place a **T/B** into a **T/B** the recipe either trashed/erased my **T/B** or the items used in the recipe.

**To Reproduce**
1. open a **T/B** (either from the hand or worn on back);
2. hover over a block of redstone & press "U" (default for JEI "Usage");
3. if all items are available in inventory, press the "+" (plus) button to add recipe into the **T/B** crafting grid;
4. the 'standard' **T/B** does not show in the centre of the crafting grid for the recipe nor the output of the recipe;
![1a](https://user-images.githubusercontent.com/62978705/115384297-06ae5280-a216-11eb-9ac8-d74fe3793ef3.png)
![2a](https://user-images.githubusercontent.com/62978705/115384303-09a94300-a216-11eb-81a7-54a09a7be87a.png)

but both bags are there, however:
 - if I click the output a 'standard' **T/B** is the result & my all my items in the recipe are gone/used without giving me my 'redstone' **T/B**;
 - if I exit/escape the GUI I will lose my 'standard' **T/B** that is in the centre of the recipe (ie. I lost the 'standard' **T/B** used in the recipe, along with everything in it)

**Expected behavior**
Either the recipe completely fails & I need a vanilla crafting table to make **T/B** colour variations ('v1.12 abilities'/colours) or I get my BrandSpankingNew redstone **T/B**

**Screenshots**
Posted up above in the 'steps' step

**Required informations (please complete the following information):**
 - Mod version: TravelersBackpack-1.16.5-5.4.1.jar
 - MC ver 1.16.5

**Additional context**
... ask & ye shall be answered...

**Comment by Tiviacz1337** [comment]
That may be the issue with JEI

**Comment by Tiviacz1337** [comment]
Have you tried reporting this issue to JEI author?

**Comment by markygnlg** [comment]
No I have not. I thought it was worth mentioning here though but I no longer worry about it since I now know to avoid it - only the 1st time it happened really confused me so I made a copy of my savegame to see why/what happened & if it was reproducible.

I only use 4 bags at most so its easy to work around it.

**Comment by markygnlg** [comment]
I'm not sure if you'll get this message but I've restarted a game & am using '[CraftingCraft](https://www.curseforge.com/minecraft/mc-mods/craftingcraft)' mod {it's a portable crafting table} & JEI is doing a similar thin but it dupes {duplicates items} rather than making them disappear - so you maybe onto something about JEI causing the issue.

I've used 'CraftingCraft' much longer than your mod & I've never noticed the duping before [coz it neva happened]...

I'll try older versions of JEI & update this thread if need be - & I'll make a JEI Issue if tests show a difference.
