### ISSUE TITLE
i get a error while loading the mod

### ISSUE THREAD

**Issue by maxichunk51** [Tiviacz1337/Travelers-Backpack#290]
idk how to describe but its the 5th time i see the error it doesnt say anything 
![Ekran görüntüsü 2021-04-27 200619](https://user-images.githubusercontent.com/83302889/116282997-125cc480-a794-11eb-85b9-9a49a46faa0d.png) this why is it happening please tell me im using the newest version

**Comment by Tiviacz1337** [comment]
Send crash log

**Comment by maxichunk51** [comment]
> Send crash log

ok
[crash-2021-04-27_17.23.35-fml.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/6392423/crash-2021-04-27_17.23.35-fml.txt)

**Comment by maxichunk51** [comment]
what should i do???

**Comment by Tiviacz1337** [comment]
I don't know yet

**Comment by Tiviacz1337** [comment]
I think I found the fix, do you have time to test it? I can't reproduce this issue

**Comment by markygnlg** [comment]
> what should i do???

I'd suggest removing CosmeticArmorReworked-1.16.5-v1b.jar {or [testing an older version of the mod <--CLICK HERE for direct link to 'Files'](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked/files/all)}

Both mods 'draw stuff' onto your character so one may interfere with the other...

2nd option to test: remove/update/downgrade any mods that either 'draw stuff' on your character &/or change storage settings {keep in mind this mod also changes/adds: sleeping bag, fluid storage, quick-change tool slots, automation via hoppers/etc, so mods you have that perform a similar function may interfere with Travelers-Backpacl}

**Comment by Tiviacz1337** [comment]
That's not the proper solution, I probably fixed it, but I can't test because I'm not able to reproduce this issue anyhow. It's because I'm storing backpack names in list, using toLowerCase method, which takes local java machine language. Maxichunk51 is probably using language which has `ı` letter instead of `i`. I've set Local.ENGLISH language, so it will always change 'I' to 'i" and not cause crash. But as I said, it needs test, and then I can upload new version.

**Comment by BlueDemonTR** [comment]
The problem possibly occurs if the system you are using is in Turkish. One of the players in the server I am playing right now has the same issue

**Comment by Tiviacz1337** [comment]
yeah that's it. Can he test the file?

**Comment by eminkoral** [comment]
I have also the same problem with Turkish keyboard. I can test it if needed.

**Comment by Tiviacz1337** [comment]
message me on discord

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3316664
