### ISSUE TITLE
Inventory access while wearing stopping and backpack clearing on the floor

### ISSUE THREAD

**Issue by NyanRose** [Tiviacz1337/Travelers-Backpack#296]
**Describe the bug**

Me and another person on our server are having some issues with the backpack. It was working great but then all of a sudden it stopped allowing us to access the inventory while it's on our back. The only way to get it off is to die(and lose all our levels). I have been using it from my inventory which has..worked but is a lot less convenient than it was before. This has happened to me and 1 other person on our server of 3 so far. Any ideas on how to fix this? I have tried resetting and changing the keybinding, respawning, ect. Nothing has worked. It still works fine in singleplayer.

 

Another thing that came up, I had my backpack spawned on the floor then logged out. After logging it the backpack was completely empty and wiped.

**To Reproduce**
I am not sure. It just...happens. When it first happened I was having no issues, just playing normal then went to access the backpack and nothing. I tried restarting, sleeping, resetting the keybind, changing the keybind, tried it in single player(still works there), restarting the server, dying, nothing fixed it. The only thing that temporarily fixed it was when we did a rollback to before the issue but then it worked for 3 access attempts then stopped. I had to die to get it off my back and now just put it on the floor when I need to access it, but I miss accessing it through my back. As for the clearing, I dont know how that happened either. I put my backpack on the ground, logged out, and when I logged back in everything was gone. (wasn't stolen, I only play with my two friends and they were as confused as I was. 

**Expected behavior**
N/A

**Screenshots**
not sure how to screen shot a button not working

**Required informations (please complete the following information):**
 - Mod version: 1.16.5

**Additional context**
N/A

**Comment by Tiviacz1337** [comment]
Could you provide log? Click few times keybind to open backpack and send me the logs

**Comment by NyanRose** [comment]
I have access to this, is this what you need? 
[latest.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/6593799/latest.log)
[2021-06-03-1.log.gz](https://github.com/Tiviacz1337/Travelers-Backpack/files/6593800/2021-06-03-1.log.gz)

**Comment by Tiviacz1337** [comment]
Have you tried opening backpack when it was on your back during this session? Also can you send me the image of backpack inventory with your items inside?

**Comment by NyanRose** [comment]
I did, I spammed b several times, nothing. If I die I can get it off, let me get you some screen shots. 
![2021-06-04_11 58 45](https://user-images.githubusercontent.com/85238760/120837656-968d2f00-c52c-11eb-8233-09ec6ddd41ad.png)
![2021-06-04_11 58 52](https://user-images.githubusercontent.com/85238760/120837660-97be5c00-c52c-11eb-8456-2198c85bd6c2.png)
![2021-06-04_11 58 55](https://user-images.githubusercontent.com/85238760/120837664-98ef8900-c52c-11eb-856f-73b9a5cdc0e6.png)
https://i.gyazo.com/aae2f7183560debfa0e948da2ed29a13.mp4

**Comment by Tiviacz1337** [comment]
![image](https://user-images.githubusercontent.com/34790800/120887295-45e00980-c5f2-11eb-85a7-184119b32186.png)
What is it?

**Comment by NyanRose** [comment]
that's a sack, it's from a mod called supplementaries. When we were moving from one area to another we used it to move more items by putting sacks in the backpack. But I was able to use the backpack with these for a few days with no issues, and one of our friends still doesn't have a problem. I can see if removing them from the bag helps?

**Comment by NyanRose** [comment]
oh....well that seemed to fix it. Odd that it wasn't a problem initially. I wonder why it was an issue, thank you I am glad it's working now

**Comment by NyanRose** [comment]
though after some death issues my backpack completely cleared after I died, so not sure what is going on :( oh well thank you for your time

**Comment by Tiviacz1337** [comment]
Probably itemstack data was too big

**Comment by NyanRose** [comment]
when I died and it cleared there were only vanilla items in it, but I will keep in mind for the future that putting sacks in the backpack can cause issues. Thank you for your assistance

**Comment by NyanRose** [comment]
Hello, quick question again and thank you for your patience. My friend and I died in the nether and when we came back our backpacks had cleared completely, this is the second time it happened. Any idea why that  might be happening? It had mostly vanilla stuff in it and a few ice and fire items. No sacks

**Comment by Tiviacz1337** [comment]
What version of mod do you use?

**Comment by NyanRose** [comment]
this version 

TravelersBackpack-1.16.2-5.1.0

**Comment by Tiviacz1337** [comment]
I recommend you to update to 5.4.2, And the issue that backpack do not save contents was present in 5.1.0 it was fixed in 5.1.1

**Comment by NyanRose** [comment]
thank you! I will let my server know to update, I really appreciate the quick responses! Love the mod by the way :)
