### ISSUE TITLE
Failed to disable Empty Button

### ISSUE THREAD

**Issue by RuggedTime** [Tiviacz1337/Travelers-Backpack#297]
**Describe**
I've disabled the empty button, but it can still be clicked. And I have changed the files in the config folder and the serverconfig folder

**Screenshots**
![image](https://user-images.githubusercontent.com/46664847/120928315-c435cc00-c716-11eb-9f9d-e58b076ab7d8.png)
![image](https://user-images.githubusercontent.com/46664847/120928339-d879c900-c716-11eb-93e7-ee6b5b12950f.png)
![image](https://user-images.githubusercontent.com/46664847/120928505-7e2d3800-c717-11eb-92f8-a76f440b2a5f.png)

**Java Version**
![image](https://user-images.githubusercontent.com/46664847/120928681-3ce95800-c718-11eb-8af8-e948ce710eab.png)

**Mod List**
![image](https://user-images.githubusercontent.com/46664847/120928542-a2891480-c717-11eb-876e-c65515f44a04.png)
![image](https://user-images.githubusercontent.com/46664847/120928645-0f041380-c718-11eb-8366-bc5bf57712ff.png)
![image](https://user-images.githubusercontent.com/46664847/120928658-1fb48980-c718-11eb-9fa6-055d0df2cc94.png)
![image](https://user-images.githubusercontent.com/46664847/120928665-27742e00-c718-11eb-98ad-a075b4c1af1e.png)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3412115
