### ISSUE TITLE
Cannot use mod in minecraft version 1.16.5, has the mod not been updated for this version?

### ISSUE THREAD

**Issue by 99noobsdied** [Tiviacz1337/Travelers-Backpack#300]
![imagem](https://user-images.githubusercontent.com/86237453/122757948-1e469d80-d290-11eb-9c19-f093aa82e173.png)
![imagem](https://user-images.githubusercontent.com/86237453/122757981-2999c900-d290-11eb-81e6-a546184f2267.png)

**Comment by Tiviacz1337** [comment]
That's not how you install mods I guess?
