### ISSUE TITLE
Bat Backpack does not give night vision

### ISSUE THREAD

**Issue by RCelty** [Tiviacz1337/Travelers-Backpack#301]
**Describe the bug**
The Bat Backpack's ability (night vision) does not work.

**To Reproduce**
Put Bat BackPack on.

**Expected behavior**
Get the effect "night vision"

**Screenshots**
![image](https://user-images.githubusercontent.com/71772102/122915317-d609a700-d385-11eb-91ef-532de1751dd1.png)
![image](https://user-images.githubusercontent.com/71772102/122915396-e9b50d80-d385-11eb-9c96-88aa570a0e0a.png)

**Required informations (please complete the following information):**
 - Mod version: [e.g. 1.16.5 - 5.4.1]

**Additional context**

**Comment by Tiviacz1337** [comment]
Abilities are not implemented yet
