### ISSUE TITLE
Quark Management GUI bug

### ISSUE THREAD

**Issue by KNAMco** [Tiviacz1337/Travelers-Backpack#303]
GUI bug  with quark inventory gui and travelers backpack 

**Screenshots**
![image](https://user-images.githubusercontent.com/86417333/123270310-6b5f8500-d4c5-11eb-8cc5-b190e594ee5c.png)

Quark: Quark-r2.4-312
TB: TravelersBackpack-1.16.5-5.4.2

Everything in quark has been disabled

**Comment by Figgmastah** [comment]
I have the same problem someone help us

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3412115
