### ISSUE TITLE
Losing Items

### ISSUE THREAD

**Issue by RCelty** [Tiviacz1337/Travelers-Backpack#304]
**Describe the bug**
My items in the backpack keep losing randomly

**To Reproduce**
Everytime I log back into the world, one or two items in the backpack disappear.

**Expected behavior**

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: [e.g. 1.16.5 - 5.4.1]

**Additional context**

**Comment by Tiviacz1337** [comment]
Could you record that?

**Comment by RCelty** [comment]
I'm afraid I can't because I'm not having free time now. But I can give you
some detail, hope it will help: lost items are from others mod, such as
nature compass, lasso from Tiny mob farm and slime boots from tinker's
construct.

Vào 17:58, CN, 25 thg 7, 2021 Tiviacz1337 ***@***.***> đã
viết:

**Comment by Tiviacz1337** [comment]
I haven't experienced any item loss from backpack, that's weird

**Comment by LGM-vehnvey** [comment]
I currently have this problem, and is with vanilla items as well. It deletes the items from the backpack whenever you try to fast stack them from your inventory to the backpack (Holding shift + clicking). Once you close the backpack HUD the items you tried to store dissapear
