### ISSUE TITLE
[1.12.2]cannot refill water bottles

### ISSUE THREAD

**Issue by tonimark** [Tiviacz1337/Travelers-Backpack#305]
**Describe the bug**
can't just refill water bottles
**To Reproduce**
1. ...get any backup
2.get a water bottle
3.empty it in the bag
4.try to refill it
5.see the error
**Expected behavior**
i could just refill the empty glass bottle with water just like emptying but instead doesn't do anything
**Screenshots**
![2021-07-07_13 17 32](https://user-images.githubusercontent.com/17166550/124742884-d4afb100-df25-11eb-8001-df79a3cea3d2.png)

**Required informations (please complete the following information):**
 - Mod version: 1.12.2-1.0.35

**Additional context**

**Comment by Tiviacz1337** [comment]
Sorry 1.12 is no longer supported
