### ISSUE TITLE
Fluid level indicator bug inside gui

### ISSUE THREAD

**Issue by oceanarose** [Tiviacz1337/Travelers-Backpack#306]
**Describe the bug**
Fluid level indicators inside the backpack gui are duplicated on another part of the screen. 

**To Reproduce**
1. Open backpack gui
2. Place fluid to either the water or lava container(s)

**Expected behavior**
Fluid level indicators appears once in the gui in the correct places.

**Screenshots**
[https://prnt.sc/19t4u9j](url)
![image](https://user-images.githubusercontent.com/87207678/125130848-a256ad00-e0f9-11eb-9e47-e968bebed93c.png)

**Required informations (please complete the following information):**
 - Mod version: 1.16.3 - 5.2.1

**Additional context**
I had just installed the mod and had no prior experience with it beforehand.

**Comment by Tiviacz1337** [comment]
Update mod
