### ISSUE TITLE
Crashed when Sleeping

### ISSUE THREAD

**Issue by Mesarasi** [Tiviacz1337/Travelers-Backpack#308]
Sleeping Bag Issue
Crashed server when trying to sleep

**To Reproduce**
1. Sleep in the sleeping bag
2.

**Expected behavior**
I expected to be able to sleep

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: [e.g. 1.16.4 - 5.3.7]

**Additional context**

**Comment by Tiviacz1337** [comment]
Update to latest mod version
