### ISSUE TITLE
When the server uses this mod, the players exit the sever, and then enter the server, they can't open the backpack on thier back. 1.16.5

### ISSUE THREAD

**Issue by UnravelY** [Tiviacz1337/Travelers-Backpack#309]
**Describe the bug**
When I added this mod in my **server**, the players **couldn't open thier backpack on thier back** **_when they entered the server next time_**. No backpack displayed on their back, and they couldn't carry another backpack because it prompted they already have one. If they want to take the bags off, **they have to kill themselves**.

 - Mod version: TravelersBackpack-1.16.5-5.4.2.jar

 - I love this mod. If you can fix this bug, I'd appreciate it.

**Comment by Tiviacz1337** [comment]
I'll check it

**Comment by Tiviacz1337** [comment]
I do not experience this issue, does the console say something?

**Comment by bakiyzr** [comment]
I solved it by deleting SkinsRestorer plugin
