### ISSUE TITLE
Backpack not placed on death

### ISSUE THREAD

**Issue by eXoQueen** [Tiviacz1337/Travelers-Backpack#310]
Normally when using this mod the backpack places itself upon death, this is a really useful feature. However, I recently died from fall damage and the backpack has not placed, nor is it among the items to be picked up - has just totally disappeared.

**Comment by Tiviacz1337** [comment]
Did you just click respawn or left the game and then entered again? Did you receive coordinates message? Do you play on server?

**Comment by eXoQueen** [comment]
Thanks for the response!This was on an aternos server – I have only ever used this mod on the server in question and every other death has been no issue for myself or other players. I immediately clicked respawn but have since had to exit the game and been back on – no sign at all though other items dropped on death were found so it shouldn’t have despawned or anything. I didn’t receive a coordinates message – never do for this server but I was near my base so I know where it was. I found the death spot but no sign of the backpack.  From: Tiviacz1337Sent: 25 July 2021 07:01To: Tiviacz1337/Travelers-BackpackCc: eXoQueen; AuthorSubject: Re: [Tiviacz1337/Travelers-Backpack] Backpack not placed on death (#310) Did you just click respawn or left the game and then entered again? Did you receive coordinates message? Do you play on server?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3495735
