### ISSUE TITLE
Backpack disappears in nether

### ISSUE THREAD

**Issue by Jabroni88** [Tiviacz1337/Travelers-Backpack#313]
**Describe the bug**
After entering the nether or reentering the overworld, my backpack was just gone. Must relog in order to get backpack back.

**To Reproduce**
1. Equip backpack
2. Enter Nether or enter overworld from the nether
3. save and quit
4. relog in to the world and the backpack is there again with all the items

**Required informations (please complete the following information):**
 - Mod version: 6.0.1 on mc version 1.17.1

**Additional context**
My game ran very slow (5-10 fps) after logging back in to retrieve the backpack in the overworld. Closing and reopening Minecraft crashed the first time when trying to restart.

**Comment by Suaverussian** [comment]
Same issue, same version. Addition- Backpack disappears entirely and unable to to retrieve with a relog under certain conditions.

To reproduce:

1. Have backpack equipped in OW
2. Unequip backpack and place in inventory
3. Enter Nether
4. Equip backpack
5. Backpack disappears completely and does not return on relog.

Found while troubleshooting for the above issue which is also happening on my singleplayer world. 

Version info
MC 1.17.1 Forge version 37.0.27 Mod Version 6.0.1

Had a single instance of the low frame issue happen as well, but no crash on relaunch. Ryzen 9 3900x RTX 3090 32GB TridentZ Neo 3600 NVmE SSD Samsung 970 1TB

**Comment by Tiviacz1337** [comment]
Confirmed, I'll work to fix it

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3429088
