### ISSUE TITLE
Backpack deleting when GameRule "keepInventory" is enabled. 

### ISSUE THREAD

**Issue by SkylerMews** [Tiviacz1337/Travelers-Backpack#316]
**Describe the bug**
When GameRule "keepInventory" is true, and the backpack is equipped, the backpack is deleted. It's not dropped or still equipped, just "gone".

**To Reproduce**
1. Change GameRule "keepInventory" to true.
2. Equip backpack.
3. Die.

**Expected behavior**
The backpack should stay equipped to the player.

 - Mod version:  1.17.1-6.0.2
 - Minecraft Version: 1.17.1
 - Forge Version: 37.0.34

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3430274
