### ISSUE TITLE
Disappearing Backpack

### ISSUE THREAD

**Issue by IDEZIHREE** [Tiviacz1337/Travelers-Backpack#317]
Problem
Backpack disappears from back at random times and it doesn't go onto the ground 

Reproduce the Glitch
Both times it has been when I go into the nether but I'm not for sure if that is the problem

Mod Version: 1.17.1-6.0.1

**Comment by Tiviacz1337** [comment]
Update to 6.0.3

**Comment by IDEZIHREE** [comment]
game crashes if you update to 6.0.3 and server does not start. same with 6.0.2. 6.0.1 works just fine with game and server though except disappearing backpack. Any ideas?

**Comment by Tiviacz1337** [comment]
what's your forge version?

**Comment by IDEZIHREE** [comment]
Im running on 1.17.1 37.0.25

**Comment by Tiviacz1337** [comment]
update to 37.0.34

**Comment by Tiviacz1337** [comment]
or newer

**Comment by IDEZIHREE** [comment]
okay Ill try it out
