### ISSUE TITLE
Suggestion: make controls more understandable

### ISSUE THREAD

**Issue by Alex-1000** [Tiviacz1337/Travelers-Backpack#319]
Please leave note on Curseforge/Github wiki that you need to scroll mouse to change hose mode because it is hard to understand what you need to do to change mode until you get mode changed by random pressing every single button

**Comment by Tiviacz1337** [comment]
![image](https://user-images.githubusercontent.com/34790800/130429200-773f51e7-d0d0-45e5-9520-ce824980c465.png)
