### ISSUE TITLE
Incompatibility with Tinker's Construct, milk texture breaks

### ISSUE THREAD

**Issue by NyanMC** [Tiviacz1337/Travelers-Backpack#32]
It doesn't crash and they're surprisingly compatible with each other, except the texture breaks for JEI and Tinker's Construct. The milk texture for the backpack GUI is fine and milk buckets still show milk correctly (even modded buckets).
Edit: The milk texture for the backpack GUI actually isn't normal, but you can place milk with the hose and it doesn't have a broken texture.

**Comment by NyanMC** [comment]
edit 2: trying to use a drain on a smeltery when the active fluid is milk causes the game to crash upon load multiple times depending on how much milk you're draining. the first time the game starts without crashing, the game will have several rendering issues (chunk you're standing in and the surrounding chunks become invisible), which can be fixed by closing the world and reloading it.

**Comment by Tiviacz1337** [comment]
Do issues still persist?
