### ISSUE TITLE
Crash with The Betweenlands barrels

### ISSUE THREAD

**Issue by MrRedstoneA1** [Tiviacz1337/Travelers-Backpack#320]
Description
When trying to transfer liquid from backpack tank to a Betweenlands barrel, when the tank is empty the game instantly crashes.

1. Equip the backpack.
2. Equip the hose.
3. Put the hose in "spill" mode.
4. Attempt to transfer liquid from the empty tank to barrel.

Expected behavior
Nothing should happen because the tank is empty. Instead the game instantly crashes.

 - Mod version: 1.0.35
 - Crash log: https://gist.github.com/MrRedstoneA1/b4a40be1e750ab379bd4b07973a4ee08

Additional Context
I also submitted a ticket to the authors of The Betweenlands, and they determined that the issue is on your side. They said:
"That's an error on Traveler's Backpack's side. More specifically, it seems to try filling the barrel with a null FluidStack, which isn't allowed. It should instead use FluidUtil#tryFluidTransfer."

**Comment by Tiviacz1337** [comment]
Sorry, 1.12.2 is no longer supported

**Comment by MrRedstoneA1** [comment]
Aw man. That means that this issue will forever be in the 1.12.2 version.
