### ISSUE TITLE
Dissapearing backpack w/ IceandFire Dragon mod

### ISSUE THREAD

**Issue by Elesvan20** [Tiviacz1337/Travelers-Backpack#322]
**Describe the bug**
Backpack Dissapearing when died from Ice and Fire dragon mod. When the dragon kills you, sometimes the backpack is placed next to the death point but other times backpack just dissapears. Also, sometimes, if Tombstone is enabled, when using the key on the grave, the backpack is added to the inventory but it was doing it every time.

**To Reproduce**
1. Ice and Fire Dragons mod
2. Equip a backpack (to the "back" of the player)
3. Get killed by dragon breath

**Expected behavior**
I expected the backpack to be placed next to the Tombstone and to my surprise, it did not.

**Required informations (please complete the following information):**
 - Mod version: 1.16.5

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3495735
