### ISSUE TITLE
Will conflict with a feature of ImproveLib

### ISSUE THREAD

**Issue by SHDocter** [Tiviacz1337/Travelers-Backpack#323]
This may not be a bug. I don't know if it will be fixed. I just report the problem. Improved Lib modified the mojang's furnace and workbench judgment method, and changed the original exhaustive method to a method that may be written by the author. The configuration file can be closed, but if you enable this setting, using the right mouse button to open the backpack in the shortcut bar will cause the game to crash, and you cannot use the shortcut key to open the backpack.
![image](https://user-images.githubusercontent.com/72510879/131549123-bbf6395a-049d-4d1e-bbbc-7536f85f9f94.png)
[improvementLibrary.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/7085766/improvementLibrary.txt)
(The source file format is json.)

**Comment by Tiviacz1337** [comment]
Can you provide crashlog?

**Comment by SHDocter** [comment]
[debug.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/7273087/debug.log)
[latest.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/7273088/latest.log)

I don't know which one can help you
