### ISSUE TITLE
Piston boots

### ISSUE THREAD

**Issue by Arcturus2022** [Tiviacz1337/Travelers-Backpack#331]
**Is your feature request related to a problem? Please describe.**
Are there any plans to add the piston boots from original mod?

**Describe the solution you'd like**
Add the piston boots to game

**Describe alternatives you've considered**
Create some other simple gear like a climbing axe

**Additional context**

**Comment by Flexico** [comment]
Something I really enjoyed about the piston boots is the "auto-jump only when sprinting" feature! ^_^
