### ISSUE TITLE
Equipping backpack tanks fps, from 60 to like 20

### ISSUE THREAD

**Issue by djL01** [Tiviacz1337/Travelers-Backpack#335]
**Describe the bug**
Anytime I equip the backpack on my person, my in-game FPS tanks from 60 to 19-24ish. Placing it on the ground or holding it in my hand works fine and nothing of note happens to my FPS.

**To Reproduce**
1. Have backpack
2. Equip backpack from its inventory
3. FPS drops from smooth to choppy

**Expected behavior**
1. Have backpack
2. Equip backpack from its inventory
3. Play game like normal with no noticeable drop in FPS

**Required informations (please complete the following information):**
 - Mod version: 1.17.1-6.0.4
 
**Other mods installed:**
appleskin-forge-mc1.17.1-2.1.0.jar
balm-1.6.0+0.jar
BetterAdvancements-1.17.1-0.1.2.116.jar
burgermod-2.5.0-1.17.1.jar
catalogue-1.3.0-1.17.1.jar
ChunkAnimator-1.17.1-1.3.3.jar
collective-1.17.1-2.64.jar
configured-1.2.0-1.17.1.jar
constructionwand-1.17.1-2.3.jar
Controlling-8.0.0.4.jar
cookingforblockheads-10.0.0+0.jar
CosmeticArmorReworked-1.17.1-v1.jar
CraftableHorseArmour-1.17.1-1.6.jar
craftingtweaks-13.0.0+0.jar
curios-forge-1.17.1-5.0.1.0.jar
elevatorid-1.17.1-1.8.1.jar
FastLeafDecay-26.jar
Food-plus-1.3.1.jar
InventoryHud_[1.17.1].forge-3.4.0.jar
iris-and-sodium-mc1.17-1.1.2+build.9.jar
ironchest-1.17.1-12.0.2.jar
jei-1.17.1-8.1.0.26.jar
journeymap-1.17.1-5.7.3rc3.jar
JustEnoughResources-1.17.1-0.13.0.131.jar
MouseTweaks-2.14-mc1.17.1.jar
replantingcrops_1.17.1-2.4.jar
silent-gear-1.17.1-2.7.4.jar
silent-lib-1.17.1-5.0.0.jar
sit-1.17.1-v1.3.1.jar
supermartijn642corelib-1.0.12-mc1.17.jar
sweetberrypie-1.17.1-1.0.jar
theoneprobe-1.17-4.0.2.jar
torchmaster-3.0.1-beta.jar
trashcans-1.0.10a-mc1.17.jar
TravelersBackpack-1.17.1-6.0.4.jar

**Comment by UnPik** [comment]
Hi @djL01,
We was experiencing the same issue in a private server and what we did, as a workaround, is to disable the hud info of this mod on client side by setting enableOverlay to false in the config file.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3667525
