### ISSUE TITLE
[1.16.5] Compatibility with Fast Workbench?

### ISSUE THREAD

**Issue by Flexico** [Tiviacz1337/Travelers-Backpack#336]
**Is your feature request related to a problem? Please describe.**
When I have a lot of mods installed, and I shift-click a stack of items out of a crafting table, there's a huge lag spike due to the game running through every recipe for each item in the stack. However, there's a mod called Fast Workbench that makes the crafting routine save the last recipe and check that first when moving on to the next item, so the lag spike completely disappears! ... In a vanilla crafting table, anyway. The problem is that the crafting grid in the backpacks doesn't use the same crafting protocol, and so the lag spike still happens when using one.

**Describe the solution you'd like**
I already contacted the creators of the Fast Workbench mod about this, and they said a compatibility patch would have to be done on your end.

**Describe alternatives you've considered**
Just dealing with the lag, or using vanilla crafting tables. I tend to bounce back and forth between both. XD

**Additional context**
I don't know what else there is to say! Thank you for your time, both in making this epic mod and taking the time to read my post!
Oh yes, and a link to the other mod: https://www.curseforge.com/minecraft/mc-mods/fastworkbench

**Comment by Tiviacz1337** [comment]
I mean I'll send you the jar file through discord or something, so you could test it. Is it okay?

**Comment by Flexico** [comment]
Oh, ok! Yeah, that works! My Discord is Flexico#4816

**Comment by Tiviacz1337** [comment]
sent invite

**Comment by Tiviacz1337** [comment]
Added in 5.4.6, 6.0.6, 7.0.0
