### ISSUE TITLE
Travelers Backpack Fabric 1.16.5

### ISSUE THREAD

**Issue by JoKi07** [Tiviacz1337/Travelers-Backpack#338]
Hi there,
I found a bug in your mod Traveler's Backpack (Fabric) and that is when I start mincraft with the fabric launcher and the mod, minecraft always crashes and shows me some error code.
I have also installed the mod that is described as necessary in the Traveler's Backpack mod description (Fabric API).
I hope the text is understandable i made it with googel translator because i'm really bad at english.
Ps. JoKi07

here is a screenshot of what mienecraft always shows me:
![Unbenannt](https://user-images.githubusercontent.com/93378324/139434154-de4d4ed6-6ecc-4fe4-955c-d5e672a28f1a.png)

**Comment by Tiviacz1337** [comment]
You have to update fabric api

**Comment by JoKi07** [comment]
okay thanks
