### ISSUE TITLE
Traveler's Backpack [FABRIC] 1.17.1-6.0.0 crash on startup

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [Tiviacz1337/Travelers-Backpack#339]
**Describe the bug**

When travelers-backpack-1.17.1-6.0.0 is installed, the game will crash on startup.

**To Reproduce**

1. Install fabric loader and API
2. Install travelers-backpack-1.17.1-6.0.0
3. Launch the game

**Expected behavior**

The game should launch.

**Logs**

https://gist.github.com/Footage2-Amply-Pounce/8ef39aebdbe069aa4a3e6f83999105a0

Forgot to install cloth config, oops, here's a log with it installed (it's the same crash regardless):
https://gist.github.com/Footage2-Amply-Pounce/b7167c0d3710470d8c4b6851b1aada56

**Required information (please complete the following information):**

 - Mod version: 1.17.1-6.0.0

**Additional context**

Fabric loader version 0.12.3
Fabric API version 0.41.0

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/3508937

**Comment by Tiviacz1337** [comment]
It's hotfix, file name is the same, because I deleted previous file since there wasn't much downloads
