### ISSUE TITLE
Travel bag disappear.

### ISSUE THREAD

**Issue by liaoshuaige** [Tiviacz1337/Travelers-Backpack#340]
When there are two travel bags in the inventory, one of them will disappear.

1. Put two Travel bags in the inventory
2. Open a Travel bag, and then press the arrow that puts everything in the inventory into the Travel bag
3. Another travel bag disappears

 - Mod version: [1.12.2 - 1.2.5]

**Comment by Tiviacz1337** [comment]
This version is way too old. Update
