### ISSUE TITLE
Trinkit issue

### ISSUE THREAD

**Issue by 32bitx64bit** [Tiviacz1337/Travelers-Backpack#341]
Describe the bug
When equipping the backpack with the trinket slot (directly) it doesnt allow u to access the backpack

To Reproduce
Just drag the backpack to the trinket slot

Expected behavior
Should just act like how u put it on normally (via the GUI)

Extra info
 - Mod version (latest 1.17 build)
on the fabric version

**Comment by 32bitx64bit** [comment]
Forgot to add a label - oops

**Comment by Tiviacz1337** [comment]
Did you enable trinketIntegration in config?

**Comment by 32bitx64bit** [comment]
I dont believe so (Hope this will be enabled by default as most ppl dont look in the config)
Thanks

**Comment by 32bitx64bit** [comment]
Alr once enabled it worked thanks
