### ISSUE TITLE
Incompatible with MouseWheelie

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [Tiviacz1337/Travelers-Backpack#343]
**Describe the bug**

Traveler's backpack crashes when using multiple stack transfer feature from MouseWheelie (ctrl + LMB).

**To Reproduce**

1. Get a backpack and a few stacks of stones (can be any items, as long as they are spread across multiple slots)
2. Open the backpack and left click on the stones while holding control
3. The game will crash

**Expected behavior**

Items should transfer from the player's inventory to the backpack.

**Logs**

- latest.log: https://gist.github.com/Footage2-Amply-Pounce/293fbd3a1e655ef2c888ea4161800c38
- crash log: https://gist.github.com/Footage2-Amply-Pounce/c0344a7bee2785e2dbd7604f11fef642

**Required informations (please complete the following information):**

 - Mod version: travelers-backpack-1.17.1-6.0.0
 - Fabric: loader 0.12.3; API 0.41.3

**Additional context**

MouseWheelie mod: https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie

**Comment by Tiviacz1337** [comment]
Could you test it on loader version 0.13.3 and api 0.46.1? Because I can't reproduce this issue

**Comment by Footage2-Amply-Pounce** [comment]
Sorry, but I am currently not active in Minecraft modding. Since the issue is quite old and not reproducible by you, I'm ok if you close it. In case anyone encounters it in the future, it's better to open a new issue anyway, considering there's been a fair amount of updates for fabric, mods and Minecraft itself.
