### ISSUE TITLE
I cant equip a backpack because of a bug

### ISSUE THREAD

**Issue by CheezeNut** [Tiviacz1337/Travelers-Backpack#346]
I was swapping items in my inventory, and when I went to swap a backpack with a brewing stand, the brewing stand disappeared from my inventory. I think I somehow equipped it or something because since then, I can no longer equip a bag, and when i try to equip one from off the ground, the backpack itself disappears.
do you have any ideas of how i could fix this? thanks.

**Comment by Tiviacz1337** [comment]
Is it possible for you to record a video? I can't reproduce this
