### ISSUE TITLE
Name changing problem

### ISSUE THREAD

**Issue by GipsyPotter** [Tiviacz1337/Travelers-Backpack#348]
**Describe the bug**
When I change the name of the backpack, it change, but when I place it down and took it up, the backpack's name changed to its default.

**Required informations (please complete the following information):**
 - Mod version: [e.g. 1.17.1 - 6.0.5]

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3596420
