### ISSUE TITLE
Green slot swap/change not working

### ISSUE THREAD

**Issue by GFreenD** [Tiviacz1337/Travelers-Backpack#350]
**Describe the bug**

**To Reproduce**
1. install the mod and notice it not working

**Expected behavior**
to swap a tool when when its in green slot while holding down z and using scroll wheel

**Required informations (please complete the following information):**
 - Mod version: 1.17.1-6.0.0

**Additional context**
i think this got added through All of fabric 4 mod not sure how the moding works in minecraft (seems like one mod pack that downloaded the other existing mod so maybe the isue is in the controls of the other?)
other then that i can swap tools normaly whit my wheel but not the ones in green slot that this mod supports.

**Comment by Tiviacz1337** [comment]
you have to hold keybinding + use scroll to make it work, also tool in your hand must be accpetable by green slot in backpack
