### ISSUE TITLE
Can't break backpack block with anything but Hand but Tinkers Survival mod doesn't allow me to.

### ISSUE THREAD

**Issue by trollkind** [Tiviacz1337/Travelers-Backpack#352]
I'm playing on 1.12.2 with both Traveler's Backpack and Tinkersurvival and I don't really want to miss out on either mod.
Tinker Survival doesn't allow breaking blocks by hand except some whitelisted ones and unfortunately only has a whitelist for tools and armor but not general minecraft blocks. It's a feature request on that mod to introduce a block whitelist but no news there.

There's a sound being played by the Tinkersurival mod when you mine something that isn't allowed (a child's laugh mocking you for trying) and it works normally when I load the save without the survival mod.

What would help on this mod's side would be allowing the breaking of the backpack block by tools too. I have found BlockTravelersBackpack.class and where it mentions the Hand as the breaking tool but I don't know what to change it to or if the file would still be valid, so I don't think I can make my own override. I guess the Hand only thing is to make sure there's an empty spot in the inventory?
Alternatively, add the "equip backpack" button to the backpack inventory screen. I know there isn't currently a place for that since the sleep button is shown when it's placed as a block but I'm sure that could be somehow remedied.
Another alternative would be a hotkey to break and equip a placed targeted backpack block but I don't know if that's possible and there already are too many hotkeys on too many mods.

Any solution would be greatly appreciated, my backpack is currently sitting in the air above my workbench since I accidentally placed it right after finally being able to build one and now I can't do anything with it.

**Comment by trollkind** [comment]
I naively simply changed "hand" to "axe" in BlockTravelersBackpack.class in the setHarvestLevel line (with notepad++) and replaced the file with 7zip in the Jar but the mod wouldn't even load anymore. I have no clue of Java or minecraft modding, just know Lua and Python and a bit of C++. So, no idea if the if notepad++ messed up the file, the Jar was invalid or if there was a checksum that's not matching anymore. I don't get an error, the mod just doesn't show up once Forge loaded.

**Comment by Tiviacz1337** [comment]
Sorry, but 1.12 is not supported anymore. You can shift + right click on backpack to automatically equip it to the back
