### ISSUE TITLE
Items lost when inside backpack during upgrade

### ISSUE THREAD

**Issue by Rasenwish89** [Tiviacz1337/Travelers-Backpack#353]
**Describe the bug**
Items inside the backpack are lost when I chose to upgrade from normal backpack to Iron backpack

**To Reproduce**
Put Items inside Backpack, then upgrade it to a different material

**Expected behavior**
I was expecting an inventory upgrade (more slots) inside backpack (author never stated that, so this part is negligible), and that my items would not get deleted

**Screenshots**
No need!

**Required informations (please complete the following information):**
 - Mod version: 1.17.1 - 6.0.0 for fabric

**Additional context**
I downloaded All of Fabric 4 for minecraft 1.17.1
The mod was inside that modpack

**Comment by b3eee** [comment]
This happend to me too! I had everything in the backpack, including other backpacks, now i dont have any of the items, its just gone:c

**Comment by 1adam2010** [comment]
dont work crafting sleeping bag

**Comment by youngchan01** [comment]
This happened to me too!

**Comment by b3eee** [comment]
YO, A LITTLE UPDATE, its stil not working for me, but i tried to get into the game with the version 1.0.1, take my backpack out, and then open the game in 1.1.1, that worked for me, if its a server, you can try to make another backpack, put it with the option in the backpack, and then yake it out eith the option inbthe backpack, that worked for me at least, sorey if 8ts hard to understand:c

**Comment by Tiviacz1337** [comment]
Issue confirmed, I'll fix it

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files fixed in 5.4.1, 6.0.1 and 7.0.0

**Comment by Drippyviro** [comment]
Hey the same thing happened to me is there any advice to help me get my stuff back? is it cause i could be running an old version?? i just downloaded this modpack.

**Comment by Tiviacz1337** [comment]
> Hey the same thing happened to me is there any advice to help me get my stuff back? is it cause i could be running an old version?? i just downloaded this modpack.

Unfortunately 1.17.1 is not supported for a very long time, I think the only way is to use backup
