### ISSUE TITLE
Backpack can't be opened

### ISSUE THREAD

**Issue by SviatoslavZinch** [Tiviacz1337/Travelers-Backpack#354]
**Describe the bug**
When I press chosen key my backpack can't be opened 
**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: 1.12.2 - 1.0.35

**Additional context**
I've installed 183 mods. Seems like the problem is in optifine

**Comment by Tiviacz1337** [comment]
1.12.2 not supported...
