### ISSUE TITLE
Grabbing the backpack with a secondary slot (and add armor slots)

### ISSUE THREAD

**Issue by NoiGS2015** [Tiviacz1337/Travelers-Backpack#355]
Hello. The Backpack has a little problem when I try to grab it when it's placed, when I have anything in my secondary hand, it doesn't let be grab it, I have to have both arms empty, wich means I have to release anything and then grab it, and the take my stuff again, it's a little annoying.

And also, the inteface is very complete, but it would be even better to have the armor slots in it and the seondary hand slot. It would save some unnecesary movements to switch to the E menu.

By the way an aditional that I just realized, when I use the crafting part, let's say I want to do a coal block, when I press Shift + left Click in the crafting result, instead of go to my already stacked coal blocks inside the backpack, it goes to my main inventory, I have to Shift + left Click it there again and it works.

My Minecraft version is 1.17.1

Good mod btw, I love it, these are the few issues that annoy me but it's very good!

**Comment by Tiviacz1337** [comment]
Forge?

**Comment by NoiGS2015** [comment]
I think I don't have it. I don't know how to see it

**Comment by Tiviacz1337** [comment]
Is the first thing that annoying? I mean these things are not worth the effort in my opinion and might probably cause more problems so

**Comment by NoiGS2015** [comment]
Well, to me it is, specially when monsters appears, is like:
"The bag!"
*Tries to grab it but it doesn't work*
"Shit I'm full inventory"
*Drops the slot in the principal hand, and tries again but still doesn't work*
"Gosh, my other hand!"
*Switchs the slot on secondary hand, and drop it, and then grab the bag, and then grab the dropped items*

It's annoying to me because I could just right-click it and go, but instead I have to go through this process (when I forget that detail), plus monsters, or let's say I have some mods with more aggresive monsters, I have to drop anything on my hands in just a few seconds to grab it and the wait to take those things again.

I mean, it is not something primordial, but it could make it even more practical.
