### ISSUE TITLE
Update to 1.18.1

### ISSUE THREAD

**Issue by UnPik** [Tiviacz1337/Travelers-Backpack#357]
Hi, 
we are using your mod in our private server and we like it. 
We would like to know if you want to update it to 1.18.1. 

Thanks!

**Comment by Tiviacz1337** [comment]
Yes mod will get update to 1.18 probably after christmas

**Comment by blockboi-cyper** [comment]
cool , cant wait

**Comment by UnPik** [comment]
Thanks!!

**Comment by Katakireza** [comment]
tnx i cant wait

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3596422

**Comment by UnPik** [comment]
Thanks!!!

**Comment by Katakireza** [comment]
No thanks to you
