### ISSUE TITLE
All items lost from backpack after I rejoin the world.

### ISSUE THREAD

**Issue by josh1221wa** [Tiviacz1337/Travelers-Backpack#358]
All items in the backpack are gone and the backpack is empty after I rejoin the world. This is a singleplayer world on Forge Optifine. Version is 1.18.1 

Mod version: 1.18.1-7.0.0

![Screenshot 2022-01-08 203350](https://user-images.githubusercontent.com/69610717/148649188-88705014-d5f6-4cbf-ae9b-73a42fcbc1eb.png)

As you can see here I've put an item into the backpack.

![Screenshot 2022-01-08 203431](https://user-images.githubusercontent.com/69610717/148649191-f47e1331-62de-467e-b5c2-1dc29f6189f9.png)

After reloading the world the item is gone.

**Comment by Tiviacz1337** [comment]
confirmed I'll work on it

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3598765
