### ISSUE TITLE
Can not equip

### ISSUE THREAD

**Issue by Thatonepalmtree** [Tiviacz1337/Travelers-Backpack#359]
**Describe the bug**
I crafted the Travelers Backpack. I go to equip {shift+R-click} the travelers backpack and it says in chat "Can't equip the backpack".  I have no armor on, and an empty off/main hand.

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**
[Travelers Backpack Bugs2.zip](https://github.com/Tiviacz1337/Travelers-Backpack/files/7834352/Travelers.Backpack.Bugs2.zip)
![Travelers Backpack Bugs](https://user-images.githubusercontent.com/97370602/148666541-0461ede2-7ee6-4ebf-8192-ff4f6de97457.png)
![Travelers Backpack Bugs2](https://user-images.githubusercontent.com/97370602/148666542-e542b1c6-3d27-4251-93de-9ca5d177539c.png)

**Required informations (please complete the following information):**
 - Mod version: [e.g. v1.17.1- 6.0.0]

**Additional context**
I have to manually put the backpack on, I can't open the inventory, but I can swap my tools.

**Comment by Tiviacz1337** [comment]
is it fabric?
