### ISSUE TITLE
Items lost when the backpack drop itself on death

### ISSUE THREAD

**Issue by UmpaLumpaHQ** [Tiviacz1337/Travelers-Backpack#360]
**Describe the bug**
When you die, the backpack place itself on the ground when you go to check all the item have been deleted

**To Reproduce**
1. place any object inside the backpack
2. die
3. Check the backpack again
4. Cry

**Expected behavior**
A fix for this bug and a new update for the mod

**Screenshots**
none

**Required informations (please complete the following information):**
 - Mod version: 7.0.0
 - Game Version: 1.18.1
 - Forge or Fabric: Forge Version

**Additional context**
none

**Comment by Tiviacz1337** [comment]
check if issue still persists on 7.0.1
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3598765

**Comment by UmpaLumpaHQ** [comment]
> check if issue still persists on 7.0.1 https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3598765

the bug is solved in the 7.0.1 thank you!
