### ISSUE TITLE
Commission and suggestion.

### ISSUE THREAD

**Issue by AdmiralAlpaca** [Tiviacz1337/Travelers-Backpack#362]
**Is your feature request related to a problem? Please describe.**
There is no problem with this mod whatsoever besides maybe the fact that hoses weren't implemented but I have better ideas.

**Describe the solution you'd like**
Adding a mini furnace to the backpack or a mini brewing stand in place of one of the tanks. 

**Describe alternatives you've considered**
Tbh there aren't any alternatives on fabric and I wanted to ask if I could commission you to do more with this mod, or if your skills lie only in porting it. Or if you can only really work with forge. Otherwise you can DM me on discord @AdmiralAlpaca ツ#0409 and we can talk price on this mod.

**Additional context**
[BackpackGUI.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/7874221/BackpackGUI.txt)
This is an idea I had that might be worth looking into if you can. It would add more versatility to the backpack without making it super overpowered given the other mods out there. Let me know what you think.

**Comment by Tiviacz1337** [comment]
I'd like to keep the original idea of backpack, therefore do not add furnace or anything else. 
I still work on Fabric version, I just sometimes do not have enough time, but I'll definitely continue developing Forge/Fabric versions on my own.
