### ISSUE TITLE
Placing backpack error

### ISSUE THREAD

**Issue by Tripplestryke245** [Tiviacz1337/Travelers-Backpack#365]
**Description**
Placing a backpack will become another backpack of specific type when placed facing a direction however only on an Aternos server

**To Reproduce**
Steps to reproduce the behaviour:
1. place backpack on a block.
2. backpack should snap into a block position and become a different version to what its item was.
*note: if replicated in single player bug is non existent
3. leave server 
4. come back into the server and any placed ocelot, cow, pig, chicken & villager back pack will disappear any other backpack will remain

**What should happen**
The backpack should be the placed item version, the same as the item's version in an inventory

**Screenshots**
Image 1-3 on shows a backpack placed facing East and image 4-6 shows a backpack placed facing South. Image 7 is after I left the server to replicate on a single player world which had no error on return, the backpacks vanished. (placing a backpack whilst facing North and West will flip the backpack) and last image shows the mods on the server
![image 1](https://user-images.githubusercontent.com/98433888/151083095-077ee11a-6bb4-45a5-97cd-960ce06fcb15.png)
![image 2](https://user-images.githubusercontent.com/98433888/151083099-589937e4-5b67-4299-828a-b6b7716ec9d2.png)
![image 3](https://user-images.githubusercontent.com/98433888/151083100-fb8b3540-4d02-4eaf-99de-bfc9f0e1897e.png)
![image 4](https://user-images.githubusercontent.com/98433888/151083102-b4878e41-37fd-48fd-9648-5a76c6219889.png)
![image 5](https://user-images.githubusercontent.com/98433888/151083105-b3a52360-04e2-41d5-870a-15f9be56291f.png)
![image 6](https://user-images.githubusercontent.com/98433888/151083108-ad3b2f02-be4c-4cd8-9b92-561d1ddafedb.png)
![image 7](https://user-images.githubusercontent.com/98433888/151085547-b2da319c-1213-40a8-b3e2-197a4deea40b.png)
![Modlist](https://user-images.githubusercontent.com/98433888/151084405-8b9f12c5-8d09-479e-9d0d-ee6c85774d90.png)

**Other info**
 - Mod version: 1.16.5 Curse forge version (36.2.0)
 - This is on aternos server
 -
**Additional info**

**Comment by Tiviacz1337** [comment]
Update to 5.4.6, and check if issue still persists

**Comment by Tiviacz1337** [comment]
Any updates on issue?
