### ISSUE TITLE
Hearts Look Weird When Wearing a Backpack

### ISSUE THREAD

**Issue by Coraline77447** [Tiviacz1337/Travelers-Backpack#368]
**Describe the bug**
When I made the backpack and put it on my hearts would have white lines and the heart textures would look unusual.

**To Reproduce**
1. Make the backpack or find one or obtain one.
2. Put it on.
3. presto! The hearts looks weird and has white lines going through them and on top of them and beneath them. Possible would still look like how they do in the screenshot that I've provided with any resource packs.

**Expected behavior**
The hearts textures should be normal and no weird white lines on top of them and the bottom and even within them.

**Screenshots**
![2022-02-07_07 03 51](https://user-images.githubusercontent.com/72243304/153011283-ccddb5e0-02ea-491d-8a5a-57633bccd0e1.png)

**Required informations (please complete the following information):**
 - Mod version: 1.18.1 7.0.1 or possibly any 1.18.X versions.

**Additional context**
I do have a mod that changes the appearance of the health bar called Scaling Health but I don't think that Scaling Health has anything to do with this and neither does any resource packs that I'm using since I'm also playing on a modded 1.16.5 world with both mods installed and not seeing anything like this in the 1.16.5 version of them both.

I'm currently using both this mod and another backpack mod that's alot like Iron Backpacks mod but mostly using the other backpack mod to carry my items while using this mod for it's sleeping bag since the other backpack mod doesn't have a sleeping bag/sleeping bag upgrade.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3667528

**Comment by Coraline77447** [comment]
Sorry for not replying back to you, I don't have any way to get notified from GitHub but I'll be testing/using the latest version a little bit later cause my internet speed is really slow right now (possibly rush hour as of internet right now) which would cause my game to lag pretty badly..

Anyways thanks for fixing the graphical/visual(?) bug since I think I would've been able to see that bug with and/or without any resource packs applied, I wasn't wearing the Traveler's Backpack in the back slot in Curios till the bug was resolved which it is now, hopefully.

When I first saw it I didn't remember my hearts looking like that with the older versions of the mod and didn't want to downgrade to the previous versions so I'd put it in my backpack from Sophisticated Backpacks mod and only used Traveler's Backpack for it's sleeping bag.

Since Sophisticated Backpacks doesn't have a sleeping bag or sleeping bag upgrade or else I would've replaced this mod with Sophisticated Backpacks since that mod is the spiritual successor to Iron Backpacks mod which that mod may have died (no longer maintained) in 1.12.2 by the looks of it...
