### ISSUE TITLE
[1.16.5] Backpack tanks revert Quark infinity-enchanted water buckets to normal

### ISSUE THREAD

**Issue by exentio** [Tiviacz1337/Travelers-Backpack#370]
**Describe the bug**
If you put a water bucket enchanted with infinity (a feature of the Quark mod), it reverts to a normal bucket

**To Reproduce**
1. Put an enchanted bucket in any tank slot
2. Pick it back and check enchantments

**Expected behavior**
The tank should either fill completely or by one unit, and the bucket should remain full and enchanted.  

**Required informations (please complete the following information):**
 - Mod version: 1.16.5 - 5.4.6

**Comment by Tiviacz1337** [comment]
Forge right?

**Comment by Tiviacz1337** [comment]
Honestly, I'm clueless how to fix that

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
