### ISSUE TITLE
[Fabric 1.18.1] Disable cape/backpack render option

### ISSUE THREAD

**Issue by Dejeh** [Tiviacz1337/Travelers-Backpack#373]
Will you make it so when you disable the backpack rendering with elytra, you could do the same for capes? So when you have a cape enabled the backpack doesn't render
```
// Render backpack if elytra is present
	"renderBackpackWithElytra": false,
```

Or as an alternative: a separate config option that disables the cape whilst wearing a backpack?

**Comment by Tiviacz1337** [comment]
Not going to do that, added config option to disable whole backpack rendering though
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
