### ISSUE TITLE
[Fabric 1.18.1] When the player is killed the backpack is duped

### ISSUE THREAD

**Issue by Dejeh** [Tiviacz1337/Travelers-Backpack#375]
Travelers Backpack v1.18.1-7.0.0
Trinkets v3.2.0
fabric api 0.46.4
Config:
```
// Places backpack at place where player died
	"backpackDeathPlace": true,
```
and trinkets integration is set to true

When the player dies, a backpack worn in the Trinkets back slot will be placed on the ground (when above y=0, see issue #376). It will also dupe as a normal item. You can see this behavior in issue #376 video

Expected behavior:
When killed, the player's backpack will be placed on the ground as a block with no dupe

**Comment by Tiviacz1337** [comment]
That's really weird one, I clearly have set that trinket should be destroyed from trinkets inventory, and it's copy should be placed on the ground. I don't know how it spawns another copy as an item

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
