### ISSUE TITLE
[Fabric 1.18.1] When the player is killed below y=1 the backpack is not placed

### ISSUE THREAD

**Issue by Dejeh** [Tiviacz1337/Travelers-Backpack#376]
Travelers Backpack v1.18.1-7.0.0
Trinkets v3.2.0
fabric api 0.46.4
Config:
```
// Places backpack at place where player died
	"backpackDeathPlace": true,
```
and trinkets integration is set to true

When the backpack is worn in the Trinkets' back slot and player is killed below y=1, in chat it says "There's no space for backpack. Dropping backpack item at..."

https://user-images.githubusercontent.com/72144320/156075348-dd11a662-79fa-44f1-a36f-24cce2675278.mp4

It also dupes (see issue #375).

Expected behavior:
When killed the player's backpack will be placed on the ground instead of dropping as an item.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
