### ISSUE TITLE
No hose recipe in AOF 5

### ISSUE THREAD

**Issue by FDK101** [Tiviacz1337/Travelers-Backpack#377]
**Describe the bug**
No hose recipe in 1.18.1 AOF but have the nozzle.

**To Reproduce**
1. Try to craft the complete hose.

**Expected behavior**
complete hose to be crafted

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: [1.18.1 - 7.0.0]
- Mod Loader: [Fabric]

**Additional context**
![image](https://user-images.githubusercontent.com/62417388/157465166-392afad6-5899-4a1e-b892-f0ef08956a95.png)

**Comment by Tiviacz1337** [comment]
Hose is not implemented yet in fabric versions
