### ISSUE TITLE
Infinite storage

### ISSUE THREAD

**Issue by VektorZ1** [Tiviacz1337/Travelers-Backpack#378]
Backpacks can be put in shulkers, and shulkers with backpacks can be put in backpacks. That is, you can make an infinite vault

1 Take 2 shulkers and 2 backpacks
2 Put a backpack in the shulker 3 Put that backpack in another shulker
4 Put the shulker with the backpack and the shulker in the backpack

You can't put a shulker in a backpack and you can't put a backpack in a shulker

**Required informations (please complete the following information):**
 - Mod version: 1.18.1-7.0.3
- Mod Loader: Forge

**Comment by Tiviacz1337** [comment]
there's blacklisted_items tag, items added to this tag cannot be put in backpack
