### ISSUE TITLE
when i try to launch the game this error pops up java.lang.RuntimeException

### ISSUE THREAD

**Issue by DRMelonHaert** [Tiviacz1337/Travelers-Backpack#384]
**Describe the bug**

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: [For example: 1.16.4 - 5.3.7]
- Mod Loader: [Fabric or Forge]

**Additional context**

**Comment by Tiviacz1337** [comment]
Can you provide any info?
