### ISSUE TITLE
no crafting recipe

### ISSUE THREAD

**Issue by 0TellMyTales0** [Tiviacz1337/Travelers-Backpack#385]
**Describe the bug**
there is no crafting recipe, and when i try to make what it says on the curseforge site for the mod it does not work, i cant make the stuff needed to make the backpack..

**Required informations (please complete the following information):**
 - Mod version: 1.18.1
- Mod Loader: Fabric

**Additional context**
![image](https://user-images.githubusercontent.com/104302266/164972186-f6398f18-573f-4819-aa77-1d5f0f654090.png)

**Comment by Tiviacz1337** [comment]
There must be a compact bug. I can craft sleeping bag
![image](https://user-images.githubusercontent.com/34790800/170556021-68038437-7212-43a2-be72-e5f940e667c6.png)
