### ISSUE TITLE
Unable to open backpack in a modpack

### ISSUE THREAD

**Issue by MasterMind1010** [Tiviacz1337/Travelers-Backpack#389]
**_I am unable to open backpack when the mod is installed in the Better Minecraft Modpack_**

I installed this mod in better minecraft modpack, the only issue is that the backpack does not open when I press B, I have checked the controls, there are no conflicting controls with B.

The backpack is equipped in back slot, and it won't open.
However, while in main hand, if I right-click it, then it opens and works just fine, but it's just that it won't open while equipped.

I am using the 1.16.5 version of this modpack and I have installed it in Better Minecraft [FORGE] - 1.16.5 modpack designed by SharkieTV_

I would appreciate if this issue is taken into consideration at the earliest

**Comment by Zytheus** [comment]
I'm having the exact same issue. Backpack works in hand but not in Back Slot. Different modpack though. No button conflicts.

**Comment by Tiviacz1337** [comment]
There's config option curiosIntegration which must be true in order for backpack to work

**Comment by MasterMind1010** [comment]
> There's config option curiosIntegration which must be true in order for backpack to work

Can you please elaborate a bit, which option under curiousIntegration and how to change it?
