### ISSUE TITLE
gui stuck

### ISSUE THREAD

**Issue by battlemonkey71** [Tiviacz1337/Travelers-Backpack#390]
Appears as if the inventory gui is stuck in my backpack's gui. All of my inventory disappeared. When I press E to open inventory i can see items that are in my backpack. But no items in my current inventory or my hotbar.

Can't figure out how to fix it. Tried placing the backpack but nothing happened. 

Don't know what I did to cause it.

![Screen Shot 2022-05-11 at 11 33 33 PM](https://user-images.githubusercontent.com/105406064/167987547-ef8ebf4e-5bd9-450b-aeae-d12177a5c0b1.png)
![Screen Shot 2022-05-11 at 11 33 28 PM](https://user-images.githubusercontent.com/105406064/167987568-6df6abe2-415f-4afd-90c3-5d803dae48a2.png)

Mod version: 1.12.2-1.0.35
Mod loader: forge

**Comment by Tiviacz1337** [comment]
1.12.2 is not supported sorry
