### ISSUE TITLE
Where is the Fabric version source code?

### ISSUE THREAD

**Issue by HyperlyBola** [Tiviacz1337/Travelers-Backpack#393]
I was trying to update the mod to 1.18.2 so I could use it on my server, then I realized this was using mc mappings. I clicked the source link on curseforge for the fabric page and it just lead me here. Is it intentionally hidden?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/3805939
