### ISSUE TITLE
Minecraft failing to launch when Travelers Backpack installed.

### ISSUE THREAD

**Issue by Azzmikaelson** [Tiviacz1337/Travelers-Backpack#395]

**Comment by Tiviacz1337** [comment]
crash log, version any informations??

**Comment by Tiviacz1337** [comment]
Oh, the temporary fix for this is installing trinkets, I'll try to fix that asap

**Comment by maciek-kajdanowicz** [comment]
When I installed trinkets the game didn't crash on load but there are no mod-related items, like the mod is not there at all

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
