### ISSUE TITLE
disappearing backpack

### ISSUE THREAD

**Issue by squidberry** [Tiviacz1337/Travelers-Backpack#396]
The backpack disappeared when I died with keep inventory in 1.16.5

1. die
2. when you try to open the backpack, it is gone

Backpack should stay with keep inventory

Mod version: 1.16.5
used forge to open

**Comment by Tiviacz1337** [comment]
Curios integration enabled?

**Comment by DonQuij0te** [comment]
Are you playing with Pixelmon 9.0.0?
For me, It worked  after I deleted Pixelmon.
