### ISSUE TITLE
[1.18.2] [Fabric] [Deathdusk modpack] Broken on Multi-player

### ISSUE THREAD

**Issue by jony-test** [Tiviacz1337/Travelers-Backpack#397]
**Describe the bug**

Single player world:

There was no button to put on back when opening it from your hand, but you could drag it into the backpack trinket slot and then the hotkey worked.

Server world:

Green arrow button to put on back is shown, and the backpack can't be placed in the trinket slot anymore.
Pressing the green arrow button will clear it from inventory but there's nothing in the trinket slot and the backpack hotkey doesn't work.

**To Reproduce**
Install [(https://www.curseforge.com/minecraft/modpacks/deathdusk)] on a server.
Join with client(also needs client version install).
Get a backpack
Open
Equip on back slot
-> Now the backpack is locked on back, the hotkey is not working and backpack disappears on death.

**Expected behavior**
The same behavior as described for Single player world.

**Required informations (please complete the following information):**
- Mod version: [1.18.2-7.1.0]
- Mod Loader: [Fabric]

**Additional context**
Personal suspicion of KubeJS scripts(i'm just a user, not the author) because it modifies the recipe, and it seems recipes that are modified this way don't show up in the right side recipe menu either.

**Comment by Tiviacz1337** [comment]
Is trinketsIntegration config option in Travelers Backpack mod enabled both on server and client?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files should be fixed in latest versions

**Comment by jony-test** [comment]
Is there a mistake maybe? I see the 3 versions updated but not the 1.18.2 one

**Comment by Tiviacz1337** [comment]
![image](https://user-images.githubusercontent.com/34790800/175143812-6d396816-db21-4b77-a855-4191ad3af2dd.png)
