### ISSUE TITLE
backpack is disappeared

### ISSUE THREAD

**Issue by Onyoss** [Tiviacz1337/Travelers-Backpack#398]
**Describe the bug**
After using sleep back, picked up my backpack, then backpack is disappeard.

**video clip**
https://youtube.com/clip/UgkxceGjJmtkRAS9_kPf4Ws6F5uUgtbc_h4K

**Required informations (please complete the following information):**
 - Mod version: [1.18.2-7.1.1]
- Mod Loader: [Forge]

**Comment by Tiviacz1337** [comment]
Does it happen everytime?

**Comment by Onyoss** [comment]
no.
i did several times, only last one, it is disappeard.

**Comment by Onyoss** [comment]
https://youtu.be/T2TAOTW1vXg?t=1849
i crafted the backpack at this point.
then I was using it as usual.
It was a sudden event.

**Comment by Onyoss** [comment]
I finded it now!!
It dropped behind the house.
I apologise for the fuss.
