### ISSUE TITLE
Suggestion [version 1.12.2 and later]

### ISSUE THREAD

**Issue by LOONG17** [Tiviacz1337/Travelers-Backpack#399]
suggestion:
add a way to display other items from other mods for example a crowbar from another weapon mod or so

possible solution:
a slot that does not limit to tool type (and maybe a option to change the tools position on the backpack)

Alternatives:
i did not come across any other alternative

**Comment by Tiviacz1337** [comment]
It is possible, you have to make datapack and add item to acceptable_tools.json item tag

**Comment by LOONG17** [comment]
alright thanks
will that run on a server too ?

**Comment by Tiviacz1337** [comment]
Yes

**Comment by LOONG17** [comment]
alright thanks
