### ISSUE TITLE
There is no hose 

### ISSUE THREAD

**Issue by tonymad** [Tiviacz1337/Travelers-Backpack#400]
This mod works excellent but there is no hose in 1.18.2. It just disappeared from the game. I cant craft or even find it in a creative mode.
Please fix it. 
Thank you for your work.

- Launcher MultiMC
- Mod version: 1.18.2
- Mod Loader: Fabric
![image](https://user-images.githubusercontent.com/107363982/173245439-545f07d2-1f19-42be-becc-ce1235fbc3bd.png)
![image](https://user-images.githubusercontent.com/107363982/173245458-c38c19d4-1fd2-48fd-93fa-f4e42560818e.png)

**Comment by Tiviacz1337** [comment]
hose is not implmented yet on fabric

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files hose is added in latest versions

**Comment by tonymad** [comment]
Thanks man! wish it would be for 1.18.2 either too

**Comment by Tiviacz1337** [comment]
There is, but curseforge moderators are still approving it, it should be available in a few minutes

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/3844873

**Comment by tonymad** [comment]
Thanks a lot!
