### ISSUE TITLE
[1.16.5] b wont open the backpack 

### ISSUE THREAD

**Issue by Noahfrechette** [Tiviacz1337/Travelers-Backpack#401]
b wont open the backpack 
**Required informations (please complete the following information):**
 - 1.16.5-5.4.7
- Mod Loader: Forge

**Comment by Tiviacz1337** [comment]
more context?

**Comment by Noahfrechette** [comment]
sorry about that but i was tired so i did not add much
but when i press the b button that should open the backpack in any slot in my inventory it does not the only way i can open it is when i right click with it in my hand

**Comment by Tiviacz1337** [comment]
backpack can be opened if worn on back (to put on back open backpack and click green button on the left) or placed in curios slot (if enableCurios in config is set to true)

**Comment by Noahfrechette** [comment]
here is proof of it being set to b
![image](https://user-images.githubusercontent.com/73401157/174134419-4f241c15-8b3c-4db2-b7a8-8b7b9206bcb5.png)

**Comment by Noahfrechette** [comment]
i have it in my curios slot and it wont open

**Comment by Noahfrechette** [comment]
do you wont me to send a video from my iphone

**Comment by Tiviacz1337** [comment]
did you set curiosIntegartion to true? in config?

**Comment by Noahfrechette** [comment]
well i cant access config because i am using a server but ok  thanks for trying
