### ISSUE TITLE
Make sleeping bag usable without the backpack.

### ISSUE THREAD

**Issue by ardissaps** [Tiviacz1337/Travelers-Backpack#403]
Make sleeping bag usable without the backpack. (also bow/crossbow on tool slot)

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack
Added
