### ISSUE TITLE
opéning the backpack

### ISSUE THREAD

**Issue by NoDreamsRemain** [Tiviacz1337/Travelers-Backpack#405]
**Describe the bug**
I want to open my backpack with a shortcut "B" but it doesnt work i alredy tried to change keybinds and didnt worked too

**Required informations (please complete the following information):**
 - Mod version:1.18.2
- Mod Loader: Forge

**Comment by Tiviacz1337** [comment]
does console say something?

**Comment by NoDreamsRemain** [comment]
no it doesnt

**Comment by Tiviacz1337** [comment]
Do you have backpack overlay? I mean you equiped backpack then overlay should be in the right bottom corner of your screen. Is there something?
