### ISSUE TITLE
Backpack disappears when equipped

### ISSUE THREAD

**Issue by shaneknysh** [Tiviacz1337/Travelers-Backpack#406]
**Describe the bug**
When putting on the backpack the back pack disappears from inventory but is not put on and is not visible on character.

**To Reproduce**
1. create backpack
2. right click while holding the backpack
3. click equip backpack button
4. back pack is not on back and not in inventory. 

**Expected behavior**
backpack is worn and is accessible via backpack inventory button

**Screenshots**

**Required informations (please complete the following information):**
- Mod version: TravelersBackpack-1.19-8.0.1
- Mod Loader: Forge

**Additional context**
When we first added the mod it was working for player 1 and not player 2. Syncing config so that player 2 config files were exactly the same as player 1 and then is stopped working for player 1 as well. It appeared to work for a few minutes for both just before syncing config files.  

We tried 4-10 backpack variations.

**Comment by Tiviacz1337** [comment]
what are your config options?

**Comment by shaneknysh** [comment]
I'm not at my PC to copy them but the player 1 are the default settings. Player 2 had one setting different but they are both at the defaults now. 

Last check the backpacks were still disappearing.

**Comment by Tiviacz1337** [comment]
Hmm, that's strange I'm testing it right now and verything works fine, give me your forge version, also do you play on modpack>

**Comment by shaneknysh** [comment]
I'll update mid versions when I get back to my PC.

From memory we have 6 mods total.

Gravestones, xaeros maps, rei, fallingtree plus pre reqs

Forge 1.19 40.0.4

**Comment by shaneknysh** [comment]
versions 

Architectury 5.5.18
Cloth Config 7.0.69
Falling Tree 1.19-3.6.1
Gravestone 1.19-1.0.0
rei 9.0.472
travellers backpack 1.19-8.0.1
xaeros mini 22.9.2
xareos world 1.23.2

forge 1.19-41.0.4

**Comment by Tiviacz1337** [comment]
When you equip backpack and it 'dissapears', do you see overlay like this? 
![image](https://user-images.githubusercontent.com/34790800/175108249-239e5c67-2e9f-4c68-bf47-ab0a6a3dd9f8.png)

**Comment by Tiviacz1337** [comment]
Also I use forge 41.0.35 try changing to this version

**Comment by shaneknysh** [comment]
I'm not there to see the exact error but the error is something about GUI overlay. 

Another bit of information, on forge version 41.0.4 single player world -> backpack works, multiplayer -> backpacks fail.

I'll test this on my machine as well when I can.

**Comment by Tiviacz1337** [comment]
can you give me crash report?

**Comment by shaneknysh** [comment]
I'm not at home. Once I get a chance to see the error myself I'll send it along.

**Comment by Tiviacz1337** [comment]
Okay

**Comment by Tiviacz1337** [comment]
Hmm, I don't know how did you launch 1.19-8.0.1 with forge 41.0.4, because version 8.0.1 is build with forge with code changes and in my dev environment 41.0.4 just crashes. That's really strange

**Comment by shaneknysh** [comment]
Crash report identifies architectury.

Updating forge to 41.0.35 and architectury to 5.7.28 resolves the issue. 

```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.architectury.event.forge.__EventHandlerImplClient_event_Pre.invoke(.dynamic) ~[architectury-5.5.18.jar%2375!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%232!/:?] {}

```

**Comment by Tiviacz1337** [comment]
And does backpack work now?

**Comment by Tiviacz1337** [comment]
Okay, if everything is fine im closing this issue
