### ISSUE TITLE
Backpack behavior is unstable when using trinkets

### ISSUE THREAD

**Issue by purejosh** [Tiviacz1337/Travelers-Backpack#409]
**Describe the bug**
When trinkets is enabled, equipping the backpack and opening it doesn't seem to work. Also, still have the option to equip the backpack via the GUI, which if using trinket's, shouldn't be allowed.

**To Reproduce**
1. Install trinkets and TB. 
2. Enable curio/trinket's compat. 
3. Try to use the backpack. 

**Expected behavior**
It should be rendered when in the backpack slot, and it should be openable using b, when using trinket's compat. Seems to work fine without trinket's enabled. 

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: travelers-backpack-1.18.2-7.1.0 + trinkets-3.3.1
- Mod Loader: Fabric 1.18.2

**Additional context**
I'm very active on discord. can screenshare with you too. purejosh#2047

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files fixed in 1.18.2-7.1.1

**Comment by purejosh** [comment]
Thank you!
