### ISSUE TITLE
Other players cannot see the items at green slots in the backpack

### ISSUE THREAD

**Issue by linzexin022** [Tiviacz1337/Travelers-Backpack#411]
**Describe the bug**
In multiplayer, other player cannot see tools in green slots.

**To Reproduce**
1. Create a multiplayer server with this mod (fabric version).
2. put tools in green slot in the backpack.
3. Let other player see the back of your player.

**Expected behavior**
Other players should see the tools at the back of the player.

**Screenshots**
![4162f4703e90c8e009b54b06d783769](https://user-images.githubusercontent.com/59003232/174812650-3865d50f-3c3d-43fd-9826-2edd3f109fd6.png)
![e25ececb70ebd80f3c22c27ff3a453b](https://user-images.githubusercontent.com/59003232/174812666-ff8ea466-e35a-48a4-8997-342685fb5f7e.png)

**Required informations (please complete the following information):**
 - Mod version: 7.1.0-1.18.2
- Mod Loader: Fabric Loader 0.14.7

**Additional context**
nope

**Comment by Tiviacz1337** [comment]
Issue is already fixed, the update will come out later this week

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files fixed in 1.18.2-7.1.1

**Comment by Tiviacz1337** [comment]
It's still under moderator review
I've already sent a message to curseforge support, it should be available today

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/3844873
