### ISSUE TITLE
prevent lighting bolt destroy with is dropped

### ISSUE THREAD

**Issue by Diclo** [Tiviacz1337/Travelers-Backpack#412]
**Is your feature request related to a problem? Please describe.**
if you are flying and you die the backpack is dropped as an item and is vulnerable to fire, lava, lightning

**Describe the solution you'd like**
upgrades that make them resistant to fire, lava and lightning bolt

**Comment by Tiviacz1337** [comment]
Forge/Fabric?

**Comment by Diclo** [comment]
sorry, not mentione the version
forge
MC version: 1.12.2
TravelersBackpack-1.12.2-1.0.35

**Comment by Tiviacz1337** [comment]
1.12.2 is not supported, backpack is immune to all damage on 1.16.5+
