### ISSUE TITLE
[1.18.2 Fabric] can not place the backpack in the trinkets back slot!

### ISSUE THREAD

**Issue by MSandro** [Tiviacz1337/Travelers-Backpack#413]
![image](https://user-images.githubusercontent.com/10937159/175268487-df503c69-cdfd-4356-8605-692eaed5b80a.png)

**Comment by MSandro** [comment]
maybe wrong tagging?
![image](https://user-images.githubusercontent.com/10937159/175268589-07e72d10-7c2d-4583-b0ed-3efcaedd57b6.png)
Inmis is working great

**Comment by Tiviacz1337** [comment]
Did you set trinketsIntegration = true in Travelers Backpack Config?

**Comment by Tiviacz1337** [comment]
![image](https://user-images.githubusercontent.com/34790800/175276597-ed4c3bc5-296a-4f87-8bb5-ddc5f3f39c2d.png)
I've already sent a message to curseforge support, it should be available today

**Comment by MSandro** [comment]
thanks, now it works.
