### ISSUE TITLE
We can drink Lava, but can't Drink Milk

### ISSUE THREAD

**Issue by ardissaps** [Tiviacz1337/Travelers-Backpack#415]
Look like it is too OP can we tune the effect (drinking lava) or making burn instead?

Addition : Currently we can drink lava, but can't drink milk? Is it supposed to be?

**Comment by Tiviacz1337** [comment]
1) lava effect is cool in my opinion, what would you like to change
2) I will think about milk effect

**Comment by ardissaps** [comment]
> 1) lava effect is cool in my opinion, what would you like to change
> 2) I will think about milk effect

It is cool, but can make game too easy, or how about make it plus minus like, ok get boost but, burn out throat. Move speed but health drop 1/s. The milk just like normal milk remove effect.

**Comment by Tiviacz1337** [comment]
If any mod adds milk as fluid, it can be put in tanks and drank via hose 
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
