### ISSUE TITLE
[Modd Support] Stacker

### ISSUE THREAD

**Issue by ardissaps** [Tiviacz1337/Travelers-Backpack#417]
**Is your feature request related to a problem? Please describe.**
It crashed when we insert stacked liquid bucket of lava/water/etc inside the backpack slot (above tube).

**Describe the solution you'd like**
Able to fill the bucket slot with stackable filled bucket without crash.

**Describe alternatives you've considered**
When stackable filled bucket fill the slot, let the fluid fill the tube until full then move the empty bucket below as usual and reduce the above filled bucket according to how much fluid taken to tube.
For now, I just temporally configure the Stacker to hold maximum 1 stack of liquid bucket to avoid crashing.

**Additional context**
The mods that be able to stack fluid bucket (and other items).
https://www.curseforge.com/minecraft/mc-mods/stacker
Thank you very much sir no hurry!

**Comment by Tiviacz1337** [comment]
The crash will be fixed, you still need to put by one bucket though

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric - Crash fixed, but it still goes by one bucket
