### ISSUE TITLE
Cloth Config 2

### ISSUE THREAD

**Issue by Faerycat18** [Tiviacz1337/Travelers-Backpack#418]
Saying that I need cloth config 2 file but I downloaded the file that was under the files folder. 

1. Start minecraft.

Minecraft should have started and I would have a cool backpack mod.

**Required informations (please complete the following information):**
 - Mod version: 1.19
 - Mod Loader: Fabric

**Comment by Tiviacz1337** [comment]
cloth config 2 is dependency and is required to run travelers backpack for fabric

**Comment by Faerycat18** [comment]
what is the link for cloth config 2? when i click the cloth config for the mod it takes me to a cloth config that is not the right one because my game crashes
