### ISSUE TITLE
Cloth Config Mod

### ISSUE THREAD

**Issue by Faerycat18** [Tiviacz1337/Travelers-Backpack#419]
What is the correct cloth config 2 file? I followed the link to the cloth config mod but it seems to be the incorrect one.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/3827487
travelers backpack also require cardinal components

**Comment by Tiviacz1337** [comment]
If it does not work try updating fabric api to at least 0.56.1
