### ISSUE TITLE
Upgraded Backpacks not increasing in size

### ISSUE THREAD

**Issue by Ryxpoint** [Tiviacz1337/Travelers-Backpack#420]
**Describe the bug**
All of the backpacks have the same size. Nothing changes with them when opened. 

**To Reproduce**
1. Compare Backpack Sizes.

**Expected behavior**
Backpack UIs are the exact same

**Required informations (please complete the following information):**
 - Mod version: travelers-backpack-1.18.2-7.1.2
- Mod Loader: Fabric 0.14.8

**Comment by Tiviacz1337** [comment]
There are no backpack tiers, all are the same only cosmetic changes
