### ISSUE TITLE
Using the Hose on Powdered Snow Causes a Crash [1.19 Fabric]

### ISSUE THREAD

**Issue by TheSwanDragon** [Tiviacz1337/Travelers-Backpack#421]
**Describe the bug**
Using the "Suck" mode with the Hose causes the game to crash.

**To Reproduce**
1. Equip a Traveler's Backpack
2. Hold a Hose set to Suck (does not matter which tank is selected, or even if the tank is empty/has something else)
3. Right click on a block of Powdered Snow to Suck it

**Expected behavior**
One of two options:
A. Powdered Snow is sucked up and added to the tank.
B. Nothing happens, other than a "fail" sound if applicable.

**Screenshots**
![image](https://user-images.githubusercontent.com/31599991/177456738-b178afea-cdf3-46e1-9e5d-603fc9a29c75.png)

**Required informations (please complete the following information):**
 - Mod version: 1.19 - 8.0.1
- Mod Loader: Fabric

**Additional context**
While I do have a few other mods loaded, I do not have any mods that should affect how Powdered Snow or the Backpack works (various Origins mods, Essential, and Comforts). Specific modlist can be provided if that would be helpful.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
