### ISSUE TITLE
Sleep during day

### ISSUE THREAD

**Issue by GlitchedGamerGIT** [Tiviacz1337/Travelers-Backpack#422]
I play with the Vampirism mod and it would be great if you could sleep during the day to make it nighttime. I can also see this helpful without the Vampirism mod as it allows you to let hostile mobs spawn instead of waiting until night, as peaceful as it is to travel during the day sometimes you need specific resources that you can only get at night.

**Comment by Tiviacz1337** [comment]
wont add
