### ISSUE TITLE
Please move Empty Tank button away from crafting result and Equip button.

### ISSUE THREAD

**Issue by Inurosen** [Tiviacz1337/Travelers-Backpack#424]
**Is your feature request related to a problem? Please describe.**
"Empty" button is very close to crafting result slot and Equip/Unequip button and sometimes misclicking leads to unintentioal clearing of the tanks.

**Describe the solution you'd like**
Having Empty Tank buttons a bit higher somewhere in the middle between bucket slot and crafting result slot would be nice.

**Describe alternatives you've considered**
As an alternative it could ask for confirmation

**Comment by Tiviacz1337** [comment]
Empty tank buttons will be removed, instead player has to hold shift and click on tank to drain fluid

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack
