### ISSUE TITLE
Found a bug that could cause the game to crash

### ISSUE THREAD

**Issue by CaesarGalahad** [Tiviacz1337/Travelers-Backpack#425]
@[Tiviacz1337](https://github.com/Tiviacz1337) 
When the player holds the hose and presses the shift, then right-click any box or fence that can open the GUI, the game will crash

[crash-2022-07-11_21.46.49-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/9084932/crash-2022-07-11_21.46.49-client.txt)
[latest.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/9084934/latest.log)

If someone uses this bug on the server, it will be very bad

**Comment by CaesarGalahad** [comment]
**_It would be great if you could fix this bug as soon as possible_**

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
