### ISSUE TITLE
Can't enter a server with this mod

### ISSUE THREAD

**Issue by 0DarkShock0** [Tiviacz1337/Travelers-Backpack#427]
When i try to enter a server that as this mod, a weird, long message appears

1. Install the mod on both server and client-side
2. Enter the server

**Screenshots**
![imagem_2022-07-12_145938572](https://user-images.githubusercontent.com/87604243/178507882-e6230590-881b-46cf-bbc6-0e9de4d080e2.png)

**Required informations (please complete the following information):**
 - Mod version: 1.18.2,7.1.2
- Mod Loader: Fabric

**Comment by Tiviacz1337** [comment]
console logs?
