### ISSUE TITLE
Using Squid Backpack With Water Crashes Game

### ISSUE THREAD

**Issue by TheExplosion** [Tiviacz1337/Travelers-Backpack#429]
The game crashes whenever i try to access the squid backpack

1. Joined server, pressed B
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Registry Object not present: travelersbackpack:potion_fluid
Exit Code: -1

1.18.2 Forge

Edit: With water inside of the squid backpack, you are unable to access the squid backpack at all. 
Also the water breathing effect doesn't seem to work. NV does. 

Same exact error report.

**Comment by Tiviacz1337** [comment]
check if there's the same backpack mod version on the server and the client please
