### ISSUE TITLE
Not sure what exactly happened, but some worn backpacks on my server disappeared from the players back

### ISSUE THREAD

**Issue by futurenp** [Tiviacz1337/Travelers-Backpack#43]
Me and one of the members of my server both had died and waited a while before hitting respawn (probably about 10 mins minimum) 
When we respawned we both had no backpack.
I am not sure what happened but the config was set to keep the backpack on after death.

**Comment by Tiviacz1337** [comment]
there are some known problems with that, as for now you must deal with it, I'll try to fix it asap though
