### ISSUE TITLE
Compatiblity with corpse mod

### ISSUE THREAD

**Issue by Thelegendking** [Tiviacz1337/Travelers-Backpack#431]
Using the mod named corpse this backpack always gets randomly placed on ground away for player's death location or gets dropped as an item when player dies but because of that backpack gets glitches because there's a corpse in death location and there is no place for backpack so as I mentioned before it glitches to a random location and gets placed on it because of that it becomes really difficult to find backpack again. I have also tried using curious mod's back slot on backpack but the results were same. Perhaps a true/false kind of compatiblity config for corpse might work

Mod Link : https://www.curseforge.com/minecraft/mc-mods/corpse

**Comment by Tiviacz1337** [comment]
Don't you get message on chat, with backpack coordinates?

**Comment by Thelegendking** [comment]
Yeah I do but it literally gets inside blocks I have to dig my way through blocks to find it and not to mention if you die near lava or in lava good luck looking for your backpack cuz it gets placed way deep in lava... that happened to me when I died near lava I was even not that close it too

**Comment by Tiviacz1337** [comment]
No proper api in corpse mod

**Comment by Thelegendking** [comment]
RIP, thanks for trying though.

**Comment by Tiviacz1337** [comment]
I found the way to add compatibility, it'll be available in next update

**Comment by Tiviacz1337** [comment]
Added compat for Corpse 
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files
https://modrinth.com/mod/travelersbackpack/versions
