### ISSUE TITLE
Suggest the open backpack key toggle in and out of the backpack like the vanilla inventory key does.

### ISSUE THREAD

**Issue by WesHay** [Tiviacz1337/Travelers-Backpack#432]

**Comment by Tiviacz1337** [comment]
I dont understand this suggestion

**Comment by WesHay** [comment]
Sorry my first time on this platform, hope the below helps.
I have my travel-pack key set to b. when I hit "b" it opens the pack inventory screen but you need to hit escape to close the pack inventory screen. The normal "e" key for the default inventory when used will open it then if you hit "e" again will close it (toggling in and out of inventory) It would be nice if the Travel-pack also did this toggle action with the assigned key press.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3879360 it is available for 1.19 as for now, I'll update rest of the versions soon

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all

**Comment by WesHay** [comment]
Thanks 👍
