### ISSUE TITLE
Universal Graves Support

### ISSUE THREAD

**Issue by KatNyxion** [Tiviacz1337/Travelers-Backpack#433]
**Is your feature request related to a problem? Please describe.**
There does not seem to be support for the Universal Graves mod. When you die and the "backpackDeathPlace" is set to false, the backpack pops out of your inventory. This happens both when Trinkets compatibility is enabled and disabled.

**Describe the solution you'd like**
Backpacks to go inside the Grave created by Universal Graves

**Describe alternatives you've considered**
Using a different backpack mod, but we really like the design of this one its much more immersive and nice.

**Comment by Thelegendking** [comment]
I agree same is happening with corpse mod too

**Comment by KatNyxion** [comment]
This is legit so people don't steal the backpacks and stuff. like, even just giving them a *locking* feature would be helpful?? We use a graves mod so people can get their things back and no one else can take them. The backpacks not going into the graves kind of defeats the point of that and makes it so people won't want to actually wear the backpack

**Comment by GeorgeGedox** [comment]
I'm having the exact same issue on 1.18.2, this is the only mod that is broken with both You're in Grave Danger graves and the Universal Graves mods

**Comment by coolGi2007** [comment]
I'm going to try and tackle fixing this issue, so expect a pull request within a week or so.

**Comment by KitPickles** [comment]
This also happens with GravceStone Mod (https://www.curseforge.com/minecraft/mc-mods/gravestone-mod). We actually have a situation right now where someone died in a water cave (just an accident) and the grave was where we expected it to be but the backpack is nowhere to be found. because it must have been place on some random block nearby. Could solve this problem by having backpacks go into graves. 

Off topic slightly, are there console commands to give back a player's backpack? the GeaveStone Mod does have console commands to do that. Thanks!

**Comment by Tiviacz1337** [comment]
All those gravestones mod don't even have an api to add any compat from my end

**Comment by Webmetz** [comment]
I will test it with
https://tlmods.org/en/mods/enigmatic-graves/
To see if this would be a better gravestone mod in combination with TB.

**Comment by Webmetz** [comment]
Update on Enigmatic Graves  https://www.curseforge.com/minecraft/mc-mods/enigmatic-graves

I was able to die while wearing the backpack 12 times, and 12 times in the inventory. In multiple ways.  I didn't lose the backpack ONCE!

**Comment by KatNyxion** [comment]
Its forge only unfortunately, but at least something works for the people with the issue on forge lol.

From testing other backpacks as well it seems to only be this one that has the issues with going inside graves. From what I can see from just how this and other backpack mods works, is that this one doesn't use the "back" or "back trinket" slot only, it makes its own extra slot. and I think thats where the issue is coming in because the grave mods don't recognize the backpack even when its in "trinket compatibility" mode

**Comment by Tiviacz1337** [comment]
Added compat for Corpse, Gravestone mod and Enigmatic Graves for Forge;
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files
https://modrinth.com/mod/travelersbackpack/versions
fabric soon

**Comment by Tiviacz1337** [comment]
Added for Fabric:
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
https://modrinth.com/mod/travelersbackpack/versions
