### ISSUE TITLE
Cant open backpack when on my back

### ISSUE THREAD

**Issue by MisterWhale17** [Tiviacz1337/Travelers-Backpack#436]
**Describe the bug**
i cannot open my backpack when its on my back, the key to open it is binded but if i press it nothing happens
**To Reproduce**
1. I put it on my back
2. i tried to take it off
3. couldnt open it

**Expected behavior**

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: [For example: 1.16.4 - 5.3.7]
- Mod Loader: [Fabric or Forge]
- 1.17.1
- Forge

**Additional context**

**Comment by Tiviacz1337** [comment]
Do you play on server?

**Comment by DtaboFK** [comment]
Yes, when I deploy a server, the hotkey for the mods is't avaliable

**Comment by Tiviacz1337** [comment]
You can try to reinstall whole server and check if it works. I can't reproduce this issue in my dev environment and there was that kind of issue and I told them to delete whole server and install files again and it worked
