### ISSUE TITLE
Forge 41.0.98 Compatibility 

### ISSUE THREAD

**Issue by rsta79** [Tiviacz1337/Travelers-Backpack#437]
**Describe the bug**
Mod cannot be loaded in forge 41.0.98 (above 41.0.94), 
Forge API makes breaking changes in 41.0.94, please fix it.

**Required informations (please complete the following information):**
- Mod version: 1.19 -  8.0.4
- Mod Loader: Forge 41.0.98

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3879360
