### ISSUE TITLE
Keybind configuration doesnt appear in minecraft settings

### ISSUE THREAD

**Issue by miguelybarra** [Tiviacz1337/Travelers-Backpack#438]
**Describe the bug**
I have various mods installed and I want to change the keybind to enter to backpack inventory, but in settings -> controls Traveler´s backpack does not appear to modify the keys. Is there another way to change the keybinds?

**To Reproduce**
1. enter controls settings

**Expected behavior**
In settings option to change keybinds

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: 1.19- 8.0.4
- Mod Loader: Forge

**Additional context**
Other mods installed:
balm
curios 
jei
journeymap
tombstone
waystone

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3879360
