### ISSUE TITLE
Squid backpack without buff in water

### ISSUE THREAD

**Issue by JueXiuHuang** [Tiviacz1337/Travelers-Backpack#439]
**Describe the bug**
I equip the squid backpack and sink into water, but didn't get night vision and water breathing buff.

**Expected behavior**
When I equipped with squid backpack and sink into water, press E I should see two buffs listed at left hand side.

**Screenshots**
![image](https://user-images.githubusercontent.com/32955131/179456682-11c5b294-4e2e-4fcd-91db-ed441c9d5f4c.png)
![image](https://user-images.githubusercontent.com/32955131/179456718-f591e82f-de03-44fd-8eb8-287e819e595b.png)
![image](https://user-images.githubusercontent.com/32955131/179456741-41c15d48-9640-4d9f-af00-17ce2891f0a0.png)

**Required informations (please complete the following information):**
 - Mod version: 1.19.-8.0.2
- Mod Loader: Forge

**Comment by JueXiuHuang** [comment]
Also, when I wear magma cube backpack, I didn't have immunity to fire damage.

**Comment by JueXiuHuang** [comment]
the setting of enableBackpackAbilities already set to true

**Comment by Tiviacz1337** [comment]
backpack abilities are available from 8.0.3 mod version, please update
