### ISSUE TITLE
1.18.2 cannot put into trinket slot

### ISSUE THREAD

**Issue by Merith-TK** [Tiviacz1337/Travelers-Backpack#441]
**Describe the bug**
Wont let me put into trinkets

**To Reproduce**
1.18.2, attempt to put into trinkets slot

**Expected behavior**
goes into trinkets

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: 1.14.8
- Mod Loader: Fabric

**Additional context**
[modpack](https://git.merith.xyz/modpacks/ultron)
Download as zip and import to either MultiMC or PolyMC launcher, 

tested in singleplayer

**Comment by Tiviacz1337** [comment]
you have to set config option - enableTrinkets to true
