### ISSUE TITLE
Uncampatible with TLlauncher

### ISSUE THREAD

**Issue by ElFavoHP** [Tiviacz1337/Travelers-Backpack#442]
when creating a forge server, with the TLlauncher it does not run the mod and does not let the person enter, only people with a premium account.

 - Mod version: [1.19-8.0.5]
- Mod Loader: [Forge]

**Comment by Tiviacz1337** [comment]
I'm pretty sure it has nothing to do with the mod, check your installation

**Comment by ElFavoHP** [comment]
> Estoy bastante seguro de que no tiene nada que ver con el mod, revisa tu instalación

It's a bit strange because it works for me but it doesn't let other people, when they enter it tells them an error that the mod is missing, but if they have it in the mods folder it's like they don't recognize it, but it works for me

**Comment by Tiviacz1337** [comment]
If it works for you, then it's not the problem with the mod itself. You have to figure it out, if it crashed or something then indeed it would be the mod problem, but if mod is missing then it has to do with installation or something

**Comment by ElFavoHP** [comment]
> If it works for you, then it's not the problem with the mod itself. You have to figure it out, if it crashed or something then indeed it would be the mod problem, but if mod is missing then it has to do with installation or something

If i share u the error, could you tell me what the problem is?

**Comment by Tiviacz1337** [comment]
I do not use TLlauncher I don't know what might be the problem

**Comment by ElFavoHP** [comment]
Thanks!
