### ISSUE TITLE
Not activating curios slot

### ISSUE THREAD

**Issue by TheAndroidx1** [Tiviacz1337/Travelers-Backpack#443]
**Describe the bug**
Curios does not add any slots when traveler's backpack and curios are the only mods, and In when I add the artifacts mod, curios generates the slots, but the backpack can be placed on any slot and keybind wont work and pack wont render.

**To Reproduce**
1. install travelers backpacks and curios alone
2. enable curios integration in config
3. load world
4. no curios slots

**Expected behavior**
I expect the back slot to appear in curios gui, and for the backpack to render and function when equipped.

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: Traveler's Backpack [1.18.2 - 7.1.6] Curios API [1.18.2 - 5.0.7.1]
- Mod Loader: [Forge]

**Comment by Tiviacz1337** [comment]
You have to set Travelers backpack config option - curiosIntegration to true
