### ISSUE TITLE
No legit way to get iron golem backpack in 1.19 (as far as I can tell)

### ISSUE THREAD

**Issue by MrCheschire** [Tiviacz1337/Travelers-Backpack#444]
**Describe the bug**
There doesn't seem to be a way to get the iron golem backpack without going into creative or using commands. There might be a way to get it but I am not aware of one since I haven't been able to find one within a village blacksmith chest and there are no chests within the armorer villager building.

**To Reproduce**
How can you reproduce something that isn't there.

**Expected behavior**

**Required informations (please complete the following information):**
 - Mod version: 1.19-8.0.2
- Mod Loader: Fabric

**Comment by Tiviacz1337** [comment]
![image](https://user-images.githubusercontent.com/34790800/181734329-1f64d4ac-7050-48d4-8205-48fc0ba8fc1d.png)

**Comment by Tiviacz1337** [comment]
I will consider changing it though, but as for now here's the answer
