### ISSUE TITLE
LAN game other player can't toggle ability with squid backpack

### ISSUE THREAD

**Issue by forestsecret** [Tiviacz1337/Travelers-Backpack#445]
**Describe the bug**
Started a LAN world other player in world crashes every time they try to toggle the squid backpack ability. 

**To Reproduce**
1. ...Start LAN world Survival cheats ON
2. Have someone else join world
3. Get squid backpack
4. have other player open it and attempt to turn on ability

**Expected behavior**
I expected the ability to toggle on and off.

**Screenshots**
![config issue](https://user-images.githubusercontent.com/110189619/181595022-18426802-48f6-4158-b678-8adba88f9b1c.jpg)

![crash report](https://user-images.githubusercontent.com/110189619/181595110-018068c5-19aa-4ba6-b9d3-ef9b0dd8d5c1.PNG)

**Required informations (please complete the following information):**
 - Mod version: 1.19-8.0.7
- Mod Loader: Forge

**Additional context**

**Comment by Tiviacz1337** [comment]
Tell the other player to load to any singleplayer world first, it doesnt matter can be even superflat. And then tell him to connect to Lan.

**Comment by forestsecret** [comment]
Hey thank you so much that worked!

**Comment by forestsecret** [comment]
> Tell the other player to load to any singleplayer world first, it doesnt matter can be even superflat. And then tell him to connect to Lan.

Hey I thought the issue was fully fixed, but it's not. The abilities work for the connected player but when they cycle their weapons or interact with backpack like putting water in it they get kicked. same connection lost screen as before. Any advice is appreciated. 
![crash report](https://user-images.githubusercontent.com/110189619/181649434-13659394-1368-4934-9025-a545dadb8677.PNG)

**Comment by Tiviacz1337** [comment]
Does issue still persists when player joins again to server?

**Comment by Tiviacz1337** [comment]
the issue will be fixed on 1.19.1, Im not updating 1.19 anymore

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all

**Comment by forestsecret** [comment]
I'm sorry for not replying sooner. Yes the issue still persists when player joins again to server. Also will downloading the new version hopefully fix this issue? Sorry I'm new to all of this. I appreciate all the help!

**Comment by Tiviacz1337** [comment]
Yes, issue is fixed in latest version
