### ISSUE TITLE
Dehydration Mod Compatibility

### ISSUE THREAD

**Issue by ardissaps** [Tiviacz1337/Travelers-Backpack#446]
Would you like to make drinking water with hose restore [Dehyrdation](https://www.curseforge.com/minecraft/mc-mods/dehydration) for 1.18.2? thank you

**Comment by cdburgess** [comment]
I second this for 1.19. I have been playing this in the Medieval Minecraft Fabric 1.19 and the hose won't work for the hydration mod. If that could be connected somehow that would be great:
1- add purified water to tank
2- connect hose
3- drink from tank to refill hydration

**Comment by ardissaps** [comment]
Or at least drink raw water can hidrate us, that alone is make me happy already. But more feature like above mentioned would be perfect!

**Comment by cdburgess** [comment]
@ardissaps I agree! The tanks won't even replenish our thirst bar. So I hope this can be easily remedied. I'm certain it can. As long as the code for the hose uses the same command as "drink" from the bottle, bucket, flask, etc.

**Comment by Tiviacz1337** [comment]
purfied water is not available in the mod as fluid, it complicates things. I can try adding raw water, but then it should hydrate player like normal water bucket and here I ask. Does purified water hydrate player the same as normal water bucket?

**Comment by ardissaps** [comment]
> purfied water is not available in the mod as fluid, it complicates things. I can try adding raw water, but then it should hydrate player like normal water bucket and here I ask. Does purified water hydrate player the same as normal water bucket?

Not quite sure, it seems like purified have same hydration but with less poison, sometime when we drink raw water it can make us thirst faster, afaik.

**Comment by jmadarg** [comment]
Any update on this?

**Comment by Tiviacz1337** [comment]
I'd like to add this compat, althrough Dehydration mod does not have maven repository and I can't add it to my Dev environment, since cursemaven plugin is broken in some way on Fabric

**Comment by jmadarg** [comment]
https://github.com/Globox1997/Dehydration/issues/92#issuecomment-1225848975
That is the only comment on the matter I've seen from Globox_Z. 
I also wanted to add that I managed to store purified water on the backpack (on a prevous version tho, may try to test it tomorrow again) on a convoluted way and to be able to drink it is the same process in reverse.
What I did was:
- Get the purified water bucket
- Place it in the world
- Suck it with the hose
It didn't said purified water while in the tank tho, but don't remember what it said

**Comment by Tiviacz1337** [comment]
I know it has api, but I can't add the mod to my dev environment, because cursemaven plugin is broken

**Comment by Tiviacz1337** [comment]
I've asked a question on Dehydrated mod github for information about thirst values that should be added while drinking specific fluids, as soon as I get answer, I'll make compat

**Comment by CuteistCat** [comment]
well u got anser (https://github.com/Globox1997/Dehydration/blob/1.20/src/main/resources/data/dehydration/hydration_items/vanilla_items.json)

**Comment by creeloper27** [comment]
This would be lovely if it got reopened as I needed this for one of my servers lately :(, also it seems `dehidration:purified_water` is a thing now, Is this what you meant was missing with this comment @Tiviacz1337 ?

> purfied water is not available in the mod as fluid, it complicates things. I can try adding raw water, but then it should hydrate player like normal water bucket and here I ask. Does purified water hydrate player the same as normal water bucket?

**Comment by Tiviacz1337** [comment]
I'll look into it

**Comment by Tiviacz1337** [comment]
> This would be lovely if it got reopened as I needed this for one of my servers lately :(, also it seems `dehidration:purified_water` is a thing now, Is this what you meant was missing with this comment @Tiviacz1337 ?
> 
> > purfied water is not available in the mod as fluid, it complicates things. I can try adding raw water, but then it should hydrate player like normal water bucket and here I ask. Does purified water hydrate player the same as normal water bucket?

Dehydration mod does not have it's bucket item registered as fluid storage, they have to register it first, then I'll be able to make it restore hydration.

**Comment by Tiviacz1337** [comment]
Created pull request to their repository with compatibility fix, if they merge and release update the compatibility will be available

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack/versions
Added for fabric 1.20.1 because author do not support other versions
