### ISSUE TITLE
I can't craft anything

### ISSUE THREAD

**Issue by VixxenBlood** [Tiviacz1337/Travelers-Backpack#447]
**Describe the bug**
I can't craft anything. At all. I have the supplies but when I put it in the crafting table and nothing. I can't make any of it and it doesn't show up in my 'can't craft yet' section. BUT! The keybindings do show up but they're reddened like they're unavailable . I have no idea what I'm doing wrong.

**To Reproduce**
1. Put items in crafting table to craft
2. Nothing happens

**Expected behavior**
The item to show up to craft

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: [1.19]
- Mod Loader: [Fabric]

**Additional context**
I've downloaded other versions and they don't work either.

**Comment by Tiviacz1337** [comment]
craft what, because I don't understand

**Comment by VixxenBlood** [comment]
Any of it. The tank. The sleeping bag. I put in the recipes for them and nothing shows up to craft. At all. I switched to forge and it works there but not on Fabric.

**Comment by VixxenBlood** [comment]
Okay! I think I have it fixed. I guess the online server I was using has an option to download mods so even though I had it downloaded on my curseforge the online server also needed it to be added to it. So! For future reference for anyone having the same issues and reading this. If you're using an online server, make sure it doesn't ALSO need the mod downloaded there. xD
