### ISSUE TITLE
Server crashes when clicking the S button in the backpack GUI

### ISSUE THREAD

**Issue by Duck-Deng** [Tiviacz1337/Travelers-Backpack#448]
**Describe the bug**
Server crashes when clicking the S button in the backpack GUI

**To Reproduce**
1. Start your MC server
2. Load Travelers-Backpack Mod
3. Open the backpack GUI
4. Click the S buttom
![image](https://user-images.githubusercontent.com/64295725/182739850-2b0a967e-74b6-47a0-ad43-cdd040b1ea2d.png)

5. Server will crash

**Expected behavior**
Server no longer crashes and functions work properly

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: 1.16.5-5.4.13
- Mod Loader: Forge

**Additional context**
Server software: CarServer [GitHub Link](https://github.com/Luohuayu/CatServer)
Crash log: [https://pastebin.ubuntu.com/p/r5ycmvJK7C/](https://pastebin.ubuntu.com/p/r5ycmvJK7C/)
![image](https://user-images.githubusercontent.com/64295725/182740671-55680383-2e59-441c-9d0d-c70950257bd0.png)

**Comment by Tiviacz1337** [comment]
Use https://pastebin.com/ for crash log please

**Comment by Duck-Deng** [comment]
> Use https://pastebin.com/ for crash log please
Since the copy became a hyperlink, this became a redirect link. Feel sorry.
My log is in "Additional context" part.
![image](https://user-images.githubusercontent.com/64295725/182989087-9ae1fe0e-608f-4cd1-b5b1-b43b90fe6d1c.png)
https://pastebin.ubuntu.com/p/r5ycmvJK7C/

**Comment by Duck-Deng** [comment]
> Use https://pastebin.com/ for crash log please

Use https://pastebin.com/ for crash log please
Since the copy became a hyperlink, this became a redirect link. Feel sorry.
My log is in "Additional context" part.
![image](https://user-images.githubusercontent.com/64295725/182989688-8bb0f5a4-4f2a-4d9d-9c75-31fe42bdd7c2.png)

https://pastebin.ubuntu.com/p/r5ycmvJK7C/

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3919459
