### ISSUE TITLE
Travelers Backpack not unequipable 

### ISSUE THREAD

**Issue by TypicalDavid611** [Tiviacz1337/Travelers-Backpack#449]
After putting the travelers backpack on, after trying to using the keybind to use it, the inventory space didn't appear and I haven't been able to open the backpack up or unequip it

**Comment by Tiviacz1337** [comment]
Version, Forge/Fabric, Server/Single?

**Comment by TypicalDavid611** [comment]
Version was 1.15.2, on CurseForge and server

**Comment by Tiviacz1337** [comment]
1.15.2 is not supported sorry

**Comment by TypicalDavid611** [comment]
Oh, okay.
