### ISSUE TITLE
[Feature request] Tough as Nails integration

### ISSUE THREAD

**Issue by AquaticFish** [Tiviacz1337/Travelers-Backpack#45]
Hey, there's a mod which I think would work perfectly if it was integrated with your backpack mod, that mod being tough as nails, I'm sure you've heard of it, you can currently carry around the regular and purified water, but you can drink only the regular water and it does not replenish thirst, it would be cool if you to could make it so thirst is replenished by drinking directly from the tanks, or even replenish bottles with what's in the tanks.

**Comment by Trynthlas** [comment]
+1 just ran into this myself, would like to see this feature!

**Comment by Red-EyedFairace** [comment]
+1 on this.

**Comment by MedicMike104** [comment]
+1 Would be prefect.

**Comment by Tiviacz1337** [comment]
I'll do my best

**Comment by EternalShadow17** [comment]
this and also all of pam harvest craft juices would be nice. they cant be put in the tank at all atm.

**Comment by Tiviacz1337** [comment]
Compat with purified water almost ready. Should be available in next week

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-integrations
