### ISSUE TITLE
Items duplicate and/or disappear with Squid Backpack

### ISSUE THREAD

**Issue by ThomMcLean** [Tiviacz1337/Travelers-Backpack#453]
**Describe the bug**
My wife and I have been using the mod for about two weeks. We recently added several mods in order to use the MrBlueYeti resource packs (Better Dogs/Wolves/Pigs/Chickens/Sheep) on a Fabric profile. It may not be related to the additional mods or the resource packs and rather something that happened after the latest Traveller's Backpack update. I believe both occurred at the beginning of the play session (Curse Forge updated your mod and we added the MrBlueYeti resource packs/supporting mods)

My wife noticed that items in her Squid Backpack were being duplicated. When she moved an item from the backpack (after using "B" to open the pack) to inventory and closing the backpack inventory.. The item would reappear in the Squid Backpack. Switching to a standard backpack eliminated the problem of duplication. At other times, items moved from inventory to the backpack would disappear when the pack was reopened. We have the same exact setup and at first, when connecting to her LAN world, I didn't experience the problem with my Squid Backpack. Last night, the issue began to happen on my profile both when connected to her LAN world or running single player on my computer with a test world. Same for me, a standard backpack resolved the duplication/disappearing.

Have not tried any of the other backpacks with abilities. Currently it has only happened with the Squid backpack.

We have removed the Squid backpack by disabling and redownloading the mod. Issue did not resolve. We created new Squid backpacks both from the recipes and via Creative Mode menu drag and drop into inventory. Issue remains.

I really enjoyed using the Squid backpack for the Water Breathing and Night Vision effects. I keep it in my inventory and just use is like a scuba tank when I want to explore underwater and avoid opening it or putting anything in it.

**To Reproduce**
1. Press B to open squid backpack
2. Move an item from backpack to inventory and close backpack
3. Reopen backpack and the item you moved is now showing in both the inventory and backpack

**Expected behavior**
Previous version (before the sorting buttons were added) allowed items to be moved between player inventory and backpack without duplication or deletion

**Screenshots**
Can attempt to provide if needed.

**Required informations (please complete the following information):**
 - Mod version: travelers-backpack-1.19-8.0.3.jar
- Mod Loader: Fabric 0.14.8

**Additional context**
New mods added to run MrBlueYeti resource packs added per his instructions:

CompleteConfig completeconfig-2.0.0.jar

Custom Entity Models cem-0.7.1.jar

Entity Texture Features entity_texture_features_fabric-4.0.1.jar

Lithium lithium-fabric-mc1.19-0.8.1.jar

MidnightLib midnightlib-0.5.2.jar

ModMenu modmenu-4.0.4.jar

Phosphor phosphor-fabric-mc1.19.x-0.8.1.jar

Puzzle puzzle-1.4.0-1.19.jar

Sodium sodium-fabric-mc1.19-0.4.2+build.16.jar

Also using Trinkets for backpack slot  trinkets-3.4.0.jar

**Comment by Tiviacz1337** [comment]
I'll take a look at it

**Comment by ThomMcLean** [comment]
Thank you very much! I think your mod is fantastic and I am happy to provide additional information if it’s helpful.

Thom McLean

**Comment by Tiviacz1337** [comment]
Do you use trinkets?

**Comment by Tiviacz1337** [comment]
It seems that trinkets integration is broken, you can disable trinketsIntegration = false to use backpacks and abilities

**Comment by ThomMcLean** [comment]
Yes, we are using trinkets. I think I put the version down at the bottom of the bug report as the very last mod in the list.

Thom McLean

**Comment by ThomMcLean** [comment]
I will disable the trinkets and see if that makes any difference with the Squid Backpack on our end and report back to you. As I mentioned in the bug report, it does not seem to be affecting the standard backpack. The trinkets integration seems to work just fine, only when we try to put things in the Squid Backpack. Have no idea why that would make any difference.

Thom McLean

**Comment by Tiviacz1337** [comment]
I know, trinkets integration is broken with all backpacks that have abilities

**Comment by ThomMcLean** [comment]
Thank you for clarifying that. Trinkets integration is a nice feature, but it’s not a dealbreaker by any means. We can just keep the backpack in our hot bar

Thom McLean

**Comment by Tiviacz1337** [comment]
You can use built-in backpack wearing feature

**Comment by Merith-TK** [comment]
I can confirm this is happening on basically anything that isnt an basic backpack,

**Comment by ThomMcLean** [comment]
Just to close the loop..

Disabled Trinkets and tested basic backpack and squid backpack. Both of them working as intended with no duplication so far using the Squid backpack.

I had loaded Trinkets because I didn't understand that the built-in backpack wearing feature allowed the pack to be on the back and NOT take up a chest slot for armor. Unless you want to wear the backpack AND a cape or have other mods that use Trinkets, there is no need for Trinkets mod to have the pack on your back.

If Trinkets integration can be fixed in a future release, that is nice to have an intended feature working as intended  :)

As far as I'm concerned, I will just use the built-in backpack wearing feature.

Thank you for looking into this!

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all issue should be fixed in latest versions
