### ISSUE TITLE
Can't enable abilities

### ISSUE THREAD

**Issue by ITCMD** [Tiviacz1337/Travelers-Backpack#454]
**Describe the bug**
Even though it is set to "true" in the server common config file, I see the following:
![image](https://user-images.githubusercontent.com/32961763/182991981-301128d6-dd88-4fdb-a61a-ae8c9c7209dd.png)

Here's the world\serverconfig\travelersbackpack-server.toml file:
```
#Server config settings
[server]
	toolSlotsAcceptSwords = true
	disableCrafting = false
	#Enables wearing backpack directly from ground
	enableBackpackBlockWearable = true
	#Backpack immune to any damage source (lava, fire), can't be destroyed, never disappears as floating item
	invulnerableBackpack = true
	enableBackpackAbilities = true
	#Range: > 250
	tanksCapacity = 4000
```

**Required informations (please complete the following information):**
 - Mod version: 1.18.2 - 7.1.6
- Mod Loader: Forge

**Comment by Tiviacz1337** [comment]
server config is kinda of broken, next update will transfer whole server config to common config, what will resolve the issue

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all

**Comment by ITCMD** [comment]
Thank you for the quick update!
