### ISSUE TITLE
Post an updated list of all backpack crafting recipes

### ISSUE THREAD

**Issue by forestsecret** [Tiviacz1337/Travelers-Backpack#455]
**Is your feature request related to a problem? Please describe.**
Trying to craft the iron, gold, diamond, etc. backpack in survival using adventure backpack FTB wiki recipes isn't working.

**Describe the solution you'd like**
A book that spawns in the players inventory upon spawn or near their spawn in a chest.

**Describe alternatives you've considered**
Or make a post here with all of the updated crafting recipes

**Additional context**
I'm not sure if maybe you have made a list or not if so please link it to me. Thank you.

**Comment by Tiviacz1337** [comment]
there is mod called jei, where you can look up all recipes pretty easily
