### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Athaias** [Tiviacz1337/Travelers-Backpack#456]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 8/6/22 7:40 PM
Description: Ticking block entity

java.lang.AbstractMethodError: Method com/tiviacz/travelersbackpack/tileentity/TravelersBackpackTileEntity.getLevel()Lnet/minecraft/world/World; is abstract
	at com.tiviacz.travelersbackpack.tileentity.TravelersBackpackTileEntity.getLevel(TravelersBackpackTileEntity.java) ~[travelersbackpack:1.16.5-5.4.14] {re:classloading}
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.cactusAbility(BackpackAbilities.java:349) ~[travelersbackpack:1.16.5-5.4.14] {re:classloading}
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.abilityTick(BackpackAbilities.java:155) ~[travelersbackpack:1.16.5-5.4.14] {re:classloading}
	at com.tiviacz.travelersbackpack.tileentity.TravelersBackpackTileEntity.func_73660_a(TravelersBackpackTileEntity.java:553) ~[travelersbackpack:1.16.5-5.4.14] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mca.mixin.json:MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.tiviacz.travelersbackpack.tileentity.TravelersBackpackTileEntity.getLevel(TravelersBackpackTileEntity.java) ~[travelersbackpack:1.16.5-5.4.14] {re:classloading}
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.cactusAbility(BackpackAbilities.java:349) ~[travelersbackpack:1.16.5-5.4.14] {re:classloading}
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.abilityTick(BackpackAbilities.java:155) ~[travelersbackpack:1.16.5-5.4.14] {re:classloading}
	at com.tiviacz.travelersbackpack.tileentity.TravelersBackpackTileEntity.func_73660_a(TravelersBackpackTileEntity.java:553) ~[travelersbackpack:1.16.5-5.4.14] {re:classloading}
-- Block entity being ticked --
Details:
	Name: travelersbackpack:travelers_backpack // com.tiviacz.travelersbackpack.tileentity.TravelersBackpackTileEntity
	Block: Block{travelersbackpack:cactus}[facing=south]
	Block location: World: (137,66,-3998), Chunk: (at 9,4,2 in 8,-250; contains blocks 128,0,-4000 to 143,255,-3985), Region: (0,-8; contains chunks 0,-256 to 31,-225, blocks 0,0,-4096 to 511,255,-3585)
	Block: Block{travelersbackpack:cactus}[facing=south]
	Block location: World: (137,66,-3998), Chunk: (at 9,4,2 in 8,-250; contains blocks 128,0,-4000 to 143,255,-3985), Region: (0,-8; contains chunks 0,-256 to 31,-225, blocks 0,0,-4096 to 511,255,-3585)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mca.mixin.json:MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 2 total; [ServerPlayerEntity['Leviathan_X3217'/661, l='ServerLevel[world]', x=-57.78, y=66.57, z=-0.87], ServerPlayerEntity['TheDamage_'/858, l='ServerLevel[world]', x=136.06, y=64.00, z=-3995.77]]
	Chunk stats: ServerChunkCache: 3160
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,69,48), Chunk: (at 0,4,0 in 0,3; contains blocks 0,0,48 to 15,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1216592 game time, 1216592 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 53841 (now: false), thunder time: 8461 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.19.0-18-amd64
	Java Version: 1.8.0_275, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1015627456 bytes (968 MB) / 2461007872 bytes (2347 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 12
	JVM Flags: 2 total; -Xmx4096M -Xms1024M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/Forge_Latest_1.16.5.jar object_holder_definalize PLUGINSERVICE 
		/Forge_Latest_1.16.5.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/Forge_Latest_1.16.5.jar capability_inject_definalize PLUGINSERVICE 
		/Forge_Latest_1.16.5.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/Forge_Latest_1.16.5.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.35
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		inventorysorter-1.16.1-18.1.0.jar                 |Simple Inventory Sorter       |inventorysorter               |18.1.0              |DONE      |Manifest: NOSIGNATURE
		WizardsAnimals_2.5.jar                            |Wizard Animals Plus           |wizard_animals_plus           |2.5.0               |DONE      |Manifest: NOSIGNATURE
		minecraft-comes-alive-7.0.11-forge.jar            |Minecraft Comes Alive         |mca                           |7.0.11              |DONE      |Manifest: NOSIGNATURE
		mermaidtail-1.4b.jar                              |Mermaid Tail Mod              |mermaidtail                   |1.16.4-1.4.0        |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.16.5-5.1.jar                      |Tree Harvester                |treeharvester                 |5.1                 |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE
		prefab-1.6.5.15.jar                               |Prefab                        |prefab                        |1.6.5.15            |DONE      |Manifest: NOSIGNATURE
		Genesis-0.5.1.jar                                 |Genesis                       |genesis                       |0.5.1               |DONE      |Manifest: NOSIGNATURE
		Pehkui-3.3.3+1.16.5-forge.jar                     |Pehkui                        |pehkui                        |3.3.3+1.16.5-forge  |DONE      |Manifest: NOSIGNATURE
		LibraryFerret-Forge-1.16.5-2.5.1.jar              |Library Ferret                |libraryferret                 |2.5.1               |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.2.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.2      |DONE      |Manifest: NOSIGNATURE
		JRFTL [1.16.5]-1.2.jar                            |JRFTL                         |jrftl                         |1.2                 |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5p5.jar                     |Journeymap                    |journeymap                    |5.8.5p5             |DONE      |Manifest: NOSIGNATURE
		CookingForBlockheads_1.16.5-9.3.4.jar             |Cooking for Blockheads        |cookingforblockheads          |9.3.4               |DONE      |Manifest: NOSIGNATURE
		Placebo-1.16.5-4.7.0.jar                          |Placebo                       |placebo                       |4.7.0               |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.16.5-5.4.14.jar               |Traveler's Backpack           |travelersbackpack             |5.4.14              |DONE      |Manifest: NOSIGNATURE
		culinaryconstruct-forge-1.16.5-4.0.1.0.jar        |Culinary Construct            |culinaryconstruct             |1.16.5-4.0.1.0      |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.4.32.jar                |Bookshelf                     |bookshelf                     |10.4.32             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		creeperconfetti-3.7.jar                           |Creeper Confetti              |creeperconfetti               |3.7                 |DONE      |Manifest: NOSIGNATURE
		DarkUtilities-1.16.5-8.0.14.jar                   |Dark Utilities                |darkutils                     |8.0.14              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Apotheosis-1.16.5-4.8.99F.jar                     |Apotheosis                    |apotheosis                    |4.8.99F             |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		WAWLA-1.16.5-8.0.9.jar                            |WAWLA                         |wawla                         |8.0.9               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		inventorypets-1.16.5-2.0.15.jar                   |Inventory Pets                |inventorypets                 |2.0.15              |DONE      |Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.5.22.jar                      |Carry On                      |carryon                       |1.15.5.22           |DONE      |Manifest: NOSIGNATURE
		Blocklings 7.0.0_b4.1 - 1.16.5.jar                |Blocklings                    |blocklings                    |7.0.0.4             |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-universal.jar                |Forge                         |forge                         |36.2.35             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		wooltweaks_1.16.5-1.3.jar                         |Wool Tweaks                   |wooltweaks                    |1.3                 |DONE      |Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.21.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.3.4.335.jar                   |Tinkers' Construct            |tconstruct                    |3.3.4.335           |DONE      |Manifest: NOSIGNATURE
		CaptureAmob-Forge-1.16.5-1.0.2.jar                |Capture a mob                 |capturetomob                  |1                   |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.1.20.jar         |EnchantmentDescriptions       |enchdesc                      |7.1.20              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		silent-lib-1.16.3-4.9.6.jar                       |Silent Lib                    |silentlib                     |4.9.6               |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |DONE      |Manifest: NOSIGNATURE
		baubles-1.8.7.1-1.16.5.jar                        |Baubles                       |baubles                       |1.8.7               |DONE      |Manifest: NOSIGNATURE
		ironfurnaces-1.16.5-2.7.7.jar                     |Iron Furnaces                 |ironfurnaces                  |2.7.7               |DONE      |Manifest: NOSIGNATURE
		silent-gear-1.16.5-2.6.30.jar                     |Silent Gear                   |silentgear                    |2.6.30              |DONE      |Manifest: NOSIGNATURE
		SchoolsOfMagic1.16.5-2.1.04.jar                   |Schools of Magic: Second Semes|schoolsofmagic                |2.1.03              |DONE      |Manifest: NOSIGNATURE
		Origins-1.16.5-0.7.3.9-forge.jar                  |Origins                       |origins                       |0.7.3.9             |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.157.jar                         |Mantle                        |mantle                        |1.6.157             |DONE      |Manifest: NOSIGNATURE
		collective-1.16.5-4.37.jar                        |Collective                    |collective                    |4.37                |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.16.5-1.7.13.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.13       |DONE      |Manifest: NOSIGNATURE
		Runelic-1.16.5-7.0.3.jar                          |Runelic                       |runelic                       |7.0.3               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		cfm-7.0.0pre22-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |DONE      |Manifest: NOSIGNATURE
		architectury-1.32.66.jar                          |Architectury                  |architectury                  |1.32.66             |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.4.0.jar                |AppleSkin                     |appleskin                     |2.4.0+mc1.16.4      |DONE      |Manifest: NOSIGNATURE
		mobcatcher-1.16.4-3.2a.jar                        |Mob Catcher                   |mobcatcher                    |1.16.4-3.2a         |DONE      |Manifest: NOSIGNATURE
		Craftable_NameTag 1.16.x.jar                      |Craftable Name Tag            |bkcraftablenametag            |[1.16,)             |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.14.64-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.14.64             |DONE      |Manifest: NOSIGNATURE
		SimpleBackpack-1.0-1.16.jar                       |Simple Backpack               |skbackpacks                   |1.0                 |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.16.5-2.1.22.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.22       |DONE      |Manifest: NOSIGNATURE
		SilentGems-1.16.3-3.7.16.jar                      |Silent's Gems 3               |silentgems                    |3.7.16              |DONE      |Manifest: NOSIGNATURE
		Quick Harvest-1.16.5-1.5.1.jar                    |Quick Harvest                 |quickharvest                  |1.5.1               |DONE      |Manifest: NOSIGNATURE
		Craftable Horse Armour  Saddle-1.16.5-1.7--Forge.j|CHA&S - Craftable Horse Armour|craftablehorsearmour          |1.7                 |DONE      |Manifest: NOSIGNATURE
		lootbagmod-1.16.5-2.4.0.jar                       |Loot Bag Mod                  |lootbagmod                    |1.16.5-2.4.0        |DONE      |Manifest: NOSIGNATURE
		Cyclic-1.16.5-1.5.18.jar                          |Cyclic                        |cyclic                        |1.16.5-1.5.18       |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
	Crash Report UUID: e47065ff-39b3-424b-9663-631d62497c59
	Player Count: 2 / 10; [ServerPlayerEntity['Leviathan_X3217'/661, l='ServerLevel[world]', x=-57.78, y=66.57, z=-0.87], ServerPlayerEntity['TheDamage_'/858, l='ServerLevel[world]', x=136.06, y=64.00, z=-3995.77]]
	Data Packs: vanilla, mod:inventorysorter (incompatible), mod:wizard_animals_plus, mod:mca, mod:mermaidtail (incompatible), mod:treeharvester, mod:jei, mod:prefab, mod:genesis, mod:pehkui, mod:libraryferret, mod:caelus, mod:jrftl (incompatible), mod:journeymap (incompatible), mod:cookingforblockheads (incompatible), mod:placebo (incompatible), mod:travelersbackpack (incompatible), mod:culinaryconstruct (incompatible), mod:bookshelf, mod:creeperconfetti (incompatible), mod:darkutils (incompatible), mod:apotheosis (incompatible), mod:waila, mod:wawla, mod:inventorypets (incompatible), mod:carryon, mod:blocklings, mod:forge, mod:wooltweaks, mod:ironchest, mod:tconstruct, mod:capturetomob, mod:enchdesc, mod:silentlib (incompatible), mod:biomesoplenty, mod:baubles (incompatible), mod:ironfurnaces, mod:silentgear, mod:schoolsofmagic, mod:origins, mod:mantle (incompatible), mod:collective, mod:elevatorid, mod:runelic, mod:cfm (incompatible), mod:architectury, mod:appleskin, mod:mobcatcher (incompatible), mod:bkcraftablenametag, mod:cloth-config (incompatible), mod:skbackpacks, mod:aquaculture (incompatible), mod:silentgems, mod:quickharvest, mod:craftablehorsearmour, mod:lootbagmod, mod:cyclic (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Tiviacz1337** [comment]
What happend when game crashed, I mean what did you do with backpack?

**Comment by Athaias** [comment]
My friends had placed a bunch of backpacks down in the world in their house I guess and the server crashed. Then it would restart and whenever we tried to join it would crash the server. New people or people not near where the backpacks were could still join though.

**Comment by Tiviacz1337** [comment]
fixed in 5.4.15 https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
