### ISSUE TITLE
Duplicating Items when using shears on backpack

### ISSUE THREAD

**Issue by cdburgess** [Tiviacz1337/Travelers-Backpack#457]
Using the feature to shear the backpack from a custom pack to the basic travelers backpack, I can continuously duplicate a basic travelers backpack from a single shear/backback. Also anything in the inventory of the pack will be duplicated.

**To Reproduce**
1. Add Stone Golem Pack and shear to crafting
2. Grab the basic backpack 
3. The shear and Stone Golem Backpack remain
4. ANything in the golem pack will now also be in every basic pack

**Expected behavior**
When you shear a backpack to a basic pack, the backpack in the crafting table should disappear. I like the idea of leaving the items in the pack so you don't have to empty it first. But it shouldn't leave you with both copies.

**Required informations (please complete the following information):**
 - Mod version: Medieval MC [Fabric] - 1.19
- Mod Loader: Fabric on CursedForge

**Comment by Tiviacz1337** [comment]
I can't reproduce this issue on my clear installation, probably mod conflict

**Comment by cdburgess** [comment]
Good to know! Thanks for the heads up. It is likely the crafting table in Toms Simple Storage then. I will test it on a crafting table. I didn't think about the possibility of a mod conflict.

**Comment by cdburgess** [comment]
Testing with a normal crafting table works as expected. This issue is related specifically to Tom's Simple Storage crafting.
