### ISSUE TITLE
Use Milk in storage tanks

### ISSUE THREAD

**Issue by cdburgess** [Tiviacz1337/Travelers-Backpack#458]
**Milk will not go into storage tanks**
It seems all other liquids (water, potions, lava, etc) will go into the backpack tanks. Yet milk will not?

**Describe the solution you'd like**
I would like the milk to be able to go into the tank.

**Describe alternatives you've considered**
Ummm... just keeping the milk bucket in a storage slot instead.

**Comment by cdburgess** [comment]
I see this was closed as completed but there was no code associated with the bug fix. What this updated? Or was it closed as will not fix?

**Comment by Tiviacz1337** [comment]
there's no bug, milk is not available in minecraft as fluid, therefore it cant be put in tank

**Comment by cdburgess** [comment]
Thanks for the update.

**Comment by Tiviacz1337** [comment]
also milk can be stored in tanks on forge, if any other mod adds milk as fluid to the game
