### ISSUE TITLE
Abilities disabled by config option

### ISSUE THREAD

**Issue by RyanBv** [Tiviacz1337/Travelers-Backpack#460]
When I'm on my aternos server, it doesn't let me use the backpack abilities and I get this message: Abilities disabled by config option, does anyone know how to fix it please
![image](https://user-images.githubusercontent.com/111029501/184049367-3bd83df5-a7a0-4a30-a26c-47c278d4cbb6.png)
[](url)

**Comment by Tiviacz1337** [comment]
1. Do you have abilities enabled in your config and your server config?
2. What version do you play?

**Comment by Kiwi-Co** [comment]
I have the same issue on aternos server. Abilities are enabled in the server config.

**Comment by Tiviacz1337** [comment]
Can you answer the quesions I asked?

**Comment by Kiwi-Co** [comment]
TravelersBackpack-1.18.2-7.1.7.jar

**Comment by Kiwi-Co** [comment]
Forge - 1.18.2(40.1.73).

**Comment by Kiwi-Co** [comment]
Nvm it works in 7.1.8 version of the mod.

**Comment by Tiviacz1337** [comment]
Yeah, issue was fixed in that version
