### ISSUE TITLE
[Fabric 1.18.2] Why does one bucket convert to 81000 points?

### ISSUE THREAD

**Issue by lazurit11** [Tiviacz1337/Travelers-Backpack#461]
Isn't 1 bucket of liquid supposed to be equal to 1000 millibuckets?
![image](https://user-images.githubusercontent.com/62574650/184418759-1142a691-9df3-436b-9cd7-64efe8840443.png)

**Comment by Tiviacz1337** [comment]
Fabric modloader uses different system of fluids measurement. 81000 equals to 1 bucket of fluid here and it is completely correct. Forge uses millibuckets.
