### ISSUE TITLE
Server Crash on attempting to equip backpack 1.19.1

### ISSUE THREAD

**Issue by MrT451** [Tiviacz1337/Travelers-Backpack#462]
When i click on the backpack from inventory, it opens the gui.  When I click to equip the backpack, the server crashes and I get the following message:

Internal Exception io.netty.handler.codec.EncodedrException: java.io.EOFException: fieldSize is too long! Length is 2, but maximum is 0

Can someone please help?

**Comment by Tiviacz1337** [comment]
does it happen on single player?
