### ISSUE TITLE
Travlers backpack not working

### ISSUE THREAD

**Issue by CopyRightguy** [Tiviacz1337/Travelers-Backpack#463]
**Describe the bug**
See image
![image_2022-08-14_201901699](https://user-images.githubusercontent.com/111247055/184551614-a61a0926-70a4-4c1b-ac0f-a9ce307711ca.png)

**To Reproduce**
1. Launch any 1.19 or above version of the mod

**Expected behavior**
see image

**Screenshots**
see image

**Required informations (please complete the following information):**
 - Mod version: 1.19.1-8.1.1.jar, 1.19-8.1.0, 1.19-8.0.8, 1.19-8.0.7
- Mod Loader: forge

**Comment by CopyRightguy** [comment]
whoops

**Comment by Tiviacz1337** [comment]
probably outdated forge, try updating

**Comment by CopyRightguy** [comment]
I tried, but I still have the same issue

**Comment by CopyRightguy** [comment]
the weird thing is, it only happens after a few relaunches of forge

**Comment by Tiviacz1337** [comment]
make sure you play on 1.19.1+ not 1.19 also what forge version?

**Comment by CopyRightguy** [comment]
![image](https://user-images.githubusercontent.com/111247055/184932465-66ab23ca-df82-4865-ac44-b5d57704e8ff.png)

**Comment by CopyRightguy** [comment]
pls help

**Comment by CopyRightguy** [comment]
i have no idea how but i fixed it
