### ISSUE TITLE
Keybinds not working

### ISSUE THREAD

**Issue by Millepertuis** [Tiviacz1337/Travelers-Backpack#464]
**Describe the bug**
We have installed the mod with Curios (on the modpack Pixelmon)
We had to rearrange the keybinds for each of the mods to make sure that nothing was set on the same key.
We can use the backpack while it's in our inventory, place it on our back... But while it's on our back, we can't open it. 
We can use the hose tho. 
Would it be cause by Curios? We cannot see it on our backs too. 
(I say we cause we are three players on our server and no one can open it)

**To Reproduce**
1. Put the backpack on your back
2. Open it with the key bind.

**Expected behavior**
Is there a incompatibility with any of our mods ? 

**Screenshots**
Here is our mods : 
![image](https://user-images.githubusercontent.com/111248954/184553996-a2593f8b-401d-4e97-948f-b0f0ca2e095a.png)

**Required informations (please complete the following information):**
- Mod version: 1.16.5 - 5.4.14
- Mod Loader: Froge

**Additional context**
We are playing with the Pixelmon mod pack. Would it be cause by it? 
Could it be on the server end?
I made a file of our mods : https://mega.nz/file/sPckXbIS#FDPLYGYhbzWbPCDJp5A7Z-UIN7I5rKyGo91FIxFPQco

**Comment by Tiviacz1337** [comment]
try removing xareos minimap and check if it works

**Comment by Millepertuis** [comment]
Even if I changed every keybind?

**Comment by Tiviacz1337** [comment]
yes
