### ISSUE TITLE
Duping any items [Trinkets mod compatibility issue?]

### ISSUE THREAD

**Issue by Gredys** [Tiviacz1337/Travelers-Backpack#466]
**Describe the bug**
When using equipped Backpack in Trinket (Trinkets mod) slot - it is possible to dupe any items.

**To Reproduce**
1. Get any Backpack and equip it in Trinket slot.
2. Open Backpack with hot key.
3. Place any item in any slot other then first one available.
4. Press S (Sort) button on top. (nothing will be changed visually, but on code side - inventory already changed and displaying information is no longer valid for slots that are outside of items count)
5. Take back that "any item" in your inventory and close Backpack.
6. Open Backpack again and you will see your "any item" is still inside with addional one in your inventory.

**Expected behavior**
When pressing Sort button while Backpack is equipped in Trinkets slot - it must sort items inside and display the result in same way as opening Backpack while holding it in hands.
P.S. It is better to make check what items exactly can be extracted from the backpack and deny operation if request item is not listed in real backpack content. Otherwise it's really easy to cheat/bug.

**Screenshots**
(none, but I can make video on request)

**Required informations (please complete the following information):**
 - Mod version: 1.18.2 - 7.1.4
- Mod Loader: Fabric

**Additional context**
Using modpack Deathdusk. It contains Trinkets mod and Travelers Backpacks. Dunno if its important.

**Comment by Tiviacz1337** [comment]
this issue is fixed in 7.1.5 mod version
