### ISSUE TITLE
Squid backpack - Abilities not working

### ISSUE THREAD

**Issue by LambertsCode** [Tiviacz1337/Travelers-Backpack#467]
The abilities aren't working, no night vison or water breathing. I updated to the most recent release and it didn't fix the issue. Also updated dependencies.

**Comment by LambertsCode** [comment]
Found the issue, the enable ability doesnt show up

**Comment by cityslicker773** [comment]
How were you able to get the option to show up?

**Comment by drago15243** [comment]
For anyone else with this issue, there may be a texture pack without the button there I assume, it's still there above the taking off backpack button. 
![image](https://user-images.githubusercontent.com/12012614/187092810-470493a3-e9b1-420b-9b55-5c27e7323d87.png)
