### ISSUE TITLE
Cannot open backpack

### ISSUE THREAD

**Issue by giabao06** [Tiviacz1337/Travelers-Backpack#469]
**Describe the bug**
The keybind used to open the backpack doesn't open the backback

**To Reproduce**
1. Press the key bound to open the backpack

**Expected behavior**
The backpack inventory should be opened

**Required informations (please complete the following information):**
 - Mod version: 1.17.1-6.0.0
- Mod Loader: Fabric

**Additional context**
Modpack: All of Fabric 4 (Xaero's minimap and Xaero's world map removed as per a suggestion in a closed issue about this; replaced with Voxelmap)

**Comment by Tiviacz1337** [comment]
use 1.17.1-6.0.8 mod version

**Comment by giabao06** [comment]
Will update tonight to see. Thank you

Aug 25, 2022 6:02:56 PM Tiviacz1337 ***@***.***>:

**Comment by giabao06** [comment]
Working now, closing issue. Thank you very much
