### ISSUE TITLE
Not letting me go into my backpack.

### ISSUE THREAD

**Issue by RenaAthena** [Tiviacz1337/Travelers-Backpack#473]
I got the travelers backpack and I right clicked on it and it put it on It when I go to my backpack slot it doesn't show the backpack and it wont let me access it in any way  tried changing my key binds didn't work.

**Comment by Nikkinicki** [comment]
I also have this problem. My backpack is on my back but I cannot open it nor does it show in the slot. I can actually put ANOTHER back pack on :(

**Comment by Tiviacz1337** [comment]
mod version

**Comment by SrRapero720** [comment]
Same problem
Version: 7.1.8 - FML 40.1.73
Modpack: 
[WaterMineModpack-waterfall-5.2.0.zip](https://github.com/Tiviacz1337/Travelers-Backpack/files/9437208/WaterMineModpack-waterfall-5.2.0.zip)


SCREENSHOT (no any wearer)
![image](https://user-images.githubusercontent.com/29090346/187011333-3364b16e-d862-4005-9532-5f447484977d.png)

SCREENSHOT (force wearing with shift+click and after wearer try to press B or check curious)
![image](https://user-images.githubusercontent.com/29090346/187011353-ab3619c9-eb5a-4ace-89e0-57082bc293f4.png)
![image](https://user-images.githubusercontent.com/29090346/187011363-bbd209a9-6344-4ed2-9eec-7df6cfa512b5.png)
![image](https://user-images.githubusercontent.com/29090346/187011423-570f5052-5976-4a0a-bb25-50722ea48533.png)

SCREENSHOT USING OTHER BACKPACK FORCING WEARING
![image](https://user-images.githubusercontent.com/29090346/187011457-8c7717b5-2d6a-45d7-8cc8-ef37d87c1ed8.png)

**TO GET BACK THE BACKPACK**
Just die, corail never wearer backpack again

**Comment by Tiviacz1337** [comment]
https://github.com/Tiviacz1337/Travelers-Backpack/issues/476
See this, there's solution. If it doesn't fix your issue, open again.
