### ISSUE TITLE
Backpacks can't equip or used (With curious)

### ISSUE THREAD

**Issue by SrRapero720** [Tiviacz1337/Travelers-Backpack#476]
**Describe the bug**
Sorry my english is bad.
Backpacks can't equip normally in inventory or using the button to equip in the backpack, armor slot arent avariable.
but its posible to force-equip backpack from the floor sneaking and right clicking. doing this backpack get equiped but is not usable or unequipable
Also, if you try to equip another pack. mod warns "you have already a backpack worn"
![2022-08-29_02h59_39](https://user-images.githubusercontent.com/29090346/187153587-ddda71e0-8868-4f06-b6ed-430495b147df.png)
![2022-08-29_02h59_48](https://user-images.githubusercontent.com/29090346/187153541-f053271b-e119-4d92-a5e8-d5d644156dc0.png)

Reading about how mod works i found use curious, also in the overall of the curious mod describes
> _Slots are only made on-demand. There are no slots included by default, all slots are created only as needed. This reduces instances where one or more superfluous slots are present without any suitable items to go into the slot._

Looking for that i found when i use only travelers backpack the back slot from curious isn't enabled.
![2022-08-29_03h05_12](https://user-images.githubusercontent.com/29090346/187154206-80d2b238-ca08-42f1-ac0a-d33c417c8929.png)

So i install other backpack mod for testing and i found the slot functional BUT the backpack arent here
Instead, you can equip 2 backpacks. 1 forced-equipped and 2 in curious slot.
![2022-08-29_03h18_35](https://user-images.githubusercontent.com/29090346/187156853-65322514-2eba-420d-98b1-78eb0e620770.png)

Also something weird, if i equip backpack on curious slot manually and try to use keybind to open the backpack... this no open, but if i have a forced backpack equiped and also equip backpack in curious slot back you can use keybind to open the curious backpack
<video src="https://user-images.githubusercontent.com/29090346/187159478-e41088f7-76c4-4eaa-a0cd-52329c1329b3.mp4"></video>

**Required informations (please complete the following information):**
 - Mod version: [1.18.2 - 7.1.8]
- Mod Loader: [Forge-40.1.73]

**Additional context**
Modpack 
[WaterMineModpack-waterfall-5.4.0.zip](https://github.com/Tiviacz1337/Travelers-Backpack/files/9443217/WaterMineModpack-waterfall-5.4.0.zip)

**Comment by SrRapero720** [comment]
Also i "reported" this before in other issue,  but issue are less documented and can't be the same problem
[https://github.com/Tiviacz1337/Travelers-Backpack/issues/473#issuecomment-1229107314](url)

**Comment by SrRapero720** [comment]
**Updated:**
Trying to found the problem i delete the cfg files but nothing changes. so i decided (from other reasons) made a cleanup of all useless config files (including server files)
Aparently after that, backpacks get back to work fine. 

So if someone get the same problem, make a cleanup of all config files (patience after all)

PRESSING B: 
![image](https://user-images.githubusercontent.com/29090346/187337136-5867bb0b-2ed8-452a-9cda-73a3e896e640.png)

OPEN NORMAL BACKPACK:
![2022-08-29_21h31_00](https://user-images.githubusercontent.com/29090346/187337171-bc4c17c5-c909-406e-a3f0-628aa39ec9a1.png)

**Comment by SrRapero720** [comment]
I reopen the issue, because normal backpack works fine but curious no. cant be equiped or opened, but its accesible from curious slot.

**Comment by Tiviacz1337** [comment]
@SrRapero720 For backpack to work in curios slot, you have to change config option curiosIntegration from false to true in Traveler's Backpack common config

**Comment by SrRapero720** [comment]
I know and i set curious integration on true (before test curious) and no work

**Comment by Tiviacz1337** [comment]
basically, to put backpack on you have to hold backpack in hand, right click it then the gui will open and click the green equip button on the left side. Alternative option is to shift click from the ground. - That's if curios integration is set to false. If curios integration is set to true you can either - put backpack in back slot manually by draging from inventory to back slot or shift right click if backpack is placed on the ground.

**Comment by Tiviacz1337** [comment]
Make sure you dont have any backpack equipped when you change curiosIntegration from false to true or from true to false.

**Comment by SrRapero720** [comment]
I undestand the functionallity, so i made a new video
Its a dedicated server, no have the xaeros minimap (only ftb)
<video src="https://user-images.githubusercontent.com/29090346/188501267-d9f7f67e-ca2e-4e02-b370-ad2784af7b8b.mp4"></video>

**Comment by SrRapero720** [comment]
Backpack cannot be equiped on interface and cannot be opened with keybind

**Comment by Tiviacz1337** [comment]
I see you changed the config option on server, did you change config option on client too?

**Comment by SrRapero720** [comment]
Now works the keybind, also something i see. when i have a higher or lower fluid tank size in server config but no sync in local tank display a fake limit

Tank server have 50,000 but client display max 40,000
![image](https://user-images.githubusercontent.com/29090346/188523022-45cb491b-390c-4e10-9a3f-1b18d1d38efb.png)
But its confusing having to update local and server configs.

Afterall i see is not a bug. but is a unintuitive configuration system. 
so thanks for the help

**Comment by Tiviacz1337** [comment]
I find it confusing too, but they have to be the same on client & server. So I'm closing this issue
