### ISSUE TITLE
Duping on 1.18.2

### ISSUE THREAD

**Issue by itsdinkd** [Tiviacz1337/Travelers-Backpack#477]
https://github.com/itsdinkd/AQM2/issues/91 

Using any version of travelers backpack for 1.18.2, and apply soulbound (Soulbound in AQM is from Youre in grave danger) and use shears and such you can dupe your entire backpack as the linked issue mentions.

**How to reproduce**
    Enchant a backpack with soulbound (unknown if this has to be done)
    Shear it in a crafting table to make a standard backpack
    Contents inside are now duped as you still have the old backpack and the new one.

**Comment by Tiviacz1337** [comment]
do you shear it in basic crafting table? or modded one

**Comment by Tiviacz1337** [comment]
bug fixed but it is still processing on curseforge site

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files fixed in latest update
