### ISSUE TITLE
The regeneration from dragon backpack is not working.

### ISSUE THREAD

**Issue by Hotaru-Snowy** [Tiviacz1337/Travelers-Backpack#478]
**Describe the bug**
The regeneration from dragon backpack isnt working. Although this should not be a bug, but I hope it could be solved.
I think it works like beacon well work. (Or remove the regeneration.~_~)

**To Reproduce**
first is the end.

**Expected behavior**
Null

**Screenshots**
nope

**Required informations (please complete the following information):**
 - Mod version: maybe all.
- Mod Loader: both

**Additional context**
im sorry for my poor english.

**Comment by Robocraft999** [comment]
same. Regen doens't fill up the hearts (maybe because it's reset every tick?)

**Comment by Tiviacz1337** [comment]
forge/fabric? mod version?

**Comment by Robocraft999** [comment]
forge 1.18.2-7.1.8

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all fixed in 7.1.9
