### ISSUE TITLE
Squid Backpack no abilities @Tiviacz1337

### ISSUE THREAD

**Issue by Frection** [Tiviacz1337/Travelers-Backpack#479]
**Describe the bug**
Squid Backpack does not provide water breathing or night vision. Simply started taking drowning damage. No matching status effects given. Only effect was manaboost from archon.

**To Reproduce**
1. ...Load up game, get backpack, go under water

**Expected behavior**

**Required informations (please complete the following information):**
 - Mod version: 1.19.2-8.2.0
- Mod Loader: Fabric

**Additional context**
Medieval MC Fabric 1.19.2 CurseForge
No additional/removed mods
Seems like a cool mod anyways, but was disappointed by bug

**Comment by SirDhyne** [comment]
Confirming this bug; squid pack does not provide the expected ability when worn or held. Same modpack.

**Comment by Tiviacz1337** [comment]
![image](https://user-images.githubusercontent.com/34790800/188327526-3eb266a2-032c-47f6-912c-adc7d7df2ad6.png)
