### ISSUE TITLE
Duping/Rolling Back issues with backpack

### ISSUE THREAD

**Issue by zerevoidd** [Tiviacz1337/Travelers-Backpack#480]
Any item has a chance of rolling back/disappearing out of any type of backpack when using this mod in the Medieval Minecraft modpack (Fabric 1.19.2) I'll put something in the bag then minutes later it will be gone or my bag will be what it was 5 minutes ago instead of what it should be. Most notable items that this happens with are weapons.

**Comment by Tiviacz1337** [comment]
Traveler's Backpack mod version?
