### ISSUE TITLE
Disappearing backpack

### ISSUE THREAD

**Issue by Thund3rmonk3y1** [Tiviacz1337/Travelers-Backpack#481]
No problems when the bag is on my back but I usually keep an extra one in my inventory for loot runs and it frequently goes missing after logging back into the game, forcing me to craft another. I usually prepare for this by putting everything away before I log out but now its getting kind of annoying.

As far as I know there's no way to force it to happen but there seems to be a random chance upon logging out and logging back in

Mod version 1.16.5
Medieval MC

**Comment by Tiviacz1337** [comment]
Well, I don't know what might be the issue here. Random chance to disappear seems weird to me. Maybe it depends on the content of the backpack? you might play with that a bit. As for now, I've never experienced this issue
