### ISSUE TITLE
Duping Bug with IE Storage Crates

### ISSUE THREAD

**Issue by Robocraft999** [Tiviacz1337/Travelers-Backpack#483]
**Describe the bug**
Storage crates (maybe shulkerboxes too but I didn't tested them) get stacked even if they have different content and the content gets duplicated (because you have e.g. 2 crates with the same content). The content of the second crate gets deleted btw.

**To Reproduce**
1. put a storage crate with suff in it in the backpack
2. sort the backpack
3. put another storage crate in the backpack (empty of filled)
4. sort again

**Expected behavior**
Storage crates with different content get not stacked.

**Required informations (please complete the following information):**
 - Mod version: 1.18.2 - 7.1.8
- Mod Loader: Forge (only tested forge)

**Additional context**
Has something to do with the sorting I guess.
Edit: Maybe change `ItemStack.isSame()` (dont respects tags) to `ItemStack.isSameItemSameTags()` here: https://github.com/Tiviacz1337/Travelers-Backpack/blob/1.18.2/src/main/java/com/tiviacz/travelersbackpack/inventory/sorter/ContainerSorter.java#L216

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
fixed in 7.1.9
