### ISSUE TITLE
Backpack disappears from grave using "trinketsIntegration" and You're in Grave Danger mod

### ISSUE THREAD

**Issue by Makaren0** [Tiviacz1337/Travelers-Backpack#484]
**Describe the bug**
I have recently set up a clean server integrating trinkets, You're in Grave Danger and Traveler's Backpack. Enabling the "trinketsIntegration:true" option to integrate the backpack into the corresponding slot in the GUI offered by Trinkets. When the tomb is picked up it does not return the backpack in the corresponding slot, but it does return the other trinkets correctly or a backpack in the inventory without using the special slot.
I have also noticed that I cannot access the backpack inventory directly with the defined key while the backpack is equipped in this slot.
**To Reproduce**
1. Trinkets, You're in Grave Danger y Traveler's Backpack
2. fabric-server-mc.1.19.2-loader.0.14.9-launcher.0.11.0

I could provide more debug information, but I think it's really easy to reproduce the error. But please, if you need more information I can provide it

**Comment by Tiviacz1337** [comment]
Do you have trinketsIntegration enabled on client?

**Comment by Tiviacz1337** [comment]
Didn't backpack get placed on the ground?

**Comment by Makaren0** [comment]
> ¿No se colocó la mochila en el suelo? Creo que desapareció porque configuré la regla de baratijas para destruir cuando el jugador muere, porque la mochila tiene su propia ubicación lógica posterior a la muerte.

I was expecting this issue, I disabled it in a test environment and it doesn't seem to work.
And in the absence of more similar answers, I assume that all this will come from some incompatibility that I can't discover.

Later I'll try to do a simulation again with your latest mod pack. Thanks for the suggestions

**Comment by Ozakinn** [comment]
Go to your yigd.toml and set the trinket to true

```
[graveSettings.graveCompatConfig]
levelzXpInGraves = true
levelzXpDropPercent = 100
claimRuleOverride = "CREATE_GRAVE"
prioritiseTheGraveyardGraves = false
graveyardSearchRadius = 10
keepAllTrinkets = true
```

**Comment by Wilson-Cal** [comment]
Seems to be an issue with a default config setting in the youre-in-grave-danger mod. Doing what @Ozakinn suggested fixed the issue for me.

**Comment by Ozakinn** [comment]
> Seems to be an issue with a default config setting in the youre-in-grave-danger mod. Doing what @Ozakinn suggested fixed the issue for me.
> 
> However, all of the items inside the backpack do disappear.
> 
> Update: Switching to the Universal Graves mod solved the issue. Backpack is placed on the ground next to the grave with all items inside.

I'll try that mod too later. I feel like there is a duplicate bug with the traveler backpack and youre-in-grave-danger mod. players in my server keeps killing each other causing massive items(netherites, diamonds, and same armors/swords) in inventory and chests.

**Comment by Tiviacz1337** [comment]
It'll be fixed in upcoming update

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files fixed
