### ISSUE TITLE
Special Backpacks display wrong design when crafted with colored standard backpack

### ISSUE THREAD

**Issue by unweeked** [Tiviacz1337/Travelers-Backpack#485]
**Describe the bug**
If you craft a Special backpack (like cake) using a colored backpack (like pink) the item will be the correct one, but since the data of the old Backpack is still stored (in order to keep the Inventory), the backpack will still render as colored (pink) if the player wears the backpack.

**Expected behavior**
The correct backpack is displayed (cake)

**Required informations (please complete the following information):**
 - Mod version: 1.18.2 newest
- Mod Loader: Forge
On a server

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
Fixed on Fabric
(Forge soon)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
