### ISSUE TITLE
Modifcation of ItemStack.EMPTY's NBT data

### ISSUE THREAD

**Issue by Ellemes** [Tiviacz1337/Travelers-Backpack#486]
**Describe the bug**
Backpack inventories are being initialized with an empty item stack which nbt's is being modified by this mod which is not very good as it is causing a lot of lag when sending item nbt to the client.

**To Reproduce**
As simple as wearing a backpack as far as I'm aware.

**Expected behavior**
Not to write data or try to get nbt data from ItemStack.EMPTY.

**Screenshots**
![image](https://user-images.githubusercontent.com/5214513/189525722-a4b0bd60-d54c-433a-9b2d-ccb1475e8deb.png)
As you can see empty items all have nbt originating from this mod.

**Required informations (please complete the following information):**
 - Mod version: 1.18.2-7.1.5, seems to affect anything newer.
- Mod Loader: Fabric

**Additional context**
https://github.com/Tiviacz1337/Travelers-Backpack/blob/7e69b21fe10f48e6a50bd829bc389bc22020ff91/src/main/java/com/tiviacz/travelersbackpack/capability/TravelersBackpackWearable.java#L22

This seems to be at least one of the causes of the issue as the Inventory is made with an empty ItemStack.

Also this is a stacktrace we get on AOF's servers when I made a mod to log when `getOrCreateNbt` is called on `ItemStack.EMPTY`:
[log.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/9542433/log.txt)

~~Edit: this looks bad too... https://github.com/Tiviacz1337/Travelers-Backpack/blob/23fa94521b923a60657ee548c6c5f92aea6a64be/src/main/java/com/tiviacz/travelersbackpack/component/TravelersBackpackComponent.java#L113-L114~~ Nevermind I misread this.

**Comment by Tiviacz1337** [comment]
is the backpack currently on the back when you are stacktracking this?

**Comment by Ellemes** [comment]
Unsure, this is happening on a server so I can only assume someone is wearing a travellers backpack.
Trinket integration is off.

**Comment by Tiviacz1337** [comment]
As I can see on screenshot it seems like traveler's backpack is inside imnis backpack is it right?

**Comment by Ellemes** [comment]
Well Imnis writes `ItemStack.EMPTY` stacks to their inventory, and traveler's backpack is writing data to `ItemStack.EMPTY` so all the air stacks have this nbt data.

**Comment by Tiviacz1337** [comment]
That's really strange I can't reproduce this issue

**Comment by Tiviacz1337** [comment]
If you could give me steps how to reproduce this issue I'd be glad. In my dev environment Empty itemstacks are just empty.. Also code you sent

 ItemStack wearable = ItemStack.EMPTY; 
 wearable.writeNbt(tag); 

it does not write tag to ItemStack.EMPTY, but ItemStack.EMPTY is being written to tag. Which later is checked if player hasWearable then it should sync. Ye as I said before reproducing steps would be great

**Comment by ouroborus** [comment]
I've been see this on my server as well. Running AOF5 1.5.1 which uses travelers-backpack-1.18.2-7.1.5

**Comment by ouroborus** [comment]
I think this might actually be a bug with upgrading inmis backpacks. To reproduce it, put a Traveler's Backpack in a Frayed Backpack, upgrade the Frayed Backpack, then check the NBT data.

**Comment by ouroborus** [comment]
I'm not sure which mod is causing the issue, but this can be reproduced with the help of [Inmis](https://www.curseforge.com/minecraft/mc-mods/inmis). Put a Traveler's Backpack in a Frayed Backpack, upgrade the Frayed Backpack, observe the NBT data.

**Comment by Tiviacz1337** [comment]
What is this mod which shows nbt tags? (on previous screenshot)

**Comment by Tiviacz1337** [comment]
Hm I think the issue might be located in syncing. Can you enable TrinketsIntegration and check if it still happens?

**Comment by ouroborus** [comment]
> Hm I think the issue might be located in syncing. Can you enable TrinketsIntegration and check if it still happens?

I'm not able to reproduce it with `"trinketsIntegration": true`

**Comment by Tiviacz1337** [comment]
Yeah so it seems that's issue with syncing of component

**Comment by Tiviacz1337** [comment]
Anyone who might know how to reslove this issue can make a pull request or help.

**Comment by Tiviacz1337** [comment]
Fixed 
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
