### ISSUE TITLE
Storage issue with shulkers and backpacks

### ISSUE THREAD

**Issue by LerinGotchri** [Tiviacz1337/Travelers-Backpack#487]
**Describe the bug**
You are able to put a backpack inside of a shulker, and a shulker inside of a backpack. Thus creating an 'infinite capacity storage'.
**To Reproduce**
1. Uh...described above

**Expected behavior**
I'd expect you to not be able to either
A: Put a backpack into a shulker
B: Be able to put a shulker into a backpack
**Screenshots**
![2022-09-19_12 42 19](https://user-images.githubusercontent.com/113933619/191080077-f5833c7a-4ce5-4bb6-b81f-b45d299d3920.png)

**Required informations (please complete the following information):**
 - Mod version: 1.19.2-8.2.1
- Mod Loader: Fabric

**Additional context**

**Comment by TelepathicGrunt** [comment]
For the dev to solve this easily, they can make the backpack item override this canFitInsideContainerItems method to return true and make their backpack’s item slots check and reject any item that returns true for that method
https://github.com/TelepathicGrunt/Bumblezone/blob/db7d29cd8e02466bd01d8ea697cd22b09a57601d/src/main/java/com/telepathicgrunt/the_bumblezone/items/BzBlockItem.java#L21

This will prevent backpacks from being put into shulker boxes and prevent shulker boxes from being put into backpacks. Thus breaking the infinite storage issue. Other mods with shulker box-like items should also be doing the same to prevent infinite nesting as well. My Bumblezone mod’s honey cocoon does the same so this change would work with Bumblezone too.

**Comment by Tiviacz1337** [comment]
Thank you @TelepathicGrunt didnt know about this useful method, backpacks won't be placeable in shulkerboxes

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
Available for Fabric
(Forge soon)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
