### ISSUE TITLE
Ignore shield when picking up backpack

### ISSUE THREAD

**Issue by shaneknysh** [Tiviacz1337/Travelers-Backpack#489]
**Is your feature request related to a problem? Please describe.**
Right clicking a backpack on the ground will put the back pack on if:
1. your hand is empty and
2. you have no shield equipped

**Describe the solution you'd like**
Backpack is picked up and worn when right clicked regardless if you have a shield equipped.

Additionally (nice to have), if you are wearing backpack and right click a backpack on the ground it would be nice to be able to swap the backpacks.  

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Tiviacz1337** [comment]
Backpack can be picked up with any item in hand now
I didnt add swapping backpack feature

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
Available for Fabric
(Forge soon)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
