### ISSUE TITLE
Full compatibility with REI / JEI

### ISSUE THREAD

**Issue by ascpial** [Tiviacz1337/Travelers-Backpack#491]
JEI (Just Enough Items) and REI (Roughly Enough Items) are mods that are really useful, especially with other mods that adds a lot of crafting.

It could be nice to have full support for these mods on the backpack to allow a better user experience.
This is the conditions where no support is provided for the "move items" functionnality of JEI /REI :

- On Forge
  - JEI when the backpack is accessed through the inventory (right click or via the equipped backpack)
  - REI when the backpack is placed on the ground
  - REI when the backpack is accessed through the inventory (right click or via the equipped backpack)
- On Fabric
  - JEI when the backpack is placed on the ground
  - JEI when the backpack is accessed through the inventory (right click or via the equipped backpack)
  - REI when the backpack is placed on the ground
  - REI when the backpack is accessed through the inventory (right click or via the equipped 

I should also mention that using JEI on the Farbic Loader is not ideal because custom recipes with mods like Create or Farmers Delight are not supported.

**Comment by Tiviacz1337** [comment]
Forge has JEI support
Fabric has REI support

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
Added REI support for all Fabric versions

**Comment by ascpial** [comment]
I quickly tested the update on fabric and it seems to work well.
Great job, and thanks for maintaining this great mod!
