### ISSUE TITLE
Crafting result doesn't show in backpack - Fabric 1.18.2-7.1.7

### ISSUE THREAD

**Issue by knzconnor** [Tiviacz1337/Travelers-Backpack#493]
**Describe the bug**
I put things in the crafting grid, and can pull the result out, but no preview for the result shows (so I better have it right). Also, won't fil lingredients from REI. That could be because I manually added it to Valheisa Enchanced Vanilla. But it does show up in REI so at least some of the default config works

**To Reproduce**
1. Make backpack
2. Put stuff in crafting area

Or:
1. Open backback
2. Select transfer ingredients from recipe in REI

**Expected behavior**
You can see the crafting preview, and transfer from REI works

**Required informations (please complete the following information):**
 - Mod version : 1.18.2-7.1.7
- Mod Loader: Fabric

**Comment by Tiviacz1337** [comment]
hmm, do you use trinkets integration or not? Also do you access crafting by B button or in hand or as a block
