### ISSUE TITLE
Ability not working.

### ISSUE THREAD

**Issue by Giffdude** [Tiviacz1337/Travelers-Backpack#495]
I was playing and finally worked myself up to be able to create the blaze backpack, and it's ability to nullify fall damage wasn't working. I've tried looking up videos but it haven't found anything

**Comment by Ryuushen** [comment]
Same thing with Squid Backpack

**Comment by ADIOP55550** [comment]
@Giffdude @Ryuushen 
Make sure you have enabled the ability, that was the cause for me:
![image](https://user-images.githubusercontent.com/31273119/193560344-2b6e349f-6253-4d05-b082-c6220c88882e.png)

**Comment by Giffdude** [comment]
Thank you very much!
