### ISSUE TITLE
Let's add Ukrainian localization! (made by me)

### ISSUE THREAD

**Issue by beefufo** [Tiviacz1337/Travelers-Backpack#496]
Hi, I'm not sure how to use GitHub, but I created a Ukrainian translation file for Travelers Backpack, and I'm ready to submit it! How do I do that? Thanks!
![Screenshot 2022-10-05 000544](https://user-images.githubusercontent.com/92248916/194035705-1a84b183-1e50-40c8-91d3-2525bc8aa6b1.png)

**Comment by beefufo** [comment]
Also, can I change the "item" to "this backpack"?

**Comment by Tiviacz1337** [comment]
You can send it to me on discord if you want Tiviacz1337#1878 or send it here, how you want

**Comment by Tiviacz1337** [comment]
If it's possible please send it soon, because I will release update
