### ISSUE TITLE
Missing Architectury requirement

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [Tiviacz1337/Travelers-Backpack#498]
**Describe the bug**

Neither fabric mod json nor CF page list Architectury as a requirement for this mod.

**To Reproduce**

1. Install the mod without Architectury and try to launch the game
2. Crash

**Expected behavior**

An error message telling the user to install Architectury.

**Logs**

https://gist.github.com/Footage2-Amply-Pounce/505e876fd794dd5529a443b578f88095

**Required informations (please complete the following information):**

- Mod version: 8.2.2
- Mod Loader: Fabric 0.14.9 + API 0.62.0

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all 
Should be fixed. If not reopen issue.
