### ISSUE TITLE
Dying to fire causes a crash, if Trinkets is installed

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [Tiviacz1337/Travelers-Backpack#499]
**Describe the bug**

If you die from fire damage, the game crashes, but only if Trinkets is installed.

**To Reproduce**

1. Install the mod and Trinkets
2. Join a world and either set yourself on fire or let a blaze kill you; you don't have to have a backpack or anything in your inventory at all
3. Crash

**Expected behavior**

No crash.

**Logs**

https://gist.github.com/Footage2-Amply-Pounce/22afd3a6d18090bbb2f93b006e5aca3d

**Required informations (please complete the following information):**

- Mod version: 8.2.2
- Mod Loader: Fabric 0.14.9 + API 0.62.0

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
Should be fixed. If not reopen issue.
