### ISSUE TITLE
[1.16.5] Travelers backpack crash (on server) when roughly enough items is installed 

### ISSUE THREAD

**Issue by quentin452** [Tiviacz1337/Travelers-Backpack#500]
**Describe the bug**
Travelers back crash on server on startup if roughly enough items is installed

**To Reproduce**

1. start server
2. crash

**Required informations (please complete the following information):**

 - Mod version: 1.16.5-5.4.10.
- Mod Loader: FABRIC

**Logs**

[latest.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/9805245/latest.log)

**mods list**

Cardinal-Components-API-2.8.3
cloth-config-4.16.91-fabric
fabric-api-0.42.0+1.16
RoughlyEnoughItems-5.12.385
travelers-backpack-1.16.5-5.4.10

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/4033117 fixed

**Comment by quentin452** [comment]
thx
