### ISSUE TITLE
backpack's custom name disappears.

### ISSUE THREAD

**Issue by mortdecai91** [Tiviacz1337/Travelers-Backpack#501]
the custom name i put on my backpack disappears after i put it down to use it as a bed(this happened to me in my survival world, i recreated it in my test map.)

sorry for the resolution, was trying to get the lowest possible to be able to upload a clip then this is what i came up with.

https://user-images.githubusercontent.com/116187001/196733489-12e0a00e-9763-4b2e-8665-1097d1a2e25f.mp4

**Comment by mortdecai91** [comment]
forge, i was using it in rlcraft modpack.

**Comment by Tiviacz1337** [comment]
1.12.2 is not supported
