### ISSUE TITLE
Item Duplication 1.16.5 - 1.18.2

### ISSUE THREAD

**Issue by TheTornEye** [Tiviacz1337/Travelers-Backpack#503]
**Describe the bug**
You can duplicate items using the Crafting Table section of the back pack. BUT it's only on the backpacks with abilities. (I found it on the Blaze Backpack specifically, but recreated it with the Squid as well)

**To Reproduce**
1. Equip backpack on back (With Curios, I didn't check this as a chestplate, since it wouldn't let me try without removing Curios)
2. Turn on Ability (doesn't seem to work while ability is off)
3. Put a stack (at least 2) of something in the crafting table section.
4. Split the stack(right click). The Original stack stays the same, but the split stack can be placed.
5. Transfer duped stack to inventory, not backpack inventory(sometimes disappears but not every time.

**Expected behavior**
I didn't expect the original stack to not split.

**Screenshots**
I don't have screens but I can get them if you'd like.

**Required informations (please complete the following information):**
 - Mod version: 1.16.5 AND 1.18.2 (Seems fixed on 1.12.2, haven't attempted in 1.19.1)
- Mod Loader: Forge 

**Additional context**
Does not work on ground or in inventory, only seems to dupe while on back.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all fixed
