### ISSUE TITLE
Cresh report

### ISSUE THREAD

**Issue by Chinkrask** [Tiviacz1337/Travelers-Backpack#504]
**Describe the bug**
The game is uncapable of loading completely and crashes before the main menu.

**To Reproduce**
1. Open the game launcher using CurseForge with the profile that has been attached to this post at the bottom.
2. Login with you Microsoft account.
3. Press the "Play button".
4. Wait until it happens.

**Expected behavior**
The game should open without issues.

**Screenshots**
![Captura de pantalla (132)](https://user-images.githubusercontent.com/87289073/199117518-3448be0f-2f19-4ea1-a342-2e6efa317cc0.png)

**Required informations (please complete the following information):**
 - Mod version: 1.19.2 - 8.2.6
- Mod Loader: Forge - 43.1.1

**Additional context**
According to the crash screen, it has relations with entities. I have know knowledge on this, so I can only especulate that has something to do with dying due to the "LivingChangeTargetEvent".
[a.zip](https://github.com/Tiviacz1337/Travelers-Backpack/files/9905259/a.zip)

**Comment by Chinkrask** [comment]
Something I forgot to mention is that I did deleted the configuration files for Traveler's Backpack

**Comment by Tiviacz1337** [comment]
Please update your forge version

**Comment by Tiviacz1337** [comment]
If issue resolve, close this thread

**Comment by Thundy822** [comment]
Hi, I've had the same problem and updated my Forge, but it still crashes

**Comment by Tiviacz1337** [comment]
What is crash report now?

**Comment by KeithLerner** [comment]
having this same issue on a forge 1.18.2 server. Using forge 40.1.80, had to jar fix this file to get the server operational at all but my understanding is that "sometimes it be like that". The mod works as expected and without error in single player worlds.

Exact error is as follows:
`Failure message: Traveler's Backpack (travelersbackpack) has failed to load correctly
                java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/LivingChangeTargetEvent
        Mod Version: 7.1.14`

**Comment by Tiviacz1337** [comment]
What do you mean jar fix? did you try using forge 40.1.84?

**Comment by Tiviacz1337** [comment]
Made a quick check and you have to update forge to 40.1.84

**Comment by KeithLerner** [comment]
> having this same issue on a forge 1.18.2 server. Using forge 40.1.80, had to jar fix this file to get the server operational at all but my understanding is that "sometimes it be like that". The mod works as expected and without error in single player worlds.
> 
> Exact error is as follows: `Failure message: Traveler's Backpack (travelersbackpack) has failed to load correctly java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/LivingChangeTargetEvent Mod Version: 7.1.14`

This was resolved by downgrading/reverting the server's mod version to 7.1.13. The client still uses mod version 7.1.14 when connecting to the server but this has not produced any additional errors.

**Comment by Tiviacz1337** [comment]
I'm 99% sure updating to forge 40.1.84 will resolve the issue, since I'm using newly added class to forge in 7.1.14 which was introduced in 40.1.84
