### ISSUE TITLE
Backpack not equiping

### ISSUE THREAD

**Issue by Sin-Kaine** [Tiviacz1337/Travelers-Backpack#505]
**Describe the bug**
I found a backpack in a barrel, and when I tried to equip it, I cant
**To Reproduce**
1. Found  a  Iron Golem Travelers Backpack
2. Attempted to equip
3. Failed to go into ANY slot on chest

**Expected behavior**
Expected to be able to use the backpack
**Required informations (please complete the following information):**
 - Mod version: [1.19.2 v10]
- Mod Loader: [Medieval MC Fabric]

**Comment by Tiviacz1337** [comment]
right click on backpack in hand and click green equip button on the bottom left of the gui
