### ISSUE TITLE
[1.18.2]The Melon Backpack's harvest cd decreases failed after enabling the ability.

### ISSUE THREAD

**Issue by LitnhJacuzzi** [Tiviacz1337/Travelers-Backpack#507]
As the title said, if you put the melon backpack on the ground, trigger its ability to enabled, destroy it and place it again to check the harvest cd, you'll find the time is freezed at the initial value.

The reason has been found, which is described as "tick update invalid", caused by method TravelersBackpackBlockEntity::tick cannot be invoked when necessary.

The root was located in class TravelersBackpackBlock, method getTicker(...). It's turned out to be a logic mistake, and the solution is as follows:
Add "!" judgement before level.isClientSide and TravelersBackpackConfig.enableBackpackAbilities.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files fixed
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
