### ISSUE TITLE
1.12.2 crashes with building gadgets copy & paste tool

### ISSUE THREAD

**Issue by eXenonGH** [Tiviacz1337/Travelers-Backpack#509]
version : 1.12.2
i placed the copy & paste tool from building gadgets in the backpack, but whenever i point at it in the backpack the game crashes, can't get it out of the backpack anyway.

here's the crash report

[crash-2022-11-12_22.57.02-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/9995833/crash-2022-11-12_22.57.02-client.txt)

update : i managed to delete it with trashslot mod, while holding an item with the cursor it doesn't crash when pointing at the item, i moved it to the trashslot but and got rid of it, it even crashes when pointed at anywhere normally, thankfully i had vanilla fix which saved me alot of time

**Comment by Tiviacz1337** [comment]
sorry 1.12.2 is no longer supported
