### ISSUE TITLE
Localisation problem

### ISSUE THREAD

**Issue by BlackShadow77** [Tiviacz1337/Travelers-Backpack#510]
**Is your feature request related to a problem? Please describe.**
I usually help to translate mods and i also usually use this mod when i play. When i select my language in minecraft options this mod support localisation but there is a huge problem: In english i say "an orange pen" so we have color before object; in italian (my language) we say "una penna arancione" (literally "a pen orange"). When i set the mod lang in italian i also expect a swap of adjective (ex. "zaino del viaggiatore di volpe" and not "volpe zano del viaggiatore") but this not happen and sounds weird.

**Describe the solution you'd like**
i think it possible to include a variable in some string in lang file where the mod put the block name so i can move that when i update lang files based on language. 

**Describe alternatives you've considered**
An alternative solution may be change how mod build the name string of a backpack and insert in lang files the complete name of every single backpack.

**Additional context**
i hope is not a personal mistake but i didn't see any of this feature in lang files yet

**Comment by Tiviacz1337** [comment]
Okay, my only possible solution for that - tell me what you think. 
Since backpack names are created by Seperate translation of backpack variant eg. "Standard" + different translation of "Traveler's Backpack". 
I can swap it for Italian language, so It'd be translation of "Traveler's Backpack" + translation of "Standard"
Does it satisfy you?

**Comment by BlackShadow77** [comment]
Yes, that would be great!
I hope that will be easy as i read when u have to modify code. 

I also suggest to add some comments in the italian file for future readers about the "unique" system to avoid bugs and bad translations in updates.

**Comment by Tiviacz1337** [comment]
You can translate here: https://localazy.com/p/travelers-backpack
The change is only code-wise so the whole lang file stays the same

**Comment by Tiviacz1337** [comment]
![image](https://user-images.githubusercontent.com/34790800/214620647-9e553c22-903e-4c9b-a782-bc40f8b12d13.png)
That's how it looks in game

**Comment by Tiviacz1337** [comment]
Also, the update is ready and I'll probably release it tomorrow (26.01) so if you are able to make translation quickly let me know, so I'll delay update

**Comment by BlackShadow77** [comment]
@Tiviacz1337 Ty for the fast reply; i'm on mobile right now so I can't do much. I can update translations in next 2 days (26-27/01/23) if you can wait this time but I also need your help for some context on some entries. I can't work on it until 18:00-19:00 GMT+1.

Tell me if it's possible this rush or if u want to release on 26 anyway.

**Comment by Tiviacz1337** [comment]
Sure I can wait, let me know what entries are bothering you

**Comment by Tiviacz1337** [comment]
-screen.travelersbackpack.none - basically it means that there's no fluid in thank
![image](https://user-images.githubusercontent.com/34790800/214939721-74f73e6c-940a-4eb2-9b2b-da211af41f68.png)

-ability.travelersbackpack.item_and_block(in particular the §6 §e symbols) - symbols which start with § represent color values in game so you have to keep them as they are, item, block and item & block mean that ability is available for this backpack either in item form, block form or in both forms - for example cactus fills with water on back and on ground
![image](https://user-images.githubusercontent.com/34790800/214939989-b497b965-675f-43ff-ab06-18227cd0bc93.png)

-ability.travelersbackpack.item - ability is available only for item form - when player wears the backpack on the back
-ability.travelersbackpack.block - ability is available only for block form - when backpack is placed on the ground
-screen.travelersbackpack.settings_back - arrow that on click hides the menu below (it goes back to backpack)
![image](https://user-images.githubusercontent.com/34790800/214940412-05edec41-c973-4f09-b9c2-bf65774e8310.png)

**Comment by BlackShadow77** [comment]
i did all translations and i fixed some typo, update some existing entries and so on.

I hope is all fine, i wait any notification from you just in case i did something wrong.

Thanks for the clear explanation with images, really helpfull to better adapt translatios

**Comment by Tiviacz1337** [comment]
I've approved all translations and I believe you it's correct since I do not know italian language. 
Thank you for your help!

**Comment by Tiviacz1337** [comment]
@BlackShadow77 I had to make some significant changes to lang files, because my implementation of words swapping place in backpack name was causing crash. I'd be glad if you could take a look at it since you've translated it_it recently.

**Comment by BlackShadow77** [comment]
Sorry for late answer, I moved myself on others projects.
I'm sorry about this problems, I didn't want to cause more work to you and anyone else. Feel free to revert any problem concerning this particular situation until u'll have the time and the force of will to work on it.
About me; I'll do new translations on the website asap to avoid more delay in the new release and more problems.
It's late, sorry for typos.

Keep in touch.

**Comment by BlackShadow77** [comment]
I updated all translations so regarding italian lan it's all done.
