### ISSUE TITLE
All Mod Items Disappear

### ISSUE THREAD

**Issue by grimmlinz** [Tiviacz1337/Travelers-Backpack#512]
So I was moving from an old world to a new one and swapped from Forge to Fabric & I wanted to give myself a backpack that I previously had. When I tried to give myself the backpack from creative it disappeared multiple times, when I would pick up a dropped item it would replace the backpack and the backpack would be gone. So then I tried to just give myself the items to craft the backpack, but the tanks I had given myself also disappeared. I tried looking up the crafting recipes in REI and no recipes appeared. 
I'm playing on version 1.12.2-7.1.12 Fabric with all the required dependencies.

**Comment by Tiviacz1337** [comment]
Check your installation, if you play on server check if mod is installed on server etc.
