### ISSUE TITLE
Traveler's Backpack encountering error while loading

### ISSUE THREAD

**Issue by Maltshakes** [Tiviacz1337/Travelers-Backpack#514]
**Describe the bug**
Trying to play a modpack with Traveler's backpack but keep encountering an error when trying to start the game

**Screenshots**
![2022-11-24 21_47_03-Minecraft_ 1 19 2](https://user-images.githubusercontent.com/76584081/203860955-965575a7-0465-4663-84ae-8e3f114bc3c8.png)

**Required information (please complete the following information):**
- Mod version: 1.19.2 - 8.2.8
- Mod Loader: Forge

**Additional context**
[crash-2022-11-24_21.41.40-fml.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/10087177/crash-2022-11-24_21.41.40-fml.txt)

**Comment by Tiviacz1337** [comment]
Can you update forge to latest 1.19.2 version?

**Comment by Maltshakes** [comment]
I've updated to Forge version 43.1.57 and got this crash:
[crash-2022-11-28_11.38.21-fml.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/10102832/crash-2022-11-28_11.38.21-fml.txt)

**Comment by Tiviacz1337** [comment]
Does crash occur with only tb installed

**Comment by Maltshakes** [comment]
It's tough to test for because it only occasionally occurs. That said, I created an instance with just TB and started up the game multiple times. So far no crash.

**Comment by Tiviacz1337** [comment]
It might be compatibility issue
