### ISSUE TITLE
Client crash while crafting

### ISSUE THREAD

**Issue by LNatit** [Tiviacz1337/Travelers-Backpack#516]
**Describe the bug**
I installed the mod on my server, and when I was crafting in the backpack the client crashes (The server runs properly).
The crash doesn't seem to occur each time when I'm crafting.

**Required informations (please complete the following information):**
 - Mod version: 1.19.2-8.2.8
- Mod Loader: Forge

**Additional context**
Here is the detailed crash info.
[错误报告-2022-12-1_20.57.56.zip](https://github.com/Tiviacz1337/Travelers-Backpack/files/10132608/-2022-12-1_20.57.56.zip)

**Comment by Tiviacz1337** [comment]
Do you craft something specific? Or it happens everytime

**Comment by LNatit** [comment]
Well, I got the question. It is caused by a client mod called Smooth Swapping.
Here is the repository link: [https://github.com/Schauweg/Smooth-Swapping](url)
Sorry for the misjudge :(
(I actually don't know where to report this bug lol)

**Comment by Tiviacz1337** [comment]
report it to their devs
