### ISSUE TITLE
Ability to hide the visual of the backpack

### ISSUE THREAD

**Issue by Red6785** [Tiviacz1337/Travelers-Backpack#517]
**Is your feature request related to a problem? Please describe.**
As much as I like this mod, the backpack models often stick out and interfere with elytras, capes, and any visual that goes on the back. People who like minimalistic looks also sometimes wish they could disable the visual.

**Describe the solution you'd like**
I would like the option to disable the visual of the backpack.

<img width="2048" alt="Screen Shot 2022-12-04 at 2 32 05 PM" src="https://user-images.githubusercontent.com/88458171/205514070-85257a87-7240-4267-bad6-9018fc7e3b59.png">
Here you can see the backpack's visual contrasting greatly with wings from Icarus.

**Comment by Tiviacz1337** [comment]
So it would hide the backpack for you and all players that see you? Or only for you, how you see this feature

**Comment by Red6785** [comment]
Either works to be honest. I think that if doable, it should hide for everyone. Possibly have rendering backpacks be in the config?

**Comment by Tiviacz1337** [comment]
I'll add config option to disable all backpack renderings for player. It means that neither you nor anyone will have visible backpack from your client if option is set to true. Does it satisfy you?
