### ISSUE TITLE
Backpack cannot be used in server

### ISSUE THREAD

**Issue by GezaRamadhani01** [Tiviacz1337/Travelers-Backpack#523]
Hello, I can't use the backpack on the server, I suggest this mod is compatible with the server and the bag can be used.

**Comment by Tiviacz1337** [comment]
What do you mean by that? If backpack is installed on client & server it works fine

**Comment by robbenrose** [comment]
I'm having this issue too. 1.19.2 server, I can open the backpack but can't click the equip button in the bottom left of the GUI. It highlights when I mouse over it but doesn't equip, and if I put it in the back curios slot it still won't open when I use the keybind. Double checked the keybinds for any conflicts and there were none.

**Comment by msameer** [comment]
Same here but it's installed simply on a client. Cannot equip it on trinket slot and does not open when I hit 'b'. No keybinding conflicts. 1.19.2

**Comment by Tiviacz1337** [comment]
does the console say something? can you try to /kill and then equip backpack? I can't reproduce this issue by any means

**Comment by msameer** [comment]
I do not see anything in the console

**Comment by robbenrose** [comment]
That worked! Thank you so much!! If possible, maybe have the mod detect
curios and auto-enable the integration?

-Robert
