### ISSUE TITLE
Not able to open backpack inventory on server

### ISSUE THREAD

**Issue by MasterMind1010** [Tiviacz1337/Travelers-Backpack#528]
**I am not able to open backpack inventory on my modded server**
In hand, the backpack inv opens just fine, but when equipped on back slot, it does not open..
Curious integration is on, so backpack goes on the curious back slot
The modlist is 
[
![image](https://user-images.githubusercontent.com/105385697/210634767-c51d4420-9e55-48f3-b4f0-c04058172acd.png)
]

**To Reproduce**
1. Enable curious integration
2. equip backpack on back slot (curious)
3. press the keybind assigned to open backpack

**Expected behavior**
Backpack inventory should open, but does not open

**Required information (please complete the following information):**
 - Mod version:  1.16.5-5.4.24
- Mod Loader: Forge

**Additional context**
Keybinds are not clashing, yet it isnt opening, curious integration is also turned on on the server
Im using aternos server...

**Comment by Tiviacz1337** [comment]
can you try without xaeros minimap?

**Comment by MasterMind1010** [comment]
There was a problem in the configuration of the mod, fixed it..
Thnx for your time and awesome mod!
