### ISSUE TITLE
Cannot Equip Backpack (Until After Death) After Sleeping In Sleeping Bag

### ISSUE THREAD

**Issue by ereese99** [Tiviacz1337/Travelers-Backpack#529]
**Describe the bug**
Check the description

**To Reproduce**
1. Make sure the backpack has a sleeping bag
2. Place the backpack
3. Sleep
4. Try to re-equip the backpack
5. Fail
6. Kill yourself
7. Equip a backpack as normal

**Expected behavior**
I expect the backpack to be unequipable after sleeping in the sleeping bag until after a player death happens

**Required informations (please complete the following information):**
 - Mod version: 1.19.2 - 8.2.10
- Mod Loader: Fabric

**Comment by LoAlCo** [comment]
This same issue happened to me. Killing my player allowed me to equip the backpack on my back again.
I am on forge 1.19.2. Version 8.3.4 of the mod
I have a lot of mods installed, around 140-ish so it could be caused by any one of those mods
