### ISSUE TITLE
Can't use backpack after a while

### ISSUE THREAD

**Issue by ButtMan2016** [Tiviacz1337/Travelers-Backpack#530]
I don't really know if it is random or when traveling worlds but after a while the backpack become unusable.
Pressing B does nothing anymore. Dying, picking up the backpack then right clicking also does nothing.
Right clicking when the backpack is on the ground does nothing. But you still can put it on your back.
The abilities still work tho even if the backpack is unusable.
If you quit the game and log back in it's still not working.
But crafting a new one works.

To Reproduce:
It' seems to be random after a while or when traveling worlds.
(It happened to me twice and it was after 2 or 3 days of playing about 3-8h each days.)

 - Mod version: 1.19.2-8.2.11
- Mod Loader: Forge 43.1.53 and 43.2.1

**Comment by Tiviacz1337** [comment]
is there any error in console?

**Comment by ButtMan2016** [comment]
no errors at all

**Comment by DarkPhoenixSw** [comment]
Hello, the same error happens to me but I discovered a way to recover the items in the backpack. If you place a chest, a hopper and the backpack on top, the objects will be transferred, although I think not all of them will be transferred. Like this:
![Captura de pantalla 2023-01-21 114917](https://user-images.githubusercontent.com/123253125/213872245-e47823f1-3c3a-4660-b027-40109a9f5907.png)

**Comment by Tiviacz1337** [comment]
> Hello, the same error happens to me but I discovered a way to recover the items in the backpack. If you place a chest, a hopper and the backpack on top, the objects will be transferred, although I think not all of them will be transferred. Like this: ![Captura de pantalla 2023-01-21 114917](https://user-images.githubusercontent.com/123253125/213872245-e47823f1-3c3a-4660-b027-40109a9f5907.png)

No logs in console for you too?

**Comment by sucoec** [comment]
I have a problem with the mod, 3 or 4 days ago it worked perfectly, today when I play again the backpack shows me as if it was equipped with the items that were inside but now I can not retrieve the items or see the backpack.
![image](https://user-images.githubusercontent.com/78398833/214175337-7b830249-d7ec-4fdd-9c93-293f28f8590c.png)

**Comment by Tiviacz1337** [comment]
but it's not my mod I guess? I didn't made this backpack mod on screenshot

**Comment by ButtMan2016** [comment]
this backpack icon can be added from the curio slot + a ui mod? maybe. but anyway i still have the issue with your backpack. thanks to @DarkPhoenixSw for the trick i never thought about that and i play with tech mods xD

**Comment by Tiviacz1337** [comment]
Does backpack work after extracting items via hopper?

**Comment by TR27XD** [comment]
> I don't really know if it is random or when traveling worlds but after a while the backpack become unusable. Pressing B does nothing anymore. Dying, picking up the backpack then right clicking also does nothing. Right clicking when the backpack is on the ground does nothing. But you still can put it on your back. The abilities still work tho even if the backpack is unusable. If you quit the game and log back in it's still not working. But crafting a new one works.
> 
> To Reproduce: It' seems to be random after a while or when traveling worlds. (It happened to me twice and it was after 2 or 3 days of playing about 3-8h each days.)
> 
> * Mod version: 1.19.2-8.2.11
> * Mod Loader: Forge 43.1.53 and 43.2.1

Same thing happened to me, on a Minecraft 1.19.2 forge server 43.2.4. 
By dying I took my backpack out. I opened it on my hand and i tried to take out some items but this caused a server crash. I restarted the server and then used a hopper to take out the items. 
I tried equipping different backpacks but I still couldn't open them after I equipped them. My friend is still able to use backpacks normally. I attached the crash report. Hope this helps
[crash-2023-01-30_11.52.27-server.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/10550015/crash-2023-01-30_11.52.27-server.txt)

**Comment by Tiviacz1337** [comment]
Thanks for crash log, I know what's the issue, it'll be fixed in the next update

**Comment by Tiviacz1337** [comment]
> > I don't really know if it is random or when traveling worlds but after a while the backpack become unusable. Pressing B does nothing anymore. Dying, picking up the backpack then right clicking also does nothing. Right clicking when the backpack is on the ground does nothing. But you still can put it on your back. The abilities still work tho even if the backpack is unusable. If you quit the game and log back in it's still not working. But crafting a new one works.
> > To Reproduce: It' seems to be random after a while or when traveling worlds. (It happened to me twice and it was after 2 or 3 days of playing about 3-8h each days.)
> > 
> > * Mod version: 1.19.2-8.2.11
> > * Mod Loader: Forge 43.1.53 and 43.2.1
> 
> Same thing happened to me, on a Minecraft 1.19.2 forge server 43.2.4. By dying I took my backpack out. I opened it on my hand and i tried to take out some items but this caused a server crash. I restarted the server and then used a hopper to take out the items. I tried equipping different backpacks but I still couldn't open them after I equipped them. My friend is still able to use backpacks normally. I attached the crash report. Hope this helps [crash-2023-01-30_11.52.27-server.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/10550015/crash-2023-01-30_11.52.27-server.txt)

Also my question, do you use trinkets integration?

**Comment by TR27XD** [comment]
no, im not using trinkets
