### ISSUE TITLE
Backpack disappeared on death

### ISSUE THREAD

**Issue by SampsterBee** [Tiviacz1337/Travelers-Backpack#533]
I was playing on a single player map, and then I died to a creeper on a hill and when I respawned my backpack wasn't were the cords were saying it was. I wish I had a screenshot but the game crashed I think to other reasons and I couldn't find the crash log. But here's where it said it should be and I think it wasn't there because it was supposed to be on block above the one I'm looking at which might have gotten blown up by the creeper so it had no where to go? I'm not sure but I can't find it anywhere :( 

![2023-01-22_20 16 20](https://user-images.githubusercontent.com/123346657/213965858-1d6a3a1e-ce29-458e-ab03-4e8f9a7bfc90.png)

I'm playing on 1.19.2 on Fabric and using travelers-backpack-1.19.2-8.2.10 file download

**Comment by Tiviacz1337** [comment]
If you could give me the exact steps how to recreate this issue, I'd be glad

**Comment by SampsterBee** [comment]
> If you could give me the exact steps how to recreate this issue, I'd be glad

Yes of course, I was on the side of this hill like halfway on a block when a creeper blew on me while I was not touching the keyboard. My body flew down the hill and the death spot is I believe where my body landed, But just the block that it counted as my death spot was blown up by the creeper. I'm assuming because spot it told me it would be in chat no longer was there it didn't know where to put the bag or something? I'm not very smart so I think thats what happened haha.

The most important thing about recreating it was that I was at the top of the hill and the creeper came from behind me but on level ground with me and pushed me down while blowing up the area it counted my death at. I hope that make sense or helps

**Comment by Tiviacz1337** [comment]
Does backpack disapear everytime creeper kills you like that?

**Comment by SampsterBee** [comment]
No it was just that time I died to a bunch of creepers but my backpack was always still there when I got back

**Comment by Tiviacz1337** [comment]
Should be fixed in the upcoming update

**Comment by SampsterBee** [comment]
Okie :3

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
I've discovered strange bug which caused to destroy backpack if creeper kills player. 
This update removes backpack from affected blocks list after explosion, so no explosion can destroy backpack ever
