### ISSUE TITLE
Backpack UI Buttons are way too loud.

### ISSUE THREAD

**Issue by TheAyes** [Tiviacz1337/Travelers-Backpack#534]
**Describe the bug**
Buttons sounds in the Backpack UI are very loud. I assume the loudness of these sounds isn't affected by the games volume sliders.

**Expected behavior**
Sounds become more quiet if I turn down the volume.

**Required informations:**
 - Mod version: 1.19.2-8.2.10
- Mod Loader: Quilt Loader 0.17.8

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
Reduced button volume to match default minecraft button sound
sound is affected by master volume slider
