### ISSUE TITLE
Backpack Abilities Not Working on Medieval Minecraft Modpack [Fabric]

### ISSUE THREAD

**Issue by SparcleeLasagnia** [Tiviacz1337/Travelers-Backpack#536]
**Describe the bug**
I have not been able to use either the squid or the bat backpack abilities. I don't see any of the GUI buttons listed on the mod page, nor can I find a button that can activate the abilities.

**Required informations (please complete the following information):**
 - Mod version: travelers-backpack-1.19.2-8.2.9.jar
- Mod Loader: Fabric

**Additional context**
I'm wondering if the other inventory sorting GUI from the modpack is removing the ones for the backpack?

**Comment by Tiviacz1337** [comment]
Does medieval minecraft use changed gui texture?
