### ISSUE TITLE
Going to release update for 1.20 instead?

### ISSUE THREAD

**Issue by darkwiz666** [Tiviacz1337/Travelers-Backpack#537]
It's been somewhat recent since the last update, but it supports 1.19.2 and doesn't seem to work on 1.19.3. I assume you guys are just going to work on updating it when 1.20 launches?

**Comment by Tiviacz1337** [comment]
The mod will get 1.19.3 release too

**Comment by Tiviacz1337** [comment]
1.19.3 is available for Forge & Fabric
