### ISSUE TITLE
bug occurs with carry on mode

### ISSUE THREAD

**Issue by Rogenar** [Tiviacz1337/Travelers-Backpack#539]
Sneak into the hidden backpack with the carry mod installed+ When I right-click, the bag appears to be on my back, but he's carrying the bag on his lap. the bag is showing on my back but the bag is visible on my back but the bag does not open and the bag is not worn until I die.

**Comment by Tiviacz1337** [comment]
any more information? mod version game version modloader

**Comment by Rogenar** [comment]
fabric 1.19.3 0.14.13, travelers-backpack-1.19.3-8.3.0, carryon-fabric-1.19.3-2.0.4.15

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric
https://modrinth.com/mod/travelersbackpack
Fixed
