### ISSUE TITLE
Crash on Start with new Update 1.19.2

### ISSUE THREAD

**Issue by suerion** [Tiviacz1337/Travelers-Backpack#541]
**Describe the bug**
Bug Crash the Server on Startup

**To Reproduce**
Start Server with Update from yesterday

**Expected behavior**

**Required informations (please complete the following information):**
 - Mod version: 1.19.2
- Mod Loader: Fabric

---- Minecraft Crash Report ----
Crash Log:
https://pastebin.com/MkqaR6cT

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all fixed in latest update
