### ISSUE TITLE
Abilities config is set to true on serverconfig but doesnt work (1.19)

### ISSUE THREAD

**Issue by CeZerTyui** [Tiviacz1337/Travelers-Backpack#542]
- Mod version: TravelersBackpack-1.19-8.0.8.jar
- Mod Loader:  Forge
![picofproblem](https://user-images.githubusercontent.com/109993782/216783731-2639c8b3-c316-4cb2-9228-73e781e5fa4c.PNG)
in game it still says disabled
But the server config says its true
`
#Server config settings
[server]
	toolSlotsAcceptSwords = true
	disableCrafting = false
	#Enables wearing backpack directly from ground
	enableBackpackBlockWearable = true
	#Backpack immune to any damage source (lava, fire), can't be destroyed, never disappears as floating item
	invulnerableBackpack = true
	enableBackpackAbilities = true
	#Range: > 250
	tanksCapacity = 4000

`

**Comment by CeZerTyui** [comment]
Edit: Apparently they do work, it just shows that its disabled

**Comment by Tiviacz1337** [comment]
1.19 is not supported
