### ISSUE TITLE
I put backpack on back and can no longer access

### ISSUE THREAD

**Issue by Mickymoo9** [Tiviacz1337/Travelers-Backpack#543]
I hit the button to place the backpack on back and cannot open it with the B button i assigned to open it.
It is not on any pieces of armor or garments.

**To Reproduce**
1. Pushing the eqiup button on the left

**Expected behavior**
Visibly see the backpack on your back but unable to open it

**Required informations (please complete the following information):**
 - Mod version: [For example: 1.16.4 - 5.3.7] I am running on fabric with the all the fabric 6 pack

**Comment by Tiviacz1337** [comment]
try using other keybind
