### ISSUE TITLE
Crash when right clicking on backpack.

### ISSUE THREAD

**Issue by KostromDan** [Tiviacz1337/Travelers-Backpack#545]
**Describe the bug**
Crash when right clicking on backpack. Maybe cause because i have 2 curio slots for back.
Also another crash caused backpacks, but i think it multimine error. https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/466

[crash-2023-02-10_08.57.12-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/10704165/crash-2023-02-10_08.57.12-client.txt)
[latest.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/10704166/latest.log)

**Comment by Tiviacz1337** [comment]
Do you play on server? 
Do you have curiosIntegration enabled on both server & client?

**Comment by KostromDan** [comment]
It's single player.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack
Should be fixed in latest update
