### ISSUE TITLE
HUD doesn't render when RPG-HUD is installed

### ISSUE THREAD

**Issue by MrRedstoneA1** [Tiviacz1337/Travelers-Backpack#546]
The tank HUD doesn't render when RPG-HUD is enabled. Only way to get it to render again is to set RPG-HUD mode to Vanilla, but that defeats the whole purpose of using RPG-HUD.

Traveler's Backpack 1.12.2-1.0.35
RPG-HUD 1.12.2-3.8.1

I'm hoping bug fixes can still be done for 1.12.2 since there are still many players who use it and we don't have other options. Some mods won't ever be updated to newer versions.

**Comment by Tiviacz1337** [comment]
Sorry, 1.12.2 is not supported/not getting bug fixes. Traveler's Backpack Overlay is not a big deal though

**Comment by MrRedstoneA1** [comment]
Damn, that's unfortunate. It's difficult to keep track of which tank is selected without the overlay, but at least I can use the hose tooltip to check.
