### ISSUE TITLE
not work on servers,

### ISSUE THREAD

**Issue by Agartha95** [Tiviacz1337/Travelers-Backpack#547]
The new update does not work on servers, the previous one does

**Comment by Tiviacz1337** [comment]
version?

**Comment by Agartha95** [comment]
> ¿versión?

New 1.18.2 update

**Comment by Tiviacz1337** [comment]
Whats the error?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
Fixed in latest version
