### ISSUE TITLE
Shulker enabling option in config file

### ISSUE THREAD

**Issue by doks91** [Tiviacz1337/Travelers-Backpack#548]
Can you put option in config file to enable putting shulker boxes inside backpack.

**Comment by Mburgoso** [comment]
Prueba cambiándole la etiqueta la a shulker. Si lo que detecta es el nombre de "minecraft:shulker_box" no se podría a menos que averigues como cambiarle el nombre. (De casualidad sabes si se puede mantener la mochila al morir.) ¿Hay alguna manera?

**Comment by deadtoxaris** [comment]
> Prueba cambiándole la etiqueta la a shulker. Si lo que detecta es el nombre de "minecraft:shulker_box" no se podría a menos que averigues como cambiarle el nombre. (De casualidad sabes si se puede mantener la mochila al morir.) ¿Hay alguna manera?

you can download mod like "You're in Grave Danger" and everything will be put into a grave where you died and it will send coordinates of gave to chat. also if you die in void, all of your stuff will be saved

**Comment by deadtoxaris** [comment]
> Can you put option in config file to enable putting shulker boxes inside backpack.

smrdis
:)

**Comment by Tiviacz1337** [comment]
Won't do, causes infinite storage
