### ISSUE TITLE
Backpack rolls back to old inventory

### ISSUE THREAD

**Issue by Myddrim** [Tiviacz1337/Travelers-Backpack#549]
**Describe the bug**
After mining, I've cleared my loots and leave my essentials and valuables in my backpack. When I log out of the server and return again, all the items were gone or "rolled back". This also created a lot of duplicated items too. 

**To Reproduce**
1. Logging out the server
2. Re-enter the server and look into the backpack

**Expected behavior**
I want my backpack to keep the updated inventory.

**Screenshots**
-nil-

**Required informations (please complete the following information):**
 - Mod version: 1.19.2 - 8.2.13
- Mod Loader: Fabric

**Additional context**
-nil-

**Comment by Tiviacz1337** [comment]
Do you use trinkets integration?

**Comment by Myddrim** [comment]
Yes, I do have Trinkets installed in the server. Also, my tools are slowly disappearing too. Everytime I log off, or the server resets, something will disappear. I have gone into Creative to cheat my tools back multiple times as well.

**Comment by kangming06** [comment]
I also encountered this problem in 1.18.2.

**Comment by Tiviacz1337** [comment]
> I also encountered this problem in 1.18.2.

Trinkets integration enabled too?

**Comment by kangming06** [comment]
> > I also encountered this problem in 1.18.2.
> 
> Trinkets integration enabled too?

yes

**Comment by Tiviacz1337** [comment]
Okay, I've noticed that items that have been shift clicked into backpack dissapear

**Comment by Tiviacz1337** [comment]
Okay, I've probably found the soultion, fix will be available in next update

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all fixed

**Comment by Myddrim** [comment]
Yes, I'm using trinkets integration. I see that the latest version probably
solved it and will give it a shot. Since I've am using ender pouches now, I
don't risk losing my tools so I've not been tracking the losses of common
decorative blocks count.



Best Regards,
Milton Lai
