### ISSUE TITLE
Items Lost

### ISSUE THREAD

**Issue by serkanyersen** [Tiviacz1337/Travelers-Backpack#552]
**Describe the bug**
I crafted a backpack just for Create items. I was arranging and creating memory slots, to test the new memory slots I clicked the arrow button to move the items to my inventory then back to backpack. I did this 1-2 times then I realized bunch of items are missing. before I stop I lost more than half the contents in the backpack :/

**To Reproduce**
Not sure if will repro, but I'll describe what I had
1. have one backpack on you
2. have you inventory half full with different items.
3. create a new backpack
4. but items in it, have multiple stack of the same items
5. arrange them in the back pack and create memory slots for these items
6. use arrows to move them to your inventory
7. use up arrow to move them back
8. sort the backpack
9. do 6,7,8 few more times.
10. items are lost

all items I had in the backpack were create stuff, iron sheets, gold sheets, shafts, cogs, all gone.

**Expected behavior**
backback should not lose items no matter what.

**Screenshots**

**Required informations (please complete the following information):**
 - Mod version: 1.19.2 - 8.2.12
- Mod Loader: Quilt 1.18.1-beta.25

**Additional context**
Add any other context about the problem here. it's possible this is a much more common problem. I keep misplacing items somehow. things I'm sure I had were nowhere to be found. maybe this was the reason. hard to say.

**Comment by Tiviacz1337** [comment]
Could you record the video to reproduce the issue?

**Comment by serkanyersen** [comment]
Thank you for a quick answer. Repro'd in creative mode.

https://user-images.githubusercontent.com/30582/219969011-3ebc0404-a5c0-488a-b564-9ae4105341ba.mp4


This clearly demonstrates the issue. you can see the items disappearing when there is not enough space. both from the backpack and from the inventory. compare the first frame and the last frame.

I suggest disabling this feature if there is no immediate fix, hours of progress was lost :/

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all fixed
