### ISSUE TITLE
language update zh_cn.json for 1.19.2

### ISSUE THREAD

**Issue by WadjetSama** [Tiviacz1337/Travelers-Backpack#553]
[zh_cn.zip](https://github.com/Tiviacz1337/Travelers-Backpack/files/10778923/zh_cn.zip)

**Comment by Tiviacz1337** [comment]
Lang file is missing few entries, look up on latest en_us json and I'll update

**Comment by WadjetSama** [comment]
[zh_cn.zip](https://github.com/Tiviacz1337/Travelers-Backpack/files/10920147/zh_cn.zip)
Now it's all done.

**Comment by Tiviacz1337** [comment]
Updated on Forge
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all for fabric
