### ISSUE TITLE
[Crash] Crash when doing something?

### ISSUE THREAD

**Issue by Catomax262** [Tiviacz1337/Travelers-Backpack#554]
**Describe the bug**
It crashed when i fiddled around with the sort slot thingies.

**To Reproduce**
1. Click the settings button
2. Enter the sorting settings
3. Fiddle around?
4. Boom, crash!

**Expected behavior**
Not crashing!

**Screenshots**
n/a

**Required informations (please complete the following information):**
 - Mod version: 1.18.2 - 7.1.25
- Mod Loader: Forge

**Additional context**
crash log: https://crashy.net/6738d7a8-b593-404d-9ee1-e6ea38198070
I can't give a clear reproduction, it was unexpected.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack
Fixed
