### ISSUE TITLE
Crafting module sometimes breaks and crafts brown dye for every item when an extra NBT tag is stored into the backpack

### ISSUE THREAD

**Issue by Frontear** [Tiviacz1337/Travelers-Backpack#556]
**Describe the bug**
Playing MedievalMC, noticing that every so often the backpack can break and obtain an extra NBT tag `SleepingBagColor: 0`. Although it doesn't seem like it should do anything, it completely breaks crafting. Putting any item into the crafting table consumes it to craft brown dye, why brown dye I have no idea. This issue can be completely fixed by _REMOVING_ the previously mentioned NBT tag.

**To Reproduce**
No consistent manner of reproduction, just that an NBT tag is added somehow through playing through the modpack.

**Expected behavior**
Regardless of the NBT tag being there, it shouldn't break crafting entirely.

**Screenshots**
Can attach later if necessary

**Required informations (please complete the following information):**
 - Mod version: 1.19.2-8.2.13
- Mod Loader: Fabric

**Additional context**
Normal backpacks dont seem to have the previous NBT tag, whereas bugged backpacks do. It seems strange given the NBT label should indicate its part of a standard travellers backpack, but its not.

**Comment by Tiviacz1337** [comment]
Could you record the video of bugged crafting

**Comment by ChheungS** [comment]
Hey, not the original poster but I had the same issue. I'm also playing MedievalMC version 18.5 Fabric edition. If you need more information let me know.

https://www.youtube.com/watch?v=WQBxTF0Plws

**Comment by Tiviacz1337** [comment]
So basically, putting any item in crafting grid makes brown dye?

**Comment by Tiviacz1337** [comment]
I just downloaded Medieval MC 19.5 and can't reproduce the issue

**Comment by ChheungS** [comment]
I updated the modpack to v19.5 and also couldn't reproduce it. Would definitely not recommend playing on v18.5

**Comment by Tiviacz1337** [comment]
Seems it was something wrong with modpack itself, anyways fixed - update medieval mc
