### ISSUE TITLE
Craft Dupli 1.19.2 Fabric

### ISSUE THREAD

**Issue by GrisKillPR** [Tiviacz1337/Travelers-Backpack#559]
Sorry for bad english

With my friend we can dupli stuff in crafting table of a backpack

To Reproduce :
https://www.youtube.com/watch?v=3-gQjhHx-qg
Just craft anithing and let your friend take the item after he take it you can take an other

And this is duplicated

- Fabric 1.19.2 0.14.14
- Traveler's Backpack 1.19.2 8.2.14
- Fabric API 0.75.1 1.19.2
- Cloth Config 8.2.88
- Cardinal Components API 5.0.2

Im verry sorry for bad english

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
