### ISSUE TITLE
[1.16.5]Traveler's Backpack clashes with Pixelmon

### ISSUE THREAD

**Issue by yuankun1** [Tiviacz1337/Travelers-Backpack#561]
**Describe the bug**
null
**To Reproduce**
1.Wear a backpack
2. Two mods together at the same time will cause the backpack worn to disappear

**Expected behavior**

**Screenshots**

**Required informations (please complete the following information):**
1.16.5 forge
- TravelersBackpack-1.16.5-5.4.30
- Pixelmon-1.16.5-9.1.3-universal
**Additional context**
When I press the B button, I still open my backpack

**Comment by Tiviacz1337** [comment]
Pixelmon replaces player renderer completely, I can't do anything about it. Wont fix
