### ISSUE TITLE
Textures are in the wrong place and not sure what's causing it.

### ISSUE THREAD

**Issue by saditude** [Tiviacz1337/Travelers-Backpack#563]
For my friend, the orange bed is a white bed, and so on. Every crafting recipie says it's actually the item to the right of it, but for my friend it's normal.
![image](https://user-images.githubusercontent.com/109985547/223602591-e46d6886-a789-4fbe-8d68-629da42c20d4.png)
![image](https://user-images.githubusercontent.com/109985547/223602749-79099a15-88cf-40f6-bae2-59e43271eb9c.png)
![image](https://user-images.githubusercontent.com/109985547/223602770-0b859237-103d-4a9d-beae-43ccdfe4f3e7.png)

**Comment by Tiviacz1337** [comment]
What mod version do you use?

**Comment by saditude** [comment]
1.19.3? I'll have to check when I get home.

**Comment by Tiviacz1337** [comment]
I don't know tell me the mod version first, so I could check that

**Comment by saditude** [comment]
1.19.3-8.3.3

**Comment by Tiviacz1337** [comment]
There must be some id's error, I don't know maybe try removing Traveler's Backpack completely then add it again.

**Comment by saditude** [comment]
It's not working. I'm going to try switching to Fabric instead of Quilt and see if that works.

**Comment by saditude** [comment]
Changing to fabric fixed it.
