### ISSUE TITLE
CRASH placing sleeping bag

### ISSUE THREAD

**Issue by FlipperCargo368** [Tiviacz1337/Travelers-Backpack#565]
TravelersBackpack-1.19.2-8.2.16.jar

I place a sleeping bag then the game crashes and gives me this message.

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "com.tiviacz.travelersbackpack.blockentity.TravelersBackpackBlockEntity.getSleepingBagColor()" because "blockEntity" is null

If you need to see grab any sleeping bag, shift click , then crash.

**Comment by FlipperCargo368** [comment]
Weirdly if you use setblock and or place it using backpack it works. It only crashes if placed by hand.

**Comment by Tiviacz1337** [comment]
Sleeping bag can't be placed via item, only by backpack, I'll fix that

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack
Fixed
