### ISSUE TITLE
my backpakc Disappear's : FORGE: 118.2

### ISSUE THREAD

**Issue by Gismov2** [Tiviacz1337/Travelers-Backpack#566]
when ever i wear my backpack it will Disappear if i log out or after some time i think and i cant go into it and when i try and put a new one on it says i already got one on

![image](https://user-images.githubusercontent.com/116737473/224423954-fcfd2314-6a8f-4df8-b596-babfa2bc8f28.png)

**Comment by Tiviacz1337** [comment]
mod version

**Comment by Gismov2** [comment]
> mod version

1.18.2

**Comment by Gismov2** [comment]
ah mb heres sceen shot
![image](https://user-images.githubusercontent.com/116737473/225101670-0a3c7011-5498-41ad-9de5-f12941b87e7f.png)

**Comment by Tiviacz1337** [comment]
Do you know exact opportunity when backpack dissapeared? Also, can you open inventory of backpack?

**Comment by Gismov2** [comment]
> Do you know exact opportunity when backpack dissapeared? Also, can you open inventory of backpack?

i can not open it and it happends when ever you go in and out of the server and like i could have my backpack on and then when i would relog in it would be gone off my back and i couldent open and i would have to kms to get it to spawn on the ground to derfore pick it up

**Comment by Tiviacz1337** [comment]
Do you play with other mods?

**Comment by Gismov2** [comment]
yes, do you want a list?

**Comment by Gismov2** [comment]
> Do you play with other mods?

yea do you want a list?

**Comment by Gismov2** [comment]
> what forge version do you use?
![image](https://user-images.githubusercontent.com/116737473/225120853-e898a334-10e8-4efb-a78c-295aa3b68148.png)
there you go

**Comment by Tiviacz1337** [comment]
do you have trinkets integartion enabled?

**Comment by Gismov2** [comment]
> do you have trinkets integartion enabled?

as a mod or what is that?

**Comment by Gismov2** [comment]
i dont qhite understand

**Comment by Tiviacz1337** [comment]
do you use curios as mod?

**Comment by Gismov2** [comment]
> do you use curios as mod?

no

**Comment by Gismov2** [comment]
is that why it doesent work?

**Comment by Tiviacz1337** [comment]
It's probably compatibility issue, is it possible for you to check with only tb installed if bug occurs

**Comment by Gismov2** [comment]
> It's probably compatibility issue, is it possible for you to check with only tb installed if bug occurs

so i think i fixed it i was just useing an older version on the server i was playing on and i am sorry for wasting your time
