### ISSUE TITLE
Crash with FTB Chunks with latest version.

### ISSUE THREAD

**Issue by Poke097** [Tiviacz1337/Travelers-Backpack#567]
**Mod Loader: Fabric 0.14.17
MC Version: 1.19.2
Launcher: Curseforge Launcher**

**1. Describe the bug** 

When updating to the latest version of Traveler's Backpack, it causes a crash with FTB Chunks on start-up.

It seems to be this mixin:
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector getOtherEntities(Lnet/minecraft/class_1937;Lnet/minecraft/class_1297;Lnet/minecraft/class_238;)Ljava/util/List; in travelersbackpack.mixins.json:ExplosionMixin from mod travelersbackpack failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap travelers-backpack-refmap.json`

**2. Write steps to reproduce the bug**

1. Update Traveler's Backpack
2. Install FTB Chunks
3. Crash on start-up

**3. What is expected behaviour** 

To not crash with FTB chunks which is odd.

**4, Crash Logs**
https://mclo.gs/68TJxDO

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
