### ISSUE TITLE
Problem when someone change mode to auto sort/lock

### ISSUE THREAD

**Issue by AviationTwelve** [Tiviacz1337/Travelers-Backpack#568]
[crash-2023-03-20_01.25.12-server.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/11013029/crash-2023-03-20_01.25.12-server.txt)
![image](https://user-images.githubusercontent.com/94953287/226228579-d35d7de4-7374-43a9-bf7e-953c59b32443.png)

**Comment by Tiviacz1337** [comment]
fixed in latest mod version 1.19.2-8.2.18
