### ISSUE TITLE
Backpack stuck on character, cannot access, cannot remove.

### ISSUE THREAD

**Issue by jsftv** [Tiviacz1337/Travelers-Backpack#569]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 1.19.2 
Modloader Version 0.13.17
All of Fabric 6 1.5.0

1. Describe the bug 

Traveler's backpack appears on character. I cannot access the contents of the backpack and I can't remove the backpack. I've tried /kill, changing keybinds, reloading into the server, and restarting the server. The tank GUI shows in the bottom right, but the backpack doesn't appear in the backpack slot.

2. Write steps to reproduce the bug
 - Have a backpack equipped already
 - Open Traveler's backpack
 - Click the equip button in the bottom left

4. What is expected behaviour 

To be able to remove the backpack?

5. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Update traveler's Backapck to latest version which is 1.19.2-8.2.16 and check if issue still occurs, if so - reopen

**Comment by Aliochah** [comment]
Hello, I have this issues, I have updated the mod to the lastest version, nothing seems to changes.
