### ISSUE TITLE
Make crafting slots inaccessible unless you manualy put items in it

### ISSUE THREAD

**Issue by beefufo** [Tiviacz1337/Travelers-Backpack#570]
Would be nice! I really wish the mod restricted me from auto dragging all my inventory items into the backpack just to fill up the crafting slots in the end. (tbf my issue was initially the fact that using any other inventory sorting mod it would sort items and put them, as if on purpose, in all of the available brown crafting slots FIRST, which I thought was hilarious because out of all slots these ones I need clear at all times)

**Comment by beefufo** [comment]
So like, the only time you are able to use brown slots is if you click on an item, and put it in, so shift clicking on items from the original inventory ignores the brown slots!

**Comment by Tiviacz1337** [comment]
but shift clciking from orginal inventory put items in backpack blue slots first

**Comment by beefufo** [comment]
Yes, but what I mean is not letting crafting slots ever be shift+click accesible, like when you just want to blindly quickly shift click all transferrable items to the backpack and not worrying about thinking how much you gotta shift click until you also fill up crafting slots

**Comment by Tiviacz1337** [comment]
Wont add
