### ISSUE TITLE
SERVER CRASHED LAST NIGHT THIS IS THE LOG

### ISSUE THREAD

**Issue by breeece** [Tiviacz1337/Travelers-Backpack#571]
0. FORGE 44.1  
MC 1.19.3

1. SERVER CRASHED WHILE I WAS ASLEEP.

2. NOT SURE 

3. EXPECTED BEHAVIOR IS THAT THE SERVER SHOULD RUN FINE

4. NO SCREENSHOTS AVAILABLE AT THE MOMENT. I WILL ATTACH ALL SERVER LOGS. 

[crash-2023-03-22_04.34.43-server.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/11045964/crash-2023-03-22_04.34.43-server.txt)

[crash-2023-03-22_04.35.45-server.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/11045966/crash-2023-03-22_04.35.45-server.txt)

**Comment by Tiviacz1337** [comment]
Update to latest version for 1.19.3 if issue still occurs reopen
