### ISSUE TITLE
Dupe Glitch

### ISSUE THREAD

**Issue by ereese99** [Tiviacz1337/Travelers-Backpack#572]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric
1.19.2 - 0.4.18

1. Describe the bug 

Items get duped when swapping backpack equipped with the exact same type of backpack (e.g. bat backpack for bat backpack)
The one youre putting on gets the items that are currently in your backpack duped into it

2. Write steps to reproduce the bug

Wear a backpack of any variant
Go into your inventory and pick up a backpack of the same variant, and swap it with the one you have on 
Put the other backpack that's in your inventory on the ground
See that it has the same items

3. What is expected behaviour 

Items will be duped

**Comment by ereese99** [comment]
Mod version 8.2.17

**Comment by ereese99** [comment]
8.2.19 is not available on Fabric 1.19.2

**Comment by RatherChaotic** [comment]
Could you post a video of this dupe? I can't seem to replicate it
