### ISSUE TITLE
Back pack bug

### ISSUE THREAD

**Issue by SirDante94** [Tiviacz1337/Travelers-Backpack#573]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
1.18.2-Forge-40.2.1  TravelersBackpack-1.18.2-7.1.28 

1. Describe the bug 
When we disconnect from the server with the backpack equipped disappears, we can´t access the inventory of the backpack and when we try to equip another one says that we have one equipped.

2. Write steps to reproduce the bug

Equip a backpack, disconect and enter again we dont know if is a problem with the server or the mod

3. What is expected behaviour 

We want to see the backpack when
we reconnect to the server and use it normally

4. Screenshots (If applicable)
![2023-03-25_19 17 42](https://user-images.githubusercontent.com/128936576/227750095-5e6a0f1c-bd09-403d-a96a-15157aa6d5f7.png)
![2023-03-25_19 17 45](https://user-images.githubusercontent.com/128936576/227750096-f61e15bb-c542-429b-b456-48e72823d939.png)
![2023-03-25_19 17 46](https://user-images.githubusercontent.com/128936576/227750097-9edb8d56-86d0-482d-a524-8234d4514394.png)
![2023-03-25_19 18 32](https://user-images.githubusercontent.com/128936576/227750098-2bf67e2e-af84-45db-ac31-3742155b2fce.png)

**Comment by Tiviacz1337** [comment]
Check if issue occurs with tb installed only

**Comment by SirDante94** [comment]
I tried only with tb and also install one by one the mods, I had no problems in one player but in the server the error keeps happening IDK what is happening and causing this problem

**Comment by Tiviacz1337** [comment]
even with only tb installed, the issue occured on server?

**Comment by Kingxrs** [comment]
> I know that you may not even be playing the game but the reason it happens on servers is because of the /skin plugin, the backpack being in the back of your character bugs out whenever the skin changes (this happens when you're a premium account and a non-premium server is using /skin plugin as it has to first load the default skin with the backpack and then the premium one, bugging it out), the only solution I found to make use of the backpack without dying is removing the /skin plugin.

Thank you so much man, i was trying to found a fix to this thing and you got it
