### ISSUE TITLE
Upgrade to support Fabric 1.19.4

### ISSUE THREAD

**Issue by lospejos** [Tiviacz1337/Travelers-Backpack#576]
**Is your feature request related to a problem? Please describe.**
Please upgrade mod to support Fabric 1.19.4

**Describe the solution you'd like**
Mod upgraded to support Fabric 1.19.4

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
