### ISSUE TITLE
Create Structure deletes backpack when dying.

### ISSUE THREAD

**Issue by Schmensch** [Tiviacz1337/Travelers-Backpack#577]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

- Fabric 0.14.18
- Minecraft 1.19.2
- Travelers Backpack 1.19.2-8.2.17
- Create 0.5.0-1.19.2

1. Describe the bug 

When backPackDeathPlace is set to true in the travelersbackpack config, and you are impaled by a moving drill from the create mode (https://github.com/Fabricators-of-Create/Create) the backpack isn't placed where it's supposed to be. The chat message still exists, however at the location there's nothing.

2. Write steps to reproduce the bug

Materials required for a moving drill:
   - Get a creative motor
   - Get a create piston
   - Get a create drill
   - Get a pison pole

Assemble the moving drill:
   - Place the piston
   - Place a number of piston poles behind it
   - Place the drill in front of the drill
   - Place the creative motor next to it

The drill should start moving and dealing damage to everything in front of it. You can change the direction by making the speed of the motor negative.

If stand in front of the drill and die by being impaled by it, the backpack isn't placed anywhere and just dissapears along with all items inside of it. The chat message for it being placed still exists. There is nothing interesting in the chat lot.

3. What is expected behaviour 

The backpack should be placed next to the drill, or if that isn't possible it should be dropped as an item instead.

I guess this is because Create structures prohibit blocks from being placed inside of them, but they aren't blocks themselves. This could lead to Travelers Backpack's thinking there is space to place the backpack when there actually isn't any.

**Comment by Tiviacz1337** [comment]
I just tested it it seems like the backpack is getting placed but it's getting drilled right away

**Comment by Tiviacz1337** [comment]
Fixed for Forge:
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files
https://modrinth.com/mod/travelersbackpack/versions
fabric soon

**Comment by Tiviacz1337** [comment]
Fixed for Fabric:
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
https://modrinth.com/mod/travelersbackpack/versions
