### ISSUE TITLE
Slot reserving not ignoring NBT

### ISSUE THREAD

**Issue by jeytee84** [Tiviacz1337/Travelers-Backpack#579]
AOF6 1.5.1
MC 1.19.2
**8.2.17**

When a slot is reserved to a tool and the duraility changes, the reservation no longer applies.

The reservation should work regardless of durability, or there should be an option to ignore NBT data (probably should be set to ignore by default)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
https://modrinth.com/mod/travelersbackpack/versions
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric
