### ISSUE TITLE
Crash when swimming with Dragon Traveler's Backpack equipped

### ISSUE THREAD

**Issue by Lgmrszd** [Tiviacz1337/Travelers-Backpack#587]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Modloader: Fabric 0.14.19
Mod version: 1.19.2-8.2.18 (but also happened on previous version)
Modpack: All Of Fabric 6 (1.5.3, but also happened in 1.5.2)
1. Describe the bug 
When attempting to swim in water with Dragon Traveler's Backpack equipped and it's ability enabled, the client crashes.

2. Write steps to reproduce the bug
- 1. Equip Dragon Traveler's Backpack
- 2. Enable it's ability
- 3. Jump into the water and swim (double tap W key)

3. What is expected behaviour 
No Crash

Crash log:
https://gist.github.com/Lgmrszd/0323e6521f7edcd96977b467dbc3bfa0

**Comment by Tiviacz1337** [comment]
Fixed
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
https://modrinth.com/mod/travelersbackpack/versions
