### ISSUE TITLE
Request to have the tanks and tools on screen to be hidden or moveable. 

### ISSUE THREAD

**Issue by AbandonedPlayer** [Tiviacz1337/Travelers-Backpack#588]
So my issue is that the GUI in the bottom left is overlapping the GUI for my Meka-Suit (Mekanism) so it makes it hard to read.
![gui issue](https://user-images.githubusercontent.com/128874971/232357917-45aecc9c-3f84-48dc-b7ad-3092fec25d61.png)
If there is a way to make the GUI for the tank and tools either be hidden or moveable to another corner that would be amazing!
The only real spot I could consider putting them is in the bottom left but I'm sure there are other mods that put stuff there so if it could be customizable that would be better for any situation.

**Comment by Tiviacz1337** [comment]
Just check the config file.. there's option to completely disable gui or move it around with coordinates
