### ISSUE TITLE
Mod not showing for 1.19.4

### ISSUE THREAD

**Issue by Ruecookie** [Tiviacz1337/Travelers-Backpack#589]
So basically, the mod will NOT show in the Minecraft mod list when you enter the game. I been wanting to use it but I can't since its not registering, it also seems people have commented on cursed forge about it not working for version 1.19.4, hopefully this is fixed quickly, this is forge btw. It also doesn't crash so I'm not able to provide any way on why it's not showing up for Minecraft itself

![Screenshot 2023-04-17 013915](https://user-images.githubusercontent.com/130807751/232392617-86cfd94b-2f01-45ef-a27b-d464b820f4a4.png)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
Download latest now, it has been replaced
