### ISSUE TITLE
what do i do when it says travalersbackpack failed to load properly?

### ISSUE THREAD

**Issue by Personunavailable** [Tiviacz1337/Travelers-Backpack#591]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

forge 1.19 v8.4.2

1. Describe the bug 

when i load into monecraft it says [mod name] failed to load properly and i cant fiqure it out. and i am hopeing i will get an answer here

**Comment by Tiviacz1337** [comment]
show crash log

**Comment by Personunavailable** [comment]
got it to work
