### ISSUE TITLE
Crashing at opening config tab in Backpack

### ISSUE THREAD

**Issue by AnChedraui** [Tiviacz1337/Travelers-Backpack#594]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Custom modpack, Forge 1.16.5

1. Describe the bug 
It just crashes the game whenever I click in config tab in the backpacks

2. Write steps to reproduce the bug

Opening backpack and clicking on config tab

3. What is expected behaviour 

Just to work normally, i guess?

4. Screenshots (If applicable)

Cant take SS cause insta crash, i can use all the other features in the backpack just cant click on tools button in the backpack
[crash-2023-04-21_22.14.26-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/11300153/crash-2023-04-21_22.14.26-client.txt)

https://pastebin.com/N6ppkR9L

**Comment by Tiviacz1337** [comment]
What language do you use in game

**Comment by AnChedraui** [comment]
Spanish, I really can't understand why the hell does that make it to crash, but actually worked, i Just changed to English and its working perfectly. Thanks.
