### ISSUE TITLE
Game crash upon Shift-Clicking empty bucket into backpack

### ISSUE THREAD

**Issue by TheBloodSwiper** [Tiviacz1337/Travelers-Backpack#595]
**Modpack:** Medieval Minecraft version 1.19.2 (v20.5) - Fabric 0.14.19
**Travelers-Backpack version:** 1.19.2-8.2.18
**Bug:** Shift-clicking empty bucket into backpack crashes my game and generates a crash report. Previous version did not have this problem for me, and happened for the first time right after I updated to most recent version of the modpack.
[crash-2023-04-23_02.12.21-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/11303963/crash-2023-04-23_02.12.21-client.txt)

When I think of it: I did not try other backpack types. This crash occurred when using the Lapiz Backpack, though I don't believe that should really matter, but, just in case, now you know.

**Comment by TheBloodSwiper** [comment]
And it's not a one-time occurrence, as I have 3 logs from 3 attempts. I now drag and drop empty buckets manually.
Other buckets are fine.

**Comment by Tiviacz1337** [comment]
update to 1.19.2-8.2.19

**Comment by TheBloodSwiper** [comment]
Nice, that did the trick.
