### ISSUE TITLE
When deep underground, backpack is placed at y-level 1 on death no matter what level you were at on death

### ISSUE THREAD

**Issue by Landrin201** [Tiviacz1337/Travelers-Backpack#597]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

MC: 1.19.4, forge 45.0.43
Configs: backpackDeathPlace = true, backpackForceDeathPlace = true
The mod is running on a server

1. Describe the bug 
When below y-level 1, I've noticed that when you die with the backpack equipped it will not be placed in the spot where you died; instead, it will be placed at y-level 1. So, if you were at coordinated x100, z100, y-30, then the backpack will be placed at x100, z100, y0. 

2. Write steps to reproduce the bug
Go deep underground, below y-level 1, and /kill

3. What is expected behaviour 
The backpack should be placed where you died

4. Screenshots (If applicable)

**Comment by Landrin201** [comment]
I also am using this gravestone mod: https://www.curseforge.com/minecraft/mc-mods/gravestone-mod

I thought that it may have been a conflict there, so I tested above ground: it works fine with the gravestone mod when above y-1. The backpack successfully gets placed next to the gravestone.

**Comment by Landrin201** [comment]
I found the problem: When void protection is on, the y-level is set to 1. I think you should add to the if statement.

First, check to see if the player is in the End. If they are, and they died below y=0, set temp_y to y=1.
IF the player is not in the end, then set tempY to -64. PErsonally, I'd actually set it higher in this case- if you set it to do, say, -55 then you'd ensure that it can't get placed under bedrock and become unretrievable. 

https://github.com/Tiviacz1337/Travelers-Backpack/blob/4ec081bded1b8c7fc542c148a14fd221748b6cce/src/main/java/com/tiviacz/travelersbackpack/util/BackpackUtils.java#L83

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all fixed
