### ISSUE TITLE
Unable to cycle tools in backpack.

### ISSUE THREAD

**Issue by RenniStuffmin** [Tiviacz1337/Travelers-Backpack#598]
(I'm running the Forge variation of the mod, version 8.4.2.)

As the title suggests, I seem to be unable to cycle between tools in my backpack. I made sure that the tools were in the green slots in my backpack. I've tried both default and custom key bindings.

Steps to Produce Bug:
1.) Have respective mods installed.
2.) Put tools into green slots in backpack.
3.) Attempt to cycle between tools in hand and those in green slots.
4.) Have nothing happen.

Expected Behavior: Tools cycle.

Mods installed, if it helps:
1.) Forge 45.0.49 for MC 1.19.4
2.) OptiFine HD_U_I3
3.) Architecture 8.1.79
4.) Cloth Config 10.0.96
5.) Curios 5.1.4.2
6.) Roughly Enough Items 11.0.597
7.) gigaherz's Tool Belt 1.20.0
8.) Xaero's Minimap 23.4.0
9.) Xaero's World Map 1.30.0
10.) Traveller's Backpack 8.4.2, as mentioned above

Screenies:
![2023-04-28_07 24 07](https://user-images.githubusercontent.com/15113498/235137807-2634e762-dc8f-4f65-a91c-ea66824447da.png)
![2023-04-28_07 24 14](https://user-images.githubusercontent.com/15113498/235137820-79cf6a58-a30a-43f0-958e-afe48e614e6e.png)
![2023-04-28_07 24 29](https://user-images.githubusercontent.com/15113498/235137826-6d02b3d8-92f5-43af-91dc-66f423890ed0.png)
![2023-04-28_07 27 22_edit](https://user-images.githubusercontent.com/15113498/235138847-2537f577-a3f8-46fc-9fe6-ed3858ca67bc.png)

Thanks in advance!
 
EDIT: I'm an idiot lol. I thought the hose tanks were bugged, too, but I just needed to suck up some water with the hose first. Hose tanks are working as intended.

**Comment by Tiviacz1337** [comment]
you have to use scroll to cycle tools, if you want to only click then edit client config

**Comment by RenniStuffmin** [comment]
OK, so I HOLD the swap button/key, then use the scroll wheel. I had used an older version of this mod in the past, and I was able to just click the swap button. I was confused, but thanks for the info!
