### ISSUE TITLE
Suggestion ( MC 1.12.2 )

### ISSUE THREAD

**Issue by Kasia1403** [Tiviacz1337/Travelers-Backpack#599]
To add a configurable button to close backpack ( because pressing ESC in my modpack causes server stop and freezes Minecraft ).

**Comment by Tiviacz1337** [comment]
1.12.2 is not supported

**Comment by Kasia1403** [comment]
@Tiviacz1337 Why 1.12.2 is not supported ? 1.12.2 is my favourite version and my favourite mod Dr Zhark's Mo' Creatures is still not updated past 1.12.2. I don't like that.

**Comment by Tiviacz1337** [comment]
because 1.12 is 6 years old
