### ISSUE TITLE
Travelers Backpack uses more CPU time than any other mod

### ISSUE THREAD

**Issue by gittibene** [Tiviacz1337/Travelers-Backpack#605]
This is on Fabric 1.19.2, Travelers Backpack slows down the game significantly, using between 6 and 18% CPU time, making it the most demanding mod in our modpack. Why?

https://spark.lucko.me/wX1INtnvTY

**Comment by Tiviacz1337** [comment]
where is it visible, i'm not familiar with this site

**Comment by gittibene** [comment]
There's a "mods" button at the top where you can see every mod and it's sub processes and how much CPU time is spent on each one.

**Comment by gittibene** [comment]
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/117588629/60b2896b-b8e6-42a5-8c01-5eec462bcf53)

**Comment by Tiviacz1337** [comment]
well, that's because backpacks has to be rendered with special model, you can reduce this by removing unnecessary backpacks

**Comment by Tiviacz1337** [comment]
I just checked simple hats, they use special models sure, but they are made via json files. Traveler's Backpack creates backpack model from code, that affects cpu usage

**Comment by gittibene** [comment]
Interesting, is there a reason you use code instead of model files?

**Comment by Tiviacz1337** [comment]
Well, I just don't know how to exactly transfer json model to game and be able to manipulate with specific parts in real time, like I can with code model. I mean let's say dissapearing sleeping bag when deployed
