### ISSUE TITLE
Ghost bag when picking a bag up with carry on

### ISSUE THREAD

**Issue by Aceplante2** [Tiviacz1337/Travelers-Backpack#606]
When I pick up a bag with the carry on mod, an inaccessible "ghost bag" seems to be created and takes up the slot and preventing you from equipping a new bag until you relog.

**Comment by Tiviacz1337** [comment]
version, modloader.....

**Comment by Aceplante2** [comment]
Apologies, Forge 1.18.2

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all should be fixed if not reopen
