### ISSUE TITLE
Shulkers in Backpacks

### ISSUE THREAD

**Issue by saditude** [Tiviacz1337/Travelers-Backpack#607]
Me and my friends have a modded server, where we just got shulkers, and wanted to put them in a backpack. We did some looking and saw you "patched" it and wondered if there is the ability to have it as an option in the config file? So that way owners of servers or single player can put shulkers in their backpack if they want.

**Comment by TprScruffy** [comment]
I just realised this issue in my single player. i updated from 1.19 to 1.19.3 and everytime i take a shulker out i cant put it back in. This will totally nullify this mods use for me. Really am hoping for a setting option to allow this.
![2023-05-13_17 13 26](https://github.com/Tiviacz1337/Travelers-Backpack/assets/111855278/0cb1c2f1-8e91-4751-abec-928e3a697d18)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files added for forge
https://modrinth.com/mod/travelersbackpack/versions

**Comment by TprScruffy** [comment]
Thank you so much Tiv😁❤️❤️

**Comment by saditude** [comment]
Newly generated config doesn't have any blacklisted items line, but doesn't seem to change anything. Any idea on what i'm missing?
