### ISSUE TITLE
Tank Settings not Working

### ISSUE THREAD

**Issue by Aetrnl94** [Tiviacz1337/Travelers-Backpack#608]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Game Version: 1.19.4
Mod-Loader Version: Forge 45.0.55
Mod Version: TravelersBackpack-1.19.4-8.4.3.jar

1. Describe the bug 

Unable to change backpack storage capacity via mod settings.

2. Write steps to reproduce the bug

When I open up the mod configuration tool in Minecraft, navigate to Traveler's Backpacks -> Common -> Backpack Settings, and change the tank storage capacity. No matter what value I change it to, the tank defaults to 5,000 capacity when I look at it in-game, and when I use a hose to fill it up to max, then close the backpack, occasionally when open it again, it shows "2,000/5,000", even if it was fully filled. Some new backpacks also show a capacity of a MAX of 2,000, and have less inventory slots than normal as well.

3. What is expected behaviour 

When setting the tank capacity to 10,000, I would expect the storage tank in my backpack to also increase to 10,000. Instead, it stays at 5,000.

4. Screenshots (If applicable)
![2023-05-08_18 16 43](https://user-images.githubusercontent.com/131720204/236957252-7c79abdb-1fa8-48b1-8846-d48152c8c564.png)
![2023-05-08_18 18 23](https://user-images.githubusercontent.com/131720204/236957442-51642a88-4d90-42fe-ba98-33bc7a79166d.png)
![2023-05-08_18 18 50](https://user-images.githubusercontent.com/131720204/236957443-75d25404-26e6-416f-8e79-9f0a54a7b12c.png)

**Comment by Tiviacz1337** [comment]
will be fixed in next release

**Comment by Aetrnl94** [comment]
Awesome, thanks for the update. Any idea as to an ETA on that (within a few days, within a week, within a month, longer, etc.)?
Thanks again!

**Comment by Tiviacz1337** [comment]
within week, two

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all fixed
