### ISSUE TITLE
Mod not showing

### ISSUE THREAD

**Issue by TheXReaper** [Tiviacz1337/Travelers-Backpack#609]
forge 1.19.4, mod is not showing neither in the mods section or in the game
i downloaded every single latest version, still wont work
also tried other version, still the same

**Comment by Tiviacz1337** [comment]
Please check if you downloaded correct files, someone just reported other issue for 1.19.4 with latest update, so it seems you are doing something wrong

**Comment by TheXReaper** [comment]
> Please check if you downloaded correct files, someone just reported other issue for 1.19.4 with latest update, so it seems you are doing something wrong

ok its working now, but please can you tell me if they spawn on mobs natrully, cause on my skeleton farm i found creeper backpack in the chest and i am sure i didnt put it there, replyed last 3 minuts and i actully didnt put it there so.... do they spawn on mobs and if they do, do they also have the effects from the backpack, cause am sure a skeleton wearing a creeper backpack  shouldve exploded right :) ?
