### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by ReactorNefg** [Tiviacz1337/Travelers-Backpack#610]
0.Fabric 1.16.5

1. The crash report you provided indicates that there was a rendering issue in Minecraft related to the "Traveler's Backpack" mod. The specific error message states that the entity with the ID 70710, which is a "Брутальный пиглин" (Brutal Piglin) in the "ClientLevel" world, does not provide a component of type "travelersbackpack:travelersbackpack_entity".

2.
   1.Spawn a brutal piglin

3. Crash

Crash log : https://pastebin.com/VyMRRe5E

**Comment by Tiviacz1337** [comment]
already reported will be fixed in next update

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files fixed
