### ISSUE TITLE
Backpack Feedback/Concepts

### ISSUE THREAD

**Issue by Aceplante2** [Tiviacz1337/Travelers-Backpack#611]
The netherite backpack is WAY too expensive for the extra +1 it gives over the diamond traveler's pack. Maybe make it crafted from the magma cube pack instead of the regular one and give it fire resistance at least?? Also it should also give +5 armor instead of 4, becuase the recipe requires a netherite BLOCK. For the other ores that isnt that much of a stretch, but a block of netherite is the equivalent of 36 ancient debris.

Same with the wither pack that requires three wither skeleton skulls and a NETHER STAR, and is (basically) completely cosmetic right now? Maybe it could give you the ability to hover when crouching? or at least the slow falling potion effect.
Edit: I just got one from a wither skeleton, so is this supposed to be a wither SKELETON pack? If so, the current ability of negating the wither effect is fine, but the recipe should only require one skull not 3. and definitely not the nether star.

The bee pack is also not very good right now compared to many of the others. How about it also gives players regeneration when standing on a flower (be sure to include forge/flowers)

Skeleton pack should give a 50% chance to not consume any arrow even tipped/modded ones.

Emerald pack should require a villager pack in its crafting recipe (instead of the regular travelers one), and in exchange give you the hero of the village effect for better villager trades? The gifts you get from being hero of the village are not that good but can be useful in large amounts, but the villager pack requirement means you must at least have leveled up a librarian villager fully and paid a hefty price.

The wolf pack could automatically tame any nearby wild wolf. MAY YOUR DOG ARMY BECOME REALITY

The snow traveler's pack should allow players to walk on powdered snow. If you wanted the basic packs to not have abilities, this ability could be added to a new "rabbit traveler's backpack" instead?

A new "slime traveler's backpack" that negates fall damage? This would be a precursor to the blaze pack, but obtained much earlier. Maybe, instead of just negating fall damage, players would bounce and take 25% fall damage instead?

A piglin pack that makes piglins not attack you (as if you were wearing gold. This should also apply to the gold backpack?)

Also, can all packs have a few slots for arrows, say in the top left? Currently they holds tools, water, can craft, but not hold arrows? To clarify, I mean slots that can be used, and would be consumed whenever you shot an arrow. Imagine a quiver.

**Comment by Tiviacz1337** [comment]
changed netherite backpack recipe
