### ISSUE TITLE
Minecraft crashes when crouching and right-clicking a block.

### ISSUE THREAD

**Issue by aseycay** [Tiviacz1337/Travelers-Backpack#614]
My game crashes when I crouch+right-click a block (when trying to place, empty hands, non-placeable item in hands). This only happens in 1 world on a server. I made a single player world and the issue was not present. I've tried reinstalling minecraft entirely and the issue persists.
[crash-2023-05-11_12.22.39-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/11455109/crash-2023-05-11_12.22.39-client.txt)

**Comment by Tiviacz1337** [comment]
Update Traveler's Backpack on server

**Comment by aseycay** [comment]
Thank you so much!
