### ISSUE TITLE
PLAYER HAVING CRASH ON MY SERVER. :"(

### ISSUE THREAD

**Issue by breeece** [Tiviacz1337/Travelers-Backpack#615]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
FORGE 44.1.23
1.19.3
TravelersBackpack-1.19.3-8.3.9

1. Describe the bug 
CRASH UPON STARTING UP. ONE OF MY PLAYERS REPORTED THIS TO ME. I AM RUNNING THE SAME VERSION ON MY PERSONAL CLIENT WITH NO ISSUES. NOT SURE WHAT IS HAPPENING HERE.

2. Write steps to reproduce the bug
HAVE TRAVELERS BACKPACK INSTALLED, RUN MINECRAFT LAUNCHER. LAUNCH GAME. CRASH.

3. What is expected behaviour 
RUN GAME WITH NO CRASH.

4. Screenshots (If applicable)
[latest.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/11457881/latest.log)
[crash-2023-05-11_20.53.37-fml.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/11457882/crash-2023-05-11_20.53.37-fml.txt)

**Comment by Tiviacz1337** [comment]
Maybe he could update forge

**Comment by breeece** [comment]
I will suggest that but we did just update forge for the server and the
playwr and it was running fine. I'm not sure if some options somewheere
have messed up the player's game or what.

**Comment by Tiviacz1337** [comment]
so basically it works for you but for your friend it does not?

**Comment by breeece** [comment]
Correct. I had them delete and regenerate the config also. It's pretty odd.

**Comment by Tiviacz1337** [comment]
make sure you both have the same installation, since it works for you there's something wrong with other player installation
