### ISSUE TITLE
Minor incompatibility with Trinkets Curios Theme

### ISSUE THREAD

**Issue by SplendidAlakey** [Tiviacz1337/Travelers-Backpack#617]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 0.14.19 + API 0.76.0
Traveler's Backpack 8.2.20 (1.19.2)
[Trinkets Curios Theme](https://www.curseforge.com/minecraft/mc-mods/trinkets-curios-theme) 0.2.2

1. Describe the bug 

Shift-clicking on a backpack, while in creative, and Trinkets integration is enabled, the game crashes.

I'm reporting here, instead of Trinkets Curios Theme, because Traveler's Backpack is the only mod, that uses Trinkets and causes this crash. For example, [Artifacts](https://www.curseforge.com/minecraft/mc-mods/artifacts-fabric) doesn't crash, when doing the same with their trinkets.

2. Write steps to reproduce the bug

     1. Install Traveler's Backpack and it's dependencies
     2. Install Trinkets Curios Theme
     3. Enable Trinkets integration in the Traveler's Backpack config
     4. Launch the game, make sure you are in creative
     5. Grab any backpack and left-click on it, while holding shift
     6. Crash

3. What is expected behaviour 

The backpack should just get equipped without causing the crash.

4. Logs (If applicable)

https://gist.github.com/SplendidAlakey/9c95eb81e9db7f678fb589763c50826a#file-crash-log

https://gist.github.com/SplendidAlakey/9c95eb81e9db7f678fb589763c50826a#file-latest-log

**Comment by Tiviacz1337** [comment]
does it work if you put backpack manually in the slot?

**Comment by SplendidAlakey** [comment]
Sorry for a delayed response, but that's not possible. Trinkets Curios Theme moves all the slots to a separate place, just like Curios does, and it's not accessible in Creative mode. You can equip it however you like in Survival without any issues. Any other mods, that use Trinkets, can be shift-clicked to be put into appropriate slots anyway and after switching to Survival, you can confirm that they are there and working as intended.

**Comment by Tiviacz1337** [comment]
Fixed in latest version: 
CF: https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
Modrinth: https://modrinth.com/mod/travelersbackpack/versions
