### ISSUE TITLE
Death by explosion deletes backpack and Corpse Compat

### ISSUE THREAD

**Issue by itsdeadfrosty** [Tiviacz1337/Travelers-Backpack#620]
Forge. TravelersBackpack-1.18.2-7.1.28.jar

Upon death by explosion. Backpack does not place on ground, but instead auto deletes itself. 

Also requesting compatibility with the Corpse Mod that when dropped as an item instead is placed in the Corpses inventory.

2. Write steps to reproduce the bug
die by explosion.
Backpack not placed on ground as block entity.

3. What is expected behaviour 
that the shit works XD

**Comment by Tiviacz1337** [comment]
can't reproduce, backpack places on ground after explosion, maybe it's compat issue with corpse

**Comment by itsdeadfrosty** [comment]
you actually had a run in with this in 2019 seen here

https://github.com/DarkPacks/Crackpack-3/issues/25

This happened to a buddy of mine on my server about a week ago.

**Comment by itsdeadfrosty** [comment]
also what do you think of the corpse suggestion

**Comment by Tiviacz1337** [comment]
still can't reproduce this issue check it with travelers backpack installed only

**Comment by Tiviacz1337** [comment]
> also what do you think of the corpse suggestion

maybe in the future

**Comment by itsdeadfrosty** [comment]
cool

**Comment by Tiviacz1337** [comment]
added compat with corpse

**Comment by Tiviacz1337** [comment]
Compat added
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files
https://modrinth.com/mod/travelersbackpack/versions
