### ISSUE TITLE
Server crash when sorting backpack

### ISSUE THREAD

**Issue by ReactorNefg** [Tiviacz1337/Travelers-Backpack#621]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.16.5 travelers-backpack-1.16.5-5.4.26 

1. Describe the bug 
When you press the sort button, the server crashes when sorting the backpack

2. Write steps to reproduce the bug
  1.Open the backpack
  2.Put items
  3.Press the sort button

3. What is expected behaviour 
https://pastebin.com/791ydxWg

4. Screenshots (If applicable)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/61548817/ef792845-9f44-4ad5-bd4f-7417d8652321)

**Comment by Tiviacz1337** [comment]
Update to latest version
