### ISSUE TITLE
Fluid compatibility

### ISSUE THREAD

**Issue by Random832** [Tiviacz1337/Travelers-Backpack#623]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
1.18.2 Forge 7.1.32 [verified color issue is still present in current source code]

1. Describe the bug 
Tinker's Construct potion fluid shows up pink colored in GUI, and Traveler's Backpack potion fluid is just called "Potion" in other mods' tanks.

3. Write steps to reproduce the bug
Place Tinkers Construct potion fluid [obtained by clicking a bottle on any tinkers construct tank] in a backpack. Backpack GUI [both HUD and inventory] will show it as the default color of the uncraftable potion.

Place Traveler's Backpack potion fluid in e.g. a Tinkers Construct Smeltery. Hovering over it will just say "Potion"

This issue almost certainly applies to other mods as well, I simply haven't tested with the others [Thermal, Create, and Immersive Engineering all add potion fluids, and Industrial Foregoing has ore processing fluids that are likely to have the same color issue]

4. What is expected behaviour 
Color should match color of the potion. Call the stack sensitive getColor method - for some reason you only call it when the fluid is your potion fluid instead of in all cases.
Name should match name of the potion. Override the stack sensitive getDescription method.

[Note: This issue is not about not being able to *drink* the other mods' potion fluids, which may be too complex to implement. Just displaying colors and names correctly]

**Comment by Tiviacz1337** [comment]
I can't find stack sensitive getColor method

**Comment by Random832** [comment]
sorry, I was referring to IClientFluidTypeExtensions.getTintColor - I remembered the name of the method incorrectly

**Comment by Tiviacz1337** [comment]
oh okay I see now nevermind

**Comment by Tiviacz1337** [comment]
Fixed
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files
https://modrinth.com/mod/travelersbackpack/versions
