### ISSUE TITLE
Inconsistant behavior for potions in backpack tanks

### ISSUE THREAD

**Issue by h3lias** [Tiviacz1337/Travelers-Backpack#627]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 1.18.2-0.14.19 with travelers-backpack-1.18.2-7.1.26

1. Describe the bug 

When filling the tanks manually with potions, the hose allow the player to drink from it
However, when the tanks are filled with the suck function of the hose (from a Create Mod fluid tank here), it is not drinkable anymore

2. Write steps to reproduce the bug

Fill the tanks by sucking potion from a Create Mod fluid tank and try to drink it

3. What is expected behaviour 

The player should be able to drink the potion

**Comment by Tiviacz1337** [comment]
The compat will be added in the next update and following fluids will be drinkable:
tconstruct:potion
create:potion

**Comment by Tiviacz1337** [comment]
Added for Forge:
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files
https://modrinth.com/mod/travelersbackpack/versions
fabric soon

**Comment by Tiviacz1337** [comment]
Added for Fabric:
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
https://modrinth.com/mod/travelersbackpack/versions
