### ISSUE TITLE
Fabric 0.42.0 MC 1.16.5 Game Crashed when started

### ISSUE THREAD

**Issue by WERDXZ** [Tiviacz1337/Travelers-Backpack#628]
Fabric 0.42.0 MC 1.16.5 Game Crashed when started
trinkets-2.6.7
fabric-api-0.42.0+1.16
travelers-backpack-1.16.5-5.4.28
modmenu-1.16.23
RoughlyEnoughItems-5.12.385
Cardinal-Components-API-2.8.3
cloth-config-4.14.64-fabric / cloth-config-4.16.91-fabric.jar

It just crashed on game init stage, when generating recipes(i think)

the log is here

[minecraft-exported-logs-2023-06-01T10-43-57.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/11628094/minecraft-exported-logs-2023-06-01T10-43-57.log)

**Comment by Tiviacz1337** [comment]
download cloth api

**Comment by Tiviacz1337** [comment]
Fixed:
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
https://modrinth.com/mod/travelersbackpack/versions
