### ISSUE TITLE
Configs for specific backpacks

### ISSUE THREAD

**Issue by Chubblezap** [Tiviacz1337/Travelers-Backpack#629]
**Is your feature request related to a problem? Please describe.**
I'm running a server where we host events every now and then, and sometimes these events are parkour challenges. However, even though we can prevent people from cheating them by disabling the use of fireworks/elytra near them, we can't disable the spider backpack without disabling *every* other pack ability as well. 

**Describe the solution you'd like**
I'd like the config file to have a listing of blacklisted backpack abilities rather than the blanket "are abilities enabled" toggle, or some other equivalent solution.

**Describe alternatives you've considered**
If the abilities supported Fabric Permission API i could theoretically confine the ability restrictions to a specific area, but that seems like overkill.

**Comment by Tiviacz1337** [comment]
I'll add config option to disable specific abilities in the next update

**Comment by Tiviacz1337** [comment]
Added for Forge:
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files
https://modrinth.com/mod/travelersbackpack/versions
fabric soon

**Comment by 0m3ga4** [comment]
Glad to see this is coming to fabric, ty.

**Comment by Tiviacz1337** [comment]
Added for Fabric: 
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
https://modrinth.com/mod/travelersbackpack/versions
