### ISSUE TITLE
Backpack won#t place in trinkets slot 1.19.2

### ISSUE THREAD

**Issue by IpGa13** [Tiviacz1337/Travelers-Backpack#630]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1.19.2-8.2.22 Fabric

1. Describe the bug 
Cannot place Backpack in Trinkets slot even with config enabling trinkets

2. Write steps to reproduce the bug
Install Trinkets 3.4.2 and TB Fabric, grab a backpack, try placing it into the Slot and watch as nothing happens.

3. What is expected behaviour 
Backpack sits nicely in trinkets backpack slot

**Comment by Tiviacz1337** [comment]
did you enable trinketsIntegration in Traveler's Backpack config?

**Comment by IpGa13** [comment]
> trinketsIntegration

Yes

**Comment by Tiviacz1337** [comment]
on client& server?

**Comment by IpGa13** [comment]
i play singleplayer

**Comment by Tiviacz1337** [comment]
someone just reported bug on fabric 1.19.2 and backpack can be placed in trinkets slot, check your configs & mods
