### ISSUE TITLE
Backpack duplication glitch

### ISSUE THREAD

**Issue by Kiwi-Co** [Tiviacz1337/Travelers-Backpack#631]
**Mod loader and version-**
Minecraft 1.19.2
Fabric 1.19.2 (0.14.21)
travelers-backpack-1.19.2-8.2.22.jar

**Bug-** 
Backpack duplicates with trinkets integration on.

**Steps to reproduce the bug-**
1. Turn on trinkets integration.
2. Take two of the same backpacks with different items in them.
3. Put one of them in the trinkets backpack slot.
4. Open the backpack using the key bind.
5. Now right click the backpack on your trinkets slot while holding the other backpack.
6. Repeat step 4.
7. You will have two backpacks with same content as one of the backpack did.

**Expected behavior-**
Backpack should have different content as earlier but now it has copied the content of the other backpack.

**Video showing how to reproduce the bug-**
[2023-06-06 17-21-43.zip](https://github.com/Tiviacz1337/Travelers-Backpack/files/11664308/2023-06-06.17-21-43.zip)

**Comment by Tiviacz1337** [comment]
firstly try updating to latest fabric mod version for 1.19.2

**Comment by Kiwi-Co** [comment]
Oh I made a mistake!. The bug was on the latest version of the mod. sorry.

**Comment by Tiviacz1337** [comment]
Okay, so this happens because trinkets is not calling proper methods when player is swapping trinkets that are the same items but with different nbt data. The only way to fix it right now would be to disabling ability to put backpack in trinkets slot, if the same type of backpack is already in the slot. Basically player would need to take backpack from slot first, then put new backpack in empty slot.

**Comment by Tiviacz1337** [comment]
I'll release update with this fix
and I've already reported bug to trinkets creators

**Comment by Kiwi-Co** [comment]
How to remove the back slot in trinkets? I disabled trinkets integration but the back slot wont go.

**Comment by Tiviacz1337** [comment]
back slot is created by json file so theres currrently no way to disable it I think

**Comment by Kiwi-Co** [comment]
then do you know any other mod that uses the back slot? so that the slot is not just there and does something.

**Comment by Tiviacz1337** [comment]
i dont know you have to find by yourself, so you disabled trinketa integration for tb to avoid dupe bug? and use built in equip system?

**Comment by Kiwi-Co** [comment]
yes. For the time i will use the built in system.

**Comment by Kiwi-Co** [comment]
I found a mod called elytra slot which lets you put elytra in trinkets slot. It adds a separate slot, so is it possible to combine that slot and the back slot so that they work to gather?

**Comment by Tiviacz1337** [comment]
[emilyploszaj/trinkets#](https://github.com/emilyploszaj/trinkets/issues/253)

**Comment by Kiwi-Co** [comment]
Since they are not replying, how about removing this feature from the mod. This bug is very easy to replicate so I don't think anyone would use the integration once they found the bug.

**Comment by Tiviacz1337** [comment]
Fixed: 
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/versions
