### ISSUE TITLE
[1.20-9.0.1version]Disappears when placed in water

### ISSUE THREAD

**Issue by Baishilalala** [Tiviacz1337/Travelers-Backpack#633]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.20-9.0.1

1. Describe the bug 
1.The backpack disappears when placed in water
2.The backpack slot in the equipment bar is opened, but the backpack will not appear in the slot when equipped

2. Write steps to reproduce the bug
1.Place a bag in water
2.equip a backpack

3. What is expected behaviour 
1.It should not be disappeared
2.It should be appeared in the slot when equipped correctly

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Fixed in latest update
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/versions
