### ISSUE TITLE
1.20 Realm java Forge

### ISSUE THREAD

**Issue by mrsmalls23** [Tiviacz1337/Travelers-Backpack#634]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 
On the realm the mod exists but they cannot be crafted, or even placed out of creative.

2. Write steps to reproduce the bug
Join realm
get materials to craft a basic backpack parts
put them in the crafting table

3. What is expected behaviour 
a piece of the backpack to be crafted

4. Screenshots (If applicable)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/136209180/fdcfdb88-b9dd-45da-b607-1213896eea0e)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/136209180/78378bf7-3b4d-4c35-adb0-e6db06b57ede)

**Comment by Tiviacz1337** [comment]
you can't use mods on Minecraft Realms
