### ISSUE TITLE
Unable to use integrations for travelers backpack

### ISSUE THREAD

**Issue by BuffQueen** [Tiviacz1337/Travelers-Backpack#636]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 
When i take the bag out of my hand or be it being on my back, i am unable to use the integrations button at the bottom left. 

2. Write steps to reproduce the bug
Press B with backpack on back.
Click integrations - bottom left.
Nothing happens.

3. What is expected behaviour 
Backpack from back to drop to hand or backpack from hand to be transferred to back

4. Screenshots (If applicable)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/136308795/22780d2d-8f76-4b56-8bf7-79da4a4eef8a)

**Comment by Tiviacz1337** [comment]
it is clearly written that you have to "put backpack in back slot"... if you use trinkets/curios put backpack in back slot which those mods add

**Comment by BuffQueen** [comment]
yeah dude. it was in back slot but it's not working?
