### ISSUE TITLE
How to combine improvment with backpack...

### ISSUE THREAD

**Issue by kotenka123** [Tiviacz1337/Travelers-Backpack#637]
I think i'm not very smart but i don't understand what else i need to combine this things 
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/136387393/133a4ac9-8ca4-4d93-bf76-dcba7132f08b)

backpack is already leather. so... what else? I haven't found any information in guide

**Comment by eyelessness** [comment]
hey! so i figured it out, cause i was having the same issue. its leather in the template area.
