### ISSUE TITLE
Smithing table not upgrading leather tier backpack - 1.20-9.0.1

### ISSUE THREAD

**Issue by NicoleReyesAlveal** [Tiviacz1337/Travelers-Backpack#640]
0. Minecraft 1.20, Forge.
TravelersBackpack-1.20-9.0.1

1. The smithing table is not merging the iron upgrade with the leather tier backpack.
2. Craft a leather tier backpack, craft an iron upgrade. Put both in the smithing table.
3. The smithing table should upgrade the leather tier backpack to the iron tier backpack.

**Comment by Tiviacz1337** [comment]
put leather in first slol

**Comment by NicoleReyesAlveal** [comment]
I suggest adding that information somewhere, since its not mentioned while playing.
