### ISSUE TITLE
Standard Backpack unable to be upgraded in smithing table. Fabric v1.20-9.0.2

### ISSUE THREAD

**Issue by Vesta91** [Tiviacz1337/Travelers-Backpack#642]
Fabric v1.20.1-9.0.2

Standard Backpack unable to be upgraded to iron tier in smithing table

![javaw_NxueUe1gk4](https://github.com/Tiviacz1337/Travelers-Backpack/assets/48779691/96fad4e5-1f5e-4fd3-ab96-d120c8440cbc)
![javaw_LgHu0sTYfh](https://github.com/Tiviacz1337/Travelers-Backpack/assets/48779691/2c2284b7-0328-402d-8206-3b2c8fc09ca5)

**Comment by Tiviacz1337** [comment]
you have to open backpack in hand first to be able to apply upgrade
It will be fixed in next update though

**Comment by Tiviacz1337** [comment]
Fixed:
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
https://modrinth.com/mod/travelersbackpack/versions
