### ISSUE TITLE
Key binds aren't working (at least for me)

### ISSUE THREAD

**Issue by majorsig** [Tiviacz1337/Travelers-Backpack#643]
I'm running it on fabric 1.19+ in the medieval Minecraft modpack.
The mod works as intended except for when I equip it I can not open the backpack even if I switch key binds.

**Comment by Tiviacz1337** [comment]
make sure any other keybind is not linked with backpack keybind, I'm sure it works since many players play on medieval mc and they didn't report such issue

**Comment by Krzysztof23** [comment]
unfortunately, the problem also applies to me, version 1.19.2 2.8.2.29-30, both on the version with the ending 29 and 30, the associated key does not work
![2023-08-07_10 37 31](https://github.com/Tiviacz1337/Travelers-Backpack/assets/67221783/a9da57a9-5adc-4457-b6ae-0fb9bdc44087)
