### ISSUE TITLE
Item dissapears when updating this mod

### ISSUE THREAD

**Issue by AoSankaku** [Tiviacz1337/Travelers-Backpack#645]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
fabric
1.19.2-8.2.18→1.19.2-8.2.24

1. Describe the bug 
Upgreading this mod removes about a half of items in my backpacks.
This bug is caused by the upgrading system update of Traveler's backpack. This update reduced the default storage of backpacks, and actually removes excessive items in the backpack instead of scatters them.
Furthermore I can't even upgrade backpacks before opening it once. This means you can't protect myself from this bug.

2. Write steps to reproduce the bug
- Install Travelers backpack 1.19.2-8.2.24
- Fill your backpack with some items
- Upgrade Travelers backpack to 1.19.2-8.2.26
- Open your backpack
- About a half of your items are gone!

3. What is expected behaviour 
Scatters the excessive items.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
this issue is fixed in 8.2.28 you can upgrade backpack without opening it
