### ISSUE TITLE
How to recover backpack from backup?

### ISSUE THREAD

**Issue by BoostedDampi** [Tiviacz1337/Travelers-Backpack#646]
Hi there, for some strange reason (will try to make a bug report when I find out why it happens) the backpack was dropped in item form in a wall after not being placed. Since it was dropped in a wall it vanished. is it possible to recover the backpack from the backup file?

**Comment by Tiviacz1337** [comment]
yes it is possible find backpack uuid in backpacks folder which is located in world folder, then use /restore <backpackuuid> <playerName>
