### ISSUE TITLE
Place leather in first slot (template slot)

### ISSUE THREAD

**Issue by ShadoUrufu** [Tiviacz1337/Travelers-Backpack#647]
Place leather in first slot (template slot)

_Originally posted by @Tiviacz1337 in https://github.com/Tiviacz1337/Travelers-Backpack/issues/639#issuecomment-1591422659_
           Forgot to check on this. It does not work. Shift-clicked on leather, on the upgrades, on the backpacks, etc.. nothing is going inside of the table, at all. Even tried dragging them to all the slots, nothing.

**Comment by Tiviacz1337** [comment]
what mod version do you use

**Comment by ShadoUrufu** [comment]
travelers-backpack-1.19.4-8.4.5

I'm playing in 1.19.4 because the mods I want to use only run in this version. I'm using the experimental features that bring in some of the 1.20 stuff, like armor trims, the new smiting template for netherite, and cherry wood.

**Comment by Tiviacz1337** [comment]
Recipes added for experimental features for 1.19.4 are available on mod versions 8.4.6+ update your mod and you'll be able to upgrade backpack

**Comment by ShadoUrufu** [comment]
I only see 8.4.5 currently on curseforge, but i'll check the github.

**Comment by Tiviacz1337** [comment]
you use forge?

**Comment by ShadoUrufu** [comment]
Fabric/Quilt. Fabric mods work on Quilt.

**Comment by ShadoUrufu** [comment]
Alright, version 8.4.6 showed up, tested it, and it now works properly. Thank you.
