### ISSUE TITLE
Backpack tier not upgradeable in 1.19.4 when using 1.20 addons

### ISSUE THREAD

**Issue by Ruby51244** [Tiviacz1337/Travelers-Backpack#648]
Modloader: Fabric Loader 0.14.21
Mod version: 1.19.4-8.4.5

Issue: The Backpacks are not upgradeable in 1.19.4 if you are using the 1.20 addons (possible to enable when creating a new world) since the smithing table got reworked (requires templates now) and because of it you are unable to move the backpack and tier upgrades into the smithing table. the only way i have currently found to obtain the higher tier backpacks is using creative mode for normal backpacks or editing the items NBT value for the other backpacks.

Bug is reproduced by enabling the 1.20 addons when creating a world in 1.19.4

Expected behaviour: being able to move the backpack and the upgrade into the smithing table to upgrade it

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/version/EGYtV3xo
Released update
