### ISSUE TITLE
[1.20.1] sleeping bags issues

### ISSUE THREAD

**Issue by Bass2style** [Tiviacz1337/Travelers-Backpack#649]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge Version : 47.0.16
Mod version : 9.1.2

1. Describe the bug 
sleeping bags aren't working, clicking with them doesn't nothing.

2. Write steps to reproduce the bug
craft or give a sleeping bag and try to sleep during night (or day, but same result).
 

3. What is expected behaviour 
fall a sleep like a cute baby

4. Screenshots (If applicable)
nothing to see here.

**Comment by Tiviacz1337** [comment]
sleeping bags work only at night

**Comment by Bass2style** [comment]
even at night, those are not in my case. clicking with them does nothing.

**Comment by Tiviacz1337** [comment]
oh, if you mean you cant place them on the ground - it's not a bug, sleeping bag can be used only if deployed from travelers backpack. Maybe I'll change that in the future though
