### ISSUE TITLE
Forge 1.20.1 can't add upgade in smithing table , because of templates for armor slot?

### ISSUE THREAD

**Issue by CTMOM** [Tiviacz1337/Travelers-Backpack#650]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 

2. Write steps to reproduce the bug

3. What is expected behaviour 

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
use leather in first slot
