### ISSUE TITLE
Forge 1.20.1 "Invalid Player Data" Error Screen in Singleplayer

### ISSUE THREAD

**Issue by amyyy04** [Tiviacz1337/Travelers-Backpack#651]
Played with friends in a multiplayer lan world with other mods (waystones, collective, curios forge, infinite trading, journeymap, JEI, silent lib, falling tree, curious armor stands, mouse tweaks and balm forge) and the host player couldnt load the world in singleplayer the next day.

After the "loading" square gets complete and the "joining" shows up, you get the error screen saying "Connection Lost - Invalid Player Data" and it takes you back to the server list, yet we're trying to open the save in singleplayer. All the other vanilla saves we had would open right away with the mod, but the one we had backpacks on wouldnt. We took all the mods out the mods folder one by one, the only one that solved was the Traveler's Backpack.

Im not sure if it's a bug related to the mod itself or the interaction with the other mods. May be a forge bug aswell, but just thought i would share it here cause we didnt have a backup and we lost all the itens inside our backpacks since we had to uninstall the mod to load the save... 

(English is not my first language, sorry if i mispelled/misused any words)

![2023-06-24 (4)](https://github.com/Tiviacz1337/Travelers-Backpack/assets/137637399/76d78059-dd5a-4159-824f-76ff7332abae)

We were using Radmin VPN to play Lan

**Comment by Tiviacz1337** [comment]
could you show me the console log when you login to server? what errors does it throw

**Comment by amyyy04** [comment]
> could you show me the console log when you login to server? what errors does it throw

We can's log in the server because it's not an open server, my friend enters the world in singleplayer and then opens to Lan... is there a way to see the console log in singleplayer? sorry im new to this

**Comment by Tiviacz1337** [comment]
hmm, you will have to check in .minecraft logs folder

**Comment by amyyy04** [comment]
[debug.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/11857725/debug.log)

[latest.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/11857727/latest.log)

i found these two logs from the same time i tried opening the save... tell me if it's not what you're looking for

**Comment by Tiviacz1337** [comment]
Try adding this mod to your server; 
https://www.curseforge.com/minecraft/mc-mods/packet-size-doubler-forge

**Comment by amyyy04** [comment]
It worked!!!! Thank you so much <3
