### ISSUE TITLE
Forging upgrade backpacks cannot be performed within fabric 1.20 version.

### ISSUE THREAD

**Issue by QianMuu** [Tiviacz1337/Travelers-Backpack#652]
Error display:  Unable to upgrade backpack using this method.

Function request: Can a suitable backpack with wings be hidden? I hope so, it will be more aesthetically pleasing.

**Comment by Tiviacz1337** [comment]
what method. 
use leather in first slot then backpack and in last slot backpack upgrade 
if you want to hide bcakpack while wering elytra, theres already config option for that

**Comment by QianMuu** [comment]
> 什么方法。 在第一个插槽中使用皮革，然后背包，并在最后一个插槽背包升级 如果你想隐藏bcakpack而wering elytra，there's already config options for that

yep  I put leather, regular backpack, and upgraded iron chips into the forging table.
But it cannot be upgraded.
It will prompt that you cannot upgrade using this method. (And the font overlaps).
