### ISSUE TITLE
Crash when trying to update from 1.19.4 to 1.20.1

### ISSUE THREAD

**Issue by alequipelatte** [Tiviacz1337/Travelers-Backpack#653]
Using Fabric 0.14.21-1.20.1

I just updated the Traveler's Backpack mod from **travelers-backpack-1.19.4-8.4.0** to **travelers-backpack-1.20.1-9.1.0**. On a new world or one started in 1.20.1, the world loads fine and there are no problems. However, if I try to import my 1.19.4 save file, it loads, shows the "Joining world" screen, and then immediately goes to the "Saving world" screen and crashes.

The crash report lists Traveler's Backpack, though I can't understand what it's trying to tell me. If I remove the Traveler's Backpack mod, there are no crashes, but of course, all the things in my backpack's inventory are missing.

Here is the crash report: https://mclo.gs/Sy16LdT

Thank you in advanced.

Edit: Sorry, I don't know how to add labels yet... I only just joined a few moments ago to post this.

**Comment by Tiviacz1337** [comment]
I don't know probably old save is not compatbile with new version, try removing backpack in old save, and then import world and create new backpack
