### ISSUE TITLE
unable to upgrade travelers backpack

### ISSUE THREAD

**Issue by Quantumrage10** [Tiviacz1337/Travelers-Backpack#654]
playing on forge 1.20.1 tested both server and client side and with all other mods removed

for some reason I'm unable to upgrade any of the travelers backpacks at the smiting table and i can't even find any information to figure out if I'm doing it correctly

go to the smiting table, add the backpack, add the upgrade (leather backpack iron upgrade etc) and nothing happens, 

I would expect to see an output as an iron upgraded backpack

I'm guessing this has something to do with the new smiting templets that were recently added to vanilla?

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/48039324/b91f8151-345f-49de-8677-49942515dd8a)

**Comment by Tiviacz1337** [comment]
Again use leather in first slot, please look at similiar issues before submiting new report.. Also latest version 1.20.1 has tooltip on upgrades that says you need leather in first slot

**Comment by Quantumrage10** [comment]
hay thanks for letting me know, also no the tooltip does not specify to use leather in the first slot, it states that you must combine with a leather tier backpack in the smiting table, i would highly suggest posting a screenshot showing how to do this, or writing it into the mod description on the website at least, and yes having it say that on the tooltip would help greatly as well
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/48039324/6c1d0f1f-03bb-4553-9884-f87f5972147c)
