### ISSUE TITLE
fabric-1.20 .Unable to upgrade my backpack, that's the problem I encountered.

### ISSUE THREAD

**Issue by QianMuu** [Tiviacz1337/Travelers-Backpack#655]
![03@1LKSZZY1PS6K7A2IQGM5](https://github.com/Tiviacz1337/Travelers-Backpack/assets/50398180/7ffb9d81-6357-4a16-984a-04b70196c0c8)

**Comment by Tiviacz1337** [comment]
try opening your backpack first
