### ISSUE TITLE
configuration issue

### ISSUE THREAD

**Issue by Miaochan** [Tiviacz1337/Travelers-Backpack#656]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
TravelersBackpack-1.19.2-8.2.29 for Forge

1. Describe the bug 
The configuration on server is not effective.For instance,If I enable 'backpack abilities' on client side,then I am able to obtain the backpack abilities on the server although 'backpack abilities'option has been disabled on server side

**Comment by Tiviacz1337** [comment]
you have to edit configuration on both sides

**Comment by Tiviacz1337** [comment]
abilities wont work if enabled only on client side

**Comment by Tiviacz1337** [comment]
do these effects work though, on client it can show visual effects but in fact these effects should not work
