### ISSUE TITLE
Softlock/Crash on latest Fabric mod version with REI.

### ISSUE THREAD

**Issue by 0m3ga4** [Tiviacz1337/Travelers-Backpack#657]
**0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)**
MC (Server) 1.19.2 
Fabric 0.14.21
Mod 8.2.25

**1. Describe the bug** 
Using REI to max autofill recipes in the backpack causes the game to enter a state where you can't interact with anything until disconnect and reconnect, retrying after each time you connect makes the CPU usage on the server skyrocket until crash after about 3-4 disconnects.

**2. Write steps to reproduce the bug**
Open backpack, preview a recipe in REI, shift click the + to autofill it.

**3. What is expected behaviour** 
It should add the recipe to the crafting table with as many resources as it can.

**4. Screenshots (If applicable)**

Video 1 shows standard responsiveness of the server:
https://gyazo.com/aad9b1ec563fd7d9d6dc3dca1c926b0c

Video 2 shows recipe failing to max fill, followed by softlock:
https://gyazo.com/a4b2679b049e49b1bb69a8e34176f995

Edit: Worth noting I did test that this only occurs with Travelers Backpacks, and only with the latest version. Filling still works on standard crafting tables with the latest version of Travelers, or in the backpack in the prior version I was using (I believe it was 8.2.22).

**Comment by jmadarg** [comment]
Are you sure only happens in 8.2.25? We having the same issue with 8.2.24 (server runs the Bigchadguys plus modpack)
In case its relevant, REI version is 9.1.619

**Comment by 0m3ga4** [comment]
> Are you sure only happens in 8.2.25? We having the same issue with 8.2.24 (server runs the Bigchadguys plus modpack) In case its relevant, REI version is 9.1.619

Oh my mistake, I think the last version I was using might have been 8.2.22. I deleted it when I installed the update so I'm not 100% certain but I believe that's the one that didn't crash using REI autofill.

**Comment by Tiviacz1337** [comment]
This bug occurs in every fabric version

**Comment by Tiviacz1337** [comment]
but is fixed in dev so wait for the next update

**Comment by GGORG0** [comment]
Same issue here. I can't rejoin the server: 
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/51029895/def702d6-b080-4e63-bb92-eb9b54e037a6)

After restarting the server, every time I join it crashes the entire server with 
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/51029895/098803b0-c92e-4807-8906-a37d06333d42)

How can I fix it temporarily to at least be able to join the server (and preferably keep all my items)?

**Comment by Tiviacz1337** [comment]
Fixed
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric
https://modrinth.com/mod/travelersbackpack
