### ISSUE TITLE
[bug] [compatibility] Backpack GUI Buttons Overlap

### ISSUE THREAD

**Issue by N0aW** [Tiviacz1337/Travelers-Backpack#658]
Minecraft Version: Fabric 1.20.1
Mod Version: 1.20.1-9.1.1

Mods like EMI and Stylish Effects overlap the "Backpack Settings" buttons.'

This makes the crafting grid modification buttons impossible to press.

**How to reproduce:**

- Use a mod like EMI
- Open a backpack
**Expected behavior:**
- The buttons would push other mod GUI's right
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/76262280/ec2ad0f5-3d13-427d-adb3-78e950d771a2)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/76262280/9d019e3e-564f-49bc-a44f-76b4d79475b0)

**Comment by Tiviacz1337** [comment]
will be fixed in the next update

**Comment by Tiviacz1337** [comment]
Fixed
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric
https://modrinth.com/mod/travelersbackpack
