### ISSUE TITLE
Crash when joining server

### ISSUE THREAD

**Issue by kellixon** [Tiviacz1337/Travelers-Backpack#66]
Forge version 14.23.5.2847. TravellersBackpack 1.0.20.20 + other 165 mods.
Crash when connecting to local server, and black screen. On the server computer everything is fine, crash only on the second computer in a local area network. After removing the mod everything works fine.
[report-crash.zip](https://github.com/Tiviacz1337/Travellers-Backpack/files/3665151/report-crash.zip)

**Comment by Tiviacz1337** [comment]
Does issue still persist?
