### ISSUE TITLE
[Bug] Disabled Crafting not working

### ISSUE THREAD

**Issue by A5ho9999** [Tiviacz1337/Travelers-Backpack#660]
Fabric 1.20.1
Mod Version: https://modrinth.com/mod/travelersbackpack/version/KeTPhdV4

1. Describe the bug 
Disabling the Crafting server side doesn't actually disable it for players. The lock shows Crafting Disabled but players can still put items into the slots and craft anyway.

2. Write steps to reproduce the bug
- Disable crafting in server config
- Join via client without it disabled
- Craft something in the backpack

3. What is expected behaviour 
It shouldn't allow crafting and possibly should automatically remove the crafting overlay (the orange boxes overlay)

4. Screenshots (If applicable)
https://media.discordapp.net/attachments/726977741424951416/1126732564967718932/Screenshot_582.png
https://media.discordapp.net/attachments/726977741424951416/1126732565366186114/Screenshot_583.png
https://media.discordapp.net/attachments/726977741424951416/1126732565643018280/Screenshot_584.png
https://media.discordapp.net/attachments/726977741424951416/1126732565974351943/Screenshot_585.png

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/versions
fixed

**Comment by A5ho9999** [comment]
Thanks
