### ISSUE TITLE
Dupe with REI (Fabric 1.19.2)

### ISSUE THREAD

**Issue by Newermond** [Tiviacz1337/Travelers-Backpack#662]
0. Fabric 1.19.2 [v0.14.21] + Backpacks Mosd [v8.2.25] + REI [v9.1.619]

1. Dupe

2. Put one item in the first slot of the backpack
Use "paste craft" from REI
Done

3. Item must not be duplicated 

4. Video: https://drive.google.com/file/d/1RleZRJztRLLkzW489nm4dNfXncv0080C/view?usp=sharing

**Comment by Tiviacz1337** [comment]
Fixed 
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric
https://modrinth.com/mod/travelersbackpack
