### ISSUE TITLE
Equipped Backpack Disappear and Can't be Opened

### ISSUE THREAD

**Issue by JigiLi** [Tiviacz1337/Travelers-Backpack#663]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
    Forge 1.19.2-8.2.29

1. Describe the bug 
    Not sure what happened, but I cannot open my equipped backpack. It shouldn't be a keybind issue since I was able to open it using the same keybind, and there is no keybind confict. I cannot see my backpack equipped when I changed it to third person POV, but when I try to put on another backpack, it says "A backpack has already been equipped" (basically unable to put on other backpack as well). However, other players in the server do see my backpack equipped.

    This was somehow fixed after I /kill myself (while keeping inventory), and I might be the only one in the server who encountered this, but I do see someone else saying this on a forum, and he said this happened to him after server crashed once. My server also crashed once before I noticed this issue, so it might be the cause.

2. Write steps to reproduce the bug
  Not sure.
  I. equip the backpack
  II. have logged off several times, and server had crashed or restarted a few times before noticing the issue.

3. What is expected behaviour 
Backpack is always visible on the back and should open when pressing corresponding keybind.

4. Screenshots (If applicable)
None

**Comment by Tiviacz1337** [comment]
I can't fix issue with exact steps how to reproduce it, I haven't encountered this issue in my dev environment

**Comment by JigiLi** [comment]
actually, I found that everytime I exit the server and log back in, my backpack is going to disappear until I kill myself

**Comment by JigiLi** [comment]
> I can't fix issue with exact steps how to reproduce it, I haven't encountered this issue in my dev environment

actually, I found that everytime I exit the server and log back in, my backpack is going to disappear until I kill myself

**Comment by KLONOA9X6** [comment]
> I can't fix issue with exact steps how to reproduce it, I haven't encountered this issue in my dev environment

I think it can be reproduce.
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/95112579/31b88306-ae65-4077-9317-133977513f3e)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/95112579/2f43ece1-d4a0-4969-b62b-6fa731e15e6a)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/95112579/e8da0a91-5bce-49f6-8fd4-6bfe523c6ec3)
When you installed curios, put the backpack on ground, hold shift and right click the backpack, the backpack will disappear, but while you check your playerdata, you can found it.

**Comment by JigiLi** [comment]
> > I can't fix issue with exact steps how to reproduce it, I haven't encountered this issue in my dev environment
> 
> I think it can be reproduce. ![image](https://user-images.githubusercontent.com/95112579/253157597-31b88306-ae65-4077-9317-133977513f3e.png) ![image](https://user-images.githubusercontent.com/95112579/253157926-2f43ece1-d4a0-4969-b62b-6fa731e15e6a.png) ![image](https://user-images.githubusercontent.com/95112579/253157637-e8da0a91-5bce-49f6-8fd4-6bfe523c6ec3.png) When you installed curios, put the backpack on ground, hold shift and right click the backpack, the backpack will disappear, but while you check your playerdata, you can found it.

Is it actually the same thing? I don't know what "shift + right click" does to the backpack on the ground, but I don't think equipping/putting the backpack on is the same as putting something in the curios slot.
装备背包和戴饰品是一样的吗？我看旅行者背包也不需要任何饰品mod作前置，所以装备上背包本身应该就是不占据饰品的槽吧？我用其他饰品mod也是不占据背部的饰品槽的

**Comment by KLONOA9X6** [comment]
你有其他饰品mod吗？
我想我猜到问题出在哪了

**Comment by Tiviacz1337** [comment]
What is this modpack

**Comment by KLONOA9X6** [comment]
> What is this modpack

Server: Mohist-1.20.1-160

Mods:
```
ad_astra-forge-1.20.1-1.15.1.jar
architectury-9.0.8-forge.jar
AttributeFix-Forge-1.20-20.0.2.jar
botarium-forge-1.20-2.1.0.jar
canary-mc1.20(.1)-0.2.6.jar
cfm-forge-1.20.1-7.0.0-pre36.jar
cloth-config-11.0.99-forge.jar
create-1.20.1-0.5.1.d.jar
create_jetpack-forge-4.0.0.jar
curios-forge-5.2.0-beta.3+1.20.1.jar
ferritecore-6.0.0-forge.jar
Jade-1.20-forge-11.1.4.jar
kotlinforforge-4.3.0-all.jar
l2artifacts-2.4.3.jar
l2complements-2.4.10.jar
l2library-2.4.9.jar
l2weaponry-2.4.8.jar
MaxHealthFix-Forge-1.20-11.0.2.jar
memoryleakfix-forge-1.17+-1.1.1.jar
moonlight-1.20-2.6.0-forge.jar
REIPluginCompatibilities-forge-12.0.55.jar
resourcefulconfig-forge-1.20-2.0.0.jar
resourcefullib-forge-1.20.1-2.1.1.jar
RoughlyEnoughItems-12.0.626.jar
simpleplanes-1.20.1-5.2.3.jar
supplementaries-1.20-2.5.18.jar
Terralith_1.20.x_v2.4.1.jar
toms_storage-1.20-1.6.3.jar
TravelersBackpack-1.20.1-9.1.3.jar
yesstevemodel-1.20-release-1.1.4.jar
```

Plugins:
```
EssentialsX-2.20.1-dev+29-6012959.jar
EssentialsXChat-2.20.1-dev+29-6012959.jar
EssentialsXSpawn-2.20.1-dev+29-6012959.jar
RHLeafDecay-1.20_R1.jar
spark-1.10.43-bukkit.jar
voicechat-bukkit-2.4.13.jar
```

**Comment by KLONOA9X6** [comment]
> is it on cursefoge launcher?

Nope
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/95112579/3f0e450c-5797-4c6a-94ba-0db85521ea48)

**Comment by Tiviacz1337** [comment]
check if your keybindings do not conflict. If curios integration is set to false, backpack will use built-in equip mechanic. Make sure curiosIntegration is set to false on both server and client

**Comment by KLONOA9X6** [comment]
> check if your keybindings do not conflict. If curios integration is set to false, backpack will use built-in equip mechanic. Make sure curiosIntegration is set to false on both server and client

Wait, server config not sync to client?
(Interesting...)

**Comment by Tiviacz1337** [comment]
no

**Comment by KLONOA9X6** [comment]
OK, problem is solved.
Sorry...
