### ISSUE TITLE
TB causes a crash while using crafting interface with REI

### ISSUE THREAD

**Issue by Soulrel** [Tiviacz1337/Travelers-Backpack#667]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.19.2 0.14.21
Traveler's Backpack 1.19.2-9.2.25

1. Describe the bug 
When using REI v.9.1.619 (1.19.2), using the quick craft button to copy the recipe onto the crafting interface inside the backpack causes a crash while on a server. It will give an error:
"Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(51) + length(2) exceeds writerIndex(51): PooledUnsafeDirectByteBuf(ridx: 51, widx:51, cap: 51)"

This makes it impossible to rejoin, as this error will disallow you to rejoin the server. A server reset is needed, as it is impossible to force kick the player stuck.

2. Write steps to reproduce the bug
(1) Open Backpack
(2) Select the quick craft button (the plus to automatically put resources in a crafting square)
(3) Disconnects you with the error above, and requires a server restart to fix. This is a client side bug, as the server log only notes that the player took too long to log in and ultimately disconnects them.

3. What is expected behaviour 
The items are placed in the crafting grid within the bag.

4. Screenshots (If applicable)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/139660346/6c9d9a38-2011-4d85-9c81-a9f10509ac80)

**Comment by Tiviacz1337** [comment]
This issue has already been resolved in latest update for Fabric for all versions 1.16.5-1.20.1

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/4638229
