### ISSUE TITLE
Items Bug

### ISSUE THREAD

**Issue by Falconx94** [Tiviacz1337/Travelers-Backpack#668]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Minecraft 1.19.4
Forge 45.1.0

1. Describe the bug 

I'm using the Mod on an ATERNOS server, but lately I haven't been able to use the backpack and my friends reported the same bug.

What it does is that it began to lose or clone the objects when you put them in the backpack or take them out, some items came to eliminate them.

2. Write steps to reproduce the bug

It is simply opening the backpack and without having anything, but having items in the inventory the backpack replicated the same items, if one of the items is entered it is multiplied in the inventory or eliminated, if the backpack already had few items it also multiplies them just clicking on it or removes them (if an item already had the counter at 2 or more,
When clicking, the item remained in the backpack slot and was removed from the normal inventory, you could even remove the same item with the same number that it had)

3. What is expected behaviour 

3. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Are you sure you use the latest version? Do you have the same version on server & client? Do you have the same config settings on client & server?

**Comment by Falconx94** [comment]
yes, is the same version on both, the client and the server, including the settings

**Comment by Tiviacz1337** [comment]
try updating forge to latest version for 1.19.4, it seems like something is wrong with your installation or there's compatibility issue
