### ISSUE TITLE
[BUG] Viewing the contents of a backpack with fluid in it after upgrading it from leather tier causes a crash.

### ISSUE THREAD

**Issue by Magic00Squirrel** [Tiviacz1337/Travelers-Backpack#669]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
This issue occurred on Forge version 47.1.3 for Minecraft version 1.20.1. The version of the mod in question is version 9.1.4 for Minecraft version 1.20.1. This issue occurred even when traveler's backpack was the only mod installed.

1. Describe the bug 
Pressing the CTRL key to view the contents of a backpack (any kind) that has been upgraded from the leather tier to iron or higher that previously contained any amount of fluid in it before being upgraded will cause the game to crash. This crash occurs even if the the world is closed or the game is closed and reopened. This issue is fixed once the backpack has been opened for the first time. 

2. Write steps to reproduce the bug
Obtain a water bucket, leather tier traveler's backpack (any kind), leather, smithing table, and iron tier upgrade. Fill the backpack with at least one water bucket. Place the leather, backpack, and iron tier upgrade into the smithing table and upgrade the backpack. Hover over the now upgraded backpack item with the mouse cursor and press CTRL. The game will now crash.

3. What is expected behavior 
The game will not crash and the contents of the newly expanded inventory will be shown to the player.

4. Screenshots (If applicable)
![Screenshot 2023-07-16 213545](https://github.com/Tiviacz1337/Travelers-Backpack/assets/136050789/be8d06e6-c22e-48f4-9d76-9386831a8fb5)

5. Crash report
[crash-2023-07-16_21.33.33-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/12066120/crash-2023-07-16_21.33.33-client.txt)

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
https://modrinth.com/mod/travelersbackpack/versions
Fixed
