### ISSUE TITLE
Stored Backpacks missing 

### ISSUE THREAD

**Issue by Fluffypuppy666** [Tiviacz1337/Travelers-Backpack#673]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Minecraft Ver:1.20.1
Forge 47.1.0 - (47.1.30)

1. Describe the bug 
Upgraded server today from Forge 47.1.0 to 47.1.30 also backpack mod from last version 3 to 4
Backpacks currently on my char are fine no issues, I have many backpacks in chests and scattered around full of items these are all missing this includes the mod upgrades in a chest I had as well.
Yes like a moron this time I forgot to backup the world folder before upgrade but as it was just a link to latest forge ver and the backpack upgrade I didn't see the point...don't laugh!
I did read a previous issue about missing backpacks and there is someway to restore this but it does not say how?
I had rolled back the forge version and no change, Any ideas would be helpfull.

2. Write steps to reproduce the bug

3. What is expected behaviour 

4. Screenshots (If applicable)

**Comment by Fluffypuppy666** [comment]
Ah that sucks as that means I have lost many thousands of items as had a lot of full backpacks.. Scattered all over the world.

**Comment by Fluffypuppy666** [comment]
An update on this issue. So everything placed and stored in over-world spawn area is gone for good however anything 2k blocks out of spawn if fine and has its contents intact also anything in the Nether is fine. So it's a pain I lost a lot of stuff but not as bad as it could of been.
Question.... is it possible for future update to make it possible that if you name a backpack it would create a id file for it and contents remain listed inside and would make it as safe as placing a chest down?

**Comment by Tiviacz1337** [comment]
seems like a good idea
