### ISSUE TITLE
Inconsistent values between recipes and screenshoots

### ISSUE THREAD

**Issue by Estro-1** [Tiviacz1337/Travelers-Backpack#674]
Hello,

I just downloaded the mod on the 1.20.1-9.1.2 version and started playing with it but when I tried to do the backpack tank recipe, following the CurseForge screens, it didn't worked because the recipe has changed following your last week [commit](https://github.com/Tiviacz1337/Travelers-Backpack/commit/ab19722a8c87055da2dc18707e481cc37a2ab46d)

CurseForge Screen : 
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/7215153/e8eaf768-166a-444c-957d-281ac87620c4)

Expected recipe : 
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/7215153/9d14ed5a-a847-48e1-8deb-fe78587a4a39)

Look like it should also includeall of the other recipes included in this commit
And by the way, any idea why the craft isn't appearing in the recipe book even if I have the needed components ?

**Comment by Tiviacz1337** [comment]
already updated on site
