### ISSUE TITLE
I'm on 1.19.4, forge 45.1.16, and the recipes don't work.

### ISSUE THREAD

**Issue by attemptnumber58** [Tiviacz1337/Travelers-Backpack#681]
![resim_2023-07-26_232859020](https://github.com/Tiviacz1337/Travelers-Backpack/assets/140645235/cdd0564c-e562-4b42-99bc-1dc46bff5178)
Here's the issue.
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/140645235/a79e2b21-4e36-4fdd-a5b3-85b6d2cdef4a)
Here's all the other mods I'm using alongside it.
I don't know what other recipes are broken, I haven't tested all of them yet.

**Comment by Tiviacz1337** [comment]
Updated recipes on site
