### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by Batsave** [Tiviacz1337/Travelers-Backpack#682]
**Informations** 

Forge 1.19.4-45.1.0
TravelersBackpack-1.19.4-8.4.12.jar

--------------------------------------

Good morning,
I allow myself to send you a message to report a duplication bug!

the initial situation: a player had a classic backpack upgrade in iron/gold/lapislazuly

When the player dropped a TNT minecart on him, the bag was duplicated: 1 block bag on the ground and 1 item bag on the ground.

We have reproduced the bug and here is the clip of the experience: https://clips.twitch.tv/KnottyJollyTortoiseArgieB8-wFuXfyQe2e8igtOc

The list of mods present on the server is as follows: Alex's Mobs / Better Villages / Better Desert / Better Dungeons / Better Mineshafts / Better Nether Fortresses / Better Ocean Monuments / Better Strongholds / Better Witch Huts / Better Bridges / Bigger Stacks / Bottle Your XP / Citadel / Collective / Continents / JourneyMap / Library Ferret / NullScape / The Twilight Forest / Travelers Backpack / Waystone.

We tested in creative only with the plugin without any other and we have the same duplication bug.

All types of backpack are concerned 

The duplicate bag contains the same items as the original bag

Thanks in advance

Batsave

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
https://modrinth.com/mod/travelersbackpack/versions
Fixed
