### ISSUE TITLE
Additional binds

### ISSUE THREAD

**Issue by KIRUYXAN** [Tiviacz1337/Travelers-Backpack#683]
**Is your feature request related to a problem? Please describe.**
It is extremely inconvenient every time to put on and take off the backpack or activate and deactivate its ability, go into it, I suggest adding buttons for putting on / taking off the backpack and activating/deactivate the ability.

**Comment by Tiviacz1337** [comment]
I'll think about ability keybind, althrough bind for equping/unequping will not be added
