### ISSUE TITLE
equipping the back pack

### ISSUE THREAD

**Issue by joethegreat78** [Tiviacz1337/Travelers-Backpack#685]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 

I cannot equip the back pack, with or without trinkets mod. 

2. Write steps to reproduce the bug

When i go to put it in the back inventor slot it will not go into slot. 

3. What is expected behaviour 

4. Screenshots (If applicable)

**Comment by joethegreat78** [comment]
i meant to put fabric.

**Comment by joethegreat78** [comment]
Even with all mods disabled, but Travelers Backpack I cannot still place in back slot.

**Comment by Tiviacz1337** [comment]
you have to enable trinketsIntegration in backpack config, or put backpack on via button in backpack gui (right click on backpack with hand -> button in left corner of gui, then you can open gui via b button (configurable))
