### ISSUE TITLE
[bug] [1.20.1] Fluids Disappear after breaking backpack.

### ISSUE THREAD

**Issue by N0aW** [Tiviacz1337/Travelers-Backpack#686]
**Modloader Info:**

Minecraft Version: 1.20.1
Fabric Loader Version: 0.14.21
Mod Version: 1.20.1-9.1.2

**Description:** 

Once I break a backpack placed on the ground, all the fluids inside of it disappear. The tanks are empty.

**How to Reproduce**

Place a backpack with fluids into the ground and break it.

**Expected Behavior**

The backpack would have the fluids in the tanks after breaking.

**Comment by dre3002** [comment]
Where can I get the dev version of the mod?

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/versions
fixed
