### ISSUE TITLE
Traveler's Backpack causes server to crash while it (and its dependencies) are the only mods.

### ISSUE THREAD

**Issue by LightningFerix** [Tiviacz1337/Travelers-Backpack#687]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 1.16.5-5.4.31 (travelers-backpack-1.16.5-5.4.31.jar)

1. Describe the bug 

The entire server will not even start because it crashes during startup. 

2. Write steps to reproduce the bug

Have a brand new Fabric server. Put Traveler's Backpack, Cardinal Components, Cloth Config, Fabric API, and Trinkets in the mods folder. Nothing else. Start server.

3. What is expected behaviour 

The expected behavior is for the server to start and not crash.

4. Screenshots (If applicable)

Here is a log showing the server crash

[latest.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/12226261/latest.log)

**Comment by Tiviacz1337** [comment]
install cloth api

**Comment by Tiviacz1337** [comment]
try reinstalling server

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/versions
