### ISSUE TITLE
Re Dye backpack sleeping bags

### ISSUE THREAD

**Issue by Exaioh** [Tiviacz1337/Travelers-Backpack#688]
Currently, your backpack is stuck with whatever sleeping bag it has.

right-clicking it with dye when it is unrolled should dye the sleeping bag on the backpack, or in the crafting menu put a new sleeping bag to replace it

**Comment by Tiviacz1337** [comment]
you have to make another sleeping bag and then right click on placed backpack to swap sleeping bag
