### ISSUE TITLE
Game crash when attempt to show content of backpack from Curio Slot

### ISSUE THREAD

**Issue by Aspyro** [Tiviacz1337/Travelers-Backpack#692]
Modloader: Forge 47.1.3
Mod version: 9.1.4
Modpack : ATM9 v0.0.45 (no modification)

Problem: 
- Upgraded Leather Bat Backpack up to Gold Bat Backpack. Equiped it in Back slot. When pressing hotkey to show content while hovering over the slot, game crashed. Backpack was still empty. Backpack provided night vision was On.

I just reloaded the game, went to my inventory, hovered over the backpack in the curio slot, tried to show content with hotkey (CTRL) and it crashed again.

Here is first game crash report : [Gist](https://gist.github.com/Aspyro/34b5dd53939bece7db665f470a46305a)
Both of the crash reports are exactly the same

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
https://modrinth.com/mod/travelersbackpack/versions
Fixed
