### ISSUE TITLE
Can't upgrade in Smithing Table

### ISSUE THREAD

**Issue by NephiDragon** [Tiviacz1337/Travelers-Backpack#693]
Fabric 1.20

Cannot upgrade backpack in Smithing Table. I put the backpack and the upgrade template in the slots but there is no output.
It could be a mod interaction but I tried disabling my other smithing table-related mods and still cannot upgrade backpack.

standard to iron:
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/125164120/9b0f515b-5df6-43b2-a0ee-07048d406b4d)

iron to gold:
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/125164120/a22200ef-4c7f-4e47-8c6e-37d9a68a9e61)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/125164120/66b61583-d8a7-4f9b-8f10-4987620347d7)

etc

**Comment by Tiviacz1337** [comment]
you have to put leather in template slot, its written in upgrde description

**Comment by davweiss** [comment]
> > you have to put leather in template slot, its written in upgrde description
> 
> Thanks; I don't know how I missed that. It works with the Iron to Gold, and past that but when I try leather + standard backpack + iron upgrade it tells me "Item can't be upgraded this way" is there something different for the first upgrade?
> 
> ![image](https://private-user-images.githubusercontent.com/125164120/258807698-0ce02be8-a6d6-4534-bbab-8358254245cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NTA1NTAsIm5iZiI6MTcwNDY1MDI1MCwicGF0aCI6Ii8xMjUxNjQxMjAvMjU4ODA3Njk4LTBjZTAyYmU4LWE2ZDYtNDUzNC1iYmFiLTgzNTgyNTQyNDVjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxNzU3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmEyNGFiNmY0MWQ4OTc5MmUwODY4MTA2NGMyMGRiOWQzMWU4NWFmMTNlZDAxMzY3MjEyYmY5ZTk0OGFjYWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZkuxgBiB_tDdt2HEIGbGBlgai4K_kaHX6b2h7CNFm-w) ![image](https://private-user-images.githubusercontent.com/125164120/258807622-66ab6012-1d07-49a5-ae1a-cea7c3efb529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NTA1NTAsIm5iZiI6MTcwNDY1MDI1MCwicGF0aCI6Ii8xMjUxNjQxMjAvMjU4ODA3NjIyLTY2YWI2MDEyLTFkMDctNDlhNS1hZTFhLWNlYTdjM2VmYjUyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxNzU3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjVlMjQ4YWRiYmZmMDA0NDZlYTU3NDYyODEzOTlkOGYyZmMyMjk5NWFhZTNlOGUwYmE2Yjc2YzAwNjBjZjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KQc_YLmI6SeAZZL7jrIScfgMiRrvNG5UQJcaTWOl_lY)

I have the same Problem, i can't upgrade with the iron upgrade.
Upgrade with gold, diamond and netherite works
Version: 1.20.1-9.1.9

**Comment by Tiviacz1337** [comment]
open backpack, so it'll initiate it's data, then upgrade
