### ISSUE TITLE
Backpack Already equipped 

### ISSUE THREAD

**Issue by Seal4093** [Tiviacz1337/Travelers-Backpack#696]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1.20.1 version of mod is 9.1.2

1. Describe the bug 

Sometimes out of nowhere ur backpack goes off ur body in F5 U still have the effect if ur enabling ability, but u cant open the backpack if u die or clear ur self its still on u but not on u u try to but on a new backpack but u cant because theres apperantly one already on you even though there isnt 

2. Write steps to reproduce the bug

i think if u tp super far away and back this happens but not fully sure what caused this to happen

3. What is expected behaviour 

it says backpack is already equipped even though u dont have it on and it wont open

4. Screenshots (If applicable)
as u can see i have magma backpack but i cant open it nor is it on my minecraft character 
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/115389407/758e1ea7-a4e3-48d9-8c20-7b27283644b9)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/115389407/52b8f947-ffae-4d17-a506-562b4dd61efa)

**Comment by Tiviacz1337** [comment]
There must be some compatibility issue, since I can't reproduce issue in my dev envirnoment and as I see you play with few mods

**Comment by Seal4093** [comment]
> There must be some compatibility issue, since I can't reproduce issue in my dev envirnoment and as I see you play with few mods



> 0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
> 
> 1.20.1 version of mod is 9.1.2
> 
> 1. Describe the bug
> 
> Sometimes out of nowhere ur backpack goes off ur body in F5 U still have the effect if ur enabling ability, but u cant open the backpack if u die or clear ur self its still on u but not on u u try to but on a new backpack but u cant because theres apperantly one already on you even though there isnt
> 
> 2. Write steps to reproduce the bug
> 
> i think if u tp super far away and back this happens but not fully sure what caused this to happen
> 
> 3. What is expected behaviour
> 
> it says backpack is already equipped even though u dont have it on and it wont open
> 
> 4. Screenshots (If applicable)
>    as u can see i have magma backpack but i cant open it nor is it on my minecraft character
>    ![image](https://user-images.githubusercontent.com/115389407/258912113-758e1ea7-a4e3-48d9-8c20-7b27283644b9.png)
>    ![image](https://user-images.githubusercontent.com/115389407/258912387-52b8f947-ffae-4d17-a506-562b4dd61efa.png)

Just figured out how to fix just delete ur player data make sure everything that u have in ur enderchest or in invetory is in a chest and then delete it find ur player uuid and delete this will clear the invis backpack and make it able for you to put on a backpack u WILL lose everything u did have in the glitched backpack

**Comment by Seal4093** [comment]
> There must be some compatibility issue, since I can't reproduce issue in my dev envirnoment and as I see you play with few mods

Just figured out how to fix just delete ur player data make sure everything that u have in ur enderchest or in invetory is in a chest and then delete it find ur player uuid and delete this will clear the invis backpack and make it able for you to put on a backpack u WILL lose everything u did have in the glitched backpack
