### ISSUE TITLE
crash with mythril drill from mythic metals

### ISSUE THREAD

**Issue by temyy** [Tiviacz1337/Travelers-Backpack#697]
Quilt Loader 0.19.2, mod version 1.20.1-9.1.2

when putting an enchanted Mythril drill from Mythic Metals in the tool slots your game crashes

expected behaviour is the game not crashing
[crash-2023-08-12_01.02.02-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/12325602/crash-2023-08-12_01.02.02-client.txt)

**Comment by Tiviacz1337** [comment]
can't reproduce 
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/34790800/84b3e590-0ef8-42c1-bd42-b8bdd3426ef8)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/34790800/9b8e79ec-2118-4d79-a9bd-b93da19d3ee5)
