### ISSUE TITLE
Backpack Content is gone when mined with Hammer Mod tools

### ISSUE THREAD

**Issue by Dwitch87** [Tiviacz1337/Travelers-Backpack#698]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 1.20.1 - 47.1.3
TravelersBackpack-1.20.1-9.1.4
TheHammerMod-1.20.1-beta3

1. Describe the bug 
When you mine the backpack from the floor with a hammer (The Hammer Mod) the content of this backpack is gone.

2. Write steps to reproduce the bug
Place backpack, with items, anywhere, like on the floor. Then take hammer (The Hammer Mod) and get the backpack from the floor.
When you look into the dropped backpack, the content is gone.
Link to Mod - The Hammer Mod: https://www.curseforge.com/minecraft/mc-mods/the-hammer-mod

3. What is expected behaviour 
I expect, that the backpack will be dropped without loosing the content.

4. Screenshots (If applicable)
No screenshots, just a empty backpack

**Comment by Tiviacz1337** [comment]
I can't even investigate the issue, because the mod cannot be added to my dev environment and whole mode source is not public

**Comment by Tiviacz1337** [comment]
but probably it has to be reported to the hammer mod devs
