### ISSUE TITLE
Equipping Backpack crashes the game

### ISSUE THREAD

**Issue by Neubulae** [Tiviacz1337/Travelers-Backpack#699]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric, 9.1.2

1. Describe the bug 
Equipping the backpack crashes the game.

2. Write steps to reproduce the bug
1.Equip the backpack
2.Crash

3. What is expected behaviour 
Crashn't?

4. Logs
[crash-2023-08-15_05.01.08-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/12339720/crash-2023-08-15_05.01.08-client.txt)

**Comment by Tiviacz1337** [comment]
wht is your fabric version?

**Comment by Neubulae** [comment]
> wht is your fabric version?

do you mean Fabric API? 0.86.1

**Comment by Tiviacz1337** [comment]
any steps how to reproduce issue? does it crash even if its standard leather tier backpack?>

**Comment by Neubulae** [comment]
I suppose yes, I only tested a few backpacks tho.
Some assistance on discord tells me the code `stacc-api`'s complaining is here https://github.com/Devan-Kerman/Stacc/blob/master/src/main/java/net/devtech/stacc/mixin/RenderItemCountFixin.java
I suppose this might be a conflict issue between Traveler's Backpack and Stacc API...?

**Comment by Tiviacz1337** [comment]
Yeah I guess so, since I can't reproduce this issue and I do not use stacc api

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/versions

**Comment by Tiviacz1337** [comment]
fixed
