### ISSUE TITLE
compatible

### ISSUE THREAD

**Issue by FanRenLa** [Tiviacz1337/Travelers-Backpack#700]
Works with the Curios API.

If you can, you want to be able to implement it in all mc versions, not only in new versions.

**Comment by Tiviacz1337** [comment]
what versions do you mean? there's curios api support for all versions 1.16.5-1.20.1

**Comment by FanRenLa** [comment]
> 你的意思是什么版本？所有版本都支持 curios API 1.16.5-1.20.1

Yes, the popular version above 1.16, 1.12.2 can try Baubles.

**Comment by Tiviacz1337** [comment]
1.16.5, 1.17.1, 1.18.2, 1.19.2, 1.19.4, 1.20.1 have curios integration
