### ISSUE TITLE
Building Wands compatibility crash

### ISSUE THREAD

**Issue by PokeMiner20** [Tiviacz1337/Travelers-Backpack#702]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Using Fabric mod loader V 0.14.22 in MC Version 1.20.1
Backpack Version 9.1.2 and Building Wands V 2.6.8

1. Describe the bug 
The game crashes when I add a modded tool into the tool section of the backpack. most times accidentally as I am shift clicking them into my backpack's inventory

2. Write steps to reproduce the bug
With the "Building Wands" mod V 2.8.6 the game crashes when the Items from this mod enter the 'Tool Slot' within my Backpack. 

3. What is expected behaviour 
Modded tool shouldn't crash the game, but does.

4. Logs
[crash-2023-08-19_22.57.26-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/12387151/crash-2023-08-19_22.57.26-client.txt)

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/versions
fixed
