### ISSUE TITLE
DisableCrafting setting in the config does not work

### ISSUE THREAD

**Issue by dre3002** [Tiviacz1337/Travelers-Backpack#704]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

fabric-loader-0.14.22-1.20.1
Mod version: travelers-backpack-1.20.1-9.1.2.jar (Fabric)

1. Describe the bug 

After disabling crafting in the config, I am still able to use the backpacks crafting table in game. I am not opped and I am in survival mode with cheating disabled, and it will still let me craft in the backpack. When hovering over the item I am about to craft, the text "Crafting disabled" will display over the name of the item. See screenshot for clarity. 

2. Write steps to reproduce the bug

Change line 4 in the travelersbackpack.jason5 config from "disableCrafting": false," to "disableCrafting": true,
Attempt to craft item in game

3. What is expected behaviour 

Backpack crafting grid should be fully disabled when line 4 in the config is set to "true" and prevent the player from crafting any items. A bonus would be to have the whole backpack crafting grid UI/settings/overlay removed if the "disableCrafting" is set to "true" and have all slots be blue (just to provide a cleaner look and less confusion for players who attempt to craft but nothing happens). 

4. Screenshots (If applicable)

[Crafting disabled](https://prnt.sc/bMsvc-b1rWjd)

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/versions
fixed
