### ISSUE TITLE
There is an upper limit on the number of backpacks you can carry

### ISSUE THREAD

**Issue by GuZhu0710** [Tiviacz1337/Travelers-Backpack#705]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

   Version 2.10

1. Describe the bug 
     If you enter the end earth or the lower realm, the number of backpacks you carry, not including those you have already worn, can only bring 3 in total. If you go beyond that, you will have a slow effect, and the slow effect cannot be eliminated. The more backpacks you bring, the higher the slow effect level will be. (This situation will randomly occur in one of the two places entering the End Earth and the lower realm, and there is no such situation in the main world for the time being)

 

2. Write steps to reproduce the bug

3. What is expected behaviour 

4. Screenshots (If applicable)

![2023-08-23_18 31 46](https://github.com/Tiviacz1337/Travelers-Backpack/assets/142987642/35accdf8-5a7f-4ac7-b6b8-04ed12a9206b)
![2023-08-23_18 31 59](https://github.com/Tiviacz1337/Travelers-Backpack/assets/142987642/1787e534-68e8-42ea-92c1-21370459c675)
![2023-08-23_18 32 18](https://github.com/Tiviacz1337/Travelers-Backpack/assets/142987642/8ccfc980-188f-4506-89b7-4dae028d06d8)

**Comment by Tiviacz1337** [comment]
forge/fabric

**Comment by Tiviacz1337** [comment]
slowness effect is applied because as default player cant hold as mny bckpacks he wants, you can disable or configure this effect in config its intentional feature
