### ISSUE TITLE
(1.18.2 Forge) sided_setup error

### ISSUE THREAD

**Issue by TheEffortFighter** [Tiviacz1337/Travelers-Backpack#706]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge version 40.2.0 and TravelersBackpack-1.18.2-7.1.38

1. Describe the bug 
(Shown in screenshot)

2. Write steps to reproduce the bug
Launch the game with the mod installed

3. What is expected behaviour 
The game loads in with no issues, the thing is the game works sometimes, sometimes it does what's in the screenshot.

4. Screenshots (If applicable)
Screenshot:
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/82852195/2f85a488-6223-415e-bcb8-7d39e2eb0fbd)
Crash logs:
[crash-2023-08-24_15.10.13-fml.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/12432764/crash-2023-08-24_15.10.13-fml.txt)

**Comment by Tiviacz1337** [comment]
probably compat issue, you have to check if issue occurs with tb only
