### ISSUE TITLE
Game crashes when trying to load world

### ISSUE THREAD

**Issue by AmePizza** [Tiviacz1337/Travelers-Backpack#707]
I'm using Fabric with Mod version 1.20.1-9.1.2
Whenever I try to load my world it will get to the "Joining world..." screen and the game will crash.
Steps to recreate: Load the game, open a world.
The expected behavior is for the world to load.
[crash-2023-08-25_13.16.49-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/12442273/crash-2023-08-25_13.16.49-client.txt)

**Comment by gorbodoh** [comment]
I have the same error message. Attached crash report. 
[crash-2023-08-29_23.04.39-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/12466105/crash-2023-08-29_23.04.39-client.txt)

**Comment by Tiviacz1337** [comment]
does it occur with travelers backpack installed only?

**Comment by gorbodoh** [comment]
Hi, I am currently away from PC so not able to test now, but my insights from my testing were that, if there are missing items (from removed mods, obsolete in new version, etc.), the backpack renderer will attempt to render it and throw error, rather than deleting the item.

For your case, I shall test without other mods in 12 hours, and update you. Thanks.

**Comment by AmePizza** [comment]
> does it occur with travelers backpack installed only?

For my case, yes. When I removed the mod and tried it the world opened flawlessly. But when I reinstalled it and tried again it would load but I would lose the backpack. So I'm hoping to fix this so I can open the world backup and play without losing the backpack.

**Comment by Tiviacz1337** [comment]
I dont understand what's the problem here, you removed the mod so backpack disappeared and that's normal behaviour

**Comment by AmePizza** [comment]
> I dont understand what's the problem here, you removed the mod so backpack disappeared and that's normal behaviour

Correct, without the mod the world loads fine.

**Comment by AmePizza** [comment]
> > 
> 
> Hi, it doesn't occur for me if only backpack mod is installed. However I can confirm that with items from other removed mods in the backpack, it will throw this error.

Interesting. I'm pretty sure I have every mod from the last load still installed.

**Comment by AmePizza** [comment]
So, I have checked the nbt data using an external program and the only thing in the backpack that is mod-related is the hose for this mod. Could that be causing the issue?

**Comment by Tiviacz1337** [comment]
> So, I have checked the nbt data using an external program and the only thing in the backpack that is mod-related is the hose for this mod. Could that be causing the issue?

is it in the tool slot?

**Comment by Tiviacz1337** [comment]
I was finally able to reproduce this issue, seems like textRenderer is null, will be fixed in the next update

**Comment by Tiviacz1337** [comment]
just one more question, anyone who experience issue is using 1.20.1?

**Comment by gorbodoh** [comment]
I encountered the issue in 1.20.1!

**Comment by AmePizza** [comment]
The hose was not in the tool slot. I am using 1.20.1. Good to hear you found the issue! ETA on release?

**Comment by Tiviacz1337** [comment]
The update should be available by monday or tuesday

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/versions
fixed
