### ISSUE TITLE
[Suggestion] Changeable Bed Colors

### ISSUE THREAD

**Issue by andw20** [Tiviacz1337/Travelers-Backpack#708]
**Is your feature request related to a problem? Please describe.**
What the title of this is. Since 1.20 you can now change the color of the beds with dyes, maybe a feature that you can craft different colored sleeping bag and able to change the color of it

**Comment by Tiviacz1337** [comment]
you can craft different colored sleeping bags

**Comment by Tiviacz1337** [comment]
it'll be added in the next update

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack
Added
