### ISSUE TITLE
Backpack anti sort slot and reserve slots are not working

### ISSUE THREAD

**Issue by Kiwi-Co** [Tiviacz1337/Travelers-Backpack#709]
Versions:
- Travelers-backpack-1.19.2-8.2.26
- Fabric-loader-0.14.19-1.19.2
- Minecraft 1.19.2

Bug: Title

Video:
https://github.com/Tiviacz1337/Travelers-Backpack/assets/111125019/30a0da03-455d-415a-b1b5-46c0bb7bb7a0

Other server-side mods:
1. ad_astra-fabric-1.19.2-1.12.6.jar
2. artifacts-7.1.1+fabric.jar
3. balm-fabric-1.19.2-4.5.7.jar
4. botarium-fabric-1.19.2-1.8.2.jar
5. c2me-fabric-mc1.19.2-0.2.0+alpha.9.9.jar
6. cc-restitched-1.101.2.jar
7. cccbridge-1.4.1-fabric.jar
8. charmofundying-fabric-6.0.0+1.19.2.jar
9. cloth-config-8.2.88-fabric.jar
10. CraftTweaker-fabric-1.19.2-10.1.41.jar
11. create-fabric-0.5.0.i-1003+1.19.2.jar
12. dehydration-1.3.4.jar
13. do-a-barrel-roll-2.6.2+1.19.2-fabric.jar
14. EnchantingInfuser-v4.2.2-1.19.2-Fabric.jar
15. fabric-api-0.76.0+1.19.2.jar
16. fabric-end-remastered-5.2.0.jar
17. farmers-delight-fabric-1.19.X-1.3.9.jar
18. ferritecore-5.0.3-fabric.jar
19. geckolib-fabric-1.19-3.1.40.jar
20. hardcorerevival-fabric-1.19.2-9.0.2.jar
21. IngredientExtensionAPI-fabric-1.19.2-3.0.6.jar
22. krypton-0.2.1.jar
23. lazydfu-0.1.3.jar
24. lithium-fabric-mc1.19.2-0.11.1.jar
25. memoryleakfix-fabric-1.17+-1.0.0.jar
26. PuzzlesLib-v4.3.12-1.19.2-Fabric.jar
27. resourcefulconfig-fabric-1.19.2-1.0.20.jar
28. resourcefullib-fabric-1.19.2-1.1.24.jar
29. servercore-1.3.3-1.19.2.jar
30. SimpleAnimatedGuns-FR-1.19.2-v1.2.jar
31. starlight-1.1.1+fabric.ae22326.jar
32. Terralith_1.19.3_v2.3.8.jar
33. travelers-backpack-1.19.2-8.2.26.jar
34. TreeChop-1.19.2-fabric-0.17.6.jar
35. trinkets-3.4.1.jar
36. xp_obelisk-0.4.9-r+1.19.2-Fabric.jar
37. youre-in-grave-danger-1.4.9.jar

**Comment by Tiviacz1337** [comment]
you have to check with travelers backpack only, cant reproduce it must be compat issue

**Comment by Kiwi-Co** [comment]
It still doesn't work
mods:
  travelers-backpack-1.19.2-8.2.26
  fabric api-0.73.2+1.19.2
  trinkets-3.4.2
  cloth-config-8.2.88

**Comment by Kiwi-Co** [comment]
Tested with trinket-
It gave an error saying it needs cardinal component mod.
It still dint work but worked with crafting widgets turned off.

**Comment by Tiviacz1337** [comment]
is it possible for you to update fabric api to latest version for 1.19.2?

**Comment by Tiviacz1337** [comment]
Okay, you don't have to test it, I've found the issue

**Comment by Kiwi-Co** [comment]
And the other thing I noticed was that when you enable crafting and anti sort any slot the item at 1 slot below and 2 slots to the right will get the effect.

**Comment by Kiwi-Co** [comment]
When will the new version release?

**Comment by Tiviacz1337** [comment]
for forge, probably today or tomorrow, for fabric probably in the next week

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
https://modrinth.com/mod/travelersbackpack/versions
Fixed for Forge

**Comment by Kiwi-Co** [comment]
Suggestion: Remove crafting widget icon when craftingdisabled is true in the config. version travelers-backpack-1.19.2-8.2.27

**Comment by Kiwi-Co** [comment]
Any update on the release date?

**Comment by Tiviacz1337** [comment]
today

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack

**Comment by Kiwi-Co** [comment]
Unsortable slots seems to work but reserved slots doesn't. I am able to place other items on that slot.

**Comment by Tiviacz1337** [comment]
reserving slots does not block ability to place other items there, just when you shift click it goes first to reserved slot, or when you transfer from player -> backpack
