### ISSUE TITLE
I'm not getting the slowness effect even with lots of backpacks in my inventory

### ISSUE THREAD

**Issue by seriousfreezing** [Tiviacz1337/Travelers-Backpack#710]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric and 1.19.2 (8.2.26)

1. Describe the bug 
I'm not getting the slowness effect with too many backpacks in my inventory

2. Write steps to reproduce the bug
Grab several backpacks in creative mode and off you go

3. What is expected behaviour 
Having the slowness effect

4. Screenshots (If applicable)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/66693072/f9b87e2b-4025-4519-bb28-4ae9f8e8d879)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/66693072/8b0e6410-a4ea-4140-a10f-aed78cec9ebc)

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/versions

**Comment by Tiviacz1337** [comment]
fixed
