### ISSUE TITLE
 fabric server does not start

### ISSUE THREAD

**Issue by henqu3** [Tiviacz1337/Travelers-Backpack#711]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1.16.5-5.4.31-fabric

1. Describe the bug 

when I put mod the server does not start

[problem.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/12506178/problem.txt)

**Comment by Tiviacz1337** [comment]
install cloth api

**Comment by Tiviacz1337** [comment]
it'll be added as dependency in next update

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/versions
