### ISSUE TITLE
Spectrum Potions not saving when added to backpack fluids

### ISSUE THREAD

**Issue by Shibva** [Tiviacz1337/Travelers-Backpack#712]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.19.2 -0.14.22

1. Describe the bug 
The fluid data is not saving the status effects in the bag

2. Write steps to reproduce the bug
- 1. install spectrum and its dependencies off of Modrinth (preferably the alpha releases 
- 2. once in world grant yourself all advancements (this is necessary since the mod is progression based via advancements, giving yourself all of them unlocks everything
- 3. Place a Potion Workshop 
- 4. place nether wart and a ghast tear in the 3 slots forming a triangle and a Mermaid's Gem at the bottom slot shaped like it. in the last independent slot far right of the UI put 3 bottles in here; this will make a Pigment Potion that bears the effects of base regeneration
- 5.  take brew and put it into a backpack
- 6.  hover over the tank and see that the effects are lost

3. What is expected behaviour 
This might be due to how its a custom potion base of sorts; as in it relies on NBT data and the tanks might not be storing sed nbt data; hence causing it to not save correctly and wipe the effects off of it.

4. Screenshots (If applicable)

**Comment by DaFuqs** [comment]
Spectrums potions use the vanilla `CustomPotionEffects` nbt tag to store their effects, instead of being fixed potion items.
