### ISSUE TITLE
Backpacks dissapear

### ISSUE THREAD

**Issue by Tanus11** [Tiviacz1337/Travelers-Backpack#713]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 43.2.8 Minecraft 1.19.2 
Version 8.2.31

1. Describe the bug 
Backpacks placed in the world disappear upon breaking

2. Write steps to reproduce the bug
Break a Backpack

3. What is expected behaviour 
Backpack gets dropped on the floor

4. Screenshots (If applicable)

**Comment by Tanus11** [comment]
After switching back to the version 8.2.30 the backpacks drop again

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
https://modrinth.com/mod/travelersbackpack/versions 
fixed
