### ISSUE TITLE
Backpack Disappears when mined to pick up.

### ISSUE THREAD

**Issue by mojolewis** [Tiviacz1337/Travelers-Backpack#714]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 1.19.2

1. Describe the bug 
Backpack disappears with all of stuff when mined to pick up

2. Write steps to reproduce the bug
Die/ place bag down.
Try to pick it up.

3. What is expected behaviour 

4. Screenshots (If applicable)
[Paige and Josh's 1.19.2.zip](https://github.com/Tiviacz1337/Travelers-Backpack/files/12570990/Paige.and.Josh.s.1.19.2.zip)
This is the custom modpack we used.

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
https://modrinth.com/mod/travelersbackpack
finally fixed
