### ISSUE TITLE
Master level swamp villager does not have mending book for trade

### ISSUE THREAD

**Issue by FuttBucker3000** [Tiviacz1337/Travelers-Backpack#715]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 0.14.22 
Minecraft 1.20.1
travelers-backpack-1.20.1-9.1.3.jar

1. Describe the bug 
It seems that the villager backpack trade from a master level swamp librarian has bumped out the mending book from the trade pool. I'm not sure if the same applies to all the different biome librarians, but after leveling to master, the only two trades available are the name tag, and the villager backpack.  

2. Write steps to reproduce the bug
I've tested with 10 swamp villagers in survival, and 12 plains villagers in creative, none of which had the master level enchanted book. 

3. What is expected behaviour 

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
you can disable backpack trade in config

**Comment by FuttBucker3000** [comment]
How would I go about doing that? I have mod menu and menulogue, but the config option on travelers backpack is greyed out.

**Comment by Kiwi-Co** [comment]
Press crtl + r -> %appdata% -> .minecraft -> config -> travelersbackpack.json5 -> "enableVillagerTrade": = false

**Comment by FuttBucker3000** [comment]
I’m stupid and thought that new villager book update was in 1.20.1, but it was actually 1.20.2 where they add biome specific books.

**Comment by krrg** [comment]
Sorry to necro a closed issue, but I was using 1.20.2 with experimental villager trades on, and the backpack trade definitely broke the ability to get the Master level book (using the Fabric version of the mod). It would be nice if we could have the backpack trade turned on, and still have the ability to get the highest level books from Master librarians in the swamp, but it was easy enough to disable in config once I realized the problem.

This will become particularly problematic if/when the new villager trading ever becomes the default.
