### ISSUE TITLE
Backpacks/Shulkers

### ISSUE THREAD

**Issue by MelodyMcKenna** [Tiviacz1337/Travelers-Backpack#716]
**0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)**
Fabric loader 1.20.1
Mod version 1.20.1-9.1.3

**1. Describe the bug** 
Backpacks can be stored in shulker boxes using droppers.
Shulkers can be stored in Backpacks using droppers.

The Sack item from the Supplementaries (version 1.20.2.5.28) mod can also be stored in backpacks using droppers.

**2. Write steps to reproduce the bug**
- Place a backpack in a dropper
- Place a shulker box in front of the dropper
- Power the dropper to transfer the backpack into the shulker box.

**3. What is expected behaviour**
Backpacks and shulkers are unable to be stored in each other.

**4. Video**

https://github.com/Tiviacz1337/Travelers-Backpack/assets/29812480/27d170eb-fc4e-4599-975b-9e06c913e5a8

https://github.com/Tiviacz1337/Travelers-Backpack/assets/29812480/9dac495f-ed17-4664-bc89-4c6344cb1b35

**Comment by Tiviacz1337** [comment]
fixed
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/versions
