### ISSUE TITLE
Bee backpack and endermen

### ISSUE THREAD

**Issue by Efimero** [Tiviacz1337/Travelers-Backpack#717]
Minecraft 1.20.1
Fabric 0.14.22
TB 9.1.4

When using the bee backpack, endermen will not get poisoned.

Equip a bee backpack, punch an enderman, observe they do not get poisoned.

They should get poisoned like other mobs that can be poisoned by a splash potion of poison.

That's all. <3

**Comment by Tiviacz1337** [comment]
do you have ability enabled?

**Comment by Efimero** [comment]
> do you have ability enabled?

yes, definitely

**Comment by Tiviacz1337** [comment]
I just tested and endermans get poisoned like any other mob, if Traveler's Backpack is only mod. Probably some interaction like you've just said
