### ISSUE TITLE
Compatibility/Integration for Inventory Profiles Next (I.P.N.)

### ISSUE THREAD

**Issue by MomaiBlaze** [Tiviacz1337/Travelers-Backpack#718]
(First time using Github's issue feature, so sry if I end up doing something wrong ;-;)
 **Is your feature request related to a problem? Please describe.**
 When sorting through my backpack in a modded playthrough, I noticed that the backpack buttons relating to moving items to and from the backpack seemed to ignore the locked slots feature I had been utilizing from the Inventory Profiles Next mod (IPN).
 the locked-slots were supposed to only allow items to be removed from said slots when the player manually selected and dragged the items out from the slots using the mouse. Instead, using the move to/from backpack buttons took everything from my inventory that it could hold and dumped everything into any empty slot respectively, regardless of the slot locking feature's application.

**Describe the solution you'd like**
Thus, I request Compatibility and Integration for the I.P.N. mod, though I have very little understanding of the difficulties involved in this endeavor.

**Describe alternatives you've considered**
Sadly, I have not considered any alternatives to this, though I could not think of many (if any) anyway.
I hope I may come across a similar request forum for the I.P.N. mod, so I may request the same of them.

**Additional context**
(I've linked a clip I made of the problem in demonstration down below)

https://github.com/Tiviacz1337/Travelers-Backpack/assets/83843813/a029ad93-aa0f-4a35-be55-4f4b99b56949

I can wait as long as necessary (though I would find it nice for integration to be added sooner rather than later...)

**Comment by Catomax262** [comment]
HOLY MOLY POWER ITEMS FROM TOUHOU????
