### ISSUE TITLE
Optionally Remove Tanks

### ISSUE THREAD

**Issue by Cerbiac** [Tiviacz1337/Travelers-Backpack#720]
**Is your feature request related to a problem? Please describe.**
The tanks on the side of the backpacks are visually obstructive and clunky at times.

**Describe the solution you'd like**
An option for the backpacks not to have tanks, at least visually. Tanks would possibly become an upgrade.

**Describe alternatives you've considered**
Getting comfortable with the existing design for its functionality and other qualities.

**Additional context**
I'm deciding on cozy storage solutions for a mod pack. I understand this is a highly subjective issue, and at times I do enjoy the tanks for both their functionality and visual design. The 3D models and custom models of the backpacks are really cute. Nonetheless, it seems like a great feature to give more expression for its users.

**Comment by Tiviacz1337** [comment]
you mean in gui or visually on model?

**Comment by Cerbiac** [comment]
> you mean in gui or visually on model?
Visually on model
