### ISSUE TITLE
Where's my backpack if I felt in the void?

### ISSUE THREAD

**Issue by JuandiPro190** [Tiviacz1337/Travelers-Backpack#723]
Accidentally fell into the void at the end. I have other mods like the "Corail Tombstone" which allows me to save my inventory in a tomb. But it happens that the backpack that I equip is not stored in the tomb, but usually it is placed at the side of the tomb. When I fell into the void, the tomb only appeared in the center of the end, specifically where the dragon egg appears when you finish the dragon. My backpack did not appear there. I also have other mods like the Stellarity mod that enlarges the end, in case that's important.

**Comment by JuandiPro190** [comment]
And I have another question, about the same problem, in case the first solution you present is for me to use the /tb restore command. How do I highlight which is the code of the dongle I was using at that time specifically, because I use ATERNOS, and when I enter the "worlds" folder and look for the UUID code I get many, and they all recover me a different dongle, I would not know which one was the one I lost at that time.

**Comment by Tiviacz1337** [comment]
the proper backpack uuid code is printed to console while player dies.
if you die in void backpack should levitate above y = 0 on the coordinates you died
