### ISSUE TITLE
The villager's trading NBT will copy the player's backpack NBT information

### ISSUE THREAD

**Issue by xiaofan7520** [Tiviacz1337/Travelers-Backpack#725]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
1.20.1 Forge-47.1.47
1.20.1 mohist-1.20.1-426-server
TravelersBackpack-1.20.1-9.1.7

1. Describe the bug 
If villager's trading NBT have "minecraft:air", This mod will copy all the information of the first to join the player's backpack in this NBT

2. Write steps to reproduce the bug
1;Get a backpack
2;Put something in your backpack and fill it with some fluid
3;Carry this backpack
4;Use command:"kill @e[type=minecraft:villager]"
5;Summon a villager and give it a job
6;Use any NBT viewing method to view the villager's "Recipes" NBT. For example use command:"data get entity @e[type=minecraft:villager,limit=1] Offers.Recipes"
7;You can see that each "minecraft:air" is followed by all the information on the backpack. It will look like this: "buyB: {id: "minecraft:air", Count: 0b, tag: {CraftingInventory:XXXXXX"

3. What is expected behaviour 
Do nothing

4. Screenshots (If applicable)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/91411649/5cb9a8e5-b695-42af-9efa-c1bce729cdd0)

**Comment by Tiviacz1337** [comment]
Fixed:
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
https://modrinth.com/mod/travelersbackpack/versions
