### ISSUE TITLE
[feature] Millibuckets as fluid units

### ISSUE THREAD

**Issue by N0aW** [Tiviacz1337/Travelers-Backpack#726]
**Is your feature request related to a problem? Please describe.**
There are 2 ways to measure fluid amounts in Minecraft, droplets and millibuckets.

Millibuckets are more easy-to read, while as droplets can be quite difficult to read.

**Describe the solution you'd like**
A config to switch between seeing the tank's fluid amount between millibuckets and droplets while hovering over the fluid tanks.

**Describe alternatives you've considered**
Try to read and understand the droplet fluid values

**Additional context**
None

**Comment by Tiviacz1337** [comment]
Forge uses milibuckets as fluid unit, fabric uses droplets as fluid unit
