### ISSUE TITLE
Standard Traveler's Backpack (Tier Netherite) Causing World Corruption.

### ISSUE THREAD

**Issue by jwols123** [Tiviacz1337/Travelers-Backpack#727]
Version: Fabric 1.19.2
NOTE: I do have some extra mods installed and Not Enough Crashes (to see what the problem easier).

Bug: My world is corrupted and I can no longer join it

Reproducing it: Go to the creative menu, hover over the standard traveler's backpack (tier netherite), and hold control to see the slots.

The game should crash, then after you re-open it and attempt to open the world again you will crash again.

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/147277357/8327a8d2-9baa-4b1f-82d2-12e80aa7be01)
The images below this text were me re-creating it.
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/147277357/a9e5ecf1-26dc-463f-83f5-cd4d23396a1a)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/147277357/0ec1ce88-8654-4a55-bf13-41d97a14b3f4)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/147277357/7419471e-c7e5-4f66-a199-ed40c4aec95f)
[crash-2023-10-07_14.46.44-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/12838774/crash-2023-10-07_14.46.44-client.txt)

**Comment by jwols123** [comment]
Side Note, Disabling the mod seems to allow you to play again.

**Comment by Alvareto136** [comment]
This exact thing happened to me, but it didn't corrupt my world.

**Comment by Tiviacz1337** [comment]
fixed
https://modrinth.com/mod/travelersbackpack/versions
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
