### ISSUE TITLE
TravelersBackpack-1.19.2-8.2.30 incompatible with endermanoverhaul-forge-1.19.2-0.0.1 Crashes on startup

### ISSUE THREAD

**Issue by Minebrah** [Tiviacz1337/Travelers-Backpack#731]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Forge 1.19.2

1. Describe the bug 

TravelersBackpack-1.19.2-8.2.30 incompatible with endermanoverhaul-forge-1.19.2-0.0.1

https://gist.github.com/Minebrah/a7c78426c12f49bc4b8b9de159895a53

2. Write steps to reproduce the bug

Startup minecraft
Crash

3. What is expected behaviour 

Not crash

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
crash will be fixed, althrough backpacks will not be obtainable from endermans

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all 
fixed
