### ISSUE TITLE
Bag equipped, not working, does not show in inventory equip slot, can not equip another bag

### ISSUE THREAD

**Issue by JeremiahAlexanderGriffin** [Tiviacz1337/Travelers-Backpack#735]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric medieval minecraft 1.19.2 v23

1. Describe the bug 
bag is equipped on character model, cannot equip another bag or put in backpack slot, crafted another bag still not working

2. Write steps to reproduce the bug
join server hosted my shockbyte, craft bag (working) log off for the night, next day not working at all

3. What is expected behaviour 
bag to function

4. Screenshots (If applicable)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/142932296/7d11ce3b-6b10-4f99-a79c-13749ba37c06)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/142932296/c79d697b-b56d-44ee-9dd4-fd85e56e15fa)

**Comment by Tiviacz1337** [comment]
if you equipped backpack by icon in backpcak inventory, it can only be unequipped by clicking unequip button in backpack inventory which can be opened by B keybind (default, you might need to change that to avoid conflicts). to use back slot you have to enable trinkets/curios integration in travelersbckpack config file

**Comment by TirToran** [comment]
My wife and I have this issue on our personal server. It isn't a problem as we've found that running      /tb access <player>     twice solves the issue.

We have to run it evertime we log in.  Just wanted to share our work around.
