### ISSUE TITLE
Cycle tools do not work nor do they appear on the back pack itself

### ISSUE THREAD

**Issue by jalferez** [Tiviacz1337/Travelers-Backpack#736]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Mod version 1.19.2

1. Describe the bug 

Tools do not switch or cycle while they are stored in backpack

2. Write steps to reproduce the bug
(this is how it happened to me)
-have a full back pack
-shift LMB weapon/tool
-disappears into the backpack
-open and close back pack and you cannot see the tools

3. What is expected behaviour 

To be able to see the tools and;/or cycle the tools 

4. Screenshots (If applicable)

![2023-10-20_23 13 42](https://github.com/Tiviacz1337/Travelers-Backpack/assets/119442928/96af9852-791e-446e-8ca5-e729452edd02)

![2023-10-20_23 13 42](https://github.com/Tiviacz1337/Travelers-Backpack/assets/119442928/0ddd32e1-10bd-4848-a4a8-c2d49251f76e)

**Comment by Tiviacz1337** [comment]
you are using outdated reousrcepack for traveler's backpack, there's new tool widget that appears above bucket slot

**Comment by jalferez** [comment]
Can you please tell me what the resource pack is? Its a mod pack and I'm not sure what the resource pack is

**Comment by Tiviacz1337** [comment]
sadly i don't know, I do not use any resourcepacks

**Comment by Tiviacz1337** [comment]
you can see where the button is on the curseforge site, because I updated the graphics. The button is in the same place you just dont see it because it does not have texture in resourcepack, so just click on the blank spot in the place of button and it will work the same way

**Comment by jalferez** [comment]
Okay yeah i see it! Thank you so much and sorry for the hassle!
