### ISSUE TITLE
CRAFTING GLITCH

### ISSUE THREAD

**Issue by oncearebelalwaysarebel** [Tiviacz1337/Travelers-Backpack#737]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Forge 1.16.5

1. Describe the bug 

Unable to craft; random items in inventory go into random slots in the backpack.

2. Write steps to reproduce the bug

Any attempts to move things into the crafting table within a backpack.

3. What is expected behaviour 

Be able to place items in the crafting grid rather than random items from inventory in random backpack slots.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
I dont undeerstand the issue

**Comment by oncearebelalwaysarebel** [comment]
See attached -- this is what happens the moment I open my backpack, random stuff will go in that were not there or moved in by me -- in this case, random items into the liquid slots and random items NEXT to the crafting table. When I try to move stuff TO the crafting table, it moves to random places out of nowhere.
![IMG_7380](https://github.com/Tiviacz1337/Travelers-Backpack/assets/148664606/12a82414-71ca-43b9-a2ac-9accdd0d03a3)
![IMG_7382](https://github.com/Tiviacz1337/Travelers-Backpack/assets/148664606/3aca1c84-ab74-4154-8813-3861f4dc1d1b)
![IMG_7383](https://github.com/Tiviacz1337/Travelers-Backpack/assets/148664606/ba13f4f1-988a-452b-a609-e627a0dfdc55)
![IMG_7384](https://github.com/Tiviacz1337/Travelers-Backpack/assets/148664606/8cce7ae5-9f4f-4d35-a1d7-07b6c5b71f2b)

**Comment by Tiviacz1337** [comment]
what exact mod version do you use and do you play on server

**Comment by oncearebelalwaysarebel** [comment]
1.16.5, playing on a server that otherwise is having no issues.

**Comment by Tiviacz1337** [comment]
do you have the same mod version on server and client

**Comment by oncearebelalwaysarebel** [comment]
Yes, it's actually on two servers and we're having the exact same problem on both, and this only happened when we updated the mod to its newest version.

**Comment by Tiviacz1337** [comment]
does it happen with newly created backpacks or old ones

**Comment by oncearebelalwaysarebel** [comment]
Haven't tried new ones yet, but with existing ones yes.

**Comment by Tiviacz1337** [comment]
Try to create new backpack and check if issue still occurs, if not then old backpacks have old data and it's probably causing some weird bugs
