### ISSUE TITLE
[1.19.2 Forge] Crashes with Recipe Book is Pain

### ISSUE THREAD

**Issue by DTech10** [Tiviacz1337/Travelers-Backpack#738]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Forge 1.19.12-43.3.0

1. Describe the bug 

 Crashes with Recipe Book is Pain

2. Write steps to reproduce the bug

Install Recipe Book is Pain
Load Minecraft
Crash

3. What is expected behaviour 

Not crash

4. Screenshots (If applicable)

imma send logs instead:
[Latest Log](https://mclo.gs/GaiLGEL)
[Crash Log](https://mclo.gs/r5dB8Mi)

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
fixed
