### ISSUE TITLE
Mod's recipe doesn't work (Fabric/Realm)

### ISSUE THREAD

**Issue by ugoHALFDAN** [Tiviacz1337/Travelers-Backpack#740]
Fabric 1.20.2-9.2.1

I play on a realm

None of the mod's recipe work. I've tried with only the mod and his dependencies and it doesn't work.

![Capture d'écran 2023-10-23 201647](https://github.com/Tiviacz1337/Travelers-Backpack/assets/52524020/65e7647a-4467-401b-aab4-cf54362c084d)

**Comment by Tiviacz1337** [comment]
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/34790800/240640c0-c6dc-4f01-ae57-244565a4e1c3)

**Comment by ugoHALFDAN** [comment]
Already try too, sorry :/
![Capture d'écran 2023-10-24 010609](https://github.com/Tiviacz1337/Travelers-Backpack/assets/52524020/f5411723-57e5-442b-9779-1690e5c6a524)
![Capture d'écran 2023-10-24 010638](https://github.com/Tiviacz1337/Travelers-Backpack/assets/52524020/8b262755-bdff-4911-9b0c-5f43e3b8e939)

**Comment by Tiviacz1337** [comment]
oh sorry it wont work on realm, you have to have forge server and mod installed on server too
