### ISSUE TITLE
add a way to dissable backpack rendering

### ISSUE THREAD

**Issue by Meow-purr** [Tiviacz1337/Travelers-Backpack#741]
**Is your feature request related to a problem? Please describe.**
im always frustrated that when using capes(from cosmetica) the backpack rends on top of them

**Describe the solution you'd like**
A way to disable renderig of the backpack

**Describe alternatives you've considered**
not rendering the backpack when a cosmetica cape is on

**Additional context**

**Comment by Tiviacz1337** [comment]
you could check first and see that there's actually disableBackpackRender config option

**Comment by Meow-purr** [comment]
i coundent find it in mod menu but ill go check the config

**Comment by cproo12** [comment]
Also worth noting it does not show in mod menu still, which had me confused as I was being lazy enough to not check the config file, but not lazy enough to look at git and complain. 😂

Update- it seems like this config option is gone- are there any plans of bringing this back? @Tiviacz1337

**Comment by Tiviacz1337** [comment]
Oh, Please open your equipped backpack -> click cog icon which represent backpack settings (top icon on the right side) -> then click eye icon to toggle visibility

**Comment by Tiviacz1337** [comment]
I completely forgot about this functionality, sorry enjoy
