### ISSUE TITLE
Array out of bounds at index 54. 

### ISSUE THREAD

**Issue by elpideus** [Tiviacz1337/Travelers-Backpack#743]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 

When I try to load into a world the game just crashes. This is the crashlog: https://pastebin.com/WrdC36hZ

2. Write steps to reproduce the bug
a) Load the mod.
b) Enter into a world.

3. What is expected behaviour 
Load the world and be able to play.

**Comment by elpideus** [comment]
The problem was https://www.curseforge.com/minecraft/mc-mods/extra-inventory

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack
Fixed
