### ISSUE TITLE
Item Vanished From Quick Storing to Backpack

### ISSUE THREAD

**Issue by GuardianMilky** [Tiviacz1337/Travelers-Backpack#744]
### Traveler's Backpack 9.1.6 for Fabric 1.20.1

1. Description
    - I have a "Legendary The Watcher" sword in my main inventory. I was holding shift to move the items to the backpack when all of a sudden, I noticed that the sword was gone.

2. Write steps to reproduce the bug
    - Open Backpack
    - Hold Shift + Hold Left-click and swipe through numbers of items in the inventory to move them to the backpack

**P.S: Might be hard to reproduce as I myself is having a hard time doing it again.**

3. What is expected behaviour 
    - All items should be stored in the backpack without anything missing.

**Comment by Tiviacz1337** [comment]
are you sure it is not stored in tool slots?
