### ISSUE TITLE
Enderderman Trav Backpack special ability not working 

### ISSUE THREAD

**Issue by pedroHenrique57** [Tiviacz1337/Travelers-Backpack#745]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
[1.20.2] Traveler's Backpack 9.2.2 (Fabric mod loader)

1. Describe the bug 
Enderderman Travel Backpack special ability is not working, Equip, unequip, activate or deactivate special ability button, none of this things make the adicional range work.

2. Write steps to reproduce the bug
 There are no steps i think 

3. What is expected behaviour 
The Backpack should provide an adicional range, in every situation that i tested, it not provides the range.

4. Screenshots (If applicable)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/102995361/efa56011-3c33-47c5-a925-a067f65989c1)
Ability is enable and i continue having 4.5 range distance (Minecraft java default range)

**Comment by Tiviacz1337** [comment]
I know, reach attribute mod is not ported yet for fabric 1.20.2

**Comment by LunarPidgeon** [comment]
Does not appear to be working at this time. Is the reach attribute something that Fabric modloader would have to impliment, or is that under your umbrella? Is there an expected timeframe for this to be fixed?
