### ISSUE TITLE
Craft Recepies not unlocked

### ISSUE THREAD

**Issue by tMuseCoding** [Tiviacz1337/Travelers-Backpack#748]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 48.0.33 
Minecraft 1.20.2 
Travelers Backpack 9.2.2

1. Describe the bug 
Crafting Recepies are not unlocked

2. Write steps to reproduce the bug
Collect Glass + Iron no Tank recepie unlocked. Collect everything to craft the backpack itself - no crafting recepie unlocked.
the recepies only get unlocked when the player crafts the item itself (eg. when the player crafts an backpack tank the player unlocks the recepie for that crafted backpack tank)

3. What is expected behaviour 
When the player had a key item (or every item) needed for a crafting recepie it should be unlocked so the player can look it up ingame.

examples for key items: 
craft a backpack tank to unlock the standard backpack recepie

**Comment by Chitovr** [comment]
Im using Fabric and my version is 1.20.1-9.1.8 and i tried to use it but nothing is popping up unless im in creative mode. I tried making the recipe myself with no directions and nothing pops up. I had everything i needed 2 iron and 7 glass but there was nothing. I need help. i used Modrinth.

**Comment by ShiftyKrispy** [comment]
> Im using Fabric and my version is 1.20.1-9.1.8 and i tried to use it but nothing is popping up unless im in creative mode. I tried making the recipe myself with no directions and nothing pops up. I had everything i needed 2 iron and 7 glass but there was nothing. I need help. i used Modrinth.

Im having the same problem with **Forge 1.19.3**, latest mod version **8.3.9**. Currently using the mod in a server and only one of my friends managed to make normal backpacks, no one else has, nor has anyone been able to make the other variations. no one can see the recipes for some reason, tho i also dont have a catalogue mod installed which might help, but we should still be able to see the default recipes regardless.

**Comment by Kaileft** [comment]
Has anybody found a fix for this I’m using forge 1.20.4 and I’m having the exact issue. I randomly was able to make a sleeping bag but nothing else.

**Comment by alexweber** [comment]
It's definitly annoying that the recipe isn't unlocked automatically the first time you craft a tank and maybe crafting glass unlocks the tank recipe so that this way progression can occur organically.

For what it's worth all recipes are explained in the wiki: https://github.com/Tiviacz1337/Travelers-Backpack/wiki/Crafting-Recipes

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all?page=1&pageSize=20
Added for Forge

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
Added for Fabric

Closing
