### ISSUE TITLE
[Issue] Accidentally misplaced my backpack in an unknown part of the world due to R-click backpack placement

### ISSUE THREAD

**Issue by Catomax262** [Tiviacz1337/Travelers-Backpack#749]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Minecraft 1.18.2
Forge 40.2.10
TB 7.1.44

1. Describe the bug 

Dude, it NEEDS to be off by default. I was traveling around my world with a jetpack at really high velocity, but now i placed my Netherite tier backpack on a part of the world that wasn't even generated, so i couldn't even know if i placed it at first.

3. Write steps to reproduce the bug

Not needed due of it being self explanatory

4. What is expected behaviour 

Instead of behavior, i propose solutions:
1. Turn it off by default, many mods add stuff with shift + r-click with empty hand interactions.
2. Add a temporary debug backpack tracker (it doesn't have to be complicated, just send chat message with coords)

5. Screenshots (If applicable)

**Comment by muon-rw** [comment]
This was a really goofy addition. I agree it should be off by default or made _abundantly_ more clear to the player that they might have just thrown all their items somewhere they’ll never find again.

**Comment by Tiviacz1337** [comment]
will be changed to off by default

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack
off by default
