### ISSUE TITLE
[Bug] Polymorph not properly displaying the morph button

### ISSUE THREAD

**Issue by Catomax262** [Tiviacz1337/Travelers-Backpack#750]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

MC 1.18.2
Forge 40.2.10
TB 7.1.44

1. Describe the bug 

For some reason, Polymorph compat was specified, but i can't see any Polymorph buttons.

2. Write steps to reproduce the bug

1. Open backpack and select crafting slots
2. Try to put an ingot and turn it into specific mod's nuggets
3. Only nuggets from ingot's original mod appear

4. What is expected behaviour 

For it to be fully compatible

5. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
compatibility probably won't be added
