### ISSUE TITLE
Odd inventory glitch 

### ISSUE THREAD

**Issue by Trains4242** [Tiviacz1337/Travelers-Backpack#752]
Forge download game version: 1.20.1 Forge version 47.1.3

When opening a backpack it moves around the inventory and to pix it i have to close the backpack then move something in my inventory

this is on a server and i im the only one with the issue 
no idea why its doing it

Clip showing bug: https://medal.tv/games/minecraft/clips/1BHhCgaJHBc8Qw/d133787XyLM8?invite=cr-MSwyakgsMjY1NDk3NDYs

**Comment by Tiviacz1337** [comment]
do you have the same mod vrsion like on the server
