### ISSUE TITLE
[Duping] If player poicks up backpack before server restart, they have 2 bags with all items when log back in.

### ISSUE THREAD

**Issue by Zunwolf1896** [Tiviacz1337/Travelers-Backpack#755]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric-api-0.90.0+ 1.20.1
travelers-backpack-1.20.1-9.1.8

1. Describe the bug 
If a player has a placed backpack, and a couple minutes before server restart they pick it up, when they log back in after the server boots, they both have the backpack in their inventory and the backpack on the ground, including all items that were in the backpack. 

2. Write steps to reproduce the bug
Have backpack placed on the ground, around 5-1  minutes before restarting the server, 
Pick up the backpack, so it is in your inventory right before the server restarts
Log back in once it boots up
The backpack will be on the floor where it was, and also in your inventory, with all items inside duped.

3. What is expected behaviour 
The bag is either just on the floor where it was before restart, or it is only in your inventory, not two of them. 

4. Screenshots (If applicable)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/88537204/efddcbbb-eb74-4c92-b961-2e6dce3a91d1)
< the players two backpacks with the duped tools. 
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/88537204/d643eb35-11fe-4d5b-9810-e55b5200e20c)
< the players inventory with both backpacks. 

This has happened with at least three players on the server.

**Comment by Tiviacz1337** [comment]
do you use trinkets integraation?

**Comment by Zunwolf1896** [comment]
I don't believe we have trinkets installed, no

**Comment by Tiviacz1337** [comment]
I can't reproduce the issue, can you record a video or something?

**Comment by Zunwolf1896** [comment]
Hello, We have been looking into this and we believe it is probably somethign to do wiht the way the server saves player data and world file before the restart. We are running a test over the next couple restarts to see if we get it again or not. 

If this is the cause, I think it wil have jsut been conincidence the two players who found out about it happened to do it with backpacks.
