### ISSUE TITLE
Breaks AE2, and waystone blocks

### ISSUE THREAD

**Issue by Saragon4005** [Tiviacz1337/Travelers-Backpack#756]
0. Fabric 1.19.2-8.2.32 (x.x.31 works fine)

1. Describe the bug 
AE2 blocks are replaced with other AE2 blocks (or sometimes other blocks from mods) on the client side

2. Write steps to reproduce the bug
Install Applied Energistics, and/or waystones. Place down any block from those mods

3. What is expected behaviour 
Blocks would be displayed as the blocks they are supposed to be according to the server.

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/39284711/7409986e-b78c-4259-b393-dc5e86252f93)

**Comment by Tiviacz1337** [comment]
are you sure its travelers backpack issue

**Comment by Saragon4005** [comment]
There are likely multiple factors at play here, but x.x.31 works perfectly and x.x.32 doesn't. Given that this behavior can be reproduced by only changing this mod (and the versions are known) It's doing something.

**Comment by Tiviacz1337** [comment]
did you update travelers backpack on server & client?

**Comment by Saragon4005** [comment]
Changing the server version has no effect on this particular behavior. The newest, the one before (the one I have on the client) and not installed all results in the client side glitch.

**Comment by Tiviacz1337** [comment]
so it's the same on client and server is it correct
