### ISSUE TITLE
Allow emptying tanks into partially filled containers

### ISSUE THREAD

**Issue by jtuc** [Tiviacz1337/Travelers-Backpack#758]
**Is your feature request related to a problem? Please describe.**
If I'm collecting fluids, I would like to be able to hose them into my backpack and then transfer my backpack tanks to larger secondary containers. However, it seems like the current logic only attempts to transfer fluid from the container to the tank, and exits early if the container would overfill the tank - com.tiviacz.travelersbackpack.inventory.InventoryActions line 118:
```java
if(tank.getFluidAmount() + amount > tank.getCapacity()) return false;
```

**Describe the solution you'd like**
When putting a fluid container into the bucket slot, if the backpack tanks cannot contain the liquid, fallthrough and attempt to transfer fluids back the other way.
Alternatively, partially transfer fluid from containers to the backpack, and only transfer fluid the other way if the tank is full.

**Describe alternatives you've considered**
Placing containers into the world and hosing the liquid in works, but is less convenient.

**Additional context**
In this screenshot, I would expect one of the following to happen:
- The one bucket of water from my backpack tank to be added to the 6 buckets in the Basic Portable Tank.
- 5 buckets of fluid to move from the Basic Portable Tank to the Backpack Tank

![2023-11-11_15 30 13](https://github.com/Tiviacz1337/Travelers-Backpack/assets/6748724/f2f231ea-d720-4c72-8bb2-0a1444f50724)

**Comment by Tiviacz1337** [comment]
https://modrinth.com/mod/travelersbackpack/versions
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files?page=1&pageSize=20
fixed for Forge

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack/versions
for fabric
