### ISSUE TITLE
Can't blacklist/whitelist as tool modded items

### ISSUE THREAD

**Issue by BirbIrl** [Tiviacz1337/Travelers-Backpack#759]
Fabric 1.20.1-9.1.8

Describe the bug:
Using 
"toolSlotsAcceptableItems": [
"create",
":wrench"
],
or
"blacklistedItems": [
"create",
":wrench"
],
does not function, while referencing vanilla items like minecraft:apple does.
This was also tested with hephaestus and bits and chisels, none of which worked.

Write steps to reproduce the bug:
download TB and any other mod, launch the game. then in the config try to add a modded item. launch the game again.
You will still be able to place that modded item inside the backpack, even if it's blacklisted

Pozdrawiam + powodzenia :>

**Comment by Tiviacz1337** [comment]
you have to add items like: 
"create:wrench",
...
...
not like
"create",
":wrench"

**Comment by BirbIrl** [comment]
update, i forgot quotes
<img src='https://media.tenor.com/g1bZgt4-tL4AAAAC/skull.gif' width='70'>
and it reformatted it to the way i sent you
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/74369380/7553e74f-3884-424c-8eb1-da44f96d40df)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/74369380/53404903-233e-4db7-a2b7-5fb8723eb597)

while for vanilla items it seemed to have just defaulted to {minecraft}:whateveritem for when it gets split automatically

while this is entirely my bad i think it could help other silly folk like me if you changed the comment from:
// List of items that can't be put in backpack inventory (Use registry names, for example: minecraft:apple)
to
// List of items that can't be put in backpack inventory (Use registry names in quotes and followed by commas, for example: "minecraft:apple", "minecraft:stick")
