### ISSUE TITLE
Dragon Backpack Dosnt give out the effects.

### ISSUE THREAD

**Issue by PiedPiper89** [Tiviacz1337/Travelers-Backpack#760]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Playing on a server DarkRpg 7.4.9 in version 1.20.1 Fabric
(Travelers-backpack-1.20.1-9.1.8)

1. Describe the bug 

Made a DragonBackpack and it dosent give out the effects not a single one.

2. Write steps to reproduce the bug

unequiped the backpack and put it back on?!?

3. What is expected behaviour 

to get str hp reg water breathing fire resistance  night vision effects.

4. Screenshots (If applicable)
![Namnlös](https://github.com/Tiviacz1337/Travelers-Backpack/assets/101047443/e986bada-e3ef-4351-ba5d-4a55ef7b5dd2)
![Namnlös](https://github.com/Tiviacz1337/Travelers-Backpack/assets/101047443/b9a2da91-da3c-475b-97f2-95ec33cdfc7b)

**Comment by ARipeAppleByYoursTruly** [comment]
I'm pretty sure you have to manually turn on the ability by using this toggle

![282976790-b9a2da91-da3c-475b-97f2-95ec33cdfc7b](https://github.com/Tiviacz1337/Travelers-Backpack/assets/83992779/cbc8a891-3eb0-4f77-b09c-d29318ca53b6)

I also had this confusion during my playthrough with cake backpack
