### ISSUE TITLE
Backpack not showing up when players log on to multiplayer server

### ISSUE THREAD

**Issue by eliminster** [Tiviacz1337/Travelers-Backpack#761]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Java 1.20.2, Fabric 0.14.24, Multiplayer Server.

1. Describe the bug 

When a player joins the server, if they had a backpack on when they had logged out, the backpack will not show and there is nothing in inventory or anything. However, if they jump out of the server and jump back in...the backpack is back on their back and everything is correct. The server and the client have no errors, so I am unsure where to look to determine where/what to look for. I have tried on multiple accounts/players too. Happens to Operators too. 

2. Write steps to reproduce the bug

Have a backpack on, log off the server, and close out the Fabric loader. Start everything back up and log in to the server as normal.

3. What is expected behaviour 

Backpack should stay.

**Comment by Dragonfly-Totem** [comment]
Also occurs very intermittently in server for Minecraft 1.20.1, Traveler's Backpack 9.1.8, Quilt Loader 0.21.2.  It's happened to two of my players over the last couple of days.  No pattern detected so far, other than as described above -- Player logged out with backpack on, logs back in and backpack is gone.  One player had it reappear seemingly at random, I don't think they disconnected and reconnected.

**Comment by Tiviacz1337** [comment]
do you use any other mods?

**Comment by eliminster** [comment]
A few, but they are mostly performance related for the server and clients. On the Server: BetterF3, BetterStats, Blur, Clumps, Chunks Fade-In, Sodium, Simple Voicechat, and their associated libraries. We have mostly a vanilla based player gameplay system. There are a few things we use for "enhancement" to vanilla. As mods outside of vanilla play, we have JEI, Travellers, Waystones, Graves, Tom's Simple Storage, Xaero's Minimap & Worldmap. Tom's was added a few days ago but the Backpack issue was going on beforehand. On the client's side: aside from the already established mods the unique mods are: 3D Skins, Indium, ModMenu, MouseTweaks, Shulkerbox Tooltips, Traveler's Backpack, Tom's, Simple Voicechat, Waystones, Xaero's Maps, and all of their associated libraries. All are up-to-date as of the last week. Where would you like me to help look?

**Comment by Tiviacz1337** [comment]
does it happen everytime? Also what is your Cardinal components version?

**Comment by eliminster** [comment]
It happens every.single.time. 

Our Cardinal version is 5.3.0 which I believe is the updated version.

**Comment by eliminster** [comment]
I just wish to reiterate, that once we log in, we immediately jump out and go right back in, and the backpack is there. Plus, if we jump in and the pack is not there, the game still believes there is one equipped as you can not equip another backpack...if you try, it tells you that you are already wearing one. Not sure if that helps or hinders.

**Comment by Tiviacz1337** [comment]
is it possible for you to check if issue occurs with clean server only tb + required mods for tb to run?

**Comment by eliminster** [comment]
Tiv,
Just spun up a brand new server with only the requirements of Travellers. Same thing.

More info for you though:

MC version - Java 1.20.2 
Fabric Modloader - 0.14.24
Cloth - 12.0.109
Fabric API - 0.90.4
Travellers - 9.2.2
Cardinal - 5.3.0

I see there are a couple of updates I can do on those versions, but wanted to do this in baby steps in case you needed to collect more information from my test server.

-Keven

**Comment by Tiviacz1337** [comment]
Okay, I'll check that with same version of everything like you, but in about 2 days when I'll have some free time. 
Also more questions:
You do not play on LAN right? 
Does it happen with every backpack? can you create brand new backpack and check if issue still occurs?
Do you have a lot of items in backpack?
Do you have client & server config synced?

**Comment by eliminster** [comment]
We play on LAN computers but connect via an online host, but I assume you mean localhost, then no, we do not. As for trying out different packs, I am way ahead of you on that question. We have tried every backpack and, unfortunately, it produced the same results. It does not matter if it is chocked full of items or empty, same issue.

**Comment by hunorlaszlo** [comment]
Yes. Self hosted.

**Comment by eliminster** [comment]
When you asked, "Do you have client & server config synced?" can you elaborate on what you mean by that? Is there something else I am missing or should be doing on the server?

**Comment by Tiviacz1337** [comment]
I've just tested the server with same exact versions like yours and issue is not occuring...  I can disconnect from server and connect again and backpack is still there

**Comment by eliminster** [comment]
Well, if it did not happen the first go around for you, what would be the difference between my brand-new server and only the backpack mod installed and your server? Where can I look to help isolate it?

**Comment by hunorlaszlo** [comment]
> I've just tested the server with same exact versions like yours and issue is not occurring... I can disconnect from server and connect again and backpack is still there

Did you also close the client after disconnecting? Disconnecting and connecting again is the workaround we do, to get the backpack loaded.

**Comment by Tiviacz1337** [comment]
Okay, I am able to reproduce the issue after closing the client

**Comment by Tiviacz1337** [comment]
Okay, so I am able to reproduce issue on 1.20.2, but 1.20.1 seems to work correctly

**Comment by eliminster** [comment]
No, we literally just jump out of the server and then jump right back in to have the backpack available again. - KevenOn Dec 9, 2023, at 4:49 AM, hunorlaszlo ***@***.***> wrote:﻿

I've just tested the server with same exact versions like yours and issue is not occurring... I can disconnect from server and connect again and backpack is still there

Did you also close the client after disconnecting? Disconnecting and connecting again is the workaround we do, to get the backpack loaded.

**Comment by Tiviacz1337** [comment]
I have one more question, do other people see that you wear a backpack? or they also do not see the backpack on your back until you relog?

**Comment by eliminster** [comment]
In our testing, it visually is not there either. However, we just found out Friday, if you shift right click to place the pack on the ground it will right itself once you pick it up and equip it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tiviacz1337** [comment]
Is it possible for you to test on your server the file I'll provide you via Discord? I think I've fixed the issue, but I'd need additional confirmation from someone who encountered the issue often

**Comment by eliminster** [comment]
Sure thing.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tiviacz1337** [comment]
Okay so join my discord https://discord.gg/DxEbvrHu and ping me and we'll go further from that point

**Comment by eliminster** [comment]
Where is your discord server link?

**Comment by Tiviacz1337** [comment]
In previous message 

> Okay so join my discord https://discord.gg/DxEbvrHu and ping me and we'll go further from that point

**Comment by hunorlaszlo** [comment]
> I have one more question, do other people see that you wear a backpack? or they also do not see the backpack on your back until you relog?

No, backpacks are not rendered either. It's like they are not loaded at all. We haven't tried to place the backpack though.

I can also try the server, if needed sometime, mid next week. I'll reach out to you on Discord.

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack/versions
should be fixed

**Comment by HiruTwo** [comment]
@eliminster Did you find any solution?

**Comment by Hanprogramer** [comment]
Still happening
