### ISSUE TITLE
How can I make a modded potion works with fluid tank?

### ISSUE THREAD

**Issue by slottwo** [Tiviacz1337/Travelers-Backpack#762]
**Is your feature request related to a problem? Please describe.**
I'm playing with the Enigmatic Legacy mod which, among other things, adds modded potions, such as recall, molten heart and haste. I would like, for example, to use the rod potion or molten heart in the fluid tank.

**Describe the solution you'd like**
Would there be any configuration or even if you could add one to add compatibility with potions from other mods?
Or even any tips on how I could make a datapack for this?

**Comment by Tiviacz1337** [comment]
well, the problem with enigmatic legacy potions is that they don't use base Minecraft potion class, which causes the backpcak to not recognize it as potion

**Comment by Tiviacz1337** [comment]
so sadly compat with enigmatic legacy wont be added until they change their potions to extend base potion class
