### ISSUE TITLE
I can't get the cat disc to play on the nyan bag, but what I thought would be better. can we have a portable juke box in the traveler's backpacks?

### ISSUE THREAD

**Issue by Hextonic** [Tiviacz1337/Travelers-Backpack#763]
so, I play minecraft 1.12.2 when I mod it. and I noticed this mod is being worked on for very new versions.
But I hope there's chance of getting portable jukeboxes in the bags in 1.12 anyway.

also, I'm not sure if it's twilight forest, tinkers, or one of the other mods I have causing the rainbow bag to not play the disc it's made with. but I assumed that's whats supposed to happen when you eat the golden apple anyway.

so ya.. portable jukebox. people have been asking for it since 2013. it would be cool to have it in 1.12

**Comment by Tiviacz1337** [comment]
1.12 is not supported.

**Comment by Hextonic** [comment]
aw, well thank you anyway! the mod is still a great 1.12 addition
