### ISSUE TITLE
Ability button

### ISSUE THREAD

**Issue by cweet01** [Tiviacz1337/Travelers-Backpack#765]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.20.1-9.1.8.jar

1. Describe the bug 
Abilities button is not showing up and even if I hover over the section where it should be it does not say enable or disable so it's not even invisible.

2. Write steps to reproduce the bug
Made the Squid backpack and it does not do what it is suppose to do in the water.

3. What is expected behaviour 
Breath under water and see under water

4. Screenshots (If applicable)
![PXL_20231120_221113768](https://github.com/Tiviacz1337/Travelers-Backpack/assets/62656097/2c13905c-9b73-4f89-88e1-ed907265a137)

Any help will be greatly appreciated, thank you for your time. Love this mod!

**Comment by Esrepidys** [comment]
I believe you have to be wearing the backpack for the ability to be available and work properly.

**Comment by Tiviacz1337** [comment]
you have to wear backpack for ability to work

**Comment by cweet01** [comment]
I wear and it does not work there is no enable button like there should be.

**Comment by GamingSpud** [comment]
Having the backpack in your hotbar does not mean you are wearing the backpack. If the button right below where your cursor is has an arrow pointing up it means you aren't wearing the backpack. Once you wear it and press 'B' (or the wear keybind if you changed it) then you should see the ability toggle.

**Comment by cweet01** [comment]
This is from the wiki of the mod, the one button is for equipping and
unequipping and the other is a toggle button that should be there as well
for abilities of certain backpacks like the squid one...

**Comment by cweet01** [comment]
https://photos.app.goo.gl/rw4QuXp1gxQB5GNF8

Here is a video I took of me putting it on and it not working like it
should.

**Comment by GamingSpud** [comment]
You're still ignoring our comments, you have to equip the backpack like you did in the video, then open the backpack interface with it equipped and then you'll see the ability toggle.

**Comment by cweet01** [comment]
I apologize greatly for that, I did not mean to ignore the comments. It was
on me and my fault alone. For some reason or another my b keybinding was
bringing up something else so once I fixed that issue the backpack issue
was fixed. I thank you again and apologize.

**Comment by GamingSpud** [comment]
Thought you were trolling for a second lol
I apologize as well if I seemed rude, hope you enjoy trying different abilities now.

**Comment by cweet01** [comment]
Lol thank you for everything and have a holiday season! I love this mod!
