### ISSUE TITLE
Changing Sleeping Bag Colors

### ISSUE THREAD

**Issue by Esrepidys** [Tiviacz1337/Travelers-Backpack#766]
**Is your feature request related to a problem? Please describe.**
I would like to see a way to change the color of the sleeping bag once crafted into a backpack.

**Describe the solution you'd like**
A simple crafting recipe. It could use wool and/or dye.

**Describe alternatives you've considered**
A way to remove the sleeping bag and replace it with a different one.

**Additional context**
N/A

**Comment by Tiviacz1337** [comment]
you can change sleeping bag color - place backpack in the world and shift right click with another sleeping bag on the backpack
it will replace current sleepeing bag with bag in your hand
