### ISSUE TITLE
Abilities button Again Sorry 

### ISSUE THREAD

**Issue by cweet01** [Tiviacz1337/Travelers-Backpack#767]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1.20.1-9.1.8 Fabric

1. Describe the bug 

I wear it and it does not work. There is so suppose to be a button to click when you have the backpack in hotbar and go into it's inventory screen and where my mouse pointer is at is suppose to be an enable button for abilities.

2. Write steps to reproduce the bug

Made a Squid Backpack, put it on and jumped in water and could not see clearly and bubble were disappearing and losing air.

3. What is expected behaviour 

Suppose to be able to see under water and breath under water.

4. Screenshots (If applicable)
![PXL_20231120_221113768](https://github.com/Tiviacz1337/Travelers-Backpack/assets/62656097/7fba61c3-f9e8-4ac1-a94e-e520532bdc8f)

Where my mouse pointer is at is suppose to be a button to enable the abilities of the backpack if it has one and the squid one is suppose to. It's not even invisible. Just not there. Any help is appreciated thank you.

**Comment by Tiviacz1337** [comment]
You are not wearing the backpack (if it says integrations enabled, then you have to put it in back slot) 
you have to click this button first... 
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/34790800/1c880470-1c6e-4f4a-8a5f-aad42df4704f)

**Comment by cweet01** [comment]
Well I know to put it in the back slot or hit that. But even doing that no abilities kick in, Thought there was suppose to be a toggle switch under the left bucket to turn off and on the abilities? I could be wrong.

**Comment by cweet01** [comment]
Here is a picture of the button that does not show up from the mods wiki
page on curseforge

**Comment by Tiviacz1337** [comment]
what backpack do you have equipped?

**Comment by cweet01** [comment]
The Squid, it is suppose to let you breath under water and help you see
under water.

**Comment by Tiviacz1337** [comment]
could you record a video?

**Comment by cweet01** [comment]
I can try for you yes.

**Comment by cweet01** [comment]
https://photos.app.goo.gl/rw4QuXp1gxQB5GNF8

Here is a link to the video I took for you hopefully it works. If not let
me know and I will try to send another way.

**Comment by Tiviacz1337** [comment]
you have to open inventory after equipping backpack (it can be done by B button on keyboard by default) and then ability slider WILL appear
