### ISSUE TITLE
Backpack disappearing when dying with "Simple Death Chest" mod

### ISSUE THREAD

**Issue by JustRyan362** [Tiviacz1337/Travelers-Backpack#769]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.20.1 ModLoader version 0.14.24

1. Describe the bug 
When using a mod that stores your items in a chest, there is a decent chance that when the player dies, the backpack won't be placed and will simply disappear.

2. Write steps to reproduce the bug
Die when using the "Simple Death Chest" Mod by Isaiah. The backpack won't appear on the ground as a block or it will simply disappear.

3. What is expected behaviour 
I'd suggest allowing the backpack to be placed somewhere in a 4x4 block radius replacing any block that doesn't contain inventory.

4. Screenshots (If applicable)
(no backpack on ground XD)

**Comment by Tiviacz1337** [comment]
I cant see Simple Death Chest mod source, Backpack always searches for place to be placed if position where player dies is not available, so there might be possibility that chest is replacing backpack, but I cant check that because there's no source available
