### ISSUE TITLE
Crash on 1.17.1 Fabric travelers-backpack-1.17.1-6.0.34.jar

### ISSUE THREAD

**Issue by RYUKxAnime** [Tiviacz1337/Travelers-Backpack#771]
when I put a sword or a pickaxe in the tool slot
and equip the backpack it crashes
and the world is not accesible anymore

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 01/12/23, 12:52 pm
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_327.method_1727(String)" because "renderer" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.65)
	at net.minecraft.client.render.item.ItemRenderer.renderDurability101(ItemRenderer:1535)
	at net.minecraft.client.render.item.ItemRenderer.handler$dmo000$durability101$renderGuiItemOverlay(ItemRenderer:1523)
	at net.minecraft.client.render.item.ItemRenderer.renderGuiItemOverlay(ItemRenderer:421)
	at net.minecraft.client.render.item.ItemRenderer.renderGuiItemOverlay(ItemRenderer:365)
	at com.tiviacz.travelersbackpack.client.screen.OverlayHandledScreen.drawItemStack(OverlayHandledScreen.java:171)
	at com.tiviacz.travelersbackpack.client.screen.OverlayHandledScreen.renderOverlay(OverlayHandledScreen.java:76)
	at net.minecraft.client.gui.hud.InGameHud.handler$ial000$travelersbackpack$renderOverlay(InGameHud:12484)
	at net.minecraft.client.gui.hud.InGameHud.renderHotbar(InGameHud:623)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:218)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:855)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$gle000$notenoughcrashes$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:24619)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:755)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$gle000$notenoughcrashes$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:24619)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:755)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$gle000$notenoughcrashes$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:24619)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:755)
	at net.minecraft.client.main.Main.main(Main:217)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_918.renderDurability101(class_918.java:1535)
	at net.minecraft.class_918.handler$dmo000$durability101$renderGuiItemOverlay(class_918.java:1523)
	at net.minecraft.class_918.method_4022(class_918.java:421)
	at net.minecraft.class_918.method_4025(class_918.java:365)
	at com.tiviacz.travelersbackpack.client.screen.OverlayHandledScreen.drawItemStack(OverlayHandledScreen.java:171)
	at com.tiviacz.travelersbackpack.client.screen.OverlayHandledScreen.renderOverlay(OverlayHandledScreen.java:76)
	at net.minecraft.class_329.handler$ial000$travelersbackpack$renderOverlay(class_329.java:12484)
	at net.minecraft.class_329.method_1759(class_329.java:623)
	at net.minecraft.class_329.method_1753(class_329.java:218)

-- Affected level --
Details:
	All players: 1 total; [class_746['Xerone'/187, l='ClientLevel', x=-352.84, y=81.00, z=-329.91]]
	Chunk stats: 1024, 588
	Level dimension: minecraft:overworld
	Level spawn location: World: (-208,67,-192), Section: (at 0,3,0 in -13,4,-12; chunk contains blocks -208,0,-192 to -193,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 3283 game time, 3283 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$gle000$notenoughcrashes$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:24619)
	at net.minecraft.class_310.method_1514(class_310.java:755)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$gle000$notenoughcrashes$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:24619)
	at net.minecraft.class_310.method_1514(class_310.java:755)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$gle000$notenoughcrashes$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:24619)
	at net.minecraft.class_310.method_1514(class_310.java:755)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, cullleaves/smartleaves, Clear_water_and_lava_by_WhiterMv.1.0.zip, Portal Blocks RP, Tiny Totem, Water+Improved 1.17.zip, betterbeds/connectedbeds, betterbeds/fancybeds, VanillaTweaks_r769797, Ancient+Highlight.zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.5, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3209272856 bytes (3060 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GT 1030
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1d01
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 26839.83
	Virtual memory used (MB): 24661.65
	Swap memory total (MB): 10524.18
	Swap memory used (MB): 1185.83
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8192m -Xmx8192m
	Fabric Mods: 
		additionaladditions: Additional Additions 2.2.0
		advancementinfo: AdvancementInfo 1.17.1-fabric0.36.1-1.3
		advdebug: Advancements Debug 2.3.0
		allstackable: All Stackable 1.4.3-1.17.1
		always_eat: AlwaysEat 1.0.0
		amecs: Amecs 1.3.8+mc.1.17
		amecsapi: Amecs API 1.3.5+mc1.17.1
		antidrop: Anti Drop 1.17.1-1.1.0
		appleskin: AppleSkin 2.4.0+mc1.17.1
		architectury: Architectury 2.10.12
		audio_engine_tweaks: Tweaks for Audio Engine 1.2.3
		autorun-alternative: AutoRun Alternative 0.4.0
		axesareweapons: Axes Are Weapons 1.6.0
		backslot: BackSlot 1.2.2
		balm-fabric: Balm 1.9.0+0
		beaconloading: Beacon Loading 1.0.0
		beaconoverhaul: Beacon Overhaul 1.4.3+1.17
		bedrockminer: Bedrock Miner 1.0.0
		better_runtime_resource_pack: Better Runtime Resource Pack 0.9.0
		betterbeds: Better Beds 1.2.0
		betterblockoutline: BetterBlockOutline 1.2.1-1.17.1
		bettercontrols: Better Controls 1.2.1
		betterrecipebook: Better Recipe Book 1.5.5
		blue_endless_jankson: jankson 1.2.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.5.0
		cactus_storage: Cactus Storage 0.1.0
		caelus: Caelus API 0.0.16-1.17
		caffeineconfig: CaffeineConfig 1.1.0+1.17
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		capturetomob: Egg to capture mob 2.0.0
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		carpet: Carpet Mod 1.4.57
		carpet-addons: Carpet Addons 1.0.10
		carpet-extra: Carpet Extra 1.4.57
		carpet-fixes: Carpet Fixes 1.17.1-1.3.0+v211201
		carpet-tis-addition: Carpet TIS Addition 1.46.0
		chesttracker: Chest Tracker 1.1.1
		citresewn: CITResewn 0.9.1+1.17.1
		clean-debug: Clean F3 0.3.0
		cleancut: CleanCut 1.17-4.0-fabric
		clickthrough: ClickThrough 1.17.1-fabric0.36.1-0.4
		clienttweaks: Client Tweaks 6.0.0+0
		cloth-api: Cloth API 2.1.62
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-client-events-v0: Cloth Client Events v0 2.1.62
		cloth-common-events-v1: Cloth Common Events v1 2.1.62
		cloth-config2: Cloth Config v5 5.3.63
		cloth-datagen-api-v1: Cloth Datagen v1 2.1.62
		cloth-scissors-api-v1: Cloth Scissors API v1 2.1.62
		cloth-utils-v1: Cloth Utils v1 2.1.62
		coat: Coat 1.0.0-beta.17+mc1.17
		collective-fabric: Collective (Fabric) 4.26
		colytra: Colytra 2.0.0-1.17
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_focamacho_sealconfig: sealconfig 1.2.2
		com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		comforts: Comforts 0.0.7-1.17.1
		completeconfig: CompleteConfig 1.2.0
		conditional-mixin: conditional mixin 0.3.2
		configurablefurnaceburntime-fabric: Configurable Furnace Burn Time (Fabric) 1.0
		continuity: Continuity 1.1.0+1.17
		couplings: Couplings 1.6.0+1.17
		craftobsidian: Craft Obsidian 1.17.1
		creeper-backguard: Creeper Backguard 1.3.1-1.18
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.3.1
		cutefulmod: CutefulMod 1.1.0
		deathlog: DeathLog 0.2.2
		diggusmaximus: Diggus Maximus 1.5.1-1.17
		dismountentity-fabric: Dismount Entity (Fabric) 1.5
		dispenser_cauldron: Dispenser Cauldron 1.0.5
		doublejump: Double Jump Mod 1.0.1+mc1.17
		dropfullcarts: DropFullCarts 1.2.0
		dropspread: Drop Spread 1.0
		durability101: Durability101 0.0.4
		easierchests: EasierChests 1.17.1-fabric0.36.1-1.6.3
		easyautocrafting: EasyAutoCrafting 1.2+1.17
		easyelytratakeoff-fabric: Easy Elytra Takeoff (Fabric) 2.2
		easymagic: Easy Magic 2.0.2
		elytraautopilot: Elytra AutoPilot 1.1.0
		enchantingchanges: Enchanting Changes 1.0.4
		enchantmenttweaker: Enchantment Tweaker 0.0.1b
		enhancedblockentities: Enhanced Block Entities 0.5+1.17
		entityculling: EntityCulling-Fabric 1.5.0
		entityoutliner: Entity Outliner 1.2.0
		essentialaddons: Essential Addons 1.2.1
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.2
		expandedstorage: Expanded Storage 7.3.6
		explorerscompass: Explorer's Compass 1.17.1-2.0.2-fabric
		extshape: Extended Block Shapes 1.8.0
		fabric: Fabric API 0.46.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+cf39a74318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+e821752d18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+cf39a74318
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+cf39a74318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+cf39a74318
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+cf39a74318
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+cf39a74318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.1+3447790d18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+cf39a74318
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.15+b556f28c18
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.1+377137cc18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.12+e99fbe1218
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.4+cf39a74318
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+cf39a74318
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+6617390918
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.2+cf39a74318
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.35+fb8d95dab3
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.4+cf39a74318
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.6+0392f3a618
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+cf39a74318
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+cf39a74318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+cf39a74318
		fabric-models-v0: Fabric Models (v0) 0.3.1+cf39a74318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+cf39a74318
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+cf39a74318
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+f907116918
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+cf39a74318
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+cf39a74318
		fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.0+ea29b33318
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.6+ce16ae5918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.10+ce16ae5918
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+cf39a74318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+cf39a74318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+cf39a74318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+cf39a74318
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+377137cc18
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+591a0f2118
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.10+f09604ce18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+cf39a74318
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+cf39a74318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.2.0+48a9ad8918
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.3+cf39a74318
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+cf39a74318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.3+3b96517518
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.4+cf39a74318
		fabricloader: Fabric Loader 0.14.21
		fastchest: FastChest 1.2+1.17
		fastfurnace: FastFurnace 1.17-3.0
		fefafly: Feather Fall Flying 1.0.0
		ferritecore: FerriteCore 3.1.0
		fiber: fiber 0.23.0-2
		flamesweeping: FlameSweeping 1.20.1-1.1
		flytre-lib-base: Flytre Lib - Base Module 1.3.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.2
		flytre_lib: Flytre Lib 1.4.3
		forcecrawl: Force Crawl 1.0.2
		forgeconfigapiport: Forge Config API Port 2.0.2
		forgivingvoid: Forgiving Void 5.0.0+0
		fuelinfo: FuelInfo 1.0
		fullscreeno: fullscreeNO 1.0.0
		gateofbabylon: Gate Of Babylon 1.5.1-1.17.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		gca: GugleCarpetAddition 2.6.0-1.17&1.18
		gravelminer: GravelMiner 11.1.0+0
		held-item-info: Held Item Info 1.4.2+1.18
		hidearrows: Fabric Hide Arrows v1.0.1
		highlighter: Highlighter 1.1.2
		hlandbukkit_c2me-fabric_ver_1_17_libs_: libs 0.2.0+alpha.5.0
		homabric: Homabric 1.1.0
		hydrogen: Hydrogen 0.3
		iceberg: Iceberg 1.0.27
		iknowwhatimdoing: I Know What I'm Doing 4.1.1
		indium: Indium 1.0.1+mc1.17.1
		infinitetrading-fabric: Infinite Trading (Fabric) 2.1
		infinitevillagertrading: InfiniteVillagerTrading 1.17.1-fabric0.36.1-1.1
		infinityfix: Infinity Fix 1.1.0
		infinitywaterbucket: Infinity Water Bucket 2.0.0
		inventory_control_tweaks: Inventory Control Tweaks 1.3.9+MC1.17-1.17.1
		inventoryhud: Inventory HUD + 3.4.1
		inventoryprofilesnext: Inventory Profiles Next 1.8.6
		inventorytotem-fabric: Inventory Totem (Fabric) 1.5
		ipnrejects: IPN Rejects 1.0.1
		iseelava: I See Lava 1.0.0
		itemscroller: Item Scroller craftfix-1.2.6
		ivan-carpet-addition: Ivan Carpet Addition 2.2.2
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jpgscreenshot: JPG Screenshot 1.0.4
		kleeslabs: KleeSlabs 10.0.0+0
		kyrptconfig: Kyrpt Config 1.2.1-1.17
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.1.5
		letitgrow: Let it Grow 1.0.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.2.1+1.17.1
		libipn: libIPN 1.0.8
		libninepatch: LibNinePatch 1.1.0
		libraryferret: Library ferret 4.0.0
		librgetter: Librarian Getter 1.2.6-1.17.1
		libzoomer: LibZoomer 0.3.0+1.17.1
		litematica: Litematica 0.9.0
		litematica_printer: Litematica Printer 7.0.4
		lithium: Lithium 0.7.5
		local-server-entity-id-fix: Local Server Entity Id Fix 0.0.2
		lunaar-carpet-addons: Lunaar Carpet Addons 0.5.0
		magiclib: MagicLib 0.7.293+17aa28c-stable
		magiclib-1_17_1: MagicLib for 1.17.1 0.7.293+17aa28c-stable
		magna: Magna 1.5.5-1.17-pre4
		malilib: MaLiLib 0.10.0-dev.26
		masa_gadget_mod: Masa Gadget 3.1.289+1ca4352-stable
		masa_gadget_mod-1_17_1: Masa Gadget for 1.17.1 3.1.289+1ca4352-stable
		maybe-data: Maybe data 1.0.1-1.17
		mcf-reap: MaxVar reap for fabric 1.7.0
		mcpitanlibarch: MCPitanLib 1.4.9-1.17-fabric
		memoryleakfix: Memory Leak Fix 1.0.0
		messmod: MessMod 0.2.0+20220827-BETA
		midnightlib: MidnightLib 0.2.7
		minecraft: Minecraft 1.17.1
		minihud: MiniHUD 0.20.0
		minitweaks: MiniTweaks 1.1.5
		mobspawninglightlevel: Mob Spawning Light Level 1.2.0
		modmenu: Mod Menu 2.0.17
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		mousetweaks: Mouse Tweaks 2.15
		mousewheelie: Mouse Wheelie 1.8.8+mc1.17.1
		multiconnect-api: MultiConnect API 1.4.16
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.10
		no_fog: No Fog 1.3.2+1.16.5-1.19.3
		no_teleport_cooldown: No Teleport Cooldown 1.0.2
		notenoughcrashes: Not Enough Crashes 4.1.4+1.17.1
		notifmod: NotifMod 1.2
		noweakattack: No Weak Attack 1.1.2
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		omega-config: OmegaConfig 1.0.4
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_yaml_snakeyaml: snakeyaml 1.29
		orientation: Critical Orientation 1.0.2
		packed-inventory: Packed Inventory 0.2.2+1.17.1
		packet_tweaker: Packet Tweaker 0.2.0+1.17.1
		pca: Plusls carpet addition mod 0.2.5
		perfectaccuracy: Perfect Accuracy 1.1
		perspectivemod: Perspective Mod Redux 0.0.5_01
		pickablepiglins: Pickable Piglins 1.1.0+1.17.1
		pickablevillagers: Pickable Villagers 1.1.4+1.17.1
		pickupnotifier: Pick Up Notifier 2.1.0
		pistonboltbuilder: PistonBoltBuilder 1.0.3
		playerabilitylib: Pal 1.3.0
		polymorph: Polymorph 0.0.15-1.17.1
		portal_accessibility: Nether Portal Accessibility 1.0.0-mc1.17.1
		puzzleslib: Puzzles Lib 2.0.3
		quartzelv: Quartz Elevator 1.3.0+1.17
		quickshulker: Quick Shulker 1.3.1-1.17
		randombonemealflowers-fabric: Random Bone Meal Flowers (Fabric) 1.7
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		rebind-narrator: Rebind Narrator 1.0.0
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.17.1-build.69
		ring_of_attraction: Ring Of Attraction 1.1.15
		ringsofascension: Rings of Ascension 1.0.1
		roughlyenoughitems: Roughly Enough Items 6.5.433
		rug: Rug 1.17.1-1.2.0
		ruined_equipment: Ruined Equipment 2.0.0
		screenshotclipboard: Screenshot to Clipboard 1.0.8
		secondchance: Second Chance 1.2.0
		server_translations_api: Server Translations API 1.4.8+1.17
		sgui: sgui 1.0.0-rc6+1.17.1
		shieldcooldownremover: Shield Cooldown Remover 1.0.0
		shulkerloader: Shulker Loader 1.0.8
		shulkerutils: shulkerutils 1.0.4-1.17
		signtools: Sign Tools 1.0.0
		sihywtcamc: sihywtcamc 1.4.1+1.17.1
		silence: Silence 1.17.1-fabric0.36.1-1.0.1
		silentbackground: SilentBackground 1.0.1
		silky-hands: Silky Hands 1.0.2
		simplehudenhanced: Simple Hud Enhanced 1.1.0
		slotifier: Slotifier 1.17.1-1.0.1
		smoothboot: Smooth Boot 1.16.5-1.6.0
		smootherbedrock: Smoother Bedrock 1.0.4
		snad: Snad 1.1.0
		sodium: Sodium 0.3.4+build.13
		sodium-extra: Sodium Extra 0.4.18+mc1.17.1-build.97
		somnus: Somnus API 0.0.13-1.17.1
		soulbound: Soulbound 2.0.0
		spruceui: SpruceUI 3.3.0+1.17
		stacc: Stacc 1.3.0
		stacker: Stacker 2.1.3
		starlight: Starlight 1.0.0+fabric.73f6d37
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stepup: StepUp 1.17.1-fabric0.36.1-1.1
		thiccpackets: Extra Thicc Packets 1.17-1.19+
		thymine: Thymine 1.8.0
		togenc: Toggle Enchantments 1.0
		toggleableitemframes: Toggleable Item Frames 1.2.0-1.17.1
		tooltipfix: ToolTip Fix 1.0.4-1.17.1
		totos-carpet-tweaks: Toto's Carpet Tweaks 1.17.1-0.2.2
		tradingpost: Trading Post 2.0.0
		trampledisablerfabric: Trample Disabler 1.0.3
		transcendingtrident-fabric: Transcending Trident (Fabric) 2.2
		travelersbackpack: Traveler's Backpack 1.17.1-6.0.34
		treeharvester-fabric: Tree Harvester (Fabric) 5.1
		trinkets: Trinkets 3.0.4
		tweakermore: TweakerMore 3.12.0
		tweakeroo: Tweakeroo 0.11.0
		tweakerplus: TweakerPlus 1.3.1
		tweed4_annotated: tweed4_annotated 1.3.0+mc1.17
		tweed4_base: tweed4_base 1.5.0+mc1.17
		tweed4_data: tweed4_data 1.2.1
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.17
		tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.17
		uncraftingtable76: Uncrafting Table 1.1.7
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		villagerdeathmessages-fabric: Villager Death Messages (Fabric) 2.2
		villagernames-fabric: Villager Names (Fabric) 3.5
		ward_blocks: Ward Blocks 1.1.10
		warp_mod_fabric: Warp Mod 0.0.2
		weirdaddons: Weird Addons 1.17-1.4.0
		whereisit: Where Is It 1.14.3
		wither_cage_fix: Wither Cage Fix 1.0.9+MC1.17-1.17.1
		wooltweaks-fabric: Wool Tweaks (Fabric) 1.4
		worldedit: WorldEdit 7.2.7+9f3e795
		wthit: wthit 3.11.2
		wthit-plugins: Wthit Plugins 1.0.6+1.18.2
		xaerominimap: Xaero's Minimap 22.16.3
		xaeroworldmap: Xaero's World Map 1.28.7
		xpbeacons: Experience Beacons 7.0
		yungsapi: YUNG's API 1.17-Fabric-19
	Launched Version: 1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GT 1030/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.' x 6
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, cullleaves/smartleaves, file/Clear_water_and_lava_by_WhiterMv.1.0.zip (incompatible), file/Portal Blocks RP (incompatible), file/Tiny Totem (incompatible), file/Water+Improved 1.17.zip, betterbeds/connectedbeds, betterbeds/fancybeds, file/VanillaTweaks_r769797, file/Ancient+Highlight.zip
	Current Language: English (US)
	CPU: 6x AMD Ryzen 5 3500 6-Core Processor 
	Player Count: 1 / 420; [class_3222['Xerone'/187, l='ServerLevel[New World]', x=-352.84, y=81.00, z=-329.91]]
	Data Packs: vanilla, Fabric Mods, file/RugData (incompatible)
	Client Crashes Since Restart: 4
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Traveler's Backpack (travelersbackpack), Not Enough Crashes (notenoughcrashes)

**Comment by Tiviacz1337** [comment]
Delete durability101 mod
