### ISSUE TITLE
"/remove backpack command made backpack disappear 

### ISSUE THREAD

**Issue by AgentAlex367** [Tiviacz1337/Travelers-Backpack#773]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.20.1 - 0.14.25
Mod: 9.1.8

2. Describe the bug 
Backpack didn't return to inventory after it was removed

3. Write steps to reproduce the bug
wear a backpack and use the /tb remove. 

4. What is expected behaviour 
for backpack to return to inventory

5. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
/tb remove just removes backpack, do not return to player inventory
