### ISSUE TITLE
Config to not have crafting tables in the packs/make it an upgrade?

### ISSUE THREAD

**Issue by Aceplante2** [Tiviacz1337/Travelers-Backpack#776]
As of now, the "crafting table" slots are kind of glitchy. They cannot have items shift clicked into them, and also cannot be sorted with the rest of the pack when pressing the sort button. Can there be a config option to just have them be storage slots and no crafting table? Or perhaps the ability to craft can be an optional upgrade (crafting table+backpack upgrade kit), and they do not have the ability to craft by default; after all, there is no crafting table used in the initial recipe...

Perhaps with this change, you have to make a choice between it and the netherite storage upgrade, so you can either get the maximum possible storage, or the ability to craft? A fair choice in my opinion since backpacks are still OP either way

This would also provide a perfect opportunity to finally add a furnace upgrade you can apply _instead of the crafting table_, as suggested in https://github.com/Tiviacz1337/Travelers-Backpack/issues/56

**Comment by Tiviacz1337** [comment]
the crafting slots can be treated like normal storage slots you just have to click crafting widget and untick the lock icon

**Comment by Grandof1** [comment]
I personally would **love** if the `crafting grid` could be an `upgrade` instead of all backpacks having it by default. 
If possible it would be even better if could have an option in the `config` like this
```
# Set to false to make crafting grid upgrade required for backpacks to have crafting slots
default crafting table: false/true
```

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack/versions
Added for Forge

**Comment by Tiviacz1337** [comment]
https://modrinth.com/mod/travelersbackpack/versions
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Added for Fabric
