### ISSUE TITLE
Feedback: chicken backpack recipe OP

### ISSUE THREAD

**Issue by Aceplante2** [Tiviacz1337/Travelers-Backpack#777]
for something that provides an infinite reliable source of eggs without chickens, the recipe should be at least slightly harder than ONE egg?

how about:

FFF
eBe
eee

where F is the feathers, B is the backpack, and e is the eggs. The amount of feathers is unchanged, but this would mean it now requires 5 eggs instead of one, much more balanced in my opinion.

**Comment by Tiviacz1337** [comment]
Requires 3 eggs after tweaks
