### ISSUE TITLE
Blaze Backpack is crashing Forge Server (1.20.2) 

### ISSUE THREAD

**Issue by zzphere** [Tiviacz1337/Travelers-Backpack#778]
MOD VERSION: 1.20.2-9.2.3 9 (Forge)

1. Describe the bug 
Currently inside the Nether, I got shot by a blaze and it crashed my server/game. I checked the crash log and it lists Traveler's Backpack as the suspected issue. 

2. Write steps to reproduce the bug
Spawn in, blaze shoots with Blaze Backpack equipped (ability active), once I get hit, server and game crashes. See log below.

3. What is expected behavior 
To not take damage and not crash server

4. Screenshots (If applicable)
[crash-2023-12-09_11.55.48-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/13625201/crash-2023-12-09_11.55.48-client.txt)
[crash-2023-12-09_17.58.36-server.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/13625253/crash-2023-12-09_17.58.36-server.txt)

**Comment by zzphere** [comment]
I was able to replicate the issue again and can confirm, getting shot by a blaze with the ability active causes a game crash.

[crash-2023-12-09_12.10.17-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/13625270/crash-2023-1
[crash-2023-12-09_18.10.26-server.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/13625273/crash-2023-12-09_18.10.26-server.txt)
2-09_12.10.17-client.txt)

**Comment by zzphere** [comment]
Video of first crash 
https://outplayed.tv/media/aYKx6R

Video of the second crash 
https://outplayed.tv/media/Y6r5K3

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/4985853
https://modrinth.com/mod/travelersbackpack/version/1.20.2-9.2.4
fixed
