### ISSUE TITLE
Config to disable tool slot

### ISSUE THREAD

**Issue by AlisonHuang777** [Tiviacz1337/Travelers-Backpack#780]
I have a backpack that stores al my tools & weapons & etc.
I want that when I shift-click any tool in my inventory, it goes to the backpack normal slot, instead of the tool slot.

**Comment by Tiviacz1337** [comment]
just hide tool slots, it will go to normal backpack inventory on shift click

**Comment by AlisonHuang777** [comment]
What do you mean to "hide" it?
