### ISSUE TITLE
Can't equip backpack after dying. 

### ISSUE THREAD

**Issue by Zunwolf1896** [Tiviacz1337/Travelers-Backpack#781]
0. MODS
MC: 1.20.1
Fabric: 0.14.24
Travelers Backpacks: 9.1.8
YIGD: 2.0.0 beta 5

1. Describe the bug 
When players die without a backpack on, and then try and equip one, it is unequippable, the backpack vanishes. 

2. Write steps to reproduce the bug
Have no backpack attached to you or on you. 
Die
Collect your grave
Try and equip Backpack

3. What is expected behaviour 
To die and be able to equip backpack - for backpack not to vanish. 

4. Screenshots (If applicable)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/88537204/20763637-48d8-40ad-8a11-0fd1cc4d0edd)

**Comment by Zunwolf1896** [comment]
Have also mentioned this issue in YIGD - (https://github.com/B1n-ry/Youre-in-grave-danger/issues/137 ) as have been having other issues with the graves. Unsure which mod is causing this.

**Comment by Tiviacz1337** [comment]
as I read the issue in yigd, it has been resolved on their side
