### ISSUE TITLE
I cant equip a backpack anymore

### ISSUE THREAD

**Issue by SLYVERRR** [Tiviacz1337/Travelers-Backpack#782]
I was playing in a moded server and 1 time i laged and after i lagged the backpack didnt work again everytime i try to equip a backpack it doesnt work it doesnt say anything i just doesnt work when i click on the equip button it doesnt equip it just closes the backpack gui and do nothing 
Am using the 1.12.2 version of the mod with custome modpack i made

**Comment by SLYVERRR** [comment]
i fixed it

**Comment by FerrisSkai** [comment]
How did you fix this? I have encountered this issue and the only way I can figure out is deleting the player data.
