### ISSUE TITLE
Clicking buttons while holding items in cursor throws the items

### ISSUE THREAD

**Issue by Phoupraw** [Tiviacz1337/Travelers-Backpack#784]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
  - MC 1.20.1
  - Forge 47.1.44
  - Travelers-Backpack 9.1.11

1. Describe the bug 
When holding any items in the cursor, clicking any button in backpack screen will throw the items in the cursor.

2. Write steps to reproduce the bug
  1. Get some items and a backpack.
  2. Open the menu of the backpack.
  3. Click the items to hold it in the cursor.
  4. Click any [button of the backpack](https://github.com/Tiviacz1337/Travelers-Backpack/wiki/Buttons-in-Backpack-Inventory).
  5. The items in the cursor are thrown.

6. What is expected behaviour 
Items in the cursor should be kept on the cursor, or at least are offered back to player inventory, like closing a menu.

7. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack/versions
fixed

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack/versions
for fabric
