### ISSUE TITLE
/give upgraded backpacks [1.19.2]

### ISSUE THREAD

**Issue by TrevorSlobodnick** [Tiviacz1337/Travelers-Backpack#785]
**Is your feature request related to a problem? Please describe.**
Using `/give` to give myself a backpack only allows me to get the default backpack with no upgrades

**Describe the solution you'd like**
Using `/give` (or a custom command) -- give the user the specified backpack with the specified upgrades.

**Possible Examples of Command**
`/tb give @s travelersbackpack:dragon 1 DIAMOND`
`/give @s travelersbackpack:dragon{tier:5} 1`

**Comment by Tiviacz1337** [comment]
you can do that
/give @s travelersbackpack:dragon{Tier:5} 1

tier needs to be uppercase first letter
