### ISSUE TITLE
Issue with master librarians

### ISSUE THREAD

**Issue by lenisdying** [Tiviacz1337/Travelers-Backpack#787]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Forge 1.20.1

1. Describe the bug 

Since the new minecraft update, the only way to obtain mending in survival is to level up a swamp librarian to a master librarian. However this mod changes the last trade to the villager backpack, and there is no way to turn that off. Every single master librarian in the game has this as their last trade.

2. Write steps to reproduce the bug

This is less of a bug, and more of just a general issue. There should be a way to turn off the master trade, or once you buy it once it should never reappear in another villager.

3. What is expected behavior 

Expected behavior is to be able to get the mending trade from a villager, and not the backpack.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
you can disable this trade in config

**Comment by Tiviacz1337** [comment]
villager backpack will be moved to leatherworker villager in the next update

**Comment by Deadramas** [comment]
i tried to disable the trade option in the config. And the villager did not had the backpack as last option as choice, but i did not got mending either. Is there any idea about that? I just got as choice at master: only one option as choice, a nametag. Seems like the other option is just deleted complete

**Comment by Tiviacz1337** [comment]
Update: backpack will be moved to 3rd level of villager instead of being on master level

**Comment by Tiviacz1337** [comment]
https://modrinth.com/mod/travelersbackpack/versions
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files?page=1&pageSize=20
moved trade to 3rd level

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack/versions
for fabric
