### ISSUE TITLE
Forge 47.2.18 Minecraft Version 1.20.1 - Backpack Tier Upgrades cant be combined with Backpack in Smithing Table

### ISSUE THREAD

**Issue by luggiwithahoodie** [Tiviacz1337/Travelers-Backpack#789]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 47.2.18
Minecraft Version 1.20.1

1. Describe the bug 
Backpack cant be upgraded in the smithing table with the Tier-Upgrades, 

2. Write steps to reproduce the bug
Play Minecraft ?

3. What is expected behaviour 
Backpack should be upgradeable like shown

4. Screenshots (If applicable)
![Bild_2023-12-24_231100377](https://github.com/Tiviacz1337/Travelers-Backpack/assets/154763865/7fe8686e-49c5-4fa9-9921-dc985e56068b)

**Comment by Tiviacz1337** [comment]
do you have backpack upgraded to diamond tier?

**Comment by luggiwithahoodie** [comment]
> do you have backpack upgraded to diamond tier?

So i need to go from iron over Gold to diamond and then from diamond to netherite? 
i think i alread tried that but im gonna try it in a creative

**Comment by luggiwithahoodie** [comment]
> do you have backpack upgraded to diamond tier?

Damn i was stupid, it worked, thank you
I also have a iron chest mod installed that works the same way but i didnt try that, thank you
