### ISSUE TITLE
Non-Functional Hose

### ISSUE THREAD

**Issue by BeckPhillips** [Tiviacz1337/Travelers-Backpack#790]
0. Modrinth Forge, 1.19.2-8.2.37

1. Hose is unable to change modes, no matter how I arrange the keybinds.

2. Equip backpack, fill either tank, then attempt to use the hose like normal. The Mode will not change from suck, though you can change the tank selected

3. You should be able to switch between suck and blow function on the hose.

4. Screenshots (If applicable)
(they're not)

**Comment by Tiviacz1337** [comment]
you have to hold keybind and use scroll to change mode

**Comment by BeckPhillips** [comment]
Ah, okay. That wasn't really recorded anywhere, so I figured it was broken. They should likely make it more clear somewhere.
