### ISSUE TITLE
[Fabric 1.20.1] Dehydration Compatibility 

### ISSUE THREAD

**Issue by VoidSharpGithub** [Tiviacz1337/Travelers-Backpack#791]
**Is your feature request related to a problem? Please describe.**
The dehydration mod is apart of a modpack I am developing for 1.20.1. The usage of storing "Purified Water" would be extremely beneficial but does not currently work. 

**Describe the solution you'd like**
Simply allow dehydration.purified_water into the tanks of the backpacks.

**Describe alternatives you've considered**
I could download another mod I guess, but I really enjoy Travelers Backpacks.

**Additional context**
The image below showcases that the bucket will not go into this slot.
<img width="691" alt="image" src="https://github.com/Tiviacz1337/Travelers-Backpack/assets/141502076/0992ebaa-c9e3-486d-ab1a-04aa2bb323f4">

**Comment by Tiviacz1337** [comment]
every modded fluid can be put in tanks if it's registered as fluid and bucket as fluid handler. mod author needs to make changes
