### ISSUE TITLE
Bug With Backpack Buffs

### ISSUE THREAD

**Issue by TheFirstHoneyBadger** [Tiviacz1337/Travelers-Backpack#792]
0. Forge Version ( 47.2.16 )      \       Mod Version ( 1.20.1-9.1.11 )      \     ModPack : All the  Mods 9 ( 0.2.31 )

1. Item: Squid Traveler's BackPack (Traveler's Backpack Mod)

2. The Bug : the buffs keeps active even when I disable de backpack ability,  remove the backpack, drink milk or leave water.

3. Write steps to reproduce the bug: I Activated the backpack ability oce and the buffs nerver fades

4. What is expected behaviour: Nightvision and Waterbreathing all the time 

5. Screenshots (If applicable)
![2023-12-27_21 31 25](https://github.com/Tiviacz1337/Travelers-Backpack/assets/155031365/afc23448-dd79-49ca-9c78-f1bcec5b1099)
![2023-12-27_21 31 31](https://github.com/Tiviacz1337/Travelers-Backpack/assets/155031365/e30df3ba-1485-4032-b151-3b61891a1785)

**Comment by Tiviacz1337** [comment]
I've just downloaded the same modpack you use and can't reproduce the issue, effects normally disappear after disabling ability
