### ISSUE TITLE
crafting Items using REI's Move Items method on the crafting table that comes with a traveler's backpack causes the world to freeze

### ISSUE THREAD

**Issue by wumengzhixing** [Tiviacz1337/Travelers-Backpack#793]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Version：1.18.2
Forge：40.2.10
REI：RoughlyEnoughItems-8.3.681-forge.jar
Traveler's Backpack：TravelersBackpack-1.18.2-7.1.46.jar

1. Describe the bug 
crafting Items using REI's Move Items method on the crafting table that comes with a traveler's backpack causes the world to freeze

https://github.com/embeddedt/ModernFix/issues/335

2. Write steps to reproduce the bug

①. Hold the materials of the articles to be synthesized
②. Open the traveler's backpack
③. Use the R key after mouse is placed on the composite item
④. The synthesized Items are synthesized using REI's Move Items
⑤. After completion, the world freezes and the player cannot interact with any items

3. What is expected behaviour 

4. Screenshots (If applicable)
[Error reporting-2023-12-28_22.25.19.zip](https://github.com/Tiviacz1337/Travelers-Backpack/files/13787964/Error.reporting-2023-12-28_22.25.19.zip)

**Comment by Tiviacz1337** [comment]
Rei compat is not added for Travelers Backpack for Forge, JEI compat is added though. I'll try to add rei compat in the next update

**Comment by wumengzhixing** [comment]
> Rei compat is not added for Travelers Backpack for Forge, JEI compat is added though. I'll try to add rei compat in the next update

Ok, thank you very much for fixing this problem

**Comment by wumengzhixing** [comment]
Can I know when to update it? I can't wait to get the latest fix

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack/versions
Added for Forge
