### ISSUE TITLE
Backpack is not working inn multiplayer

### ISSUE THREAD

**Issue by queries112000** [Tiviacz1337/Travelers-Backpack#794]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric version, and the mod version is 1.20.4 as well as the fabric version

1. Describe the bug 
When I try to use the backpack in single player it works perfectly well, but when I try to use it in multiplayer, when I go to creative and get a bag, it gets into a slot, but then when I press b or right click, it doesn't work, And if i break any brick, the backpack gets changed with that brick, it's like it was never registered.

2. Write steps to reproduce the bug
1. I change the game to creative in multiplayer
2. I put the backpack in a slot after choosing any of them
3. I break any brick, that brick replaces the backpack (pressing right click or b does not open the backpack as well)

4. What is expected behaviour 
The backpack should open when I press b or right click

5. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
you have to install backpack on server too

**Comment by queries112000** [comment]
Do you know anywhere that can guide me on how to do that? Like is it just as simple as making a mods folder and putting the traveler’s pack jar file there? Im really not sure and I’d be very grateful if I can get some extra help!

**Comment by Tiviacz1337** [comment]
you have to set up forge server you cant use mods on client without mods on aerver learn that on your own

**Comment by queries112000** [comment]
I know that fact, but and i have mod in the folder and i have the mod installed in the server but its still not working
