### ISSUE TITLE
Incompatibility with 1.20.2 swamp librarian mending books

### ISSUE THREAD

**Issue by MaraOfGayskull** [Tiviacz1337/Travelers-Backpack#795]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric

1. Describe the bug 
Not really a bug, just a simple mistake. When getting a swamp Villager to Master level, it seems to only give the villager backpack and a name tag for trades. I've only tested it in survival, but other people have made comments on the forum about this so I figured this might be seen and taken into consideration if it was said here.

2. Write steps to reproduce the bug
When upgrading a swamp librarian villager, the last two trades will be the backpack and the name tag, making finding enough mending books incredibly difficult.

3. What is expected behaviour 
occasionally the last trades of a swamp librarian on 1.20.2 will be a mending book.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
the latest update moves backpack to 3rd level of librarian villager instead of master level
