### ISSUE TITLE
Crash with "You're in Grave Danger" mod, only with 9.1.9 version of "Traveler's Backpack" mod

### ISSUE THREAD

**Issue by Lorkhajn** [Tiviacz1337/Travelers-Backpack#798]
Minecraft 1.20.1
Fabric Loader 0.15.3
Fabric API 0.91.0+1.20.1
Cloth Config v11 11.1.118
Cardinal Components API 5.2.2
Traveler's Backpack 1.20.1-9.1.9
You're in Grave Danger 2.0.0-beta.6

(I'm using CruseForge)

When someone attempts to retrieve their items with an equipped backpack (with or without the "trinket" mod installed) from a grave in the "You're in Grave Danger" mod, the server crashes (this occurs in both solo and multiplayer modes). Additionally, upon respawning after death with a backpack enchanted with the "Soulbound" enchantment from the "You're in Grave Danger" mod, the world also crashes (this occurs in both solo and multiplayer modes), and attempting to reconnect leads to repeated world crashes. This bug is specific to version 9.1.9 of the "Traveler's Backpack" mod (no apparent issues in version 9.1.8). After downgrading "Traveler's Backpack" to version 9.1.8 on my server, the problem no longer persists.

**Comment by VirulentSlayer** [comment]
I can confirm, same problem. It is the only time my new server is crashing.
Please see link for crash reports.

https://pastebin.com/svtiYkyy

**Comment by VirulentSlayer** [comment]
I just realised I wasn't using the cardinal components mod, nethertheless the OP did have it.

**Comment by Tiviacz1337** [comment]
It'll be fixed on YIGD side, the developer already knows about the issue
