### ISSUE TITLE
Lost Backpack, restore command does not work

### ISSUE THREAD

**Issue by iRobbit** [Tiviacz1337/Travelers-Backpack#799]
So, I lost my backpack, couldn't find it anywhwere near my death. I dug down until I came across bedrock, nothing. I missed out on the coordinates that were sent in the chat, so I dont know where it is suppsed to be.
I have read about the restore command, but I can't find the backpack UUID anywhere. When I look into the backpack folder (in my world folder), I see a file called "9eced340-7c7a-4fd7-9acc-45616c55d7d9", I thought that may have been the UUID but it didn't work. It tells me "Backpack with ID 9eced340-7c7a-4fd7-9acc-45616c55d7d9 not found". And that folder is filled with notepad files with similar text, that has a bunch of unknown text in it. How do I find the UUID? I don't understand.

My files in the backpack folder has stuff like this in:

   id travelersbackpack:standard
 tag
 	RightTank fluid minecraft:lava  LastTime      Ability   CraftingSettings    RightTankAmount     xÐ SleepingBagColor    	 
MemorySlots      Tier    	 	Inventory
     Slot  Count id minecraft:clock  Slot Count id #travelersbackpack:blue_sleeping_bag  Slot Count1 id cobblemon:azure_ball  Slot Count id minecraft:bucket  Slot Count
 tag Damage   ,  id minecraft:stone_shovel  Slot Count  id minecraft:torch  Slot Count
 tag Damage   a  id minecraft:iron_sword 
 UnsortableSlots      ToolSlotsSettings    
 LeftTank fluid minecraft:water 	 CraftingInventory
    Slot  Count4 id minecraft:cobblestone  Slot Count4 id minecraft:cobblestone  Slot Count4 id minecraft:cobblestone  Slot Count, id minecraft:stick  Slot  Count, id minecraft:stick  LeftTankAmount     xÐ  Count 
   
 What do I do with this information? I don't see the UUID anywhere. Would there be any way to find the coordinates of my lost backpack?

**Comment by Tiviacz1337** [comment]
9eced340-7c7a-4fd7-9acc-45616c55d7d9 this is the uuid, you are proobably doing something wrong, try again. Check if uuid is correct
https://github.com/Tiviacz1337/Travelers-Backpack/wiki/Commands

**Comment by iRobbit** [comment]
I mean.. I tried many times. I'm not suren what the UUID is and what it is supposed to look like. If it's not the folder name of the backpack, then what or where is it..? I've tried the command many times.

**Comment by Tiviacz1337** [comment]
I just said, this is the uuid: 9eced340-7c7a-4fd7-9acc-45616c55d7d9
you have to go to your minecraft installation folder -> saves -> find your save that you play on -> find 'backpacks' folder -> 
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/34790800/638a1986-7d55-463f-8afb-7513245a0eb1)

the file with .dat extension is your backpack, you have to check what uuid it has and paste it to restore command in minecraft

if folder has bunch of those files, you are interested in the latest file (the recent file that got created when you died), take the name of this file without .dat extension (the name of this file is the said UUID) and use restore command
