### ISSUE TITLE
Skip the warning message

### ISSUE THREAD

**Issue by TheHecateII** [Tiviacz1337/Travelers-Backpack#801]
I am using Forge version 1.16.5 and the mod in its latest version 5.4.51.

I cannot skip the warning message informing me that upgrading from 5.3.2 to a higher version will delete my bags.
I want to specify that I have never launched a save with the mod before; I am on a fresh installation
Reproducing the bug is quite simple; just launch the game in version 1.16.5 with the mod.

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/83183415/502d02ad-45c4-48ef-a7c7-9ef754e1e9f1)

**Comment by Tiviacz1337** [comment]
go to config folder -> open travelersbackpack-client (client config for tb i dont remember exact name but it should be something like that) -> set displayWarning to false
