### ISSUE TITLE
Tier Up minecraf 1.20.1

### ISSUE THREAD

**Issue by Falconx94** [Tiviacz1337/Travelers-Backpack#802]
I try to level up the backpack, but it seems that it doesn't work on the blacksmithing table because it is missing a mold, I even tried on the anvil or the crafting table and it doesn't work either.

![Bug Tier Up](https://github.com/Tiviacz1337/Travelers-Backpack/assets/53576554/4303f20d-047b-4362-ab8e-31b6d3f57301)

**Comment by Falconx94** [comment]
the backpack on the image is an iron backpack

**Comment by Tiviacz1337** [comment]
use leather as template
