### ISSUE TITLE
fabric 1.20.1 - when using with multiple trinkets slots, previous backpack gets reset to empty t1.

### ISSUE THREAD

**Issue by TyoAtrosa** [Tiviacz1337/Travelers-Backpack#808]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
1.20.1 Fabric 0.15.3, mod version 9.1.9, playing local multiplayer via open world to LAN. 

1. Describe the bug 
using with mod that adds extra backpack slot, when equipping a second backpack, the first gets reset to a leather tier and has it's inventory erased (happen in both singleplayer and open to lan)

if guest player leaves game while wearing backpack, all inventory gets completely erased. (Lan only)

if guest player places down backpack and stores inventory and leaves game, when world reloaded tanks are emptied (singleplayer and open to lan)

2. Write steps to reproduce the bug

Equip first back pack in trinket slot - diamond tier, containing items
equip second backpack in second trinket slot - same as first.
press open backpack keybind. second backpack opens, first is erased.

where backpack as guest in lan game, leave and return after world reloaded by host.

place backpack with items down with inventory as guest player, and check after reload world.

3. What is expected behaviour 

either keep proper inventory regardless of slot or refuse to equip a second backpack when one is already equipped.
maybe assign separate backpacks individual separate UUIDs and files, and allow accessing backpack by UUID so that they can be restored in event of error?

4. Screenshots (If applicable)
N/A

**Comment by Tiviacz1337** [comment]
https://modrinth.com/mod/travelersbackpack/versions
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Added for Fabric
