### ISSUE TITLE
Forcing Shulkers into Backpack with Transfer Buttons

### ISSUE THREAD

**Issue by TETRA326** [Tiviacz1337/Travelers-Backpack#809]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Minecraft 1.20.1
Forge 47.2.0
Traveler's Backpack 9.1.12

1. Describe the bug 
The config to allow shulkers in the backpack is off. I am unable to place shulkers in the backpack. However, if the shulker is in my inventory and I press the backpack's `transfer-up` key, it places the shulker in the first slot of the backpack.

2. Write steps to reproduce the bug
```
1. Have shulker in inventory and open backpack GUI.
2. Press transfer-up key.
```

4. What is expected behaviour 
The shulker should be in backpack's first slot.

5. Screenshots (If applicable)

![2024-01-17_09 44 54](https://github.com/Tiviacz1337/Travelers-Backpack/assets/131730449/fbdefeed-f8a9-478e-a9e4-68a1c03a88c3)

![2024-01-17_09 45 03](https://github.com/Tiviacz1337/Travelers-Backpack/assets/131730449/3939c000-8f97-4c87-84c0-cda9c124c515)

![Screenshot_20240117_094621](https://github.com/Tiviacz1337/Travelers-Backpack/assets/131730449/8c9285d0-7255-402e-90bc-9ef5b40c13cb)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack/versions
Added for Forge

**Comment by Tiviacz1337** [comment]
https://modrinth.com/mod/travelersbackpack/versions
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Added for Fabric
