### ISSUE TITLE
Abilities ignore configuration settings

### ISSUE THREAD

**Issue by Krimatoria** [Tiviacz1337/Travelers-Backpack#810]
- Forge 1.19.2 Forge 43.3.7
- TravelersBackpack-1.19.2-8.2.38.jar

Abilities do not depend on the settings of the mod's configuration file. If you remove all abilities. Turn them off. Disable the forced activation of the ability, it can still be enabled by simply switching the toggle switch in the backpack. I'm playing on a server with friends, and the whole point of this setup is lost. 
It doesn't matter what settings I have, he'll just turn it on from his backpack. Maybe it only works for hosting, I can't verify it. 
Using the example, I showed that everything was turned off and deleted, but I easily turned it on)

_1- Just install the mod turn it off in the settings and turn them on in your backpack lol ))))_

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/106809386/ae2a1a03-3943-4e93-9d0f-1c7adfeb0a99)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/106809386/06398ecc-3ee3-43c0-a11d-6c01b9af00c2)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/106809386/504bc02a-cbcc-4670-b0a6-c63a0da6c9a4)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/106809386/f8293643-9391-4df5-802f-20fafbae9928)

**Comment by Tiviacz1337** [comment]
you have to edit config on server & client to make it work

**Comment by Tiviacz1337** [comment]
that means you have to edit config on hosting and every player has to edit config to same values too

**Comment by Krimatoria** [comment]
> вам нужно отредактировать конфигурацию на сервере и клиенте, чтобы все заработало

I don't see the server configuration file.
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/106809386/748ef49e-65c8-4139-9846-c0619c12d6c8)

**Comment by Krimatoria** [comment]
> это означает, что вам нужно редактировать конфигурацию на хостинге, и каждый игрок тоже должен редактировать конфигурацию с одинаковыми значениями.

And if the player does not want to configure it on the server, will he then play with other settings other than the server? He can still come in and use this hack cheat.
