### ISSUE TITLE
Config to Disable Backpack Rendering with Cape

### ISSUE THREAD

**Issue by Bukimari** [Tiviacz1337/Travelers-Backpack#812]
There's an option to disable rendering the backpack when an elytra is equipped, but would it be possible to add an option to disable rendering if the player is wearing a cape? The backpack model clips through the cape and can look slightly weird at times. 

This would also probably help for mods like ElytraSlot that make use of the capes tag to equip elytra into a trinket slot as right now elytra equipped into the trinket slot do not trigger the backpack to stop rendering.

**Comment by Tiviacz1337** [comment]
what do you mean by capes tag? can you elaborate? I don't know about ElytraSlot mod and how it works
