### ISSUE TITLE
Feature Request: CONFIG OPTION TO BE ABLE TO USE BACKPACK ONLY WHEN EQUIPED

### ISSUE THREAD

**Issue by Thelegendking** [Tiviacz1337/Travelers-Backpack#813]
**PROBLEM** - Hi! So what I think being able to use multiple backpacks kind off seems a bit OP even if it gives slowness effect there is a better way to approach this in balancing it imo and also in top of that the main usage of backpack is that it is used when players are in long adventures so they will eventually find some mobs spawning with backpacks or could find them somewhere else but the problem is player can't collect them cuz of the slowness effect it gives.

**SOLUTION** -  The idea is that there could be a config option of TB where player can enable that option which makes the backpack only be interactable when its equipped (whether be in Trinket slot or TB's) and it cannot be unequipped until everything from that backpack is emptied out but it can be placed in the ground via new key (Key can be assigned by the player in control option like for hose) which could be used to place the backpack on the ground and also could be equipped back with same key clicked on Backpack. When the stocked backpack is in the ground its inventory is interactable like normal chest and just like that if the backpack is broken it drops all the contained items it had (Except for the fluids it contained, they'll be destroyed).

**ACCOMPLISHMENT** - What this accomplished is that now players can collect as many backpacks as they find on their adventure but the bigger point of this is that now players can only use 1 backpack at a time making backpacks feel more balanced with no annoying slowness debuff, and also introducing a new key which makes placing the backpack on ground to deploy sleeping bag much easier and faster.

**Additional context**
A long time ago I also made a similar request on [Inmis](https://www.curseforge.com/minecraft/mc-mods/inmis) mod (Another really good basic backpack mod) about the "CONFIG OPTION TO BE ABLE TO USE BACKPACK ONLY WHEN EQUIPED" and the author actually implemented that idea on the mod so if you wanna see it as a reference check out this mod's config on how it works.

That's it, I know that's alot probably but let me know what you think about it, thank you for such a useful mod :)

**Comment by Tiviacz1337** [comment]
good idea, I'll think about it

**Comment by Tiviacz1337** [comment]
so the approach with this I came up with would be:
player equips backpack by right clicking backpack in hand and then can access it by B button
player can place backpack on the ground by shift + right click from hand
player can place backpack on the ground by shift + right click from back
player can equip backpack from ground by shift + right click 

backpack only openable from the ground or when equipped
no slowness debuff

this behaviour can be turned on by config option

Will that solution satisfy you?

**Comment by Tiviacz1337** [comment]
need feedback

**Comment by Thelegendking** [comment]
> so the approach with this I came up with would be: player equips backpack by right clicking backpack in hand and then can access it by B button player can place backpack on the ground by shift + right click from hand player can place backpack on the ground by shift + right click from back player can equip backpack from ground by shift + right click
> 
> backpack only openable from the ground or when equipped no slowness debuff
> 
> this behaviour can be turned on by config option
> 
> Will that solution satisfy you?

I'm sorry I took a little break from Minecraft but I'm back now. And YES!! that would be exactly what I want and a perfect implementation of this feature imo.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Added for Fabric

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
Added for Forge
