### ISSUE TITLE
Fabric: Compatibility with Trash Slot mod

### ISSUE THREAD

**Issue by alexweber** [Tiviacz1337/Travelers-Backpack#814]
**Is your feature request related to a problem? Please describe.**
The [Trash Slot](https://modrinth.com/mod/trashslot) mod adds an extra UI element to the inventory, however when Traveler's Backpack renders the inventrory it doesn't display any extra UI elements.

**Describe the solution you'd like**
Ideally it would render not only this but any other UI additions to the vanilla inventory

Thanks!

**Comment by Tiviacz1337** [comment]
From my tests trash slots is displayed in traveler's backpack gui

**Comment by alexweber** [comment]
@Tiviacz1337 what version did you test in?  I can confirm 100% that it doesnt work on 1.20.1 with latest versions of both mods, but granted it's an old minecraft version.  

Thanks!

**Comment by Tiviacz1337** [comment]
you use fabric or forge I tested on forge 1.20.1 and its working

**Comment by alexweber** [comment]
Fabric!

**Comment by alexweber** [comment]
@Tiviacz1337 Just tested on 1.20.1 with only Traveller's Backpack + Trash Slot and required dependencies, really doesn't work, can we re-open this please?

![2024-03-08_17 46 24](https://github.com/Tiviacz1337/Travelers-Backpack/assets/14409/2262d5bf-a2ca-458c-8429-cee59f518990)

![2024-03-08_17 46 19](https://github.com/Tiviacz1337/Travelers-Backpack/assets/14409/2920a7be-3229-4b5f-88ca-1465c9fd45fd)

**Comment by Tiviacz1337** [comment]
you have to specify if its forge or fabric when you report issue

**Comment by Tiviacz1337** [comment]
reopened will try to integrate in the next update

**Comment by Tiviacz1337** [comment]
You have to click T when in Traveler's Backpack GUI and it'll add trash slot automatically:

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/34790800/9efe8532-aa37-4d3e-9861-7998ead07b4c)
