### ISSUE TITLE
[Cross Mod] EMI Craft to Inventory Only Fill But not Craft

### ISSUE THREAD

**Issue by Phoupraw** [Tiviacz1337/Travelers-Backpack#815]
## Is your feature request related to a problem? Please describe.
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/50520903/c924155a-853c-45a0-9982-472686e19894)
### Expected Behaviour
`Craft One` and `Craft All` means moving ingredients to crafting slots. `Craft One to Inventory`, `Craft All to Inventory` and `Craft One to Cursor` means moving ingredients to crafting slots and then perform crafting (and moving results to inventory or cursor).

Backpack crafting slots should behave the same as crafting table.
### Actual Behaviour
For backpack crafting slots, `Craft One to Inventory` behaves the same as `Craft One`. `Craft All to Inventory` behaves the same as `Craft All`.

## Describe the solution you'd like
Make backpack crafting slots as similar to vanilla crafting table as possible, for better compability with mods that modify crafting tables.

## Describe alternatives you've considered
Add specific `EmiRecipeHandler` for backpack.

## Additional context
Loading 65 mods:
- animal_feeding_trough 1.0.3+1.20.1-forge
- apotheosis 7.2.2
- appleskin 2.5.1+mc1.20.1
- architectury 9.1.12
- attributeslib 1.2.1
- betteradvancements 0.3.2.161
- bookshelf 20.1.8
- botany_pots_ore_planting 7.9.0
- botanypots 13.0.22
- clickadv 1.20.1-3.6
- cloth_config 11.1.106
- collective 7.30
- cupboard 1.20.1-2.1
- curios 5.4.5+1.20.1
- davespotioneering 7
- emi 1.1.0+1.20.1+forge
- fallingtree 4.3.2
- flib 0.0.11
- forge 47.1.44
- forgeautofish 6.0.0
- forgeconfigscreens 8.0.2
- fpsreducer 1.20-2.5
- ftblibrary 2001.1.4
- ftbultimine 2001.1.2
- geckolib 4.4
- infinitetrading 4.3
- inventoryprofilesnext 1.10.9
- ironfurnaces 4.1.3
- jade 11.6.3
- jea 1.20.1-5.0.1
- jecharacters 4.5.4
- jeed 1.20-2.1.7
- jei 15.2.0.27
- jeresources 1.4.0.238
- journeymap 5.9.18
- kotlinforforge 4.8.0
- libipn 4.0.1
- libx 1.20.1-5.0.12
- lightoverlay 8.0.0
- lootbeams 1.20.1
- mcpitanlibarch 1.8.5-1.20.1-forge
- metalbarrels 1.20.1-1
- minecraft 1.20.1
- mob_grinding_utils 1.20.1-1.0.3
- mr_raw_oresprocessing 1.5
- oreexcavation 1.13.170
- patchouli 1.20.1-84-FORGE
- pipez 1.20.1-1.2.6
- placebo 8.6.0
- potionring 1.20-1.0
- puzzlesaccessapi 8.0.7
- puzzleslib 8.1.11
- reap 1.20.1-1.0.2
- shimmer 1.20.1-0.2.3
- simplemagnets 1.1.10
- sophisticatedbackpacks 3.19.5.988
- sophisticatedcore 0.5.113.524
- storagedrawers 12.0.2
- storagenetwork 1.10.0
- supermartijn642configlib 1.1.8
- supermartijn642corelib 1.1.16
- travelersbackpack 9.1.12
- uncraftingtable76 1.2.9
- universalenchants 8.0.0
- xpbook 2.2

**Comment by Phoupraw** [comment]
Traveler's Backpack Fabric 1.20.1-9.1.9 doesn't have such issue.

**Comment by alexweber** [comment]
+1 Confirm that EMI works fine with the backpack crafting interface on Fabric 1.20.1-9.1.9

**Comment by Tiviacz1337** [comment]
so it's forge?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack/versions
Added for Forge
