### ISSUE TITLE
Tool slot widget not working

### ISSUE THREAD

**Issue by NERD-NATO** [Tiviacz1337/Travelers-Backpack#816]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
On Fabric, 1.20.1, mod version 9.1.9.

1. Describe the bug 
When I open my backpack, instead of the 9 columns of storage space i expected, I get 8 columns of normal storage (including the crafting grid) and one glitchy column, part of which appears to be empty space (but are actually slots) and part of which looks like tool slots, but do not function as tool slots for the purposes of tool swap. The widget (seemingly added in 9.1.5) is nowhere to be seen.

2. Write steps to reproduce the bug
1: Open backpack (using B key or right-clicking)
2: witness bug

3. What is expected behaviour 
Assumedly, to see the inventory as shown in the mod page, as well as in the inventory preview when hovering over backpack and holding CTRL.

4. Screenshots (If applicable)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/74015645/fd095ddc-f913-48a5-9dcc-3fc7d106ee40)

Expected inventory: 
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/74015645/af8ddce2-469f-4c5c-a869-03d46ecfbaeb)

**Comment by Tiviacz1337** [comment]
The tool widget is physically in the place that it is on the second picture, you dont see it because the texture pack you use is outdated. Disable texture pack to see widgets and everything correctly
