### ISSUE TITLE
administrative command /clean

### ISSUE THREAD

**Issue by Elabrax** [Tiviacz1337/Travelers-Backpack#817]
**Is your feature request related to a problem? Please describe.**
Add the functionality that the backpack is not immune to the /clean command, or that there can be an administrative command, so that the contents of the backpack can be deleted.

**Describe the solution you'd like**
Try binding the /clean command or making the backpack not invisible in the inventory, so the command can take effect

**Comment by Tiviacz1337** [comment]
https://github.com/Tiviacz1337/Travelers-Backpack/wiki/Commands
