### ISSUE TITLE
Add option to allow for shulker boxes in backpack without decompiling .class

### ISSUE THREAD

**Issue by Glorpadorp172** [Tiviacz1337/Travelers-Backpack#818]
**Is your feature request related to a problem? Please describe.**

I have  little programming knowledge and none at all in java so I'm not smart enough to figure out how to decompile and recompile a .class file to change a 'false' value to 'true'

**Describe the solution you'd like**
a more dumbed down way of allowing or disallowing shulker boxes in backpacks. (could it possibly be done similar to how allowed tools are run through a .json?)

(travelers-backpack-1.20.1-9.1.9.jar\com\tiviacz\travelersbackpack\config\TravelersBackpackConfigData$World.class)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/157538352/acee861b-d692-49d7-8ba9-a21e660f1623)

**Comment by Tiviacz1337** [comment]
what are you doing? or try to accomplish? you can go to config folder in your minecraft installation -> find travelersbackpack-common config file and edit allowShulkerBoxes to true in notepad...

**Comment by Teimo13** [comment]
> what are you doing? or try to accomplish? you can go to config folder in your minecraft installation -> find travelersbackpack-common config file and edit allowShulkerBoxes to true in notepad...

Thank you 
I was searching the mod files for like an hour by now for that option 
ahhhhhhhhhhhh i hate myself 

But awesome mod!
