### ISSUE TITLE
Tanks Capacity config and tooltip change

### ISSUE THREAD

**Issue by Unleashed75** [Tiviacz1337/Travelers-Backpack#821]
**Is your feature request related to a problem? Please describe.**
Not related to a problem but can be confusing.
In the configs you have "tanksCapacity". These settings could be confusing for some.
While I understand how the numbers are working, if you don't know how fabric works with water, these numbers can be extra confusing.
The same goes with the tooltip. This at a glance makes no sense to the everyday minecrafter. 

**Describe the solution you'd like**
I would like to see the config changed to work by whole numbers or in millibuckets, so at a glance a user can see how many buckets it is for each tier.
Same or more importantly to have the tooltip show the user a much easier, quick to understand number.

**Describe alternatives you've considered**
I have no alternatives, I'd mainly just like to see the tooltip make more sense to my gran or my kid

**Additional context**
Shared these before. I hope it can all be changed to make more sense at a glance
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/136971457/d49267bd-9951-4a14-9f89-a7a31464d4fd)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/136971457/7fe9a2a5-4adb-4ac4-9fdb-a1aa11d9efd4)

Thanks for your time and for your mod :)

**Comment by Tiviacz1337** [comment]
Config will stay the same, just with comment 81000  = 1 bucket
tooltips will show in mb so 1000 equals 1 bucket etc.

**Comment by Tiviacz1337** [comment]
https://modrinth.com/mod/travelersbackpack/versions
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Added for Fabric
