### ISSUE TITLE
Keybind for hose and tools not working.

### ISSUE THREAD

**Issue by jwjones35** [Tiviacz1337/Travelers-Backpack#824]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 1.20.1

1. Describe the bug 
No keybinding is working for changing the hose mode, and tool swap.

2. Write steps to reproduce the bug
I've tried swapping to over a dozen new keybinds, none changed the hose from "suck" or swapped out the equipped tools.

3. What is expected behaviour 
The hose should change function, and the tools should swap.

4. Screenshots (If applicable)

**Comment by jwols123** [comment]
I'm having the same problem. suddenly a new update stopped the "swap tool or change hose mode" keybind from working. I loved this feature and would love for it to continue working as it had in the past.

**Comment by Tiviacz1337** [comment]
You have to hold keybind and scroll up or down
