### ISSUE TITLE
Config for how many storage slots each Tier will have?

### ISSUE THREAD

**Issue by PinkLasagna03** [Tiviacz1337/Travelers-Backpack#825]
I think it would be great if (just like managing how many buckets of liquid each tier stores) we could change the amount of storage each tier will have. I think adding just one row on each Tier is kinda underwhelming and not worth the upgrades, especially the netherite upgrade. 
 
It would be nice to have in the config files an option to add how many rows or/and colums of slots each Tier has. For example;
LeatherTierColums: 9
LeatherTierRows: 3
IronTierColums: 11 (instead of 9)
IronTierRows: 5 (instead of 4)
etc... 

I've considered other mods, but I wanna keep it simple. It is part of a modpack in development, but I'm searching for a great backpack modpack. I really like this one, except for the fact for the small storage slots per tier. I'm using Backpacked now for the modpack, but I do like the Tier system within your mod. Sophisticated Backpacks adds the upgrades I really don't like. Besides, I really like the tools slot and buckets storage!

**Comment by Tiviacz1337** [comment]
The problem I encounter while wanting to implement this is that I don't know what to do with crafting, In fact I could do that minimal backpack size is 3x3. What do you think about it

**Comment by PinkLasagna03** [comment]
I think that could be a great idea; Just say there has to be a minimal rows of 3 and a minimal columns of 3, so you have the crafting part, otherwise the game will crash or just use standard configs? What I also think of is having a seperate tab for the crafting table, but I can imagine that that would require a bit of rework, but see what you can do. Would love if it would be implemented in some way or another! :)

**Comment by PinkLasagna03** [comment]
@Tiviacz1337 I was wondering how it was going with this feature? I don't wanna rush you or something, it's more for my personal planning good to know if I will be able to add your mod before I can release my modpack end of this month :)

**Comment by Tiviacz1337** [comment]
I think I will be able to start working on new update by the next week. Unfortunately I think its impossible for update to come out by the end of this month. It requires me to rewrite a lot of code so it'll take some time.

**Comment by PinkLasagna03** [comment]
> I think I will be able to start working on new update by the next week. Unfortunately I think its impossible for update to come out by the end of this month. It requires me to rewrite a lot of code so it'll take some time.

@Tiviacz1337 Good to know it will be a feature! I will include your mod in my modpack anyways and just upload an update whenever your part is done. Thank you so much:)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack

Upgrades update for all mod loaders for 1.21
Increased max backpack capacity to 99 slots
