### ISSUE TITLE
Crashes when trying to  access backpack

### ISSUE THREAD

**Issue by BoWeasel** [Tiviacz1337/Travelers-Backpack#829]
0.) Modloader= Forge 1.19.4-8.4.20

1.) The squid backpack I have equipped is not showing up nor is it accessible.
When I click on the standard travelers backpack in my hotbar the game crashes. 

2.) I right-click on the backpack I have in my hotbar and the game crashes.
I also tried to shift, right-click on the backpack to put it on the ground in front of me and then access it but again the game crashed 

6. it was not expected behavior

7. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
provide crash log
