### ISSUE TITLE
Render Crash 1.19.2 Fabric

### ISSUE THREAD

**Issue by RiftSpatial** [Tiviacz1337/Travelers-Backpack#830]
Fabric 0.14.22 Version 8.2.33

1. Describe the bug 

Opening a backpack randomly crashes.

2. Write steps to reproduce the bug

Player just opens the backpack and it will randomly crash.

3. What is expected behaviour 

It doesn't crash.

Crash Report: https://paste.gg/p/anonymous/1a7a2bb758cd48f184dd88c9ee894053
(Will try to get a log as well.)

If there are other mods that may be suspected just let me know if I need to report it to them.
(We do have Sodium, and it also mentions EMI in the report as well.)

**Comment by Tiviacz1337** [comment]
https://modrinth.com/mod/travelersbackpack/versions
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Fixed for Fabric
