### ISSUE TITLE
Config to allow anything in tool slots.

### ISSUE THREAD

**Issue by jwols123** [Tiviacz1337/Travelers-Backpack#831]
My problem is small. I often have times when I find a modded tool, but it can't go into the tool slots for the backpack. This causes me to have to shove it in the storage of the backpack or my inventory.

I would like to have the ability to change the config so ANYTHING can go in the tool slots. It would be a big help, to allow modded items to go in there, along with other non-moded items or items that don't fit the category that I just want there.

The alternative of manually adding them to the whitelist list is very time-consuming and not very effective if you have a massive mod. 

I have a hard time understanding config settings other than "true" or "false". This makes it fairly troubling for me to manually add all of the different item IDs to the list, also considering my probability of typing them in wrong... I just believe that it would be a nice config to add for people that want it.

**Comment by Tiviacz1337** [comment]
added

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack/versions
Added for Forge

**Comment by Tiviacz1337** [comment]
https://modrinth.com/mod/travelersbackpack/versions
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Fixed for Fabric
