### ISSUE TITLE
Allow adding item tags to tool slots

### ISSUE THREAD

**Issue by dhouck** [Tiviacz1337/Travelers-Backpack#832]
**Is your feature request related to a problem? Please describe.**
It is tedious to configure all relevant modded items for the tool slots, especially when there are many similar tools.

**Describe the solution you'd like**
In addition to accepting item resource locations, `toolSlotsAcceptableItems` should accept item tags such as `"#botania:rods"` or `"#farmersdelight:straw_harvesters"`. 

**Describe alternatives you've considered**
Allowing globbing (`botania:*Rod`) or even regexes for item names would also solve #831 (by adding `*:*`), but that seems inelegant based on how Minecraft resource locations usually work.

**Additional context**
Currently, when I try to add an item tab, there is a crash on startup (not world startup, game startup).  This seems non-ideal even if this feature isnʼt implemented.

Game version: 1.20.1
Mod loader: Fabric
Mod version: 9.1.9

**Comment by dhouck** [comment]
Ooh, you can add items via data pack instead of config file, and data packs accept tags, so I can still do what I want here.

**Comment by Tiviacz1337** [comment]
yes use datapacks
