### ISSUE TITLE
Add vanilla brush as default tool slot item

### ISSUE THREAD

**Issue by dhouck** [Tiviacz1337/Travelers-Backpack#833]
**Is your feature request related to a problem? Please describe.**
I was surprised when I could not put a brush in a backpack tool slot

**Describe the solution you'd like**
Make the brush count as a tool

**Describe alternatives you've considered**
Add it as a tool myself via config options

**Additional context**
If you think this should not count as a tool, then Iʼd appreciate guidelines on what you expect should and should not count.  It seems more obviously a tool than the other edge cases like swords or tridents.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all?page=1&pageSize=20
https://modrinth.com/mod/travelersbackpack/versions
Added for Forge

**Comment by Tiviacz1337** [comment]
https://modrinth.com/mod/travelersbackpack/versions
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Added for Fabric
