### ISSUE TITLE
Fabric 1.19.4 Internal server error

### ISSUE THREAD

**Issue by Deathcon2040** [Tiviacz1337/Travelers-Backpack#835]
I'm running a 1.19.4 Fabric server and whenever I use a version of Travelers Backpack newer than 8.4.0. It says that there was an internal server error.

Here's a list of the mods I have installed.

- Cardinal Components API 5.1.0
- Cloth Config 10.1.105
- Fabric API 0.76.0
- Falling Tree 3.12.0
- Plasmo Voice 2.0.8
- Travelers Backpack 8.4.0 (Can't use a newer version or else it won't let anyone join)
- Trinkets 3.6.0

**Comment by Tiviacz1337** [comment]
maybe update the mod on server?
