### ISSUE TITLE
Config: loot tables for backpacks

### ISSUE THREAD

**Issue by Grandof1** [Tiviacz1337/Travelers-Backpack#836]
## Is your feature request related to a problem? Please describe.
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
- Not able to `configure` certain backpacks can be found in `loot chests` in the `config`

## Describe the solution you'd like.
_A clear and concise description of what you want to happen._

- Able to `configure` specific backpacks to where they can be found, similar to which mobs can spawn with specific backpacks
- Able to set the `percentage` of chance that specific backpack can be found in the particular `loot chest`

## Describe alternatives you've considered.
_A clear and concise description of any alternative solutions or features you've considered._
- Honestly can't think of any, I'm sorry

### Additional context
_Add any other context or screenshots about the feature request here._
- Much like how the wiki's [Loot](https://github.com/Tiviacz1337/Travelers-Backpack/wiki/Loot) page shows difference `structures`, `backpacks` and their `chances` would be extremely nice to be able to `configure` this in the `config` for each [structure](https://minecraft.wiki/w/Structure) (so I can only allow my players on my server to get specific backpacks in certain locations found via exploring)

#### Config Example: 
```
"world": {
		// Enables backpacks spawning in loot chests
		"enableLoot": true,
		// List of loot tables by structures, add/remove entries if backpacks are/not part of loot table
		"mineshaft": [
			"travelersbackpack:blaze",
			"travelersbackpack:squid",
			"travelersbackpack:sponge",
			"travelersbackpack:bat",
		],
		"ancientCity": [],
		"stronghold": [
			"travelersbackpack:sponge",
			"travelersbackpack:bat",
		],
		"burriedTressure": [
			"travelersbackpack:standard",
		],
		// Enables chance to spawn Zombie, Skeleton, Wither Skeleton, Piglin or Enderman with random backpack equipped
		"spawnEntitiesWithBackpack": false,
```
#### Note
- Not sure how would write in the chances in example

**Comment by Tiviacz1337** [comment]
I think you can disable all backpack loot from the mod and create datapacks to add backpack to loot on your own rules
