### ISSUE TITLE
Player not able to Equip Backpack when Curios API is present

### ISSUE THREAD

**Issue by thousandSun** [Tiviacz1337/Travelers-Backpack#837]
0. Forge Mod Loader (47.2.20). Traveler's Backpack version 1.20.1-9.1.12. Curios API version 5.7.0+1.20.1

2. Describe the bug 
Pressing the "Equip" button in the backpack UI doesn't equip the backpack. Has something to do with Curios API

3. Write steps to reproduce the bug
Install Traveler's backpack mod. 
Install curios API mod. 
Try to equip backpack

4. What is expected behaviour
BackPack to be equipped on player

**Comment by Tiviacz1337** [comment]
If you have curios api installed and curiosIntegration enabled then you have to put backpack manually in back slot of curios inventory
