### ISSUE TITLE
items stuck in ctrl view

### ISSUE THREAD

**Issue by lyra0627** [Tiviacz1337/Travelers-Backpack#840]
when i press ctrl while hovering over a backpack i can see items that i need on the far left, however when i open the backpack they are not there. i cannot access these items and need them.

**Comment by Tiviacz1337** [comment]
I dont understand the issue can you provide video or screenshots?

**Comment by lyra0627** [comment]
![072A2221-6A73-4FAE-A20A-3E7E8551BC5A](https://github.com/Tiviacz1337/Travelers-Backpack/assets/162420940/919761e7-f0dc-48cd-b112-1df33c5cfcf1) 
![B0AC7FA5-F8D2-4708-8EE6-160F4C421F94](https://github.com/Tiviacz1337/Travelers-Backpack/assets/162420940/8295821e-599e-4953-ad90-11bad4504ba1) 
![57107DCB-E5B2-4437-AE5F-F3DA37822E8B](https://github.com/Tiviacz1337/Travelers-Backpack/assets/162420940/46c6c4c9-d3ec-4b7d-adcd-b08c15a04a89)

**Comment by lyra0627** [comment]
Even with an empty inventory those items in the far left green boxes (circled them) can not be removed from the back pack. Including when the back pack is opened.

**Comment by lyra0627** [comment]
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/162420940/f29af3c2-36bf-4086-a177-bd0aaf9ce80f)
Same back pack in first image but opened. Those two items are not there.

**Comment by Tiviacz1337** [comment]
you are using outdated resourcepack:
the button is here
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/34790800/e6ef9fa7-836b-4ee8-b3d7-85aa1f1817d7)
you can click it and it will work, it just doesnt show because resourcpack is outdated
