### ISSUE TITLE
Ability not working on single player with the slider enabled.

### ISSUE THREAD

**Issue by WR3CKINGBALL** [Tiviacz1337/Travelers-Backpack#847]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
fabric
1.20.4

1. Describe the bug 
When using the ender pack that increases range it doesn't increase it whether or not the slider is enabled
Ability not working on single player with the slider enabled.

2. Write steps to reproduce the bug
Equip backpack and enable slider.

3. What is expected behaviour 
Ability to work on single player with the slider enabled.
![2024-03-16 20-01-45](https://github.com/Tiviacz1337/Travelers-Backpack/assets/20303657/0ef8ff07-3653-4f65-91a3-f4d281bb5db2)
single player with the slider enabled.

4. Screenshots (If applicable)

**Comment by WR3CKINGBALL** [comment]
I have many mods enabled, and i dont know if there is a conflict.  I have removed any mod that I suspect could conflict and nothing.  THANK YOU FOR YOUR EFFORT IN KEEPING THIS MOD UP TO DATE AND YOUR BUGTRACKING AND COMMUNITY FEEDBACK.
list of mods used:

additionallanterns-1.1.1a-fabric-mc1.20.4.jar                        
architectury-11.1.13-fabric.jar                                      
ArmorPoser-fabric-1.20.4-4.1.1.jar                                   
authme-8.0.0+1.20.4.jar                                              
autotools-1.20.4-fabric-2.0.jar                                      
BackToBed-Fabric-1.20-1.1.0.jar                                      
balm-fabric-1.20.4-9.0.6.jar                                         
BambooEverything-fabric-4.1.0+mc1.20.4.jar                           
blur-3.2.0.jar                                                       
CameraOverhaul-1.4.0-fabric-universal.jar                            
capes-1.5.3+1.20.2-fabric.jar                                        
cardinal-components-api-5.4.0.jar                                    
carryon-fabric-1.20.4-2.1.3.13.jar                                   
catloaf-1.1.0-1.20.4-FABRIC.jar                                      
CHAS-1.20-1.10-Fabric.jar                                            
chatanimation-1.0.5.jar                                              
clickthrough-1.20.4-fabric0.91.2-0.4.1.jar                           
cloth-config-13.0.121-fabric.jar                                     
collective-1.20.4-7.36.jar                                           
Continents_1.20.4_v1.1.4.jar                                         
crawl-0.12.2.jar                                                     
CreativeCore_FABRIC_v2.11.16_mc1.20.4.jar                            
customizableelytra-fabric-2.2.1+1.20.4.jar                           
CutThrough-v20.4.2-1.20.4-Fabric.jar                                 
DiagonalFences-v20.4.0-1.20.4-Fabric.jar                             
DiagonalWalls-v20.4.0-1.20.4-Fabric.jar                                                                                      
DistantHorizons-fabric-2.0.2-a-dev-1.20.4.jar                        
dynamiccrosshair-7.7+1.20.4-fabric.jar                               
DynamicSoundFilters-1.4.0+1.20.4.jar                                 
enchanted-vertical-slabs-1.9.2.jar                                   
endermanoverhaul-fabric-1.20.4-1.1.0.jar                             
fabric-api-0.96.4+1.20.4.jar                                         
fabric-language-kotlin-1.10.18+kotlin.1.9.22.jar                     
fastentitytransfer-fabric-1.20.x-1.2.2.jar                           
footprintparticle-0.5.1-mc1.20.2.jar                                 
ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric.jar                         
geckolib-fabric-1.20.4-4.4.2.jar                                     
GlitchCore-fabric-1.20.4-1.0.0.59.jar                                
handcrafted-fabric-1.20.4-3.2.1.jar                                  
HangGlider-v20.4.1-1.20.4-Fabric.jar                                 
HeldItemTooltips-v20.4.1-1.20.4-Fabric.jar                           
Iceberg-1.20.4-fabric-1.1.18.jar                                     
indium-1.0.30+mc1.20.4.jar                                           
inventoryhud.fabric.1.20.4-3.4.19.jar                                
invisframes-2.2.2.jar                                                
iris-mc1.20.4-1.7-alpha.1-ba8b16d4.jar                               
ItemBorders-1.20.2-fabric-1.2.1.jar                                  
ItemPhysic_FABRIC_v1.7.0_mc1.20.4.jar                                
jei-1.20.4-fabric-17.3.0.49.jar                                      
LeavesBeGone-v20.4.1-1.20.4-Fabric.jar                               
MapTooltip-fabric-1.20-3.0.0.jar                                     
mcw-furniture-3.2.2-mc1.20.4fabric.jar                               
mcw-lights-1.0.6-mc1.20.4fabric.jar                                  
mcw-windows-2.2.1-mc1.20.4fabric.jar                                 
modmenu-9.0.0.jar                                                    
moonlight-1.20.4-2.10.3-fabric.jar                                   
MoreChestVariants-1.5.0+1.20.4-Fabric.jar                            
mousewheelie-1.13.3+mc1.20.4.jar                                     
mru-0.4.0+1.20.4.jar                                                 
MultiRecipe-Mod-Fabric-1.20.4.jar                                    
notenoughcrashes-4.4.7+1.20.4-fabric.jar                             
omnihopper-2.2.4+1.20.4.jar                                          
paperdoll-fabric-1.2.0-mc1.20.4.jar                                  
particle-rain-2.0.8.jar                                              
PickUpNotifier-v20.4.2-1.20.4-Fabric.jar                             
Ping-Wheel-1.8.0-fabric-1.20.4.jar                                   
playerplates-fabric-4.0.0+mc1.20.4.jar                               
Prism-1.20.4-fabric-1.0.6.jar                                        
PuzzlesLib-v20.4.36-1.20.4-Fabric.jar                                
Quad-1.1.1+1.20.4-Fabric.jar                                         
realisticbees-1.20.4-3.8.jar                                         
resourcefulconfig-fabric-1.20.4-2.4.5.jar                            
resourcefullib-fabric-1.20.4-2.4.8.jar                               
sawmill-1.20.4-1.3.1-fabric.jar                                      
scaffoldingdropsnearby-1.20.4-3.2.jar                                
SereneSeasons-fabric-1.20.4-9.3.0.23.jar                             
serversleep-datapack.jar                                             
shared-echest-1.0.2.jar                                              
signeditlite-1.0.1+mc1.20.4.jar                                      
simplemagnets-1.1.10-fabric-mc1.20.4.jar                             
skinlayers3d-fabric-1.6.2-mc1.20.4.jar                               
slimyfloor-1.20-1.2.8.jar                                            
sodium-fabric-0.5.8+mc1.20.4.jar                                     
spyglass-improvements-1.4+mc1.20.2+fabric.jar                        
supermartijn642configlib-1.1.8a-fabric-mc1.20.2.jar                  
supermartijn642corelib-1.1.17-fabric-mc1.20.3.jar                    
textile_backup-3.1.3-1.20.jar                                        
time-and-wind-ct-1.4.8+1.20.2-1.20.4.jar                             
trashslot-fabric-1.20.4-16.0.1.jar                                   
travelers-backpack-1.20.4-9.4.0.jar                                  
villagernames-1.20.4-4.5.2.jar                                       
waveycapes-fabric-1.4.3-mc1.20.4.jar                                 
worldplaytime-1.2.1-1.20.4-FABRIC.jar                                
yet-another-config-lib-fabric-3.3.21.20.4.jar

**Comment by Tiviacz1337** [comment]
It's not the bug, fabric does not have raech distance as modifiable attribute in base code like Forge. It uses lib that was created by other modder. When I was releasing the 1.20.4 the mod hasnt been ported yet. From what can I see it is ported now, so enderman abiliy will work in the next update which will come out hopefully in the next weekend

**Comment by WR3CKINGBALL** [comment]
You the best!  Thanks!

**Comment by Tiviacz1337** [comment]
https://modrinth.com/mod/travelersbackpack/versions
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Added for Fabric

**Comment by WR3CKINGBALL** [comment]
Thanks for the update link my friend!!  Very kind of you to reach back out
to me!
