### ISSUE TITLE
Crafting issue

### ISSUE THREAD

**Issue by Dropje1** [Tiviacz1337/Travelers-Backpack#849]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
1. i am using forge fabric

2. Describe the bug 
i am exploring the mod and i realised when trying to craft it i cant craft the backpack tanks ive made sure i had the right recepie wut it wont craft i am playing on feather 1.20.4
sorry for the little info
thanks for the help in advance

**Comment by Tiviacz1337** [comment]
(https://github.com/Tiviacz1337/Travelers-Backpack/wiki/Crafting-Recipes)
