### ISSUE TITLE
Can´t start minecraft. Neoforge.

### ISSUE THREAD

**Issue by Lenny14** [Tiviacz1337/Travelers-Backpack#852]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 
Whenever I start Minecraft it crashes.
You can see the message in the provided screenshot.
There are no other mods added.

2. Write steps to reproduce the bug

3. What is expected behaviour 

4. Screenshots (If applicable)
![Unbenannt](https://github.com/Tiviacz1337/Travelers-Backpack/assets/62352501/9f956f7e-4414-4f61-9c44-4eb14030df3e)

**Comment by Tiviacz1337** [comment]
Install curios api as for now. Ill release update to fix it soon

**Comment by Tiviacz1337** [comment]
Can you show me crash log?

**Comment by Kazyilla** [comment]
> Can you show me crash log?

I'm also having this error, where do I find the crash log to send it to you?

**Comment by Tiviacz1337** [comment]
Duplicate #874
