### ISSUE TITLE
Crash placing Traveler's Backpack via non-player means

### ISSUE THREAD

**Issue by James103** [Tiviacz1337/Travelers-Backpack#853]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Mod pack: All the Mods 9 for Minecraft 1.20.1
Mod loader: Forge
Mod version: 9.1.12

### Describe the bug 
https://github.com/Tiviacz1337/Travelers-Backpack/blob/5cc56a7bd33a1ae8295065f469d34db5cab3b297/src/main/java/com/tiviacz/travelersbackpack/items/TravelersBackpackItem.java#L91

When a Traveler's Backpack is tried to be placed by a Dispenser using Quark's Dispensers Place Blocks module, the game crashes because `context.getPlayer().isCrouching()` is tried to be accessed, but `context.getPlayer()` is null.

### Steps to reproduce
1. Install Quark and Traveler's Backpacks.
2. Enable the Dispensers Place Blocks module in Quark.
3. Get a dispenser, a lever, and a Traveler's Backpack.
4. Place down the dispenser on level ground, and put a Traveler's Backpack inside it.
5. Power the dispenser.
6. The game crashes.

### Expected behaviour 

There should be a check to make sure `context.getPlayer()` exists (i.e. it is non-null) before trying to access `context.getPlayer().isCrouching()` 

Originally reported in https://github.com/AllTheMods/ATM-9/issues/1512

### Crash report
https://gist.github.com/NavajoCody/938a0cceb7bc5902a5fe58f4c71ddc18

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20 fixed for fabric

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all?page=1&pageSize=20 Fixed for forge
