### ISSUE TITLE
Trinkets integration causing item disappear

### ISSUE THREAD

**Issue by mileska** [Tiviacz1337/Travelers-Backpack#854]
Minecraft: 1.20.1 (single player)
Fabric Loader: 0.15.7
Fabric API: 0.92.0

Trinkets: 3.7.2
Traveler's Backpack: 9.1.9

Description:
When using trinket integration sometimes items disappear.

Steps to reproduce:

1. Open backpack inventory screen and add several item stacks to backpack inventory.
2. Close backpack inventory.
3. Open backpack inventory.
4. Close backpack inventory.
5. Open backpack inventory.
6. Items gone afterwards

Expected behaviour:
When multiple item stacks are transferred from player to backpack inventory, and after closing, and then reopening the backpack inventory screen, all of the item stacks previously transferred are present on the backpack inventory.

Additional Information:
Sometimes several attempts of open & close needs to happen to reproduce

**Comment by Tiviacz1337** [comment]
already reported

**Comment by Tiviacz1337** [comment]
downgrade t trinkets 3.7.1 as for now
