### ISSUE TITLE
backpack lost it's crafting grid and option about it

### ISSUE THREAD

**Issue by EVSkyFall** [Tiviacz1337/Travelers-Backpack#855]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Minecraft 1.20.1
Fabric 0.14.25
Prominence II RPG v2.7.7hf
travelers-backpack-1.20.1-9.1.8.jar

1. Describe the bug 
in some condition,  backpack lost it's ability to craft.
it loses it's crafting grid, crafting option and crafting output

2. Write steps to reproduce the bug

i have no i dea
i failed to recreate this bug from single player world but this bug persist to server.
i was able to use crafting grid, but some point, i lost the ability and every slot turned into normal slot
and crafting grid disappeared from every backpack in server for me.

single player world was working fine

3. What is expected behaviour 

having crafting grid

4. Screenshots (If applicable)

![스크린샷 2024-03-23 023518](https://github.com/Tiviacz1337/Travelers-Backpack/assets/44705761/5ad92edd-927a-4647-983b-a68f7f0052eb)

**Comment by Tiviacz1337** [comment]
idk, you might use outdated resourcepack or server owner changed config to disable crafting
