### ISSUE TITLE
Unable to switch hose modes

### ISSUE THREAD

**Issue by bribrithebrienceguy** [Tiviacz1337/Travelers-Backpack#856]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Using Fabric, 1.20.4-9.4.0

1. Describe the bug 

When using the hose with the backpack, it defaults to suck mode. When pressing the key to switch modes, nothing happens. 

2. Write steps to reproduce the bug

Reproduce by attempting to switch modes with the hose. 

3. What is expected behaviour 

Expected behavior is that when pressing bound key, the mode of the hose should switch. 

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
hold key + use mouse scroll
