### ISSUE TITLE
Backpack stuck on player

### ISSUE THREAD

**Issue by SoggyCoffee** [Tiviacz1337/Travelers-Backpack#857]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 
Backpack Stuck on player does not show up on any slots can be seen on back and used with hotkey

2. Write steps to reproduce the bug

shift right click on top of another backpack on ground

3. What is expected behaviour 

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
try to /kill and pickup backpack again
