### ISSUE TITLE
game crashes everytime i try to go near... bees??

### ISSUE THREAD

**Issue by scoutachron** [Tiviacz1337/Travelers-Backpack#858]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
forge 1.20.1, multiplayer

1. Describe the bug 
game crashes when i try to play the game and it seems to be blamming... bees.
also the mod shouldnt be installed anywhere, so i dont know how this is happening.

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Registry Object not present: travelersbackpack:bee

2. Write steps to reproduce the bug
play a multiplayer server with the mod

3. What is expected behaviour 
game will crash when you go near a bee

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
you have to install mod on client & server and both need to have same version
