### ISSUE TITLE
1.20.1 Keep Backpack On Death

### ISSUE THREAD

**Issue by S0741** [Tiviacz1337/Travelers-Backpack#859]
Keep backpack on death config option

I don't want to use the KeepInventory command from Minecraft because it keeps XP too so I disabled it and got a mod that-
keeps the inventory items but lets me be punished by losing XP... Problem is that the backpack drops from my inventory-
and I can't find the slot ID
I've been looking on google for 1.5 hours now... 

pls add the update to 1.20.1 since there are more mods for that version then more modern versions TY

**Comment by NolanHewitt** [comment]
I think its because it places the backpack as a block where you die. Try changing "backpackDeathPlace" to false in the config and see if it lets you keep it on death after that.

**Comment by Tiviacz1337** [comment]
Do you use curios/trinkets

**Comment by S0741** [comment]
I do not use curios...

And tried having "backpackdeathplace" set to false,

Instead of placing as a block it just drops as an item on the ground

**Comment by Harmless05** [comment]
In the travelersbackpack.json config try setting the `trinketsIntegration` to `false`.

> I do not use curios...
> 
> And tried having "backpackdeathplace" set to false,
> 
> Instead of placing as a block it just drops as an item on the ground

**Comment by Tiviacz1337** [comment]
I've improved overall logic for backpack placement/drop after death
As for now available on Neo 1.20.4: https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5372415
Forge & Fabric coming soon

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Fixed for fabric 
Forge soon

**Comment by LightningFerix** [comment]
I have a similar issue on 1.20.1 where I died in the ocean and the backpack is nowhere to be seen. It was never placed anywhere. Is there a way to locate the placed backpack through commands?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
Improved logic for dropping backpack for Forge
Try changing backpackDeathPlace to false now It might work. If not additional compat is required
