### ISSUE TITLE
Dupe with shearing in Refined Storage crafting grid

### ISSUE THREAD

**Issue by nathanenns** [Tiviacz1337/Travelers-Backpack#86]
When you use the recipe with shears to turn a backpack into the Traveller's Backpack in the Refined Storage crafting grid, you will create the Traveller's Backpack but it doesn't consume the original.  Also any contents will be in both the original and newly created backpack.

Tested this on Crackpack 3 both single player and on sponge server.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/2993111
