### ISSUE TITLE
Backpack inventory reset after last mod update.

### ISSUE THREAD

**Issue by creeloper27** [Tiviacz1337/Travelers-Backpack#861]
0. Modloader: Fabric, Mod Version: fabric-1.20.1-9.1.10

1. Describe the bug 
After updating the mod today the backpack contents are gone.

2. Write steps to reproduce the bug
- use the mod version from a few days ago (before the crafting table got moved) and fill a backpack
- update the mod
- observe how the backpack is empty

3. What is expected behavior 
The mod update does not reset backpack contents

4. Screenshots (If applicable)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/20074177/15ace3fe-17a0-41e9-80ba-284e4ba495b4)

**Comment by creeloper27** [comment]
My server is using [EasyAuth](https://modrinth.com/mod/easyauth), this bug seems to affect only players that are logging in using local offline authentication and not Mojang online authentication.

**Comment by Tiviacz1337** [comment]
Did you update mod on server
Update is marked as a beta and you should make backup of your world before updating the mod to beta version

**Comment by juxstified** [comment]
@Tiviacz1337 how is this resolved? items in the backpack and inventory still disappear when just moving stuff

**Comment by lorar0se** [comment]
This issue is not resolved and should be addressed. 
The mod version is the same on our client and server, and the backpack contents are gone.

What files should be restored from the backup of the world?

**Comment by Tiviacz1337** [comment]
do you use trinkets integration

**Comment by lorar0se** [comment]
Yes we do have the Trinkets mod as well.

**Comment by Tiviacz1337** [comment]
Join my discord so we can investigate the issue
write the message in bug-report

**Comment by LeftHandedBread** [comment]
I also had this issue, and it happened because I clicked "Check for Updates" on prism launcher. If it were me, I would remove the update from Modrinth and CurseForge until this bug is fixed, because as far as I know there is no way to filter out beta versions of mods in the launcher: 
https://www.reddit.com/r/PrismLauncher/comments/13ia9v2/only_download_stable_versions_of_mods/

Until that feature gets added and enabled by default, releasing betas should probably be restricted to places that aren't automatically downloaded by popular launchers. Just my 2 cents.

**Comment by Tiviacz1337** [comment]
> I also had this issue, and it happened because I clicked "Check for Updates" on prism launcher. If it were me, I would remove the update from Modrinth and CurseForge until this bug is fixed, because as far as I know there is no way to filter out beta versions of mods in the launcher: https://www.reddit.com/r/PrismLauncher/comments/13ia9v2/only_download_stable_versions_of_mods/
> 
> Until that feature gets added and enabled by default, releasing betas should probably be restricted to places that aren't automatically downloaded by popular launchers. Just my 2 cents.

do you play on server?

**Comment by LeftHandedBread** [comment]
> do you play on server?
Yes, I maintain it

**Comment by Tiviacz1337** [comment]
> > do you play on server?
> 
> Yes, I maintain it

can you join discord

**Comment by Tiviacz1337** [comment]
anyone here is able to test with the mod I'll send via dm?

**Comment by creeloper27** [comment]
> Did you update mod on server Update is marked as a beta and you should make backup of your world before updating the mod to beta version

Yes, I updated the mod on the server, actually it got updated automatically by [packwiz](https://github.com/packwiz/packwiz), I have backups, but they were not needed as I noticed that all the backpacks simply got regenerated in a sense (they got a new BACKPACKUUID), the previously owned backpacks still existed within the respective player folders in `world/backpacks`, I simply gave back players their last UUID backpack (sort by last change in the respective `world/backpacks/PLAYER_UUID` folder) using `/tb restore PLAYER_NAME BACKPACK_UUID` command, tho I suppose you could also simply copy the name of the lastest created BACKPACK_UUID, delete it and rename the second last (now the latest as you just deleted the previously latest) to the copied BACKPACK_UUID (I have not tested this tho).

**Comment by creeloper27** [comment]
> anyone here is able to test with the mod I'll send via dm?

I can do it in a few hours most likely, I'm messaging you on Discord.

**Comment by Voidmaster01** [comment]
> > Did you update mod on server Update is marked as a beta and you should make backup of your world before updating the mod to beta version
> 
> Yes, I updated the mod on the server, actually it got updated automatically by [packwiz](https://github.com/packwiz/packwiz), I have backups, but they were not needed as I noticed that all the backpacks simply got regenerated in a sense (they got a new `BACKPACKUUID`), the previously owned backpacks still existed within the respective player folders in `world/backpacks`.
> 
> As a fix I gave back players their last UUID backpack (sort by last change in the respective `world/backpacks/PLAYER_UUID` folder) using `/tb restore PLAYER_NAME BACKPACK_UUID` command, though I suppose (while the server is offline) you could also simply copy the name of the lastest created `BACKPACK_UUID`, delete it and rename the second last (now the latest as you just deleted the previously latest) to the copied `BACKPACK_UUID` (I have not tested this approach though).

what if it is a singleplayer instance/world?

**Comment by Tiviacz1337** [comment]
we found the bug it works on sever and singleplayer update will be available tomorrow

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20 fixed
