### ISSUE TITLE
Items disappear in SMP when using backpack on back.

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [Tiviacz1337/Travelers-Backpack#862]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Minecraft 1.20.1
Fabric-api-0.92.0+1.20.1
Travelers-backpack-1.20.1-9.1.9
Trinkets-3.7.2
Many other mods.....

1. Describe the bug - steps to reproduce

On SMP:
When placing items in backpack while on back, all but the first item put it or removed disappears
When using backpack in hand, everything works correctly.
On Single Player:
Everything works as expected

**Comment by Tiviacz1337** [comment]
you have to update traveler's backpack to 9.1.10 or downgrade trinkets to 3.7.1
