### ISSUE TITLE
the ocelot backpacks ability gives speed when near any mob instead of only hostile ones 

### ISSUE THREAD

**Issue by NoobKing3000** [Tiviacz1337/Travelers-Backpack#863]
Fabric 1.20.4 9.4.0

The ocelot backpacks ability always gives speed when near any mob whether it's hostile or not despite saying it should only activate if it's hostile 

1. Wear the ocelot backpack
2. Switch the ability on
3. Go near any mob
4. Should get speed effect

Should only be activating when the mob is hostile

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20 fixed
