### ISSUE TITLE
Crash on latest 1.19 due to config

### ISSUE THREAD

**Issue by Abalieno** [Tiviacz1337/Travelers-Backpack#864]
I suppose it is a missing thing in config. The config itself has that field, so it must be something else.

I don't have anything from the mod itself, this crash happens when being repeatedly killed by a mob, the exact moment I get killed. I have an empty inventory, so that too shouldn't count, since it's not some item I'm holding.

travelersbackpack-fabric-1.19.2-8.2.34

[crash-2024-04-01_13.22.02-server.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/14822920/crash-2024-04-01_13.22.02-server.txt)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20 fixed
