### ISSUE TITLE
Placing a torch on the same tile as a backpack will delete the backpack

### ISSUE THREAD

**Issue by luigil101** [Tiviacz1337/Travelers-Backpack#866]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 47.2.20
1.20.1
Mod Ver. 9.1.13

1. Describe the bug 
Placing a torch on the same tile as a backpack will delete the backpack

2. Write steps to reproduce the bug
Place a backpack down on the ground
have a torch in your offhand
accidentally place the torch on the backpack
watch it instantly go to the shadow realm, deleting all your stuff

3. What is expected behaviour 
Not being able to place the torch at all
Not losing all my things

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
are you sure the backpack didnt get equipped on you? right clicking a backpack equips it
