### ISSUE TITLE
Night vision doesnt apply when using the Bat Backpack

### ISSUE THREAD

**Issue by jessicachitas** [Tiviacz1337/Travelers-Backpack#867]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 
Then the bat backpack is worn, it does not give you night vision.

2. Write steps to reproduce the bug

- Acquire the bat backpack
- Place on ground
- Right click to put it on your back
- No night vision

3. What is expected behaviour 
Night vision to be applied to the character

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

**Comment by Tiviacz1337** [comment]
did you switch the ability slider

**Comment by jessicachitas** [comment]
Modloader is Forge and version is 1.20.4-9.4.1

Where is the ability slider located?

**Comment by jessicachitas** [comment]
All good! I found the slider, apologies and thank you!
