### ISSUE TITLE
how to make server override client settings?

### ISSUE THREAD

**Issue by fi5hii** [Tiviacz1337/Travelers-Backpack#868]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
using fabric 0.15.7 on minecraft 1.20.4 and mod version 9.4.1

1. Describe the bug 
editing the json config on the server does not override the client settings so it doesn't do anything when setting the backpack limit to 0 and the slowness to 5, it shows the slowness but doesn't slow down the player. 

2. Write steps to reproduce the bug
just doesn't do anything 

3. What is expected behaviour 
to slow down players

4. Screenshots (If applicable)
/

**Comment by Tiviacz1337** [comment]
It works for me correctly, make sure you saved the config on the server, and have the same mod version on client and server

**Comment by Tiviacz1337** [comment]
also, for syncing to work you have to update to 9.4.2
