### ISSUE TITLE
Inventory Preview Not Rendering Properly

### ISSUE THREAD

**Issue by CorvusCaledonia** [Tiviacz1337/Travelers-Backpack#869]
Mod Loader -  Fabric
Mod Version - 9.4.2
Launcher - Modrinth App

1. Items in the 'Press Ctrl to View Inventory' preview are rendering diagonally and going out of box instead of in the row.

2. Open inventory, hover over any of the backpacks and press control

3. Items should render in a row, within the box

![20240408_152843](https://github.com/Tiviacz1337/Travelers-Backpack/assets/166412252/ed2b4c9b-ae3f-44da-b34e-1eae99b3130f)

**Comment by Tiviacz1337** [comment]
can you open your backpack and show screenshot of contents inside?

**Comment by CorvusCaledonia** [comment]
The first one is the one actually equipped, the other 3 are in my inventory. I have the penalty for having multiple backpacks switched off, just in case that's of any relevance.

![2024-04-08_20 43 38](https://github.com/Tiviacz1337/Travelers-Backpack/assets/166412252/c51a8ca5-9181-4026-9750-2f646123f91c)
![2024-04-08_20 44 18](https://github.com/Tiviacz1337/Travelers-Backpack/assets/166412252/399a2443-7a98-4399-ac5d-2c3cd4f62610)
![2024-04-08_20 44 29](https://github.com/Tiviacz1337/Travelers-Backpack/assets/166412252/6b327844-ce09-4be3-8dbd-ac14766e1028)
![2024-04-08_20 44 34](https://github.com/Tiviacz1337/Travelers-Backpack/assets/166412252/4c7c73d7-06f2-403b-96e2-122f60299647)

**Comment by Tiviacz1337** [comment]
and all tooltips are bugged?

**Comment by CorvusCaledonia** [comment]
Yes all do the same thing. The first row being fine and other rows doing
the diagonal.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20 fixed
