### ISSUE TITLE
Cant not build have everything nothing shows 

### ISSUE THREAD

**Issue by Luigisinvasion** [Tiviacz1337/Travelers-Backpack#870]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 
Well everything show up in creative and my mods list like normal. I can spawn the items in, but i can't seem to be able to build them in the crafting table.

2. Write steps to reproduce the bug

just building doing 

3. What is expected behaviour 

to make

 any of the items 

4. Screenshots (If applicable)
![2024-04-08_18 46 01](https://github.com/Tiviacz1337/Travelers-Backpack/assets/61269812/b2506bbe-e042-4a06-ac9e-37d7fb1b2bc7)

**Comment by Tiviacz1337** [comment]
What is the mod version? does jei show any recipes

**Comment by Luigisinvasion** [comment]
It's 1.20.4 and yes it does I have also found in the wild a upgrade piece
so I know the mods there lol

**Comment by Luigisinvasion** [comment]
I got on today and spawn in the items to upgrade the backpack and that worked fine. Just not able to actually build them in survival. The mod isnt showing up in the list on the crafting table, but is showing on the jei

**Comment by Tiviacz1337** [comment]
please specific version and what modloader

**Comment by Luigisinvasion** [comment]
TravelersBackpack-1.20.4-9.4.0 and im using forge 1.20.4-49.0.39

**Comment by Tiviacz1337** [comment]
do you play on server?

**Comment by Luigisinvasion** [comment]
I am not just single player

**Comment by Tiviacz1337** [comment]
is it possible that you use some kind of mod that blocks crafting items that are not unlocked in recipe book?

**Comment by Luigisinvasion** [comment]
No not that I'm aware of

**Comment by Tiviacz1337** [comment]
Try /gamerule doLimitedCrafting false
