### ISSUE TITLE
Crafting Inventory not saving items correctly 

### ISSUE THREAD

**Issue by Tiviacz1337** [Tiviacz1337/Travelers-Backpack#871]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 

2. Write steps to reproduce the bug

3. What is expected behaviour 

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20 fixed

**Comment by CorvusCaledonia** [comment]
Amazing, thanks so much!
