### ISSUE TITLE
Cannot Swap Hose Modes With Tools in Tools Slots and "Tools Slots Accept Everything" Enabled

### ISSUE THREAD

**Issue by jebug29** [Tiviacz1337/Travelers-Backpack#872]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.20.4 with mod version 1.20.4-9.4.2

1. Describe the bug 
When holding Z and scrolling while tools are in the tool slot, the tools are cycled (including the hose). I have confirmed the tank is selected, both in the hose tooltip and the overlay. The issue only occurs while all items are allowed as acceptable items in the tools slot.

The issue is easily fixed for the client by blacklisting travelersbackpack:hose from items accepted in the tool slot. Perhaps this should be a default, or allow a separate binding for changing hose modes if it would be desirable behavior to allow the user to pull out the hose at any time.

2. Write steps to reproduce the bug
- Enable "Tool Slots Accept Everything" in mod settings
- Attempt to cycle through hose modes

3. What is expected behaviour 
- Hose will cycle through modes rather than entering tools slot

**Comment by jebug29** [comment]
> The issue is easily fixed for the client by blacklisting travelersbackpack:hose from items accepted in the tool slot. Perhaps this should be a default, or allow a separate binding for changing hose modes if it would be desirable behavior to allow the user to pull out the hose at any time.

After testing it appears this _only_ fixes the issue for the client. Blacklisting this in the configuration file on a server does prevent you from adding the hose to the item slots in the inventory GUI, but it doesn't fix the cycling issue with the keybind unless the client also has it blacklisted.

Blacklisting also completely prevents you from adding the hose in the backpack inventory at all, so this may also be undesirable behavior.

**Comment by Tiviacz1337** [comment]
Hose will be blacklisted from tool slots

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20 Fixed

**Comment by jebug29** [comment]
Awesome! Thanks so much!!
