### ISSUE TITLE
Chests disappeared

### ISSUE THREAD

**Issue by Lord-Greyhawk** [Tiviacz1337/Travelers-Backpack#873]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Minecraft version 1.20.4.  Fabric loader 0.15.9 

1. Describe the bug 

I started a new world after adding this and other mods. I had to manually activate this mod. When the World rendered, my Bonus chest was nowhere to be found. I decided to buil a work Bench, but Chest were not listed at all.  I reset the game twice with the same results. There were no chests. Then I exited and reset the world,  but turned this mod off, and the chests returned!

2. Write steps to reproduce the bug

Not sure. I loaded this mod with many others (156 total, but everything else was working, to the best of my knowledge)

3. What is expected behaviour 

With it active alongside my current world build, Chests disappear.

4. Screenshots (If applicable)
Sorry, didn't think to get one, not sure what to take a picture of really.

**Comment by Lord-Greyhawk** [comment]
Quick note. It was the latest Beta that it loaded, if that helps.

**Comment by Tiviacz1337** [comment]
Provide video, I don't know what you mean. CHEST like block dissapear?
