### ISSUE TITLE
1.20.4 NeoForge crash

### ISSUE THREAD

**Issue by fuyn101** [Tiviacz1337/Travelers-Backpack#874]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1.20.4 NeoForge 20.4.227

1. Describe the bug 

crash 

2. Write steps to reproduce the bug

get 1.20.4 and NeoForge 20.4.227 in MultiMC

get travelersbackpack-neoforge-1.20.4-9.4.0.jar from curseforge

only This mod

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/151902446/158aba2e-3d86-42c5-8f61-37f8ffaf8d52)

3. What is expected behaviour 

dont crash =.=

4. Screenshots (If applicable)

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/151902446/17414310-99dc-438a-94d3-ed914d95e272)

log:

[latest.log](https://github.com/Tiviacz1337/Travelers-Backpack/files/14941353/latest.log)

jdk version

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/151902446/8fee1b68-fc89-48e2-9ed9-50dcf69bc174)

**Comment by Tiviacz1337** [comment]
install curios api

**Comment by Tiviacz1337** [comment]
Fixed 
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5372415
