### ISSUE TITLE
After upgrading a backpack I cannot upgrade another

### ISSUE THREAD

**Issue by lockf** [Tiviacz1337/Travelers-Backpack#875]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge - 47.2.23
travelersbackpack-forge-1.20.1-9.1.13

1. Describe the bug 

After upgrading a backpack i can no longer upgrade any other backpack

2. Write steps to reproduce the bug

1- Upgrade a standard traveler's backpack with a gold upgrade (for example) [Works]
2- Try upgrade any other backpack with the same upgrade [Does not Work]

3. What is expected behaviour 

1- Upgrade a standard traveler's backpack with a gold upgrade (for example) [Works]
2- Try upgrade any other backpack with the same upgrade [Work]

4. Screenshots (If applicable)
![imagem](https://github.com/Tiviacz1337/Travelers-Backpack/assets/72867366/a74c1377-4ba5-4b06-bebe-b6aa8a6b9592)

![imagem](https://github.com/Tiviacz1337/Travelers-Backpack/assets/72867366/70f0d69c-b491-4d4b-b401-2e8662b313a8)

**Comment by Tiviacz1337** [comment]
You have to upgrade backpacks to all tiers, so leather -> iron -> gold -> diamond -> netherite

**Comment by lockf** [comment]
However it allowed me to upgrade directly to gold tier with no problem.
