### ISSUE TITLE
[Suggestion] Interface rework

### ISSUE THREAD

**Issue by MbtMarco** [Tiviacz1337/Travelers-Backpack#876]
I was browsing through the resource packs on Modrinth when I came across this one:
https://modrinth.com/resourcepack/enhanced-travelers-backpack-gui

And I thought it would be nice to have a similar or at least improved interface to the one we have today.
Traveler's Backpack is a great mod, however the interface is quite flat, too simple for what the mod offers, in my opinion it should be tweaked.

**Comment by Tiviacz1337** [comment]
I want backpack gui to fit vanilla guis and I'm open to any suggestions how to improve backpack gui in _vanilla_ manners.

**Comment by MbtMarco** [comment]
Understandable, then I can only recommend 2 things that don't change the "Vanilla" style of the GUI: 

- ~Water and lava rework: the water and lava textures are not like the vanilla ones. In my opinion they should be rework.~

- Add the name to the GUI: Each Minecraft gui if opened is also indicated by a name, this is missing in your mod, it would be enough to add "Backpack" or "Traveler's backpack". This i what i mean:

![Bone White Blue Groovy You Matter Desktop Wallpaper_20240413_181748_0000.png](https://github.com/Tiviacz1337/Travelers-Backpack/assets/124934175/9abfb94a-4dfa-4be7-a293-02fc4f8a9ffc)

**Comment by Tiviacz1337** [comment]
How is water and lava not the same like in vanilla? I use the same textures

**Comment by Tiviacz1337** [comment]
I mean I use textures that minecraft provides for all fluids

**Comment by MbtMarco** [comment]
I looked at the GUI again, actually you are right, sorry 😅😂

Just watch the second suggestion
