### ISSUE TITLE
Overlap JEI on crafting grid interface on 5:4 monitor

### ISSUE THREAD

**Issue by ArsenijN** [Tiviacz1337/Travelers-Backpack#878]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

- Fabric 0.15.7 
- 1.20.1-9.1.12

1. Describe the bug 

When I open the backpack and open the crafting grid, it opens and some of it is under the JEI interface as well, and when I place the blocks on the crafting grid on the side where the interfaces overlap - I get the JEI menu because it thinks I clicked to the JEI interface and not to the crafting grid
+maybe it's all the same 5:4, but the text with the inscription "Майстрування" goes beyond the interface

2. Write steps to reproduce the bug

- Have a 5:4 monitor or 1280x1024 Minecraft resolution
- Set the interface scale to 2x
- Enter the backpack and open the crafting menu

3. What is expected behaviour 

No overlapped interface or changes to menu location settings (yes, it will destroy symmetry and possibly be ugly)

4. Screenshots (If applicable)

![2024-04-13_20 39 42](https://github.com/Tiviacz1337/Travelers-Backpack/assets/67965122/a24dfcfd-ff77-4f70-9728-f3271e9e6c8c)

**Comment by Tiviacz1337** [comment]
I'll update compat with JEI in the next update

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
Fixed
