### ISSUE TITLE
NOT GAMEBREAKING / NeoForge 1.20.4 + Carry On mod, Single Player, Connection Lost when holding item with "Carry On" + pressing "B".

### ISSUE THREAD

**Issue by randomleech** [Tiviacz1337/Travelers-Backpack#879]
Hi!

**travelersbackpack-neoforge-1.20.4-9.4.0 + Carry On mod** (let's You pick up and ... carry Chests, mobs, etc.)
I do not know if this is the right place to write about it, or maybe Carry On issues thread.

Carry On: https://www_curseforge_com/minecraft/mc-mods/carry-on

I made basic backpack, 
opened it "from hand", 
clicked on "wear" icon,
opened it with "B" button, 
loaded full with random items/blocks (nothing modded - checked just now), 
closed it. 

Picked up a Chest with items in it (Carry On mod), 
pressed B (just to check what is going to happen) 
and got Connection Lost message. 

"E" button does not work (can not open inventory - nothing happens) when I am "Carry-ing On" something.

"Connection Lost" message.

"Failed to open a screen with advanced data: java.lang.NullPointerException:
Cannot invoke
"com.travelersbackpack-neoforge-1.20.4-9.4.0tiviacz.travelersbackpack.client.screens.widgets.SettingsWidget.getWidgetSize
AndPos()" because "gui.settingsWidget" is null"

Expected behaviour: Nothing.. like literally. "B" should not work, or even better (optional) "My hands are busy"  message or something - similar could be included while holding other stuff in both hands (like shield + sword).

**Comment by Tiviacz1337** [comment]
I'll add backpacks to blacklist blocks so they won't be carry-able

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all?page=1&pageSize=20
