### ISSUE TITLE
The hose modes can not be switched (1.20.1 forge)

### ISSUE THREAD

**Issue by VladosBarboss** [Tiviacz1337/Travelers-Backpack#880]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 

2. Write steps to reproduce the bug

3. What is expected behaviour 

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Default Z + scroll up or down
