### ISSUE TITLE
Compatibility with Recipe book is pain

### ISSUE THREAD

**Issue by MbtMarco** [Tiviacz1337/Travelers-Backpack#881]
The mod already works with RBIP, however it is missing how to build a basic backpack and all its components. 

https://modrinth.com/mod/rbip

**Comment by Tiviacz1337** [comment]
I'll add all crafting recipes integrated with recipe book in the next update

**Comment by MbtMarco** [comment]
Ty 🙂

**Comment by Tiviacz1337** [comment]
#748

**Comment by MbtMarco** [comment]
I close this issue because with Recipe Book Is pain mod I can see crafting recipes.
