### ISSUE TITLE
Backpack abilities not working

### ISSUE THREAD

**Issue by apollo344** [Tiviacz1337/Travelers-Backpack#882]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
CurseForge 1.20.4-9.4.0

1. Describe the bug 
backpack's special abilities arent funtioning (ie. blaze backpack is on but still taking fall damage, had immunity 24 hours ago, but not anymore)

2. Write steps to reproduce the bug
putting on any backpack with a special ability, but they function like a base backpack and abilities do not work; happens to all players in the server

3. What is expected behaviour 
backpack should produce no fall damage and immunity to blaze fireballs, but does not

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
you have to enable ability slider in backpack gui
