### ISSUE TITLE
Crafting Table Upgrade (Fabric)

### ISSUE THREAD

**Issue by CleverBalloon** [Tiviacz1337/Travelers-Backpack#885]
Simply put, I saw that you have some form of crafting table upgrade for backpacks on the forge version which adds a separate crafting table in the UI rather than forcing you to sacrifice 9 backpack slots aka a whole row for the crafting module. This is genius so please add it to the fabric version of the mod if possible. Thanks.

**Comment by Tiviacz1337** [comment]
It's already available on fabric, you can download it here: https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
It's marked as beta version, make sure to download latest version to have latest bugfixes and improvements
