### ISSUE TITLE
Backpack hotbar inventory glitch

### ISSUE THREAD

**Issue by BlankSBG** [Tiviacz1337/Travelers-Backpack#887]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

forge-1.18.2-7.1.47

1. Describe the bug 

simply opening backpacks causes the hotbar to bug out, and if you start moving items around inventories it glitches both your player and backpack inventories, also the UI has no crafting table. interacting with chests or other inventory opening interfaces fixes your items but the backpack is unusable

2. Write steps to reproduce the bug

open a backpack, boom your hotbar is weird 

3. What is expected behaviour 

to have a functioning backpack

4. Screenshots (If applicable)
![2024-04-22_00 36 50](https://github.com/Tiviacz1337/Travelers-Backpack/assets/159747295/0e793b08-19d4-43e4-bcd3-cb9980995ebc)
![2024-04-22_00 37 06](https://github.com/Tiviacz1337/Travelers-Backpack/assets/159747295/1ba75ec7-9540-4850-872d-2c2d0ba16ccc)

**Comment by Tiviacz1337** [comment]
Do you play on server?

**Comment by Tiviacz1337** [comment]
I see your JEI do not display Crafting upgrade, you are probably using outdated version, check if you have latest version on client & server

**Comment by BlankSBG** [comment]
my launcher updated the mod to the beta version, thank you for pointing that out
