### ISSUE TITLE
Crafting Table Upgrade

### ISSUE THREAD

**Issue by Ducky-911** [Tiviacz1337/Travelers-Backpack#891]
I am having trouble finding information on crafting the new upgrade to add crafting to the backpack. Is it a craftable upgrade or is it something you have to find randomly in the world? If it is craftable what is the recipe?

**Comment by Tiviacz1337** [comment]
It is craftable, you have to put blank upgrade and crafting tabler above it in crafting. You apply the upgrade like rest of the upgrades in smithing table

**Comment by Tiviacz1337** [comment]
Next update is going to add all recipes to recipe book

**Comment by Ducky-911** [comment]
Awesome thank you
