### ISSUE TITLE
I break accidentally my backpack in creative and I'm unable to use the command restore

### ISSUE THREAD

**Issue by Chexester** [Tiviacz1337/Travelers-Backpack#893]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
1.12.2

1. Describe the bug 

I died and used creative to go to my backpack but I accidentally broke it. I found the command to restore it but I'm unable to use it nor to find the backpack UUID

2. Write steps to reproduce the bug

1. Create a travelers backpack
2. Put items into the backpack 
3. Equip backpack
4. Die
5. Go into creative
6. Break the backpack by mistake 
7. Cry and search for solutions
8.  Try to use  '/tb <PlayerName> <BackpackUUID> restore
9. Is not working, go back to cry...
10. submit a bugreport

3. What is expected behaviour 

Command should be available and restore the backpack

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
backpack entry is created only when player dies with backpack on the back

**Comment by Chexester** [comment]
I died with the backpack on, so the entry was deleted the second I screwed up and deleted the backpack in creative by clicking it? Is it possible to "go back in time" in my sigleplayaer world to recover it?

**Comment by Tiviacz1337** [comment]
when you died with backpack on, you should be able to find it in backpacks folder and be able to use restore command

**Comment by Chexester** [comment]
I died with the backpack on and broke it before I could grab it and equip it again. Do you know if the file disappears in this case? As soon as I broke it I went to Google to seek answers and found the restore command in Forge. However, I never had the chance to use the command as whenever I did "/tb <player name>" the UUID should auto populate (as I read)

None of that happened. Never was able to find the backpack file within the Minecraft folders or whatsoever :(

**Comment by Tiviacz1337** [comment]
you have to open your save folder and find backpacks folder, there you will be able to find uuid of backpacks, find the recent one and copy the uuid and use /tb restore <Paste uuid here>

**Comment by Chexester** [comment]
I checked out the save folder but it seems that the backpacks folder hasn't been generated. I created a separated gamefile and I have the same result. Pls see ss attached

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/167889830/72fa672d-29c3-4859-b4e5-aa3bca448b9d)

**Comment by Tiviacz1337** [comment]
Sorry, I've noticed it now - you use 1.12.2 and restore command is not available on this version, I've dropped support for 1.12.2 long time ago sorry, there's no way to retrieve your backpack (only possible way is to use save backup if you have any but that's up to you)

**Comment by Chexester** [comment]
Crap... alright, makes sense. Thanks.
