### ISSUE TITLE
CANT CRAFT DRAGON BACKPACK, DOESNT SHOW UP IN GRID EVEN THOUGH RECIPE IS RIGHT..

### ISSUE THREAD

**Issue by gojonixeus** [Tiviacz1337/Travelers-Backpack#894]
The version of minecraft im using is 1.20.1-9.1.13

The bug is that i cant craft the Dragon Backpack even though i already have the needed items, and also i searched everywhere online but still cant find anything.

i also have the following mods just in case you guys might know if there is something incompatible:
<img width="535" alt="mods" src="https://github.com/Tiviacz1337/Travelers-Backpack/assets/168363097/ca38829c-60eb-4963-8169-60037b01a8b2">

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/168363097/908fa382-ad32-4562-9c5d-478b5ee49c26)

thats all thank you! hoping for a fast response.

**Comment by Tiviacz1337** [comment]
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/34790800/7e54bb4d-b620-49a8-b04d-7fc2f6b63707)
Next update is going to integrate with recipe book, so you'll be able to see them in-game

**Comment by gojonixeus** [comment]
Can i ask what that potion looking like is? and how to craft it? thankss!!

> ![image](https://private-user-images.githubusercontent.com/34790800/326285594-7e54bb4d-b620-49a8-b04d-7fc2f6b63707.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjk4MTUsIm5iZiI6MTcxNDMyOTUxNSwicGF0aCI6Ii8zNDc5MDgwMC8zMjYyODU1OTQtN2U1NGJiNGQtYjYyMC00OWE4LWIwNGQtN2ZjMmY2YjYzNzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE4MzgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZTQzZjA1NmVhYWNiODA1MzgxYTc3NThiNjkwMDJhN2Q5NjBhMDNhMmFkNmNjZDlkMzM5MGQyOGU2OTVjNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fsi5CO3ic8_kp3jqd6jWpEruDi7TbA2zhieJB5fPtxc) Next update is going to integrate with recipe book, so you'll be able to see them in-game

**Comment by Tiviacz1337** [comment]
It's dragon breath, you obtain it by clicking with bottle on dragon special attack
