### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by Cat3nthusiast** [Tiviacz1337/Travelers-Backpack#895]
Modrinth (Fabric) mod version 1.20.4-9.4.3

When I opened the backpack it didn't show the regular inventory layout.
There were no blue or brown slots, just plain gray like it was the regular inventory.
However, the bucket and tool slots worked just fine, even the bed.

I don't know what caused it, I just crafted the backpack and it appeared like that.

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/168427097/c1d454c1-24a9-491d-a053-2b9e35aa0b41)

**Comment by Tiviacz1337** [comment]
No missing features, if you want you can enable legacy slots colors in client config, to use crafting you have to add crafting upgrade to backpack
