### ISSUE TITLE
Disable tanks and the sleeping bag model

### ISSUE THREAD

**Issue by duarm** [Tiviacz1337/Travelers-Backpack#896]
Thanks for making Travelers backpack!

**Is your feature request related to a problem? Please describe.**

I'm not using the tanks, (I've set the capacity to 0), I've also never used the sleeping bag function, and I don't like how they look in my back, I would prefer a simple backpack without the tanks and the sleeping bag.

**Describe the solution you'd like**
A way to disable the bed and/or the sleeping bag render. So the backpack in my back is just a backpack. I wouldn't mind it being a config only option, or an in game toggle/upgrade.

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/26150581/6beac77f-0b93-419b-a583-a807115c8282)

**Comment by Darkona** [comment]
Question, would this be better as configuration or via the backpack options in-game?

**Comment by duarm** [comment]
Since it's just an optional visual thing, a client-side config via mod menu would be good enough. If someday the tank and the sleeping bag become upgrades, then it might make sense to make an easier toggle inside the backpack UI.

**Comment by TomBCosmos** [comment]
@Tiviacz1337 This would be such a good idea!

I never use the tanks on the side and with all due respect, in my opinion, the tanks on the side are not terribly visually pleasing :/ Having the backpack just look like a backpack and the tanks being removed from the GUI also would be amazing.

I do still use the sleeping bag though and I don't mind the way it looks on the backpack.

So perhaps an additional option, is to include additional crafting recipe options that leave out the tank and/ or bed so it can just be crafted without the parts you don't want. Essentially making the backpack customizable with it's modules and recipe's to reflect that.

I believe this concept was already done with the crafting table aspect of it.

**Comment by leftbones** [comment]
+1 for this, the tanks are kinda ugly on the backpack and don't feel very in line with the aesthetics of Vanilla. I'd also like to be able to disable them and their model. I don't mind the sleeping bag though.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack

Upgrades update available for all 1.21 mod loaders (optional backpack tanks as an upgrade)
