### ISSUE TITLE
i cannot craft a backpack 

### ISSUE THREAD

**Issue by Alguen-Aleatorio** [Tiviacz1337/Travelers-Backpack#898]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 

I cannot craft a standard backpack in survival mode, if there is a way to get it, please let me know

**Comment by Tiviacz1337** [comment]
mod version
