### ISSUE TITLE
Crafting upgrades does not work

### ISSUE THREAD

**Issue by CraigTurnerGame** [Tiviacz1337/Travelers-Backpack#900]
I'm using fabric 1.20.4. I put it in the crafting table how the wiki says to, but it doesn't work. I put leather on left, backpack in middle, and crafting table upgrade on right, I also tried with the iron and gold upgrades.

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/100271271/b8ab8842-39ba-4229-b350-242dd8b450f0)

**Comment by CraigTurnerGame** [comment]
Oops, wrong image. Here's the right one...
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/100271271/86f20e8d-f935-455d-807b-15c747a49225)

**Comment by Tiviacz1337** [comment]
You have to put it in smithing table, like the rest of the upgrades
