### ISSUE TITLE
Hose Mode wont toggle

### ISSUE THREAD

**Issue by Squiidt** [Tiviacz1337/Travelers-Backpack#904]
**FABRIC 1.20.1**

1. Describe the bug 
Using the hose to suck up liquid works fine, but toggling to other modes doesnt work.  There are no conflicting keybinds

3. What is expected behaviour

im pressing the keybind to change mode but nothing is happening

**Comment by Tiviacz1337** [comment]
You have to hold keybind + use scroll

**Comment by Tiviacz1337** [comment]
no further informations, closing
