### ISSUE TITLE
Add instruction to put strings into quotes

### ISSUE THREAD

**Issue by Darkona** [Tiviacz1337/Travelers-Backpack#905]
https://github.com/Tiviacz1337/Travelers-Backpack/blob/ba2a5206e3eddb5ed4c7557a301709dcae516eff/src/main/java/com/tiviacz/travelersbackpack/config/TravelersBackpackConfig.java#L182C26-L182C33

Instructions for list of items should indicate the names need to be between quotes, because the underlying parser (https://github.com/TheElectronWill/night-config/blob/master/toml/src/main/java/com/electronwill/nightconfig/toml/ValueParser.java) will look for them for strings.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5372415
Added for Neo 1.20.4
Forge coming soon

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
Added for Forge
