### ISSUE TITLE
Tools put into tool slots disappear 

### ISSUE THREAD

**Issue by YLlywelyn** [Tiviacz1337/Travelers-Backpack#906]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 1.20.1-9.1.9

1. Describe the bug 

When I place tools into the tool slots they disappear

2. Write steps to reproduce the bug

Place a tool into a tool slot

3. What is expected behaviour 

The tool doesn't disappear

4. Screenshots (If applicable)

**Comment by YLlywelyn** [comment]
Update: Have lost several items that were in the backpack, mod is unusable in this state.

**Comment by Tiviacz1337** [comment]
update to latest version and check if issue occurs

**Comment by YLlywelyn** [comment]
I have the latest release version for fabric 1.20.1 available on modrinth.  Should I be trying a beta version?  Because, frankly, items going missing from inventories is what I expect from a beta version, not a release.

**Comment by Tiviacz1337** [comment]
How to reproduce the issue? I havent encountered this issue

**Comment by Tiviacz1337** [comment]
Also do you play server/singleplayer?

**Comment by YLlywelyn** [comment]
I am playing on a server, yes.

**Comment by YLlywelyn** [comment]
With regards to how to reproduce the bug, I just put a diamond pickaxe and a diamond hoe in the tool slots to see them hanging from the bag but they didn't.  When I opened the bag to remove them they were gone.

**Comment by Tiviacz1337** [comment]
are you sure you have the same version on client and server?

**Comment by Tiviacz1337** [comment]
no further informations, closing
