### ISSUE TITLE
Can't craft sleeping bag.

### ISSUE THREAD

**Issue by Ruthless4774** [Tiviacz1337/Travelers-Backpack#907]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 
Wont let me craft sleeping bag no recipe available. 

2. Write steps to reproduce the bug
Using 2 white wool 1 red wool I can't craft the sleeping bag.

3. What is expected behaviour 
For the recipe to be there so I can craft it.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
you have to use 1 white wool and 2 other color wool
