### ISSUE TITLE
Any change of Fabric 1.20.6 soon?

### ISSUE THREAD

**Issue by bentterp** [Tiviacz1337/Travelers-Backpack#908]
Hi!

There are no backpacks at all for 1.20.6 which I can find, and the 1.20.4 release of Traveller¨s Backpack won't start on 1.20.6

So any chances for an update soon, please?

**Comment by Tiviacz1337** [comment]
1.20.5 and 1.20.6 indroduced some significant changes to how item data is stored and that requires to rewrite some of Traveler's Backpack code. Be patient, update is planned

**Comment by bentterp** [comment]
Thank you

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5416808
Neo 1.20.6

Forge & Fabric coming soon

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Fabric 1.20.6 & 1.21 
Enjoy
