### ISSUE TITLE
Crafting only checks for space in backpack

### ISSUE THREAD

**Issue by unweeked** [Tiviacz1337/Travelers-Backpack#909]
0. Forge Traveler's Backpack V1.20.1-9.1.14

1. When shift-crafting anything in a backpack, the mod only checks for free inventory slots in the backpack. That leads to situations in which shift-crafting doesn't work when the backpack is full even if there are free slots in the player inventory.

2. ^

3. The mod checks for free (or fitting) slots in both, the player's and the backpack's inventory when shift-crafting.

4. -

**Comment by Tiviacz1337** [comment]
Did you try changing the direction of arrow in crafting? This arrow determines if result should go to backpack or player's inventory. Related to issue - I will make the result to go to player's inventory if backpack's inventory is full AND arrow points to backpack inventory.

**Comment by unweeked** [comment]
Oh, I didn't even know that that's possible :)
Also, the change you suggested would be very welcomed I think because it would act more as a preference than as a strict limit where to put the items. ^^
[It's pretty obvious, but don't forget not just to check for empty slots, but also for the same item being in the backpack (it would still fit in even though the slots are not empty)
+ also, I would add that functionality both ways (put it in the backpack when the inventory is full but the backpack isn't)]
Thanks for your quick response :)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
Fixed for Fabric

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5372415
Fixed for Neo 1.20.4

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
Fixed for Forge
