### ISSUE TITLE
Can't move selected item in backpack inventory

### ISSUE THREAD

**Issue by unweeked** [Tiviacz1337/Travelers-Backpack#910]
0. Forge Traveler's Backpack V1.20.1-9.1.14

1. When you open the backpack using the Hotkey (B) while holding an item (not the backpack), it's impossible to move the item you're holding using the number keys.

2. ^

3. As long as the held item is not the backpack you're currently using, you should be able to move it using the numbers 1-9.

4. -

**Comment by Tiviacz1337** [comment]
I can't reproduce this issue and Im able to move item using number keys
Edit: reproduced

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
Fixed for Fabric

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5372415
Fixed for Neo 1.20.4

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
Fixed for Forge
