### ISSUE TITLE
No crafting recipes for any of the items in JEI (Fabric)

### ISSUE THREAD

**Issue by CatBoxFox** [Tiviacz1337/Travelers-Backpack#912]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.20.1 on my own modpack

1. Describe the bug 
No available crafting recipes for any of the items in the mod
(only one there is for soaping the sleeping bags in supplementary)

2. Write steps to reproduce the bug
I added the mod to my pack and went onto my server, no recipes avaliable

3. What is expected behaviour 
Letting me craft backpacks and tiers and items

4. Screenshots (If applicable)
I cant really show it in JEI because it isnt there.. but i can drop my modpack
[(2.3) Silver Fabric Edition-2.3.zip](https://github.com/Tiviacz1337/Travelers-Backpack/files/15407017/2.3.Silver.Fabric.Edition-2.3.zip)

**Comment by Tiviacz1337** [comment]
you have to add mod on client and server

**Comment by CatBoxFox** [comment]
> you have to add mod on client and server

It is on both the client and the server

**Comment by CatBoxFox** [comment]
correction hold on it may not be

**Comment by CatBoxFox** [comment]
Appologies, i swore i added it to the server but i guess it didnt upload. Thanks for the help!
