### ISSUE TITLE
Lost Backpack

### ISSUE THREAD

**Issue by Callibean72** [Tiviacz1337/Travelers-Backpack#915]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 
I was in the end building and fell. When I returned there was no backpack compared to previous times .

2. Write steps to reproduce the bug
Build out a 2 block wide path, start staring up and fall into the void off one of the flats of the staircase.

(i did move a bit trying to save it but im not sure if that would impact it)
3. What is expected behavior 
With the Tombstone mod also in play the backpack would have been directly next to the tomb

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
There should be message printed to your console and in logs with backpack coordinates and information if it dropped as item or has been placed on the ground. If you had your backpack equipped, you might consider using /restore command https://github.com/Tiviacz1337/Travelers-Backpack/wiki/Commands
