### ISSUE TITLE
Possibility of sharing legacy code

### ISSUE THREAD

**Issue by leonardokr** [Tiviacz1337/Travelers-Backpack#916]
I have a great appreciation for version 1.12.2 and have been playing the same map for many years, but it is not compatible with the “Corpse” mod. I searched here on GitHub for the source code of version 1.0.35 (version installed on my machine) and couldn't find it. Would you please consider sharing the code for this version, so I can try to rebuild the compatibility in it? I ask this because I imagine that this version is no longer supported, so I would compare the changes myself based on the commit messages to replicate the logic and compile a compatible version. I take this opportunity to thank you very much for your mod, your work was certainly essential for the community, and one of the responsible for me being able to play the same map for so many years.

**Comment by Tiviacz1337** [comment]
Thank you for kind words, 1.12.2 code is available in master branch
