### ISSUE TITLE
Can't upgrade backpacks

### ISSUE THREAD

**Issue by nicehax** [Tiviacz1337/Travelers-Backpack#918]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Running on forge 47.2.0 minecraft version 1.20.1

1. Describe the bug 

I can't upgrade backpacks using leather and iron tier upgrades, I thought there might have been a limit to backpacks you could have upgraded but there was nothing about that on the wiki so I think it might be a bug.

2. Write steps to reproduce the bug

I upgraded three backpacks to gold tier and one to diamond and now I can't use iron upgrades on backpacks

3. What is expected behaviour 

The backpacks get upgraded to iron tier

4. Screenshots (If applicable)
<img width="409" alt="Screenshot 2024-06-01 at 2 00 56 AM" src="https://github.com/Tiviacz1337/Travelers-Backpack/assets/171407169/f4c0087d-7db4-4fa1-b90a-516f38bcf571">
<img width="403" alt="Screenshot 2024-06-01 at 2 01 00 AM" src="https://github.com/Tiviacz1337/Travelers-Backpack/assets/171407169/19f87834-d9f3-40cb-96bb-7f5ea6483b8e">
<img width="393" alt="Screenshot 2024-06-01 at 2 01 06 AM" src="https://github.com/Tiviacz1337/Travelers-Backpack/assets/171407169/5ebf8ab0-cb2f-412b-a53f-10496efc43ca">
<img width="138" alt="Screenshot 2024-06-01 at 2 01 17 AM" src="https://github.com/Tiviacz1337/Travelers-Backpack/assets/171407169/8b7c75eb-5baf-4af7-80cd-c8564e9d718f">

**Comment by Tiviacz1337** [comment]
That's strange issue, did you ever opened these backpacks? or just newly crafted and put in the smithing table?

**Comment by nicehax** [comment]
I just newly crafted them and put them in the smithing table
Weirdly enough it was guaranteed to work when I upgraded them as default backpacks before crafting them into backpack types

**Comment by Tiviacz1337** [comment]
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/34790800/983c2e0c-2af7-4d79-b616-876482b6586d)
Works for me, is it possible you play on server?

**Comment by nicehax** [comment]
no, I play on a singleplayer world

**Comment by Tiviacz1337** [comment]
Do you try to apply iron upgrade to leather tier backpack or some other tier backpack?

**Comment by nicehax** [comment]
iron to leather, all the backpacks in the screenshots are leather tier upgrades

**Comment by Tiviacz1337** [comment]
I don't know what might cause this, maybe some mod compatibility, could you check with Traveler's Backpack only installed

**Comment by tcortega** [comment]
> Do you try to apply iron upgrade to leather tier backpack or some other tier backpack?

I play on a server and am facing this
