### ISSUE TITLE
Modpack isn't loading Traveler's backpack properly

### ISSUE THREAD

**Issue by markc1707** [Tiviacz1337/Travelers-Backpack#919]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 1.20.1-47.2.0
Mod version 1.20.1-9.1.14

1. Describe the bug 
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/155330974/0d9aec82-35d0-40b5-9b3b-e9b8d6e68447)

2. Write steps to reproduce the bug
[server testing.zip](https://github.com/user-attachments/files/15526649/server.testing.zip)

Load this modpack into CurseForge and launch the game

3. What is expected behaviour 
It's supposed to just load into the game normally

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Can you show me the crash log?

**Comment by markc1707** [comment]
> Can you show me the crash log? 

[crash-2024-06-02_17.38.54-fml.txt](https://github.com/user-attachments/files/15526987/crash-2024-06-02_17.38.54-fml.txt)

**Comment by markc1707** [comment]
> Can you show me the crash log?

**Comment by markc1707** [comment]
Sorry to bother you, but it's been a couple days and I haven't gotten a response. Any luck?

**Comment by Tiviacz1337** [comment]
try reinstalling modpack/server seems like some bad luck with mod loader

**Comment by markc1707** [comment]
I updated some of the mods and it worked once, but the same issue popped up the next time I launched the modpack.

**Comment by Tiviacz1337** [comment]
Maybe try to update forge to some more recent version?

**Comment by markc1707** [comment]
I mean I could try, I'd prefer it to be on 1.20.1 for our server, it takes a while to move every single mod to a new version. I'll try that a bit later on and research more options.

**Comment by Tiviacz1337** [comment]
I know, I just suggest to update forge for 1.20.1 to more recent version

**Comment by Tiviacz1337** [comment]
did it help?

**Comment by markc1707** [comment]
I'm on the most recent version of forge, so it didn't really work. I just went ahead and switched to 1.20.6 and used plugins instead. Thanks for your help anyways
