### ISSUE TITLE
crafting grid overlaps with emi

### ISSUE THREAD

**Issue by jackhexed** [Tiviacz1337/Travelers-Backpack#920]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Neoforge 20.4.235
travelersbackpack-neoforge-1.20.4-9.4.2

1. Describe the bug 

The grid added by the crafting upgrade is covered by EMI's GUI.

2. Write steps to reproduce the bug

* Add crafting upgrade to a backpack.
* Open the backpack GUI with EMI

3. What is expected behaviour 

It would be nice if the mod could get EMI to move out of the way somehow, or simply make the crafting GUI on top of the EMI GUI.

4. Screenshots (If applicable)

![2024-06-02_20 54 13](https://github.com/Tiviacz1337/Travelers-Backpack/assets/85714123/145338eb-8a0c-47b9-b70f-c88243b486c6)

**Comment by Tiviacz1337** [comment]
I havent done integration with emi for neo yet. It'll be available in the next update

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5492355
Fixed
