### ISSUE TITLE
hose does not get reserved properly 

### ISSUE THREAD

**Issue by Korygauger** [Tiviacz1337/Travelers-Backpack#921]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

fabric 1.20.4

1. Describe the bug 
using the reserve button on the backpack I reserved a spot for my hose. But it doesn't really work. I think it only reserves a spot for the hose in its current mode and current tank this means that you have to have the hose on a certain tank and in a certain mode to get it to store properly.

2. Write steps to reproduce the bug
reserve the slot for the hose. take it out and change either the mode or the tank, then try to put it back with shift click.

3. What is expected behaviour 
it goes to the right spot with shift click

**Comment by Tiviacz1337** [comment]
Fixed 
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
Fixed for Forge
