### ISSUE TITLE
Client Overlay Config

### ISSUE THREAD

**Issue by Blood-Tear-8** [Tiviacz1337/Travelers-Backpack#922]
- travelersbackpack-forge-1.20.1-9.1.1

- Client overlay config not working properly.

- Edit
I did note there is an update, but it is only for MC ver. 1.20.4 as well as NeoForge which I do not use.

**Comment by Tiviacz1337** [comment]
What is not working?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
Fixed
