### ISSUE TITLE
Ability to change sleeping bag color in backpack

### ISSUE THREAD

**Issue by mavdotj** [Tiviacz1337/Travelers-Backpack#923]
**Is your feature request related to a problem? Please describe.**
I crafted my backpack with a white sleeping bag, and now that I have gotten further into the game I have access to more dyes, I would like to change my sleeping bag color

**Describe the solution you'd like**
Change the recipe to change the color of a leather backpack to only if the dye is on the sides
Make the recipe to change the sleeping bag color if the dye is on the bottom

**Describe alternatives you've considered**
(none)

**Comment by Tiviacz1337** [comment]
https://github.com/Tiviacz1337/Travelers-Backpack/wiki/Changing-sleeping-bag
