### ISSUE TITLE
Game crashes upon trying to open backpack

### ISSUE THREAD

**Issue by Viaspiderz** [Tiviacz1337/Travelers-Backpack#924]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 1.19.2-0.15.11 (Using Forge launcher but idk if that means anything)

1. Describe the bug 

The game freezes and crashes entirely upon trying to open the backpack menu

2. Write steps to reproduce the bug

not really anything

3. What is expected behaviour 

The backpack should open when the key bound to it is pressed (for me it's backspace)

4. Screenshots (If applicable)

![Capture](https://github.com/Tiviacz1337/Travelers-Backpack/assets/126007719/56c9d160-38d5-43dd-8f3d-917f5c01d52d)
[crash-2024-06-12_18.37.13-client.txt](https://github.com/user-attachments/files/15811635/crash-2024-06-12_18.37.13-client.txt)
[latest.log](https://github.com/user-attachments/files/15811636/latest.log)

**Comment by M3emoo** [comment]
That exact code is happening to me as well, I have a server set up and in the log it says, ERROR]: [worlds_together] Unable to parse Version in jar:file:///C:/Users/chick/OneDrive/Desktop/Mincraft%20server/mods/travelersbackpack-fabric-1.19.2-8.2.37.jar

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5482872
Fixed
