### ISSUE TITLE
Going into wall with elytra and spider backpack makes you stuck

### ISSUE THREAD

**Issue by Tobim6** [Tiviacz1337/Travelers-Backpack#926]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 1.20.1-9.1.14

1. Describe the bug 
If you are wearing an elytra and the spider backpack and crash into a wall while flying with elytra it makes you bug in the wall going up and down

2. Write steps to reproduce the bug

Wear elytra and spider backpack with climbing ability enabled
Fly into a wall
You get stuck

4. What is expected behaviour 
You climb normally after crashing into the wall

5. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Fixed for Fabric
Forge soon

**Comment by Tobim6** [comment]
Probably won't be fixed for 1.20.1, right?

**Comment by Tiviacz1337** [comment]
will be fixed, update today

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
Fixed for Forge
