### ISSUE TITLE
Crashing with Create and Create Utilities

### ISSUE THREAD

**Issue by Alv-Rod** [Tiviacz1337/Travelers-Backpack#928]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

- Forge 40.2.21 - Mod Version 1.18.2-7.1.48

1. Describe the bug 

- Game crashes when climbing up (with a spider backpack) a fluid pipe connected to a mechanical pump and fluid tanks/steam engine (from Create Mod), most consistently when a 6-axis-gearbox from Create Utilities is present nearby or connected to the structure, although the same crash's been observed without that, or even without the mod installed.

2. Write steps to reproduce the bug
The minimum but still consistent way to reproduce the crash:
1st - Place fluid tanks in an 3x3 area, connect to them a mechanical pump, a fluid pipe connected to the pump, and another fluid pipe one block below the first, or another mechanical pump, preferably above a pool of water.
2nd - Place a 6-axis-gearbox (from Create Utilities) besides the first fluid pipe, or nearby.
3rd - Equip the spider backpack and activate its ability.
4th - Climb up the fluid pipe towards the mechanical pump.
Other elements such as making the fluid tanks into a steam engine, adding rotation with cogwheels and shafts to both the pumps and the 6-axis-gearbox and more fluid tanks make the crash more and more consistent 

- The most consistent i've got it, where it happens almost every time, is with a 3x3x3 fluid tank setup, with a steam engine connected, above a pool of water, with blaze burners beneath the whole steam engine, with two mechanical pumps both sending water from the pool into the tanks, with rotation applied to all of them, with the help of the 6-axis-gearbox and a creative motor or other source of rotational power.

- I've observed the crash at least once with Create Utilities not installed, and a few times with it installed but not in use on the world.

3. What is expected behaviour 

- Traveler's Backpack should simply not conflict with Create or Create Utilities, the Create blocks should work as intended (i.e.: rotation should be able to be applied to all the blocks involved without any issues), and the player should be able to simply climb up any Create blocks with the spider backpack.

5. Screenshots (If applicable)

- I can provide examples of the setup needed to reproduce if requested.

- Crashlog: https://pastebin.com/uG7knKfb

**Comment by Tiviacz1337** [comment]
This is problem with Create mod. The backpack just tries to spawn block particles. It seems like mechanical pump tries to get property that is not present in this block in order to create particles.
