### ISSUE TITLE
Backpack loses all NBT data when put into trinket slot

### ISSUE THREAD

**Issue by Willio2000** [Tiviacz1337/Travelers-Backpack#929]
[this is the version I used](https://modrinth.com/mod/travelersbackpack/version/1.20.4-9.4.4)
(Fabric 1.20.4, traveler's backpack version 9.4.4)

1. Describe the bug 
When you place a backpack with any nbt data on it into a trinket slot, all nbt data gets deleted, deleting all the items inside the backpack.

2. Write steps to reproduce the bug
get a standard traveler's backpack with a backpack tier of netherite and place it into a trinket slot. the backpack should turn into a leather tier backpack.

3. What is expected behaviour
Not deleting any data

4. Screenshots (If applicable)
![BaseProfile2024 06 18-11 12 12 07-ezgif com-video-to-gif-converter](https://github.com/Tiviacz1337/Travelers-Backpack/assets/65547044/49b427d3-fba0-4275-aacc-3e467ef32126)

**Comment by Willio2000** [comment]
I also tried it with nothing but travelers backpack and trinkets but it also did the same thing.
also another thing i forgot to mention is that i am on quilt. I highly doubt this is a quilt only issue so im not going to try it

**Comment by Tiviacz1337** [comment]
Update trinkets to latest version for Fabric 1.20.4

**Comment by Willio2000** [comment]
it works now, thanks
