### ISSUE TITLE
1.21 support?

### ISSUE THREAD

**Issue by NattoRiisa** [Tiviacz1337/Travelers-Backpack#930]
I mean, I would love to see this get added on 1.21 as this backpack has given me so much love with how the features are given with this mod.

**Comment by Tiviacz1337** [comment]
Neo is already ported to 1.20.6, 1.21 is also coming soon. Fabric port to 1.20.6 is almost ready so stay tuned. Forge will be available too

**Comment by NattoRiisa** [comment]
aight! thank you for the reminder <3

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5460679
Released for fabric
I'm closing this issue, if you wait for neo or forge then stay tuned it should be available soon
