### ISSUE TITLE
Crafting Grid Disappears

### ISSUE THREAD

**Issue by Salvati0n** [Tiviacz1337/Travelers-Backpack#933]
Minecraft 1.21 Fabric 0.15.11 Mod 10.0.0

- Crafting Grid disappears when picking your backpack up after putting it down.

- After applying the crafting grid upgrade, if you put down the backpack and then either use Shift+Click to put the backpack back on again or if you destroy the backpack to pick it up again, the Crafting Grid is completely gone. You have to apply a new upgrade to the backpack.

- After applying the crafting grid upgrade it should remain unless you purposely remove it by resetting the backpack.

**Comment by Tiviacz1337** [comment]
Hotfix will be available in a few hours

**Comment by Tiviacz1337** [comment]
Fixed
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
