### ISSUE TITLE
Crafting Upgrade lost when placing backpack on floor.

### ISSUE THREAD

**Issue by jshipley** [Tiviacz1337/Travelers-Backpack#934]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Minecraft 1.21, Fabric API 0.100.3+1.21

1. Describe the bug 

A backpack with a crafting upgrade loses the crafting button after being placed on the floor.

2. Write steps to reproduce the bug

* Get Traveler's Backpack (any level) with Crafting Upgrade
* Shift-right click to place it on the ground
* Right-click to look at the backpack, crafting button is still there
* Shift-right click to pick it up
* Crafting button to open crafting table is not available unless Crafting Upgrade is added again

3. What is expected behaviour 

A backpack placed on the ground should still have the same upgrades when it is picked back up

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
fixed in travelersbackpack 10.0.2
