### ISSUE TITLE
Crafting Upgrade Disappears after placing in ground.

### ISSUE THREAD

**Issue by PhyroStyx** [Tiviacz1337/Travelers-Backpack#935]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.21-10.0.0.2

1. Describe the bug 
Was using the backpack portable sleeping back for a while after I noticed that the crafting upgrade in it disappeared. I tried putting a  new one but then its gone again. After a while I found out that after placing the backpack to the ground for deploying portable bed makes the crafting upgrade disappear.

2. Write steps to reproduce the bug
- Have Crafting Upgrade on Backpack
- Place Backpack on the ground
- Open it either right click or equipped

3. What is expected behaviour 
Losing crafting ability

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
The issue was fixed in version 10.0.2 and can no longer be reproduced. Check if you use correct version
