### ISSUE TITLE
1.20.1 config screen not loading

### ISSUE THREAD

**Issue by Rocraft27** [Tiviacz1337/Travelers-Backpack#937]
Fabric 1.20.1-15.11
![Screenshot_20240627-090619_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/Tiviacz1337/Travelers-Backpack/assets/168403787/fb8490c9-56a3-4824-bd3e-68da2d380d96)

**Comment by Tiviacz1337** [comment]
what is your mod menu and fabric api version?
