### ISSUE TITLE
Bucket stacking?

### ISSUE THREAD

**Issue by RubyRezal** [Tiviacz1337/Travelers-Backpack#938]
I'm not sure if this is a bug report or a feature request. I'm currently running version 10.0.2 for Minecraft 1.21

I thought we used to be able to put filled buckets in the tank input and empty buckets would stack in the output. This doesn't happen in the latest version.
![2024-06-27_06 29 35](https://github.com/Tiviacz1337/Travelers-Backpack/assets/1816386/5a53d61b-9fa4-438e-9248-2f4dd5d9200f)

Likewise, I thought we used to be able to put a stack of empty buckets in the tank input slot and pull filled buckets out one at a time. This also doesn't happen in the latest version.
![2024-06-27_06 29 07](https://github.com/Tiviacz1337/Travelers-Backpack/assets/1816386/5eb13a56-e422-440e-ae21-61542c546886)

The ability to use bucket stacks was (or would be) a significant QoL feature. Manually placing and removing individual buckets for each fill or drain action is tedious and time consuming.

I'm trying to keep my playthrough as vanilla as possible. I'm only using the standard backpack for the convenience of portable storage, portable crafting, and tool swap. I do not intend to craft or use the hose, nor do I have any fluid storage mods loaded other than the tanks provided by Traveler's Backpack.

Thanks

**Comment by Tiviacz1337** [comment]
Yes that's something I have in plans to implement, but I had some problems with it in the past. I'll try to implement feature once again

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Added in latest update
