### ISSUE TITLE
Backpack GUI off by 1 pixel

### ISSUE THREAD

**Issue by Kal-xyz** [Tiviacz1337/Travelers-Backpack#939]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Tested in fabric (0.15.11), mod version is (1.21-10.0.2) but also probably applicable to older versions.

1. Describe the bug 

The Backpack GUI is off by 1 pixel.

2. Write steps to reproduce the bug

Open the backpack inventory.

3. What is expected behaviour 

The backpack inventory to be moved up by 1 pixel.

4. Screenshots (If applicable)

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/44576050/1465aa53-e3e9-42ca-9864-d0e2e2d80285)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/44576050/e7397e31-8f5b-43fb-82d7-0c84e9487395)

*for context*: I was making a resource pack for custom GUIs and when i tried making one for traveler's backpack, my original mesurements didn't match up and I realized that the GUI was off my 1 pixel. This could be intentional, but if it isn't please fix it.
Thank you!

**Comment by Tiviacz1337** [comment]
When I'll make a change I give a sign here

**Comment by isoextension** [comment]
ohh thats so wrong

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20

Reworked all guis in latest update
