### ISSUE TITLE
My backpack disappeared

### ISSUE THREAD

**Issue by TPL2008** [Tiviacz1337/Travelers-Backpack#94]
I died and quit to title. When i came back, my backpack disappeared with all my stuff.

Sorry about my English

**Comment by Maxitotito** [comment]
It is happening in my server too when players die in another dimension or log back from a break.
I hope this can add some more info, I do not have the logs when this happens.

**Comment by Tiviacz1337** [comment]
Is it still happening on the latest version?

**Comment by Maxitotito** [comment]
> Is it still happening on the latest version?
Have not tested in last version. As an extra info this bug was occurring while teleporting back from the end too.

**Comment by Tiviacz1337** [comment]
In a latest version I've made some significant changes and it should be fixed

**Comment by TPL2008** [comment]
> Is it still happening on the latest version?

I don't know. It's been a long time since I don't play with this mod.

**Comment by Tiviacz1337** [comment]
It should be fixed anyway
