### ISSUE TITLE
9.1.14 update crash

### ISSUE THREAD

**Issue by TheLegendofSaram** [Tiviacz1337/Travelers-Backpack#940]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Im Minecraft version 1.20.1 with fabric 0.15.11, and the mod version is the 9.1.14 for 1.20.1

2. Describe the bug 
The game crashes before loading

3. Write steps to reproduce the bug
I'm using a modpack, so first download one, Im using the modpack "SoreAss" on modrinth
Update the Travelers backpack mod, the modpack is using the 9.1.13 version
Start the game
Crash

4. What is expected behaviour 
Not to crash upon start

BTW the mexican spanish translation has some missing strings and some gramatical errors
Here is an updated es_mx file that has all the missing translation, even the config
[es_mx.json](https://github.com/user-attachments/files/16036236/es_mx.json)

**Comment by TheLegendofSaram** [comment]
[crash-2024-06-28_15.42.54-client.txt](https://github.com/user-attachments/files/16036300/crash-2024-06-28_15.42.54-client.txt)

**Comment by Tiviacz1337** [comment]
you are in grave danger mod error

**Comment by Tiviacz1337** [comment]
Dont report it to their devs I'll reverse few changes

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Fixed

**Comment by TheLegendofSaram** [comment]
Ohh okk, thanksss
