### ISSUE TITLE
Backpacks Disappear as Floating Item even when invulnerableBackpack is true

### ISSUE THREAD

**Issue by LightningFerix** [Tiviacz1337/Travelers-Backpack#941]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Mod: travelersbackpack-fabric-1.20.1-9.1.13.jar
Fabric: 0.15.11
Minecraft: 1.20.1

1. Describe the bug 

Backpacks, when dropped on the ground as an item, disappear, even when "invulnerableBackpack" is set to "true" in the config file.

2. Write steps to reproduce the bug

a. set backpackDeathPlace to false
b. set invulnerableBackpack to true
c. die
d. go back to death point but don't pick up backpack
e. wait
f. backpack disappears

7. What is expected behaviour 

The expected behavior is for the backpack to **not** disappear as the comment in the config file says.

9. Screenshots (If applicable)

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/79895448/43cf77a7-da24-4b01-af38-8ff684bfac1c)
![2024-06-28_19 51 01](https://github.com/Tiviacz1337/Travelers-Backpack/assets/79895448/e9d76eb5-28d4-49b6-894e-046272005333)

The first image shows the line in the config to show that I have set the setting to true.
The second image shows the empty space in front of me where the backpack does not exist (but used to before it despawned).

**Comment by Tiviacz1337** [comment]
Do you use other mods or just travelersbackpack?

**Comment by LightningFerix** [comment]
I do use other mods. The most relevant mod in this case is probably [Forgotten Graves](https://github.com/ginsm/forgotten-graves) which takes all the items in your inventory and puts them in a gravestone for safe retrieval later.

With the default configurations, these two mods work perfectly with each other, with the backpack planting itself right next to the grave. However, I recently had an incident where I died in water where my gravestone properly created itself, but my backpack was nowhere to be seen. Because of this, I disabled backpack placing as a block next to where you died. 

Before I enabled Trinkets integration, I was just testing out the invulnerableBackpack feature and saw that the backpack despawns like any other item. Since I opened this bug report, I have enabled Trinkets integration and it works perfectly with the grave mod, being stored in the grave upon death and then auto equipping once I retrieve my items.

However, the issue still remains that the backpack despawns when it shouldn't.

**Comment by LightningFerix** [comment]
Here is my full (server) mod list. The client list is largely identical, and any differences are minor client-side only mods such as mods that add aesthetic effects, change sound physics, click through signs, and the like.

Fabric Mods: 
		additionalstructures: Additional Structures 4.2.1
		alloy_forgery: Alloy Forgery 2.1.2+1.20
		another_furniture: Another Furniture 1.20.1-3.0.1
		anvilrestoration: Anvil Restoration 2.2
		appleskin: AppleSkin 2.5.1+mc1.20
		archers: Archers (RPG Series) 1.2.1+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		architectury: Architectury 9.2.14
		arrowentitylootdrop: Arrow Entity Loot Drop 1.2.1
		artifacts: Artifacts 9.5.12
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			expandability: ExpandAbility 9.0.4
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		axesareweapons: Axes Are Weapons 1.7.3
		azure-paxels: Azure Paxels 1.0.9
		azurelib: AzureLib 2.0.27
		azurelibarmor: AzureLib Armor 2.0.5
		balm-fabric: Balm 7.3.6
			kuma_api: KumaAPI 20.1.8
		bbb: Building But Better 1.20.1-fabric-1.0.2
		betterarcheology: Better Archeology 1.1.9-1.20.1
		betterbeaconplacement: Better Beacon Placement 3.3
		bettercombat: Better Combat 1.8.5+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.4
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.6
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		bookshelf: Bookshelf 20.2.13
		bottledair: Bottled Air 2.3
		bottleyourxp: Bottle Your Xp 3.3
		brewinandchewin: Brewin And Chewin 3.0.6+1.20.1
			mm: Manningham Mills 2.3
		casualness_delight: Casualness Delight Fabric 1.20.1-0.4-FDR
		catloaf: Cat Loaf 1.1.0
		chunkloaders: Chunk Loaders 1.2.8+a
		chunky: Chunky 1.3.146
		chunkyborder: ChunkyBorder 1.1.53
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.4
		collective: Collective 7.64
		complete_bone_meal: Complete Bone Meal 2.1.1
		cratedelight: Crate Delight 2024.6.21-1.20-fabric
		cristellib: Cristel Lib 1.1.5
			blue_endless_jankson: jankson 1.2.3
		ctov: ChoiceTheorem's Overhauled Village 3.4.4
		culturaldelights: Cultural Delights Fabric 1.0.0+1.20.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		dahmersdelight: Dahmer's Delight 1.0.2
		dataattributes_dc: Data Attributes: Directors Cut 1.6.0+1.20.1
		deathbackup: Death Backup 3.3
		dismountentity: Dismount Entity 3.3
		doapi: [Let's Do] API 1.2.15
		doubledoors: Double Doors 5.7
		dungeon_difficulty: Dungeon Difficulty 2.2.1+1.20.1
		dungeonnowloading: Dungeon Now Loading 1.5
		dungeons_arise: When Dungeons Arise 2.1.57
		dungeons_arise_seven_seas: When Dungeons Arise: Seven Seas 1.0.2
		easyanvils: Easy Anvils 8.0.2
		easyelytratakeoff: Easy Elytra Takeoff 4.2
		easymagic: Easy Magic 8.0.1
		elytraslot: Elytra Slot 6.4.0+1.20.1
			mixinsquared: MixinSquared 0.1.2-beta.6
		expandeddelight: Expanded Delight 0.3.1
		explorerscompass: Explorer's Compass 1.20.1-2.2.3-fabric
		explorify: Explorify 1.6.0
		extraspellattributes: Extra RPG Attributes 1.2.3
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		farmersdelight: Farmer's Delight 1.20.1-2.1.1+refabricated
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
				porting_lib_common: Porting Lib Common 2.3.4+1.20.1
				porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
				porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.4+1.20.1
			porting_lib_config: Porting Lib Config 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.4+1.20.1
			porting_lib_registries: Porting Lib Registries 2.3.4+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
				porting_lib_core: Porting Lib Core 2.3.4+1.20.1
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
		farmersdelightexpansion: Farmer's Delight Expansion 1.1.0+1.20.1
		farmersknives: Farmer's Knives 3.2
		fastload: Fast Load 3.4.0
			conditional-mixin: conditional mixin 0.3.2
			fastload-119-0-1-2-compat: Fastload 1.19-0-1-2 Compatibility 3.4.0
			fastload-1193-compat: Fastload 1.19.3 Compatibility 3.4.0
			fastload-1194-compat: Fastload 1.19.4 Compat 3.4.0
			fastload_fapi_forward: Fastload Fabric-api Forwarding 1.0.2
		fastpaintings: Fast Paintings 1.20-1.2.7
		ferritecore: FerriteCore 6.0.1
		fishontheline: Fish On The Line 3.2
		flowerpatch: Flower Patch 3.1.0
		followersteleporttoo: Followers Teleport Too 2.4
		forager_bow_ench: Forager Bow Enchantment 1.0.2
		forgeconfigapiport: Forge Config API Port 8.0.0
		forgottengraves: Forgotten Graves 3.2.10+1.20.1
		formations: Formations 1.0.2
		formationsoverworld: Formations Overworld 1.0.3
		friendlyfire: FriendlyFire 18.0.7
		frightsdelight: Frights Delight fabric-1.20.1-1.0.4
		fwaystones: Fabric Waystones 3.3.2+mc1.20.1
		gazebo: Gazebos 1.1.1+1.20.1
		geckolib: GeckoLib 4 4.4.7
			com_eliotlash_mclib_mclib: mclib 20
		grapplemod: Grappling Hook Mod 1.20-v1.8
		grassseeds: Grass Seeds 3.2
		graveyard: The Graveyard 3.0
		grindenchantments: Grind Enchantments 3.1.2+1.20
			codec-config-api: Codec Config API 1.0.2+1.19.3
		healingcampfire: Healing Campfire 5.3
		hearth_and_home: Hearth & Home 1.20.1-2.0.3
		herbaldelight: Herbal Delight 1.3-patch3-1.20.1
		hoetweaks: Hoe Tweaks 3.4
		imst: Immersive structures 2.1.0
		incendium: Incendium 5.3.5
		inventorytotem: Inventory Totem 3.2
		invoke: Invocations Mod 0.2.3
		jade: Jade 11.8.0
		jadeaddons: Jade Addons 5.2.5
		java: OpenJDK 64-Bit Server VM 17
		jewelry: Jewelry (RPG Series) 1.3.3+1.20.1
		keepmysoiltilled: Keep My Soil Tilled 2.2
		kevslibrary: Kev's Library 1.1.0
		kevstieredzmodifiers: Kev's TieredZ Modifiers 2.1.3
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lithium: Lithium 0.11.2
		lithostitched: Lithostitched 1.1.6
		lmft: Load My F***ing Tags 1.0.2+1.20
		luphieclutteredmod: Cluttered 2.1.0+1.20.1
		mavapi: More Axolotl Variants API 1.1.4
		mavm: More Axolotl Variants Mod 1.2.6
		mca: Minecraft Comes Alive 7.5.18+1.20.1
		mcda: MC Dungeons Armors 5.0.2
		mcdar: MC Dungeons Artifacts 4.0.3
		mcdw: MC Dungeons Weapons 9.0.4
		medieval_buildings: Medieval Buildings 1.0.1
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		mineralchance: Mineral Chance 3.6
		mobcaptains: Mob Captains 3.1.1
		modernfix: ModernFix 5.18.1+mc1.20.1
		moonlight: Moonlight 1.20-2.12.4
		moredelight: More Delight 1.2.2-1.20.1-fabric
		moremobs: More Mobs 1.5.1+mod
		moremobvariants: More Mob Variants 1.3.0.1
		mostructures: Mo' Structures 1.4.5+1.20.1
			omega-config: OmegaConfig 1.4.1+1.20.1
		moveboats: Move Boats 3.2
		moveminecarts: Move Minecarts 3.4
		mr_camps_castles_carriages: Camps. Castles. Carriages. 2.3.3
		mr_ctov_gazebocompat: CTOV - Gazebo compat 1.0
		mr_ctov_paladinsnpriestscompat: CTOV - Paladins & Priests compat 1.0
		mr_ctov_wizardscompat: CTOV - Wizards Compat 2.0a
		mr_dungeons_andtaverns: Dungeons and Taverns 3.0.3.f
		mr_mine_treasure: Mine Treasure 1.3.2
		mr_ships: Ships 3.0.1
		mr_tidal_towns: Tidal Towns 1.3
		mru: Mineblock's Repeated Utilities 0.4.3+1.20.1
		myloot: myLoot 4.0.3-1.20.1
		mythicmetals: Mythic Metals 0.19.9+1.20.1
			additionalentityattributes: Additional Entity Attributes 1.7.3+1.20.0
			common-protection-api: Common Protection API 1.0.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		naturalist: Naturalist 4.0.3
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		necronomicon: Necronomicon 1.4.2
		nethersdelight: Nether's Delight Refabricated 1.20.1-4.1.1
		noanimaltemptdelay: No Animal Tempt Delay 1.1
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		nofeathertrample: No Feather Trample 1.2
		nohostilesaroundcampfire: No Hostiles Around Campfire 5.9
		nullscape: Nullscape 1.2.6
		obscure_api: Obscure API 16
		onsoulfire: On Soul Fire 1.20-2
			midnightlib: MidnightLib 1.4.1
		oreharvester: Ore Harvester 1.3
		overweight_farming: Overweight Farming 1.20.1-2.0.3-fabric
		owo: oωo 0.11.2+1.20
		paladins: Paladins & Priests (RPG Series) 1.2.0+1.20.1
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		player-animator: Player Animator 1.0.2-rc1+1.20
		playerex: PlayerEx: Directors Cut 3.7.2+1.20.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			net_objecthunter_exp4j: exp4j 0.4.8
			opc_dc: Offline Player Cache: Directors Cut 0.6.5+1.20.1
		polymorph: Polymorph 0.49.5+1.20.1
			cardinal-components-block: Cardinal Components API (blocks) 5.2.1
			cardinal-components-item: Cardinal Components API (items) 5.2.1
			spectrelib: SpectreLib 0.13.15+1.20.1
		puffish_attributes: Pufferfish's Attributes 0.3.0
		puffish_skills: Pufferfish's Skills 0.12.2
		pumpkin_pie: Pumpkin Pie Delight 1.0.1
		puzzleslib: Puzzles Lib 8.1.21
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		qolfixes: QoLFixes 3.0-1.20.1
		railoptimization: RailOptimization 1.0
		ranged_weapon_api: RangedWeaponAPI 1.1.2+1.20.1
		recast: Recast 3.4
		recipecommands: Recipe Commands 3.3
		regions_unexplored: Regions Unexplored 0.5.5+1.20.1
			completeconfig-base: completeconfig-base 2.5.2
		relicex: RelicEx 3.4.2+1.20.1
			armorrenderlib: Armor Render Lib: Directors Cut 0.3.1+1.20.1
		replantingcrops: Replanting Crops 5.3
		respawnablepets: Respawnable Pets 1.20-1
			cardinal-components-world: Cardinal Components API (worlds) 5.2.1
		respawningshulkers: Respawning Shulkers 3.7
		roguelike: Roguelike Dungeons 2.0.4-b-1.20.1-fabric
		runes: Runes 0.9.13+1.20.1
		scaffoldingdropsnearby: Scaffolding Drops Nearby 3.2
		seasons: Fabric Seasons 2.3+1.20
		seasonsextras: Fabric Seasons: Extras 1.2-BETA+1.20
		shield_overhaul: Shield Overhaul 1.0.3
		shulkerdropstwo: Shulker Drops Two 3.3
		silentsdelight: Silents Delight fabric-1.0.0-1.20.1
		simplehats: SimpleHats 1.20.1-0.3.0
		simplyskills: SimplySkills 1.4.1+1.20.1
		simplyswords: Simply Swords 1.55.0-1.20.1
		snowundertrees: Snow Under Trees 2.4.0+1.20.1
		spark: spark 1.10.53
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		sparsestructures: Sparse Structures 2.1.2
		spawn: Spawn 1.0.3-fabric
		spell_engine: Spell Engine 0.14.3+1.20.1
		spell_power: Spell Power Attribute 0.10.3+1.20.1
		spellbound: Spellbound 1.15.0.1
			modify-drops-api: Modify Drops API 0.5.1.1
		spiceoffabric: Spice of Fabric 1.6.2+mc1.20.1
			capsaicin: Capsaicin 1.3.3+mc1.20.1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
		spoornbountymobs: SpoornBountyMobs 4.0-1.20.1
			org_apache_commons_commons-math3: commons-math3 3.3
		spoornpacks: SpoornPacks 5.0-1.20.1
		stackrefill: Stack Refill 4.4
		staffofbuilding: Staff of Building ${version}
		storagedelight: Storage Delight 1.1.1-1.20.1-fabric
		structure_pool_api: Structure Pool API 1.0+1.20.1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17
		t_and_t: Towns and Towers 1.12
		tectonic: Tectonic 2.3.5b
		terrablender: TerraBlender 3.0.1.7
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		things: Things 0.3.3+1.20
			lavender: Lavender 0.1.0-pre.18+1.20
				lavender-md: lavender-md 0.1.0-pre.3+1.20
				lavender-md-owo-ui: lavender-md-owo-ui 0.1.0-pre.3+1.20
		thornybushprotection: Thorny Bush Protection 1.2
		tiered: Tierify 1.1.0
			autotag: AutoTag 2.0.2+1.20
			autotag-convention: AutoTag Convention 2.0.2+1.20
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.15.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.15.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.15.2
			libz: LibZ 1.0.2
		tlc: The Lost Castle 1.0.1
		toms_storage: Tom's Simple Storage Mod 1.6.7
		toomanypaintings: Too Many Paintings! 1.0.1-1.20-fabric
		totw_additions: Towers of the Wild: Additions 1.3
		totw_modded: Towers Of The Wild: Modded fabric-1.20.1-1.0.5
		trashslot: TrashSlot 15.1.0
		travelersbackpack: Traveler's Backpack fabric-1.20.1-9.1.13
		treeharvester: Tree Harvester 8.7
		trinkets: Trinkets 3.7.2
		turkish_delight: Turkish Delight 1.0.0
		ubesdelight: Ube's Delight 1.20.1-0.1.5.4
		ultris_mr: Ultris: Boss Expansion 5.6.9c
		unwrecked_ships: Unwrecked Ships Plus 1.0.0-1.20
		uselessreptile: Useless Reptile 0.7.4-1.20.1
			primitive_multipart_entities: Primitive Multipart Entities 1.1.1
		variantsandventures: Variants & Ventures 1.0.3
		vietnamsdelight: Vietnam's Delight 1.0.2-1.20.1
		villagesandpillages: Villages&Pillages 1.0.0
		vinery: [Let's Do] Vinery 1.4.25
		wizardex: WizardEX: Directors Cut 1.2.0+1.20.1
			placeholder-api: Placeholder API 2.1.3+1.20.1
		wizards: Wizards (RPG Series) 1.2.0+1.20.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.5
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Fixed
