### ISSUE TITLE
Server doesn't start after installing the mod

### ISSUE THREAD

**Issue by OlHonder** [Tiviacz1337/Travelers-Backpack#942]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Using Fabric 0.14.22 and tried mod versions 1.19.2-8.2.39 and 1.19.2-8.2.26 (separately, ofc) 

1. Describe the bug 

Installed the mod on a preexisting modded server, now the server doesn't start and generates a crash report saying something about mixin transformation trinket failed

2. Write steps to reproduce the bug

-Put mod in the mod folder for the server
-Attempt to start the server like I used to do it before
-Watch the console print and generate the crash report

3. What is expected behaviour 

For the server to start normally, I hope

4. Screenshots (If applicable)
No screenshots, only crash reports

[crash-2024-06-29_17.35.54-server.txt](https://github.com/user-attachments/files/16042698/crash-2024-06-29_17.35.54-server.txt)
[crash-2024-06-29_17.26.58-server.txt](https://github.com/user-attachments/files/16042699/crash-2024-06-29_17.26.58-server.txt)

**Comment by Tiviacz1337** [comment]
Make sure you have trinketsIntegration off in trarvelers backpack config

**Comment by Tiviacz1337** [comment]
Seems like yigd is trying to mixin the class which requires Trinkets to work. You dont have trinkets so it crashes. And it tries to load this class because you probably have trinketsIntegration = true in backpack config

**Comment by OlHonder** [comment]
Didn't know it's set to true by default, will do

**Comment by OlHonder** [comment]
It's on false yet it still gives the same error

**Comment by OlHonder** [comment]
got rid of yigd, fixed
