### ISSUE TITLE
Items changed on death

### ISSUE THREAD

**Issue by PaterFrog** [Tiviacz1337/Travelers-Backpack#943]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
[latest.log](https://mclo.gs/hQ0uwqu)
Fabric 0.15.11
Game 1.20.1
Mod fabric-1.20.1-9.1.14
**.txt with all mods attached**

1. Describe the bug 
Whenever I die with my backpack in the Trinket back slot, weird things happen to my items. I have not determined a specific pattern, except that items change (they duplicate other items in the backpack), and possibly that items do get deleted as well. (I suspect the latter from a previous play session, as items I crafted mysteriously went missing. I didn't notice until the next day.)

I suspect that there may be some compatibility issues with the Trinkets mod?

2. Write steps to reproduce the bug
- install Trinket
- gamerule: keep items on death
- Equip backpack in back slot provided by Trinkets
- Die
- check inventory
- items changed and perhaps lost
- Happens on _every_ death.

3. What is expected behaviour 
- unchanged inventory

4. Attachments
[mods.txt](https://github.com/user-attachments/files/16048129/mods.txt)

**Comment by PaterFrog** [comment]
I just noticed a strange issue:
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/46433636/88d1c5cd-07ab-46dc-b265-0c5a2ae14617)

I had the bottom of the two installed, and its the one with the issues.
When I went looking through mods I might like to add to my pack, I stumbled across this version of Traveler's Backpack and noticed it wasn't installed. (I have since installed it, as you can see, and will see if this version fixes the issue.)

I have no idea how or why this happened. I used modrinth to install Traveler's Backpack a week or two ago. I don't know how or why I got a...corrupted? version of your mod.

**Comment by PaterFrog** [comment]
Hmm. Now the backpack just completely deletes itself if I have it in the Trinkets slot, despite using the keepInventoryOnDeath rule.

**Comment by PaterFrog** [comment]
This should be an issue with Traveler's Backpack's Trinkets integration, I think. Beansbackpack does _not_ have the same issue. It does use a custom gamerule to stay in the dying player's inventory which has to be turned on manually as well, but bean's gamerule does work, unlike your doNotPlaceOnDeath settings.

**Comment by PaterFrog** [comment]
I was not able to find a way to solve this issue. The backpacks delete themselves if I put them in the back slot. They don't if I keep the backpack in my hand or in the inventory (even if I keep Trinkets integration enabled).

I've uninstalled the mod for now - it's not quite stable.

**Comment by Tiviacz1337** [comment]
9.1.14 was hidden because it caused incompatibility with grave mods and other devs probably wouldnt change their code so I reverted the changes

**Comment by Tiviacz1337** [comment]
I'll check the issue

**Comment by PaterFrog** [comment]
> I'll check the issue

If you run into issues, Beans Backpacks might be a good place to look at possible solutions. Those backpacks don't disappear on death if you set the config accordingly.

**Comment by Tiviacz1337** [comment]
Okay so I've just checked it by myself - everything works correctly for me. Backpack stays in trinket slot if gamerule keepInventory = true. make sure you have trinketsIntegration enabled in travelersbackpack config

**Comment by PaterFrog** [comment]
So it'll be a compatibility issue with one of the mods, then. 
I just toggled the mod on again, and the backpacks still delete themselves completely, on death. with the integration turned on. I've tried the _place on death_ option, and the _force place_ one too, but they don't work either - the backpack's still disappearing.

Do you have any particular suggestions on how I could track down this issue?

**Comment by Tiviacz1337** [comment]
So for first you can check if it works for you on clean installation with just travelersbackpack installed, then you can add more mods and check when it breaks

**Comment by PaterFrog** [comment]
I was afraid it'd be that.

Well, an initial test with just your mod, Trinket, EMI, and dependencies, shows success.

**Comment by PaterFrog** [comment]
Ah, I got very lucky, the very first mod I tested was Bean's Backpacks, and that created the conflict:

The issue is having Bean's Backpack enabled - and that it has conflicting configs. There's a `"keepBackSlot":` setting in *two* of its config files:
(look at the marked lines near the bottom)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/46433636/bf471d3a-4944-4be1-8933-a31645395048)

If they're not set to the same value, they create an impossible situation.

**Comment by Tiviacz1337** [comment]
so im closing the issue
