### ISSUE TITLE
Corrupted data by reserving backpack slot for an enchanted item

### ISSUE THREAD

**Issue by eyescreaming** [Tiviacz1337/Travelers-Backpack#944]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Minecraft 1.21 with Fabric Loader 0.15.11
travelersbackpack-fabric-1.21-10.0.2   Tried updating to latest version fabric-1.21.1-10.0.3 but issue persists.

1. Describe the bug 
Lost connection from singleplayer world after creating reserved places for enchanted item in backpack.
When attempting to open the world again, I either get "Disconnected" to server list or Connection Lost. (lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:container_set_content')

3. Write steps to reproduce the bug

Tested with an Enchanted Golden Helmet
- [1] Place an enchanted item into backpack slot,
- [2] Enter select mode to "Choose slot with item to reserve place for this item",
- [3] Reserve a backpack slot for the enchanted item,
- [4] Exit select mode, game should disconnect with Connection Lost.
Trying to play the world should result in the same Connection Lost error.

4. What is expected behaviour 
Enter select mode, Reserve slot for item, Exit select mode, Close backpack
The world save shouldn't be corrupted

5. Screenshots (If applicable)
Error Log
https://pastebin.com/DPHBehaK

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5498352
