### ISSUE TITLE
Backpack not opening

### ISSUE THREAD

**Issue by queermeet-dev** [Tiviacz1337/Travelers-Backpack#946]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Minecraft 1.20.4 with Fabric 0.15.7 and travelersbackpack-fabric-1.20.4-9.4.6

1. Describe the bug 

Assigned a key to open backpack, but nothing happens

2. Write steps to reproduce the bug

get a backpack in creative mode (in this case the diamond backpack), put it into the inventory and click the key you assigned for opening

3. What is expected behaviour 

it should open

4. Screenshots (If applicable)

[latest.log](https://github.com/user-attachments/files/16097344/latest.log)

**Comment by Tiviacz1337** [comment]
You have to open backpack with right click, equip backpack with button in left corner of gui, and then open with keybind

**Comment by queermeet-dev** [comment]
Thanks
