### ISSUE TITLE
Empty tag c:tools/shears

### ISSUE THREAD

**Issue by Shadowglitchjpg** [Tiviacz1337/Travelers-Backpack#947]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

NeoForge 1.21, mod version 10.0.1

1. Describe the bug 

In the crafting recipe for removing backpack textures, the c:tools/shears tag is empty

2. Write steps to reproduce the bug

1. Install JEI
2. Check the crafting recipe for the leather backpack

3. What is expected behaviour 

Instead of the empty tag icon it shows shears (I think?)

4. Screenshots (If applicable)

![1mcbackpack](https://github.com/Tiviacz1337/Travelers-Backpack/assets/68738408/7024a516-b250-4abe-9d4d-5a2f8ae7f7a3)
![1mcbug](https://github.com/Tiviacz1337/Travelers-Backpack/assets/68738408/77b1662a-87bc-4ab1-b437-fb126089ab39)

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5516681
Fixed
