### ISSUE TITLE
Cant use backpack ability

### ISSUE THREAD

**Issue by tylerbriggs** [Tiviacz1337/Travelers-Backpack#948]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1.21-10.0.4

1. Describe the bug 

I cant use the abilites on any of the backpacks. Everyhting else seems to be functioning fine, and yes, I have the ability enabled

2. Write steps to reproduce the bug
Try backpack abilites

3. What is expected behaviour 

ability will not work.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
more info? what ability what backpack what is not working
