### ISSUE TITLE
Packs become unusable after update. 

### ISSUE THREAD

**Issue by Mitchmethinks** [Tiviacz1337/Travelers-Backpack#950]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

From Fabric 1.20.2 - to Fabric 1.21

1. Describe the bug 

Everything was working fine with my 1.20.2 world. I removed all my items and updated fabric, and all of my mods to 1.21. After doing the update the backpacks are still there, I can break them and place them. But as soon as I interact with them, the game crashes.  

2. Write steps to reproduce the bug

interact with backpacks after update from 1.20.2 - 1.21

3. What is expected behaviour 

ability to interact with already established backpacks. 

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
1.20.2 and 1.21 are different versions, I do not support migration
Take contents  and create new backpacks
