### ISSUE TITLE
Unable to craft the netherite enhancement (fabric 1.21)

### ISSUE THREAD

**Issue by edna321** [Tiviacz1337/Travelers-Backpack#952]
0. I use traveler's backpack for fabric 1.21 (everything even cloth config and cardinal are the latest version)

1. Unable to craft the netherite enhancement for backpack, doesn't show up in crafting table with unknown recipes on, and doesn't craft when craft manually too.
 
Or do I have to update cloth config and/or cardinal comp ?

**Comment by Tiviacz1337** [comment]
You mean netherite backpack or netherite tier upgrade?

**Comment by edna321** [comment]
I can't craft both, or is it uncraftable, like the bat backpack ?

**Comment by Tiviacz1337** [comment]
do you play on server

**Comment by edna321** [comment]
I play offline, solo world

**Comment by Tiviacz1337** [comment]
can you craft other backpacks and things?

**Comment by edna321** [comment]
Yes I can craft every craftable items and backpack from the mod, it's just the netherite backpack and upgrade that I can't craft, I play full survival, no commands.
The only other mods I have doesn't affect the storage (mods to cut trees faster, and mod to see health bar).
I added the mod after beating the dragon too.

**Comment by Tiviacz1337** [comment]
what recipe you use for backpack and upgrade

**Comment by edna321** [comment]
these
![IMG_20240707_105209_322](https://github.com/Tiviacz1337/Travelers-Backpack/assets/174938097/b1a854a2-5b9b-48a7-a40a-cd3617dc452a)
![IMG_20240707_105402_596](https://github.com/Tiviacz1337/Travelers-Backpack/assets/174938097/802e13c2-929b-48e4-bf03-0b22ba1b8da0)

**Comment by Tiviacz1337** [comment]
That's not how you craft it
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/34790800/6a063c02-d6a8-411f-91aa-1954a25c45e3)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/34790800/e436d50f-51af-494e-8d02-601f5c673bbd)
These are the correct recipes
