### ISSUE TITLE
The backpack disappears when I reconnect to the server and it have problems with Multiverse-Core puglins

### ISSUE THREAD

**Issue by AlexRmzAg** [Tiviacz1337/Travelers-Backpack#954]
1.- I have a mohist server with modifications and add-ons (I know it can cause several problems), specifically the backpacks disappear when I disconnect and reconnect and I can only see them if I die and loot my body, (corpse mod works great with this mod) .

2.- Having several worlds on the server with multiverse core and multiverse inventories, the mod continues to keep the backpacks in the inventory even when configuring the plugin so that inventories are not shared.

As a curious fact, if I disconnect with the backpack on and reconnect and change to another world, the backpack appears again.

**Comment by Tiviacz1337** [comment]
I see multiverse is for bukkit, I do not support it, cant even do anything to fix it
