### ISSUE TITLE
Game crash when you put items into the backpack, (Client & Server)

### ISSUE THREAD

**Issue by brunoXD154** [Tiviacz1337/Travelers-Backpack#955]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Neoforge-1.20.6-9.6.2

1. Describe the bug 
The Client crashes when you put any item into the backpack and you exit the menu.

2. Write steps to reproduce the bug
Open the backpack, equip the backpack, put any item, close the backpack, and done. Crash.

3. What is expected behaviour 
Sad, bc I cant play with my friends if they're clients crashes if they do this.

4. Screenshots (If applicable)
I don't have screenshots but I have the latest.log with the mods that I have. (and server has.)
[latest.log](https://github.com/user-attachments/files/16134921/latest.log)

**Comment by brunoXD154** [comment]
is my first time summiting a issue so, I really don't know if I do it right, but don't be angered at me, I tried my best.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5516680
Fixed
