### ISSUE TITLE
Recipe Book For Crafting in travellers backpack

### ISSUE THREAD

**Issue by Yo-Snowpro** [Tiviacz1337/Travelers-Backpack#958]
**Is your feature request related to a problem? Please describe.**
Whenever I'm Building or something and I'm like "oh crap I need to make like observers for example, but I dont know how so i have to go all the way back to my crafting table to see the recipe book

**Describe the solution you'd like**
Add in a portable crafting book made with a book, a crafting table, and lime dye

**Describe alternatives you've considered**
Have it built into the crafting for backpack or maybe the bookshelf one could have a second use.

**Additional context**
Nothing really.

**Comment by Tiviacz1337** [comment]
Won't add, use mods for viewing recipes like Jei, rei or emi.

**Comment by CharlZ02** [comment]
JEI dosnt work on 1.20.1 Forge
