### ISSUE TITLE
No Ability/potion affects when wearing ability giving backpacks

### ISSUE THREAD

**Issue by KreativeKngYT** [Tiviacz1337/Travelers-Backpack#959]
Latest version of 1.20.1 Forge: 47.3.5

I'm using the latest version of the mod for 1.20.1: travelersbackpack-forge-1.20.1-9.1.14. and I have used both the Magma and Dragon backpacks and either of them have given the special abilities when i wear them. the Magma backpack should have given me Fire Resistance and the Dragon backpack should have given me Fire Res, Strength, Regen, and Water breathing and Night vision when in water.

I even double checked the config just in case and Abilities says they are enabled.

**Comment by Tiviacz1337** [comment]
You have to enable ability by ability switch in inventory 
https://github.com/Tiviacz1337/Travelers-Backpack/wiki/Buttons-in-Backpack-Inventory
Check ability slider
