### ISSUE TITLE
(Suggestion) corail tombstone/baubles support 

### ISSUE THREAD

**Issue by Terravolt14** [Tiviacz1337/Travelers-Backpack#96]
I would love to have the option for it to save in a corail tombstone grave if the mod is present.
(it saves if in a bauble slot if you didn't know)

**Comment by spitballworship** [comment]
Go into the Traveller's Backpack config and set the following:
# Places backpack at place where player died
    B:backpackDeathPlace=false

This puts it in the tombstone. On my server anyway, not sure if any of Corail's configs would change this behavior since I did not change anything in that one.
