### ISSUE TITLE
Crash when in nether

### ISSUE THREAD

**Issue by NJM1564** [Tiviacz1337/Travelers-Backpack#960]
NeoForge: 21.0.78
Version: Neo forege 1.21-10.0.2

Crash's while near a ghast while wearing a dragon backpack.
Probably do to the backpacks fire protection not being updated to the new version of minecraft.

Here's the crash report
https://gist.github.com/NJM1564/817aa4f1c106a948e0d416f06a3bba3a
And log file
https://gist.github.com/NJM1564/42799f068bf8778e70ac5654b62d7a96

Tested in test overworld. Still an issue.

**Comment by Tiviacz1337** [comment]
I see you use travelers backpack 1.21-10.0.1. Update to 1.21-10.0.2
