### ISSUE TITLE
Hose toggle not working

### ISSUE THREAD

**Issue by BottledOxygen** [Tiviacz1337/Travelers-Backpack#961]
Fabric 1.21 (fabric-api-0.100.3+1.21.jar)

I am pressing the keybind to switch the modes on my hose and it is not working. The same keybind works when I switch tools from my backpack

**Comment by Tiviacz1337** [comment]
Works for me, make sure to have backpack equipped on the back, if you dont, hose doesnt work

**Comment by BottledOxygen** [comment]
I do have the backpack equipped, like I said the keybind works when I switch tools that are in the green slots on my backpack.

**Comment by Tiviacz1337** [comment]
You have to right click the hose first to attach to tank, then you can change modes

**Comment by BottledOxygen** [comment]
That doesn’t seem to be doing anything for me. I right click, hold my keybind, scroll, and nothing happens

**Comment by Tiviacz1337** [comment]
In the right bottom corner, is one of the tanks icon highlighted with white border?

**Comment by BottledOxygen** [comment]
Yes

**Comment by Tiviacz1337** [comment]
Do you hold the keybind then use scroll?

**Comment by BottledOxygen** [comment]
Yes

**Comment by Tiviacz1337** [comment]
What mod version do you use?

**Comment by BottledOxygen** [comment]
The file name is "travelersbackpack-fabric-1.21-10.0.2"

**Comment by Tiviacz1337** [comment]
Try updating to 10.0.4 and check if issue occurs

**Comment by BottledOxygen** [comment]
That did not work

**Comment by BottledOxygen** [comment]
Bump

**Comment by Tiviacz1337** [comment]
Try if it works with only Traveler's Backpack installed

**Comment by BottledOxygen** [comment]
it works when the I have just that mod installed and when I test in a singleplayer world with the rest of my mods installed

**Comment by Tiviacz1337** [comment]
I dont understand, so it works?

**Comment by BottledOxygen** [comment]
It works in single player but doesn’t seem to be working in multiplayer

**Comment by Tiviacz1337** [comment]
Just checked on server with only Traveler's Backpack installed and it works

**Comment by BottledOxygen** [comment]
That’s weird. Are there any known incompatibilities with Traveler’s Backpack and other mods? I tried looking around online and couldn’t find anything

**Comment by Tiviacz1337** [comment]
You have to check it yourself. I dont know, only TB installed works on server
