### ISSUE TITLE
Backpack unequipable

### ISSUE THREAD

**Issue by RepeatSwitch** [Tiviacz1337/Travelers-Backpack#963]
Mods: 
- Fabric Loader (v0.16.0) 
- Fabric API (v0.100.7+1.21)
- Cloth Config API (v15.0.127+fabric)
- Cardinal Components API (v6.1.0)
- Traveler's Backpack (v1.21-10.0.4)
- Trinkets (v3.10.0) **_With or without this mod they still were unequipable_**

1. The backpack can be opened via right-click while selected on hotbar but no key binds work and it cannot be equipped into the chestpiece slot or into the trinkets backpack slot

2. Was in creative mode testing for a new modpack and wasn't able to equip the backpack

3. Being able to equip the backpack into the trinket or at least chestpiece slot

**Comment by Tiviacz1337** [comment]
Open backpack from hand, you'll notice button in left bottom corner of inventory, that's how you equip the backpack
Then you can access backpack by B keybind

**Comment by Tiviacz1337** [comment]
![image](https://github.com/user-attachments/assets/d8d952c6-9c26-42d7-b5ac-53a68eda0cdd)

**Comment by RepeatSwitch** [comment]
Ah okay I didn't see that lol, thanks!
