### ISSUE TITLE
Cannot equip backpack and backpack dissapeared when i placed on ground

### ISSUE THREAD

**Issue by Jackelton10** [Tiviacz1337/Travelers-Backpack#965]
I'm on fabric on v1.20.4
Basically i tried to put my backpack on using the button in the inventory from when you just right click with it and it did not work, this does not have anything to do with another backpack being equipped. Well when i tried to place the backpack to take it back up it dissapeared in thin air and i lost all my valuables in it, please someone atleast help me fix it so i can use my other backpacks, and yes this happens to every backpack.

**Comment by Tiviacz1337** [comment]
Record a video

**Comment by NingyMD** [comment]
When you place a backpack on the ground you can pick it up to you hand by breaking it.

When you shift-Right click on it when it is placed it will be worn on your back (Use a key bind to open its inventory Default B)
When the back pack it equipped you need to open it up (using b) and click the "take off" button on the left. This will move it to your inventory.

When held in you hand you can open it with right click and click the green "Put on" button located on the left where the take off button was.


I wrote this assuming you just accidently put the back pack on.
