### ISSUE TITLE
Forge 1.21 Liquid tanks don't really work

### ISSUE THREAD

**Issue by BlaBlubMC** [Tiviacz1337/Travelers-Backpack#966]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 1.21 10.0.0

1. Describe the bug 
I cannot place empty or filled buckets in the designated areas, nor can I use the hoses.

2. Write steps to reproduce the bug
I only have this one mod installed, and I still can't put anything on the fields and I can't use the hose either.

3. What is expected behaviour 
That I can fill the tanks in the backpacks with water, milk, lava or drinks and drink from the hoses.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Its forge bug not my mod. Buckets do not work correctly. Switch to NeoForge or wait for Forge update

**Comment by cubeface114** [comment]
> Its forge bug not my mod. Buckets do not work correctly. Switch to NeoForge or wait for Forge update

I have a similar issue on Fabric with the hoses, i can suck up liquids no problem, but i cant change the hose mode its basically just stuck in suck mode even when a full tank is selected. I have bound the hose mode key bind but pressing it just shows its on suck mode for a split second before the text disappears.

**Comment by NingyMD** [comment]
> > Its forge bug not my mod. Buckets do not work correctly. Switch to NeoForge or wait for Forge update
> 
> I have a similar issue on Fabric with the hoses, i can suck up liquids no problem, but i cant change the hose mode its basically just stuck in suck mode even when a full tank is selected. I have bound the hose mode key bind but pressing it just shows its on suck mode for a split second before the text disappears.

To be sure, when you **hold** the key bind for **switching hose modes** you are using your **scroll wheel** to change the hose modes and that doesn't seem to work?
