### ISSUE TITLE
Cardinal Components API Not Required?

### ISSUE THREAD

**Issue by NingyMD** [Tiviacz1337/Travelers-Backpack#967]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.20.1-0.15.11

1. Describe the bug 
When I downloaded the mod from the cursforge launcher it didn't auto download Cardinal Components API. But its listed as a "Required Dependency"
As far as I can tell Cardinal Components API isn't need any more. If so can you list it in the description of the mod saying what versions don't need it. Even the ability's of the mod seem to work.

2. Write steps to reproduce the bug
Download travelersbackpack-fabric-1.20.1-9.1.15.jar and its dependency's but not Cardinal Components.

3. What is expected behavior
Requires Cardinal Components and breaks without it.

**Comment by Tiviacz1337** [comment]
I don't understand. Cardinal Components is still needed as required dependency for Fabric
