### ISSUE TITLE
no upgrade stuff for 1.12.2

### ISSUE THREAD

**Issue by Idfk-man** [Tiviacz1337/Travelers-Backpack#968]
Is there any reason why i cant find the crafting upgrade and tier upgrades on 1.12.2? im tryna play scape and run parasites, and im just curious if theres any reason for that? i did download through curseforge if that has anything to do with it.

**Comment by Tiviacz1337** [comment]
1.12.2 was not supported for a long time when I released an update with upgrades for backpack. 1.12.2 do not have this feature
