### ISSUE TITLE
Add optional support for Accessories instead of Trinkets or Curios

### ISSUE THREAD

**Issue by Bruhnanza** [Tiviacz1337/Travelers-Backpack#969]
**Is your feature request related to a problem? Please describe.**
Trinkets is Fabric-only, Curios API is Forge-only (and has not been updated[*](https://modrinth.com/mod/curios-continuation)), while a new mod called [Accessories](https://modrinth.com/mod/accessories) is cross-compatible with Fabric & NeoForge and has a wide array of features.

**Describe the solution you'd like**
Add optional support for Accessories so one can wear/view the backpack within your inventory without needing to use the backpack's GUI itself. This would also simplify development and information for users as both the Fabric & NeoForge mod versions could support this mod instead of 2 different ones.

**Describe alternatives you've considered**
Trinkets and Curios API are limited to a specific mod loader, have slower development, and offer fewer features compared to Accessories.

**Additional context**
Accessories even has experimental compatibility layers for mods utilizing Trinkets or Curios, but this doesn't seen to be functional with Traveler's Backpack based on my testing.

**Comment by Tiviacz1337** [comment]
Compatibility with Accessories (instead of Curios/Trinkets) is going to be default for 1.21+ mod versions. Fabric compat layer will work with backpack I have this fixed in dev environment and I will release an update probably this week

**Comment by BrandonPotter0** [comment]
> Compatibility with Accessories (instead of Curios/Trinkets) is going to be default for 1.21+ mod versions. Fabric compat layer will work with backpack I have this fixed in dev environment and I will release an update probably this week

Fantastic. I was having issues with the backpack getting unequipped whenever I logged off a local server, and having to re-equip it when I got back on <3

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5585473
Added optional integration with accessories for neo 1.21

**Comment by Bruhnanza** [comment]
Amazing. I'm closing the issue, but I hope optional integration is planned for the Fabric 1.21 version as well. Thank you for your work.

**Comment by Tiviacz1337** [comment]
Fabric update is coming this week stat tuned
