### ISSUE TITLE
Bag not wearable, disappears, and makes world unplayable

### ISSUE THREAD

**Issue by ThatRandomPersonOnGithub** [Tiviacz1337/Travelers-Backpack#971]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric, 1.21- 10.0.4

1. Describe the bug 

I cannot put the bag on the "bag" slot in Trinkets, and when i open the right-click menu, and press the button with steve on it, it disappears. i tried restarting my world, but now it's unopenable.

2. Write steps to reproduce the bug

Make Cake bag
Try to put bag on Trinkets bag slot
doesn't work
Put in hotbar
Place and open menu
Press button with steve on it
it disappears
exit and enter world
minecraft is not responding, stuck on "prepearing resources"
exit and enter program
enter world
still no cake bag

4. What is expected behaviour 
 The cake bag should not disappear, and it should be able to put on your Trinkets bag slot.

5. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
to use backpack, you have to click icon with steve and then click B to open backpack inventory
