### ISSUE TITLE
Disappearing items and stacks 

### ISSUE THREAD

**Issue by Iweleth** [Tiviacz1337/Travelers-Backpack#972]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 

When a backpack is in your hotbar and you open it's inventory, shift+clicking items from your inventory to the backpack's will result in loss of those items you've moved from your inventory. Shift+clicking multiple different items will only result in the loss of the last item. 

2. Write steps to reproduce the bug

•Place a backpack in your hotbar and get a stack of any item
•Place half of that stack inside that backpack's inventory and then close the gui
•Reopen the backpack and shift+click the rest of the stack inside then close the gui again
•Reopen the backpack and you'll see that only half of the stack remains.
[example 1](https://github.com/user-attachments/assets/7a016a8e-0b59-4230-9582-211be337ea6d)

*More than one item
•Get a stack of two or more items
•Open the inventory of a backpack in your hotbar and place half stacks your items inside, then close the gui
•Reopen the backpack and shift+click the rest of the stacks inside, then close the gui again
•Reopen the backpack and you'll see this time only the last item will be missing the second half of it's stack.
[example 2](https://github.com/user-attachments/assets/04e83465-17bf-4ff3-ac2d-ac6415688081)

3. What is expected behaviour 

No missing item quantities.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5585473
Fixed
