### ISSUE TITLE
Compatability issue with Iris shaders

### ISSUE THREAD

**Issue by phadreus** [Tiviacz1337/Travelers-Backpack#973]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
I am using the fabric version. 

1. Describe the bug 
I have a server setup and running. When I use just the fabric modded client I can join with no issue. 
However once I try to use the Iris modded client I get the error that the server requires the cardinal components api. 
Which is installed. Travelers Backpack is the only mod I have installed that requires cardinal components.

2. Write steps to reproduce the bug
Install the Iris shader loader. Try to connect to a server that has Travelers backpack installed.

3. What is expected behaviour 
Game should load without error.

4. Screenshots (If applicable)
![Screenshot_20240801_083227](https://github.com/user-attachments/assets/9fe764ca-1ac8-4db6-827d-52f72f64fa56)
![Screenshot_20240801_083449](https://github.com/user-attachments/assets/dfc4b99b-d90c-464e-9843-3ae0dd637cf0)
![Screenshot_20240801_083722](https://github.com/user-attachments/assets/f1143604-c3b1-4d9d-a4c2-97c77a0dfbb1)
![Screenshot_20240801_083859](https://github.com/user-attachments/assets/39d5b148-0504-435e-b766-43c9f0883aae)

**Comment by Tiviacz1337** [comment]
so it seems iris loader is not loading cardinal components
