### ISSUE TITLE
Unable to equip backpack due to "ghost" backpack?

### ISSUE THREAD

**Issue by XTRelite** [Tiviacz1337/Travelers-Backpack#974]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 0.16.0 (via CurseForge) and using 1.20.1-9.1.15
Also want to mention that I'm playing the BigChadGuys Plus (w Cobblemon) modpack v2.3.1 but with some changes:
Added: Cobblemounts, Cobblemon Counter, Ascension Megas, Cobblemon Unchained, Craftify, Durability Tooltips; and Removed: Chat Heads, Simple Voice, Arachnophobia, BCG+ x Whimscape, Serifed Font, Whimscape, Bisect Hosting Integration

1. Describe the bug 
Upgraded my diamond lapis backpack to netherite and am unable to equip it in the back slot or any slot. Additionally, when I press the backpack hotkey, my old diamond backpack opens as if I have it equipped. This "ghost" backpack will open regardless of whether I have the lapis backpack in my inventory or not.

2. Write steps to reproduce the bug
Honestly, just removed my backpack and upgraded it to netherite and then encountered this.

3. What is expected behaviour 
Able to equip my backpack and actually access the backpack rather than a "ghost" one.

4. Screenshots (If applicable)
I took a vid and had to downscale to 480p, trim it, and compress it as a zip but here it is:
[Untitled video - Made with Clipchamp (2).zip](https://github.com/user-attachments/files/16465113/Untitled.video.-.Made.with.Clipchamp.2.zip)
I didn't take any screenies but I can take some of the vid if you don't trust the file or it doesn't work.

Update: I can no longer seem to equip any backpack.
2nd Update: I've managed to fix this by editing the JSON to enable trinkets integration. The ghost backpack is gone and I can now equip backpacks —albeit only in the back slot now.

**Comment by Tiviacz1337** [comment]
As you can see, there's tanks and tools rendered in left bottom corner. It means you have backpack equipped. To open the backpack you have to click B. (or might be other keybind, check in controls) When you open inventory via B you'll find button to eventually unequip. You can use trinkets integration (like you did) and put backpack in back slot to use it too
