### ISSUE TITLE
Mod crashing at startup loading game stage

### ISSUE THREAD

**Issue by Kylebartaous** [Tiviacz1337/Travelers-Backpack#976]
0. ALWAYS PROVIDE INFORMATION ABOUT MOD LOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
1. Neo-forge version 21.0.146
2. Travelers-backpack version for Neo forge 10.0.3

3. Describe the bug 
4. The mod is failing to load & crashing the game window back to desktop

5. Write steps to reproduce the bug
1Install travelers backpack mod for Neo-forge version 10.0.3
2 Start the game & wait for it to try to load though the Neo-forge loading stage, when it gets to loading mods, constructing it crashes the game fully back to desktop

6. What is expected behavior 
7. With the mods installed for it to launch the game & load up mine craft title screen

8. Screenshots (If applicable)

Crash report: https://pastebin.com/iKArGm1w
Latest Logs: https://pastebin.com/hdD2gTac

**Comment by Kylebartaous** [comment]
If i need to i can try to update Neo-forge to the latest version 21.0.148. though i been messing w/ a lot of turning on & off mods that haven't been working so I'm wondering if I'm missing anything like a API or lib for this mod to work, or broke something else.

Not sure if this matters since it not really my issue, but then looking at other issues reports i noticed that there is also a open report from about 3 weeks ago, talking about Natures Compass causing errors & crashes #962 .

i do also have a bunch of the other compass mods too, listed below.

explorer's compass version 3.0.2
structure compass version 4.0.0
traveler's compass version 3.0.4a

I do use the curios mod so I'm wondering if that could be causing any problems, I'm using the curios api continuation. there is also another one that lets to be able to use curios again for this version called adorned (curios).

wondering if i also need the compat mod called Curios Compat Layer for Accessories for this to work?

**Comment by Tiviacz1337** [comment]
The crash log says it's unionlib mod issue, remove it or report to their devs
