### ISSUE TITLE
Stackable Items Still Dissapearing in 10.0.3 NeoForge Version

### ISSUE THREAD

**Issue by Launian** [Tiviacz1337/Travelers-Backpack#978]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

1. Describe the bug 
When shift+clicking stackable items into a backpack, said item count does not increase after closing and reopening the backpack. This does not seem to happen when the items are being placed by dragging them, or if there is no stack of said items in the backpack

2. Write steps to reproduce the bug

1. Open an equiped backpack
2. Shift+click a stack of items with number > 1. Leave another stack of items in your normal inventory.
3. Close and reopen the backpack; the first batch of items should be in the backpack
4. Shift+click the second stack of items into the backpack
5. Close and reopen the backpack; the item cound has not increased

6. What is expected behaviour 

Item count should be consistent

7. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Do you use accessories integration?

**Comment by Tiviacz1337** [comment]
Can't reproduce with multiple tries

**Comment by Launian** [comment]
I use it from the Curios slot in the back

**Comment by Tiviacz1337** [comment]
Okay, I'll check that

**Comment by Tiviacz1337** [comment]
You mean accessories? I do not support Curios in version 1.21-10.0.3

**Comment by Launian** [comment]
Ok, I checked, and it's actually a fork of Curios: Curios API Continuation

![image](https://github.com/user-attachments/assets/db1096ee-b0a1-4647-b20b-dbac7cb93799)

**Comment by Tiviacz1337** [comment]
I do not support this mod, I support Accessories for 1.21

**Comment by Tiviacz1337** [comment]
Traveler's Backpack latest version should work correctly with curios api continuation on neo
