### ISSUE TITLE
Items can be duplicated using the crafting upgrade slots of a backpack

### ISSUE THREAD

**Issue by CronoARG** [Tiviacz1337/Travelers-Backpack#979]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 1.21 using mod version 1.21-10.0.4

1. Describe the bug.

Items placed in the crafting slots of an equipped backpack will appear in the same crafting slots of a different backpack when equipped by using the shift+right click method thereby allowing you to infinitely duplicate them.

2. Write steps to reproduce the bug

A] Equip a backpack by any means.
B] Place items in any of the 9 crafting slots of the backpack. _(Doesn't have to be full)_
C] Unequip the backpack by any means.
D] Place and equip a 2nd backpack by pressing shift+right click while empty-handed. _(Make sure the 2nd backpack didn't already have items in the crafting slots before doing this)_
E] Open the backpack inventory and collect the items from step B which are now present in the 2nd backpack.
F] Open the first backpack to collect the items again thus doubling the amount you previously had.

_Alternate Method using only one backpack_
Do steps A&B as above.
C] Place the backpack on the ground by pressing shift+right click.
D] While on the ground, right click the backpack to open the inventory and remove the items from the crafting slots.
E] Equip the backpack again by pressing shift+right click.
F] Open and close the backpack's inventory. _(Notice the items will still be present in the backpack. At this point you can even add the items back into the crafting slots to further increase the duplication rate)_
G] Repeat steps C-F as many times as you want.

3. What is expected behaviour 

Items that are placed in the crafting slots of an equipped backpack should either be removed from those slots when the backpack is unequipped or should be completely independent of another backpack's crafting slots. The bug seems to rely on equipping a backpack using shift+right click to glitch the inventory.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Fixed will be available in the update today or tomorrow

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5601319
Fixed for Neo

**Comment by Tiviacz1337** [comment]
Fixed for Fabric
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
