### ISSUE TITLE
Crashes with Bewitchment

### ISSUE THREAD

**Issue by sdrawkcabkcaj** [Tiviacz1337/Travelers-Backpack#98]
Specifically, whenever you load Witch's Brew potions into the tank. You can load the tank while the bag is on the ground (sometimes?), but if the bag is in your inventory or on your back and you try to load up on brew, game crashes and the potion is completely lost when you start the game back up.

**Comment by Tiviacz1337** [comment]
Fixed the crash, but potions will be without effect anyway. That's because Bewitchment's brews use different tags for their potions. I'll add the compat in addon to Traveler's Backpack.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/2993111
