### ISSUE TITLE
Connection Lost on Single Player World when opening Bagpack

### ISSUE THREAD

**Issue by Ecthelion75** [Tiviacz1337/Travelers-Backpack#980]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

NeoForge-21.0.160

travelersbackpack-neoforge-1.21-10.0.3

No other mods present.

1. Describe the bug 

Game automatically disconnects from single player world when opening bagpack

2. Write steps to reproduce the bug

1) Load singleplayer world
2) Wear bagpack
3) Press B to open bagpack

3. What is expected behaviour 

Game automatically crashes when opening bagpack

4. Screenshots (If applicable)

![image_2024-08-05_161400725](https://github.com/user-attachments/assets/d6fbb420-174c-467b-830f-d71d50859eb4)

**Comment by Tiviacz1337** [comment]
Will be fixed in the upcoming update. If you want to play now you can downgrade NeoForge version to older one and it'll work correctly

**Comment by Ecthelion75** [comment]
Noted, thanks.
