### ISSUE TITLE
The code is very unreadable, and I cant' figure out how to add custom backpack via add-on mod

### ISSUE THREAD

**Issue by Tejty** [Tiviacz1337/Travelers-Backpack#981]
0.     1.16.5 Forge

1. It has a very weird rendering system, and there is a very big amount of lists containing all backpacks, and when I register new item as the backpack class, it crashes when rendering it on back in third person. I also tried adding it into the list of bags in the ModItems class, but it made some weird stuff, it had texture of different backpack, and other backpacks has been pushed in the list, that caused shuffled textures of other backpacks, and one backpack crashed when it tried to render it, with error index 43 out of range 43.

That means there is list of models it is trying to read from, but there are more backpacks in the main list

2. I already told that

3. I would expect you to rewrite your code to be more add-on friendly

4. Sorry I can't provide screenshots

**Comment by Tiviacz1337** [comment]
I am aware of that, but since you are using 1.16.5 I don't think changes are coming to this version 
at the moment I support 1.18.2-1.21 
I dropped suport for 1.16.5 some time ago

**Comment by isoextension** [comment]
java's fault

**Comment by Tiviacz1337** [comment]
Rendering has been improved for supported versions 1.20.1 forge/fabric and 1.21.x forge/fabric/neo
The updates will eventualy come out for 1.18.2 forge/fabric and 1.19.2 forge/fabric too but I want to wait a while and see if any bugs come out
