### ISSUE TITLE
Traveler's Backpack v10.0.4 crashes with Accessories

### ISSUE THREAD

**Issue by NovaViper** [Tiviacz1337/Travelers-Backpack#983]
#981  ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Minecraft v1.21
NeoForge v21.0.148/v21.0.163 (tested multiple versions in case it was something related with the NeoForge versions)
Travelers Backpack v10.0.4 from [Modrinth](https://modrinth.com/mod/travelersbackpack)

# Describe the bug 
The game crashes right after it finishes starting up with the errors `Cannot get config value before config is loaded` and `Reported exception thrown! net.minecraft.ReportedException: Rendering screen`. 

# Write steps to reproduce the bug
1. Add Travelers Backpack v10.0.4 along with Accessories v1.0.0-beta26+1.21
2. Run the game

# What is expected behaviour 
The game shouldn't be crashing during load

# Logs
With my main modpack: https://mclo.gs/0lbml0p
With TravelersBackpack and Accessories only enabled: https://mclo.gs/13dBLpC

**Comment by Yo-Snowpro** [comment]
Same with me but I use fabric and it happened to me aswell

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5601319
Fixed
