### ISSUE TITLE
 (FIXED) T'SB 9.1.15: Crashing when trying to open Creative Inventory (NullPointerException)

### ISSUE THREAD

**Issue by isoextension** [Tiviacz1337/Travelers-Backpack#984]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION 
1.20.1 Forge Mod Loader
Mod version: 9.1.15

2. Describe the bug 
Title says it all

3. Write steps to reproduce the bug
1. Install the mods in the [Crash report](https://mclo.gs/i4Sc0B4)
2. Load a multiplayer world (this only happens in multiplayer)
3. Try opening the creative inventory

4. What is expected behaviour 
The creative inventory actually work and not crash

5. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
You dont have mod installed on server or client

**Comment by isoextension** [comment]
what?
i do

**Comment by isoextension** [comment]
oh

**Comment by isoextension** [comment]
im a dumbass lmao

**Comment by isoextension** [comment]
also if it wasnt installed on the client it would give me an FMLHANDSHAKE error, not a crash (i think)

**Comment by Tiviacz1337** [comment]
so it's fixed?

**Comment by Tiviacz1337** [comment]
I thin the mod is absent on server

**Comment by isoextension** [comment]
Yes it was 😭
