### ISSUE TITLE
Honey interaction

### ISSUE THREAD

**Issue by MangoLassie142** [Tiviacz1337/Travelers-Backpack#985]
I think Honey would be a fun interaction to add to the backpack tanks. Being able to suck honey from beehives as a quicker alternative to bottling. and also allowing us to store and drink honey from out tanks for use in combat and as food.

**Comment by isoextension** [comment]
cool feature

**Comment by Tiviacz1337** [comment]
Honey is not registered as fluid in minecraft so it's not possible and I don't want to add honey in Traveler's Backpack mod.
