### ISSUE TITLE
how to fix this  

### ISSUE THREAD

**Issue by jonath605** [Tiviacz1337/Travelers-Backpack#986]
how to fix this

Game crashed while exception was in server tick loop
Error: java.lang.NoSuchFieldError: Class com.tiviacz.travelersbackpack.config.TravelersBackpackConfigData$BackpackSettings has no member field 'boolean trinketsIntegration'

**Comment by Tiviacz1337** [comment]
Need whole crash log

**Comment by jonath605** [comment]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-08-07 13:13:54
Description: Exception in server tick loop

java.lang.NoSuchFieldError: Class com.tiviacz.travelersbackpack.config.TravelersBackpackConfigData$BackpackSettings does not have member field 'boolean trinketsIntegration'
	at com.b1n_ry.yigd.compat.TravelersBackpackCompat.isTrinketIntegrationEnabled(TravelersBackpackCompat.java:21)
	at com.b1n_ry.yigd.compat.InvModCompat.initModCompat(InvModCompat.java:27)
	at com.b1n_ry.yigd.Yigd.lambda$onInitialize$1(Yigd.java:85)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$bbn000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:4142)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 331719912 bytes (316 MiB) / 1535115264 bytes (1464 MiB) up to 4529848320 bytes (4320 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 7520U with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 160 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 2.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.12042.2002
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 5.50
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 4096.00
	Memory slot #1 clockSpeed (GHz): 5.50
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 22815.62
	Virtual memory used (MiB): 12738.75
	Swap memory total (MiB): 15360.00
	Swap memory used (MiB): 746.20
	Space in storage for jna.tmpdir (MiB): available: 218056.09, total: 487450.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 218056.09, total: 487450.00
	Space in storage for io.netty.native.workdir (MiB): available: 218056.09, total: 487450.00
	Space in storage for java.io.tmpdir (MiB): available: 218056.09, total: 487450.00
	Space in storage for workdir (MiB): available: 218056.09, total: 487450.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4320m -Xms256m
	Fabric Mods: 
		accessories: Accessories 1.0.0-beta.26+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		alloy_forgery: Alloy Forgery 2.3.1+1.21
		architectury: Architectury 13.0.6
		automated_crafting_crafter_converter: Automated Crafting Crafter Converter 1.0.0
		axesareweapons: Axes Are Weapons 1.9.1
		battletowers: Classic Battle Towers 1.2.0
		betterfpsdist: Better FPS distance Mod 1.21-4.3
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.10.1-1.21
			multipart_entities: MultipartEntities 1.7-1.21
		bridgingmod: Bridging Mod 2.4.0+1.21
		cardinal-components: Cardinal Components API 6.1.1
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-block: Cardinal Components API (blocks) 6.1.1
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
			cardinal-components-item: Cardinal Components API (items) 6.1.1
			cardinal-components-level: Cardinal Components API (world saves) 6.1.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.1
			cardinal-components-world: Cardinal Components API (worlds) 6.1.1
		cloth-config: Cloth Config v15 15.0.128
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.80
		creativecore: CreativeCore 2.12.4
			net_neoforged_bus: bus 7.2.0
		cristellib: Cristel Lib 1.2.7
			blue_endless_jankson: jankson 1.2.3
		ctov: ChoiceTheorem's Overhauled Village 3.5.1
		cupboard: cupboard 1.21-2.7
		durabilitytooltip: Durability Tooltip 1.1.5
		dynamic_fps: Dynamic FPS 3.6.3
			net_lostluma_battery: battery 1.1.0
		emerald_tools: Emerald Tools 1.8.15
			pugh_tools: Pugh Tools 1.8.18
		entityculling: EntityCulling 1.6.6
		explorify: Explorify 1.6.1
		fabric-api: Fabric API 0.100.8+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.13+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.26+a5d66753d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.2.0+7e687b32d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.83+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.0+kotlin.2.0.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		fpsdisplay: FPS-Display 4.2.0+1.21
		fpsreducer: FPS Reducer 1.21-2.9
		friendsandfoes: Friends&Foes 2.0.15
		frostiful: Frostiful 2.0.0-beta.1
		geckolib: GeckoLib 4 4.5.7
		glitchcore: GlitchCore 2.0.0.2
			net_jodah_typetools: typetools 0.6.3
		gpumemleakfix: Gpu memory leak fix mod 1.21-1.8
		hopobettermineshaft: Hopo Better Mineshaft 1.2.7
		inventoryprofilesnext: Inventory Profiles Next 2.0.4
		jamlib: JamLib 1.0.11+1.21
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.7.0.92
		journeymap: Journeymap 1.21-6.0.0-beta.18
			ar_com_hjg_pngj: pngj 2.1.0
			commonnetworking: Common Network 1.0.11-1.21
			journeymap-api-fabric: JourneyMap API 2.0.0-1.21-SNAPSHOT
		justhammers: Just Hammers 21.0.2
		kotori316_version_checker: ForgeLikeVersionChecker 2.4.0
		kotori_scala: Scalable Cat's Force Fabric 3.0.0
			org_scala-lang_scala-library: scala-library 2.13.12
			org_scala-lang_scala3-library_3: scala3-library_3 3.3.3
			org_typelevel_cats-core_3: cats-core_3 2.10.1-kotori
			org_typelevel_cats-free_3: cats-free_3 2.10.1-kotori
			org_typelevel_cats-kernel_3: cats-kernel_3 2.10.1-kotori
		libipn: libIPN 6.0.2
		lithostitched: Lithostitched 1.2.5
		medieval_buildings: Medieval Buildings 1.0.2
		memorysettings: Memorysettings Mod 1.21-5.5
		midnightlib: MidnightLib 1.5.7
		milesplayz: Fantastic Remastered Structures 0.5
		minecraft: Minecraft 1.21
		mo_glass: Mo Glass 1.8.1-MC1.21
		monolib: MonoLib 1.3.0
		mostructures: Mo' Structures 1.5.0+1.21
			omegaconfig: Omega Config Architectury 1.5.1
		mousetweaks: Mouse Tweaks 2.26
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v4.3
		mr_dungeons_andtavernspillageroutpostoverhaul: Dungeons and Taverns Pillager Outpost Overhaul 1-v2.2
		mvs: Moog's Voyager Structures 4.1.3-1.21-fabric
		mythicupgrades: Mythic Upgrades 4.1.3+mc1.21
		new_shield_variants: New Shield Variants 1.3.0
		onlyhammers: OnlyHammers 1.21-0.3
		owo: oωo 0.12.11+1.21
			io_wispforest_endec_jankson: jankson 0.1.3
		quarryplus: QuarryPlus 21.0.88
		reborncore: Reborn Core 5.11.9
			team_reborn_energy: Energy 4.1.0
		repurposed_structures: Repurposed Structures 7.5.4+1.21-fabric
		smallships: Small Ships 2.0.0-b1.4
			forgeconfigapiport: Forge Config API Port 21.0.5
				com_electronwill_night-config_core: core 3.8.0
				com_electronwill_night-config_toml: toml 3.8.0
		structory: Structory 1.3.5
		structureessentials: Structure Essentials Mod 1.21-3.4
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		t_and_t: Towns and Towers 1.13.2
		techreborn: Tech Reborn 5.11.9
		thermoo: Thermoo 4.2
		toms_storage: Tom's Simple Storage Mod 2.0.9
		toughasnails: ToughAsNails 10.0.0.5
		travelersbackpack: Traveler's Backpack fabric-1.21-10.0.6
		treeharvester: Tree Harvester 9.0
		usefulbackpacks: Useful Backpacks ${version}
		uteamcore: U Team Core 5.6.0.318
		utility_belt: Utility Belt 2.4.3+1.21
		villagernames: Villager Names 8.1
		villagespawnpoint: Village Spawn Point 4.4
		wabi_sabi_structures: Wabi-Sabi Structures 3.0.0
		wardentools: Warden Tools 2.5.1+mc1.21
		waterframes: WaterFrames 2.0.14a
		watermedia: WaterMedia 2.0.69
		yigd: You're in Grave Danger 2.4.0
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			libgui: LibGui 11.0.0+1.21
				jankson: Jankson 8.0.0+j1.2.3
				libninepatch: LibNinePatch 1.2.0
	Server Running: true
	Player Count: 0 / 8; []
	Active Data Packs: vanilla, fabric, accessories, alloy_forgery, axesareweapons, battletowers, bosses_of_mass_destruction, collective, ctov, emerald_tools, explorify, fabric-convention-tags-v2, friendsandfoes, frostiful (incompatible), hopobettermineshaft, justhammers, lithostitched (incompatible), medieval_buildings (incompatible), milesplayz, mo_glass (incompatible), mostructures, mr_dungeons_andtaverns, mr_dungeons_andtavernspillageroutpostoverhaul, mvs (incompatible), mythicupgrades, new_shield_variants (incompatible), onlyhammers, pugh_tools, quarryplus, repurposed_structures, smallships, structory, t_and_t, techreborn, thermoo, toms_storage, toughasnails (incompatible), travelersbackpack, usefulbackpacks (incompatible), utility_belt, wabi_sabi_structures, wardentools, waterframes (incompatible), yigd
	Available Data Packs: accessories, alloy_forgery, axesareweapons, battletowers, bosses_of_mass_destruction, bundle, collective, ctov, emerald_tools, explorify, fabric, fabric-convention-tags-v2, friendsandfoes, frostiful (incompatible), hopobettermineshaft, justhammers, lithostitched (incompatible), medieval_buildings (incompatible), milesplayz, mo_glass (incompatible), mostructures, mr_dungeons_andtaverns, mr_dungeons_andtavernspillageroutpostoverhaul, mvs (incompatible), mythicupgrades, new_shield_variants (incompatible), onlyhammers, pugh_tools, quarryplus, repurposed_structures, smallships, structory, t_and_t, techreborn, thermoo, toms_storage, toughasnails (incompatible), trade_rebalance, travelersbackpack, usefulbackpacks (incompatible), utility_belt, vanilla, wabi_sabi_structures, wardentools, waterframes (incompatible), yigd
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -8994970139416855517
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.0-1.21

**Comment by Tiviacz1337** [comment]
Report it to yigd developer
