### ISSUE TITLE
(Suggestion) Trash can

### ISSUE THREAD

**Issue by TheMightyMcGrew** [Tiviacz1337/Travelers-Backpack#99]
I think the title speaks for itself. Possibly make it an add-on, or use the lava inside a tank as a trash can of sorts

**Comment by Sweek9** [comment]
Though not entirely necessary, a way to delete items is not a bad idea. It has been implemented in other backpack mods along with sorting. In creative mode a red x box for deleting items is added for that, putting that in the bp interface would be a quick implementation.
