### ISSUE TITLE
backpack upgrade not working 1.20.4

### ISSUE THREAD

**Issue by PoFMieze** [Tiviacz1337/Travelers-Backpack#992]
i play on version 1.20.4 and just added this mod to my modpack via curseforge. i checked twice if its the newest verion and it is

i cant upgrade the backback in the smithing table. i can put the backpack in there and put the iron upgrade next to it but nothing happens. i tried it with different backpacks and in creative mode, but it doesnt work. 

![2024-08-14_10 08 43](https://github.com/user-attachments/assets/bc030c6f-2430-4abd-ad32-49e25caac604)
![2024-08-14_10 08 56](https://github.com/user-attachments/assets/a69d8496-8b10-419c-a964-f15ed298c5e6)
![2024-08-14_10 08 59](https://github.com/user-attachments/assets/53c9cd47-14da-42fc-819a-3418e2e5f7da)

**Comment by Tiviacz1337** [comment]
You can check recipes on wiki, leather is necessary in template slot

**Comment by PoFMieze** [comment]
OMG that actually worked 😲 It wasnt like that before in another modpack, so i didnt think of that, thank you 😊
