### ISSUE TITLE
I cant switch mode with hose       

### ISSUE THREAD

**Issue by martanek90** [Tiviacz1337/Travelers-Backpack#994]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric,   1.21

1. Describe the bug 
I cant switch hose mode, i tried everything

2. Write steps to reproduce the bug

3. What is expected behaviour 

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Did you attach the hose to the backpack? Then hold Z (default) then used scroll?

**Comment by Tiviacz1337** [comment]
https://github.com/Tiviacz1337/Travelers-Backpack/wiki/How-to-use-Hose
Works as intended for me
