### ISSUE TITLE
When placing the backpack using shift+right click, your backpack gets placed but a level 1 backpack replaces the slot in Trinkets and can be placed down infinitely 

### ISSUE THREAD

**Issue by AnyaPizza** [Tiviacz1337/Travelers-Backpack#995]
0. Fabric 1.20.1, Mod version: 9.1.16

1. When my backpack is in the Trinket slot and I shift + right click the backpack on the ground. A new level 1 backpack is placed in the slot and I can infinitely place these backpacks, effectively duplicating them.

2. Place backpack in Trinket slot, Shift + Right click the backpack on the ground, keep shift + right clicking 

3. After placing the backpack, the slot should be empty and when I shift + right click my backpack it should go back into the Trinkets slot.

4. Screenshots:
![2024-08-15_00 21 51](https://github.com/user-attachments/assets/62d23e1e-fbb2-4742-afc8-e3838788e0f7)
![2024-08-15_00 22 09](https://github.com/user-attachments/assets/b7f74ba9-8555-4dc1-8a1b-4b355fa4e0fa)

**Comment by Tiviacz1337** [comment]
Seems like I have to disable ability to quick place backpack on the ground if Trinkets enabled. These mods do not have any methods to access backpack easily from the slot and it's causing issues. Update with fix will be available soon

**Comment by AnyaPizza** [comment]
> Update with fix will be available soon

Hi, I don't mean to be a bother but is there an ETA for this update?

**Comment by Tiviacz1337** [comment]
I'm working on an update. I will do my best to release version 1.20.1 by the end of the weekend. 
Update will disable quick equip and unequip if trinkets integration is enabled, but quick pickup will be added instead (shift right click with empty hand to pick up backpack to hand)

**Comment by Tiviacz1337** [comment]
Update will be available tomorrow, sorry I had tough weekend at work and didn't have enough time to finish it, I'm halfway through implementing the changes.

**Comment by AnyaPizza** [comment]
> Update will be available tomorrow, sorry I had tough weekend at work and didn't have enough time to finish it, I'm halfway through implementing the changes.

No worries, take your time. Thank you for the update!

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5758816

Fixed sorry for little delay
Enjoy

**Comment by AnyaPizza** [comment]
No worries! Thank you!
