### ISSUE TITLE
10.0.6 is not compatible with trinkets

### ISSUE THREAD

**Issue by bendem** [Tiviacz1337/Travelers-Backpack#997]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

This is MC 1.21 with Fabric 0.16.2

1. Describe the bug 

I just upgraded from 10.0.4 to 10.0.6, and had to install accessories to get back access to my backpack slot. The mod description is literally "Trinkets integration and more", yet it doesn't work with trinkets anymore.

This is just my opinion, but trinket is a lot closer to vanilla. Accessories having a completely separate UI for its slot is breaking the vanilla feeling.

2. Write steps to reproduce the bug

Have a backpack in your trinket slot in 10.0.4, upgrade, see your backpack missing and the trinket slot missing.

3. What is expected behaviour 

Trinket slot is still there and no new dependency is required in bugfix versions.

4. Screenshots (If applicable)

N/A

**Comment by Tiviacz1337** [comment]
Trinkets integration is going to be restored

**Comment by LilyKensa** [comment]
This is just your opinion *and mine*, but trinket is a lot closer to vanilla. Accessories having a completely separate UI for its slot is breaking the vanilla feeling lol

btw, can I ask why the integration was changed to accessories? Is its API more convenient?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric

Added trinkets compat in latest release
