### ISSUE TITLE
Can´t do the crafting

### ISSUE THREAD

**Issue by DhaBerna** [Tiviacz1337/Travelers-Backpack#998]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.21-10.0.6

1. Describe the bug 
Everytime I try to do the backpack tank nothing comes out of it

2. Write steps to reproduce the bug
1- Go to crafting table
2- See backpack tank recipe: a iron ingot at the top and a iron ingot at the bottom
3- Do the recipe
4- Nothing comes out

3. What is expected behaviour 
HAVE THE BACKPACK TANK TO DO THE BACKPACK

4. Screenshots (If applicable)
![image](https://github.com/user-attachments/assets/63193eaa-8e4a-41c0-a569-1f0ebc6cf6f0)
![image](https://github.com/user-attachments/assets/3fdac0f3-90ff-48ec-ad36-478fa781307f)

**Comment by Tiviacz1337** [comment]
You need glass on the sides

**Comment by DhaBerna** [comment]
![image](https://github.com/user-attachments/assets/f01931fd-d4f1-47ab-aee2-813cc90d6a25)
You sure?

**Comment by DhaBerna** [comment]
I had to get one from creative mode but you should fix it

**Comment by Tiviacz1337** [comment]
![image](https://github.com/user-attachments/assets/70de0160-1dfa-40e0-80a0-a62e12858e15)
Fabric 1.21

**Comment by Tiviacz1337** [comment]
Works for me in-game

**Comment by Tiviacz1337** [comment]
Do you play server, modpack?
